# 序章 {-}

## 試験の仕様についての詳細

この本は、AQA哲学コースとOCR宗教研究コースの倫理学の要素を扱っています。この本はこれらの仕様に沿って書かれており、(願わくは)学生、教師、そして倫理学研究を理解することに関心を持つすべての人を魅了するような形で、必要な内容をカバーしています。

したがって、いくつかの章はこれらの2つのコースのうちの1つにしか直接的に関連していません。OCR宗教研究コースの一部として倫理学を学ぶ学生は模擬的な殺人の倫理について読む必要はなく、AQA哲学コースを学ぶ学生は自然法や状況倫理を考慮する必要はありません。これは、あなたの幅広い読書の一環としてこれらの章に触れる際に、何らかの独立した価値がないと言っているわけではありません。

しかしながら、その区別は必ずしも明確ではありません。たとえば、OCRとAQAの両方とも、学生が功利主義の理論を学ぶことを要求しています。ただし、仕様は若干異なりますので、すべての内容がすべての学生に関係があるわけではありません。関連性は、受講しているコースによって決まります。これに対応するために、私たちは2つの選択肢を提案します:

* あなたのコースの初期の段階 — あなたのコースの仕様にかかわらず、その章の内容に取り組んでください。これは、その理論を評価するための完全かつ情報に基づいた文脈を与えるはずです。
* あなたのコースの後半と試験が近い時期 — あなたのコースの仕様を参照して、あなたの試験にまさに関連しているであろう内容に焦点を当ててください。これについては、あなたの教師に助言を求めるのが最善です。

## 本の構造

私たちはこの本を書く中で、学生が効果的な指導を受けているかを評価する上で学生の判断に焦点を当てるというアンドリュー・フィッシャーのアプローチに従いました。^[このアプローチは、フィッシャーとタラントの「How to Get Philosophy Students Talking」でも見ることができます。]私たちは、この問題に関して学生を権威あるものとしてとらえます。私たちは「関与する」学生を生み出したいと思っています。この目的のために、私たちはこの教材が学生たちに何かを教えたかどうかに関して学生が自身の判断を確認することができる方法を含めています。たとえば、私たちは「学生によくある間違い」、「検討すべき問題」、および「重要な用語」といった節を各章に織り込んでいます。

本書では、AQAとOCRの仕様要件に従って規範倫理学、次にメタ倫理学、そして最後に応用倫理学について扱っています。これらの違いはなんでしょうか?

アンドリュー・フィッシャー(Fisher 2011)が提唱したアナロジーを考えてみましょう。^[Fisher, Metaethics, pp. 1–4.]倫理学をサッカーのようなものだと想像してください。

* 規範倫理学者は、プレーを管理する規則に関心を持つ審判のようなものです。彼が興味を持っているのは、私たちの道徳的行動を支配する一般的な理論です。私たちは何が正しく、何が間違っているかをどうやって解明するのでしょうか?
* メタ倫理学者は、サッカーの解説者のようなものです。彼女が興味を持っているのは、倫理の実践そのものがどのように機能しているかです。たとえば、メタ倫理学者は、人々がどのように道徳的言語を使用するかについて議論するかもしれません。または不道徳な人々の心理について注釈をつけるかもしれません。あるいは道徳的な特質が存在するかどうかを尋ねるかもしれません。
* 応用倫理学者は選手のようなものです。彼らは「自分の手(あるいは足)を汚し」ます。彼らは規範倫理学の一般的なルールをとりあげて、それらの下で「プレー」します。彼らが興味を持っているのは、特定の分野で私たちはどのように行動すべきかです。たとえば、肉食、安楽死、窃盗などの問題に対して、私たちはどう対処すればよいでしょうか?

AQAとOCRの試験仕様に沿って、あなたはさまざまな規範理論が説明されているのを見ることになるでしょう。そして、あなたは実生活の例にそれらの理論が適用されるのも見ることでしょう。これらの間に挟まれているのは、メタ倫理学の章です。メタ倫理学はこう尋ねます:「ところで、倫理的な実践とは何ですか?」

私たちは、3つのタイプの倫理学をすべてカバーすることにより、内容の面と一般的な哲学的アプローチの面の両方で、倫理学に関する優れた基盤を提供したいと望んでいます。私たちは、可能な場所ではできる限り多くの例を提供し、専門用語を避けていますが、時には特定の哲学的用語を使用する必要があります。この点を念頭に置いて、私たちは巻末に幅広い用語集を設けました。私たちの希望は、この本を拾い読みしたり、最初から最後まで通して読んだりできるとあなたに感じてもらうことです。あなたがどのような選択をしたとしても、あなたが試験に必要とされる内容に自信を持ち、この本でカバーしている話題について明確な推論と正当化をもってあなたの思考力を訓練し高めていき、そして私たちと同じように倫理学に興奮し魅了されることを願っています。

## 参照文献

Fisher, Andrew, Metaethics: An Introduction (Oxford: Routledge, 2011), https://doi.org/10.1017/upo9781844652594
―, and Tallant, Jonathan, How to Get Students Talking: An Instructors Toolkit (Oxford: Routledge, 2015), https://doi.org/10.4324/9781315670645
