# はじめに {-}

## 哲学、倫理学、思考

哲学は難しいです。それが私たちをいらだたせるように感じる理由の一部は、それが難しくあるべきではないように見えるためです。結局のところ、哲学は単に思考を伴うだけで、私たちはみな思考しています — 思考することは簡単です!私たちはそれを … まあ、考えずにやっています。しかし、哲学は思考だけを含むのではなく、よく思考することも含みます。もちろん、私たちがみな思考していることは事実です。しかし、思考することは、サッカーや、数学や、パンを焼くことや、歌を歌うことと同じように、私たちがよりうまくなることができるものです。残念ながら、人々が「どうやって?」と尋ねることはほとんどありません。もしあなたが私たちを信じないなら、あなたの目を開けてください。もし私たちがもっとうまく、もっと頻繁に思考していれば、社会はずっと良くなることでしょう。

確かに、Aレベルの哲学を受講することは、世界のさまざまな問題を解決する能力をあなたに授けることはないでしょう。私たちはそれほど素朴ではありません!しかし、もしあなたが哲学に触れるならば、あなたは自分自身のことをうまく思考することのできる、1人の考える人間として発展させるでしょう。これこそが、Aレベルの哲学が単に将来の哲学者にとって役に立つだけでなく、法律、医学、構造工学 — そして、効果的かつ明確に思考する必要があるものならなんでも — の分野で意思決定と向かい合うような、将来の考える人間にとっても有効である理由です。

しかしながら、もし哲学が難しいとしたら、倫理学は本当に難しいです。これは一見したところ、そうではないように見えるかもしれません。結局のところ、倫理学は正しいと間違いについての問題を扱っており、私たちは子供のころから「正しいこと」と「間違っていること」について議論してきました。一方で、心の哲学は意識の性質のような話題を扱い、形而上学は存在そのものの性質を扱っています。確かに、物理学の哲学の講義を理解することと比較すると、ビデオゲームでの殺人の倫理について論争することは、公園での散歩のように思えるかもしれません。でもこれは、誤解を招きます。それは、他の哲学の領域が簡単であるというわけではなく、倫理学の複雑さがうまく偽装されているためです。

## 倫理学を尊重する

あなたがAレベルの倫理学を勉強し、正しいことと間違っていることを評価するときには、あなたの最初の意見を単に守るだけに時間を費やすよう誘惑され、それで満足してしまうかもしれません。いくつかの既存の信念なしに菜食主義、または中絶についての議論に参加する人はほとんどいません。もしあなたが倫理的なアプローチの中で開かれた心を持つ場合には、あなたは現在信じているものすべてを拒絶する必要はありませんが、あなたはそれらの信念のことをあなたの探求が始まる出発点またはベースキャンプとして見なければなりません。

たとえばあなたが、動物を食べることがOKである、あるいは中絶が間違っている、と考える理由は何ですか?もしあなたが慈善団体への寄付が良いと考えているなら、ここでの「良い」とは何を意味するのでしょうか?本当の成功のためには、倫理学は知的な尊重を必要とします。もしあなたが特定の立場は明らかに誤っていると考える場合には、おそらくその反応を警告の赤旗として受け止めるべきでしょう。それは、あなたが議論の重要なステップを見逃していることを示唆しているかもしれません — なぜ相手の人が、おそらくは自分自身と同程度に知的に成熟しているであろう人が、その立場を受け入れているのかをあなた自身に問いかけてください。
あなたが倫理学者としてうまく思考しているならば、あなたはあなたの見解に対して正当な理由を持っている可能性が高く、また、そのような良い理由を見つけられないような見解を再考する用意ができている可能性も高いです。このおかげで、あなたはあなたが持っている信念を正当化することができます。あなたがどんな信念を持っているにせよ、あなたがなぜそれらの信念を保持しているのかを尋ねるのは、哲学者の仕事です。あなたはそれらの信念のためにどんな理由を持っていますか?

たとえば、肉を食べることがOKだとあなたが考える理由は、それがおいしいからである、ということを想像してみてください。哲学者として、私たちはこれが特に良い理由ではないと言うことができます。おそらく、あなたのペットの猫、あなたの隣人、またはあなたの死んだ叔母を食べてもおいしいかもしれません。しかし、これらの場合、「おいしさによる正当化」は全く重要ではないようです!この議論の詳細はここでは関係ありません(このトピックの詳細については第14章を参照してください)。ここでの要点は、私たちの信念には良い理由、または悪い理由があり、それを明らかにして分析するのが哲学者の仕事であるということです。^[良い考え方、または悪い考え方への優れた入門として、私たちはジョン・ホスパースの「An Introduction to Philosophical Analysis」をお勧めします。]

## Aレベルの学生

哲学は、単なる事実の学習や「考え方の歴史」以上のものです。それは化学、数学、語学、神学などとは異なります。それはユニークです。確かに、いくつかの事実を学び、他の人が信じていることを学ぶことは重要ですが、成功したAレベルの学生は、試験のハードルを越えるとともにより良い倫理学者になるために、単に情報を反復する以上のことをする必要があります。

この本の1つの目的は、あなたが生き生きとした学問分野に関与するのを助けることです。哲学、特に倫理学は、生きている、そして進化する主題です。あなたが哲学を学ぶとき、あなたは先んじる人たちとの対話へと入ります。さまざまな哲学者が何を考えているかを学ぶことで、あなたは自分が何を考えているか、そしてその進化する対話に何を加えることができるかについて、明確にすることができます。

あなたは、この本に「ヒントと豆知識のボックス」や、学者に関する伝記の記述が含まれていないことに気づくでしょう。これらのものにも役割はありますが、私たちは、読者がそのボックスに何が入っているかを覚えれば哲学を学んだことになるのだと考えて欲しくはなかったのです。

実際に、大学の哲学の学部では初年度の学生に対して、学術的に成功しないであろう習慣の一部を捨てるように、しばしば働きかけます。なぜか?まあ、著者の1人は何年も大学で倫理学を教えてきました。哲学の学生は、しばしばこういったことを言います。「私は大学では難しいことをやるものだと思っていました!私は功利主義はAレベルでやりました。何か別の勉強することをやってもらえますか?」

この発言は、多くのことを明らかにします。最も重要なことは、倫理学を「やる」ことは情報を覚えることであるという見解です。その見解があるために、学生は「功利主義をやった」と言うことができます。彼らはいくつかの重要な事実と議論を学びました。しかし、哲学はそのようなものではありません。哲学を理解するためには、あなた自身が誠実になる必要があり、またあなたが何を考えているのかを尋ねる必要があります。そしてそのことをガイドとして用いて、学習した考え方を批判的に分析し、あなたが正当化できる結論へとあなた自身を導きます。哲学とは、いくつかの重要な事実や、他の人が言っていることを単に書き留めることに還元できない、生き生きとしたダイナミックな主題なのです。

ある人たちは「倫理」と「道徳性」を区別します。私たちはしません。私たちにとっては、それらの違いの間には何もぶら下がっていません。あなたは、この本の中でそれらの用語を切り替えて使っているのを目にするでしょう。したがって、この区別にこだわることはありません。

## 倫理をうまくやる:合法性と道徳性

道徳的な問題は法律上の問題とは異なりますが、当然ながら、道徳的な問題は法律に対して何らかの影響を及ぼすかもしれません。児童労働が道徳的に容認できないということは、私たちがそれに対して法律を持っていることを意味するかもしれないです。しかし、ある土地の法律を見ることによって、何かが道徳的に正しいのか間違っているのかを答えることは、役に立ちません。それがなぜかは、非常に分かりやすいです。法的に容認されているが道徳的に受け入れられない行為、あるいはその逆の行為をしている国を想像してみてください — この区別について、よく使われているナチス・ドイツの例が心に浮かびます。したがって、倫理についての議論の中で、法的な問題について話すことにはとても慎重になってください。かなり多くの場合には、そのような点は意味をなさないでしょう。

## 倫理をうまくやる:思慮深い理由と道徳的な理由

道徳的な理由と思慮深い理由は、分けておくものです。思慮深い理由は、物事をやる際の私たちの個人的な理由に関係しています。

いくつかの例を考えてみましょう。奴隷制を擁護するとき、人々は奴隷制を維持する理由として、それが経済を支えているという事実をよく引き合いに出していました。もちろんこれが理由となることは事実です。それは思慮深い理由です。貿易業者やプランテーション所有者のような、奴隷から恩恵を受けた人にとっては、特にそうです。しかし、そのような理由は、奴隷制の道徳的な問題にとって私たちの助けとはなりません。私たちはこう言うでしょう「OK、だけど、それが経済を助けるからってなんだっていうんだ!それは正しいのか、間違っているのか?」

## 倫理をうまくやる:規範的な主張と記述的な主張

もう1つの重要な違いは、記述的および規範的な主張の間にあります。これは時には「である/べきである」の隔たりと呼ばれます。私たちは後の章、特に第6章でこの問題に戻ります。しかし、それは一般的な倫理学の対話で非常によくある間違いであり、私たちはここでそれを強調しておく必要があると感じました。

いくつかの例を考えてみましょう。このような見出しを想像してみてください:「科学者たちは、私たちが赤いズボンをはいている人を殴りつけたい理由を説明する遺伝子を発見した。」この記事には、遺伝子と統計的証明を示す多くの科学が含まれています。それでも、これらの何ひとつとして、赤いズボンをはいている人に向かって暴力をふるうことが道徳的に受け入れられることかどうかについて、私たちに教えてはくれません。人々が何らかの形で感じ、行動する理由についての説明は、人々が道徳的にどのように行動すべきかについては、未解決のまま残しています。

肉を食べることの倫理に関連して、もうすこし深刻な例を考えてみましょう。肉食の支持者は、しばしば私たちの切歯を指摘します。これは、私たちが肉を食べることが自然であることを示しています。これは、肉を食べることが道徳的に容認できると考える理由として使用される事実です。しかし、これは悪い議論です。私たちが切歯を持っているということだけでは、私たちが道徳的にどのように行動すべきかを教えてはくれません。それは、なぜ私たちが簡単に肉を食べられるのかを説明するかもしれませんし、私たちが肉を食べるのを好む理由すら説明するかもしれません。しかし、これは道徳的な質問には関係がありません。私たちのことが信じられませんか?歯科医師たちが、私たちの歯は他の人間を生きたまま食べるよう「設計」されていることを発見した、と想像してみてください。このことは、人間を生きたまま食べることが正しいか間違っているかについて、私たちに何を教えてくれますか?何もありません。

## 倫理をうまくやる:思考-実験

あなたはまた、特にこの本を読む際には、「思考実験」として知られる哲学的な仕掛けのことに気づくでしょう。これらは仮説的な、時には非現実的な例であり、ある問​​題についての私たちの考えを助けるように設計されています。

たとえば、あなたが時間をさかのぼることができると想像してください。あなたは、まだ子供のころのあなたの祖父に銃を向けています。あなたが引き金を引くことは可能なのでしょうか?または、線路を走っている路面電車があると想像してください。あなたは、1人の太った男を線路に突き飛ばすことによって、路面電車を止めることができ、それにより5人の命を救うことができます。これは道徳的に正しい行いですか?

ここでは詳細は重要ではありません。重要なことは、「そうだけど、でもそんなことは決して起こりえない!」と答えるのでは不十分だということです。思考実験は、私たちが特定の問題について考えるのを助けてくれる仕掛けです。それらが実生活で可能かどうかは、私たちがその考えを行うのを止めるわけではありません。実際のところ、思考実験を使用するのは哲学だけではありません。アインシュタインがブラックホールの近くで自分の時計を見たら何が起きるかを質問した時には、それは思考実験でした。事実として、他のほとんどの科目で思考実験を使用しています。哲学は、より頻繁にそれらを使用し、そしてしばしばそれらが少し奇妙であるというだけなのです。

## 倫理をうまくやる:不一致を理解する

最後に、私たちは、よくある悪い議論にあなたの注意を引きつけておきたいと思います。悪い議論が間違いへとつながることを知っておいてほしいからです。友人たちのグループが、どの国が最も多くのオリンピックの金メダルを獲得したかについて、議論しているところを想像してください。マックスは中国だと言い、アラステアは米国だと言い、ディンは英国だと言います。ここには、一般的な無知や不一致があります。しかしこれは、「どの国が最も多くのオリンピックの金メダルを獲得したか」という質問に対する答えがないことを意味しているのでしょうか。違います!私たちは、人々が意見に同意しないという事実から、答えがないという結論に移行することはできません。今度は、私たちが非常に頻繁に耳にする似たような議論を考えてみましょう。

あなたとあなたの友人が、安楽死が道徳的に容認できるかどうかを議論していると想像してください。ある人は「はい」と言い、別の人は「いいえ」と言います。あなたたちはどちらも、異なる文化がどのように安楽死に関する異なる意見を持っているかを挙げています。不一致があるというこの事実は、安楽死が道徳的に容認できるかどうかという質問に対する答えがないことを意味していますか?繰り返しますが、答えは「いいえ」です。そのような答えはオリンピックの場合には導かれませんでしたし、道徳的なものでも導かれません。そのため、異なる文化が異なる道徳観を持っているからといって、それだけでは、道徳的真理が存在せず、その質問に対する答えがないということは示されません。

もしあなたが、倫理学の中では道徳的な真理が欠如しているという考え方に興味があるなら、メタ倫理学の章で道徳的錯誤理論家がまさにその立場を擁護します。

## まとめ

AQAまたはOCRのいずれによったとしても、あなたはこの章の中核的な内容について評価されることはありません。もし評価に特に関連する内容がある場合、それらは以下の章で適切な詳細をもって説明されます。

それでも、私たちは、倫理学について考えるときに避けるべきいくつかの誤りと、その代わりに検討すべきいくつかの戦略とを示せたと思っています。あなたが、勉強中にここで議論された考え方を時折見直して、あなた自身の議論の筋道を試し、あなたにとって「よく考える」ことがどのように進展しているかを評価することは、きっと価値があることです。それは弱点とはならないでしょう!著者のどちらも、そして正直な哲学者ならだれでもあなたに請け合うことができます — 哲学は難しい!私たちは、あなたにとってこの教科書が役に立つものであり、倫理を通したあなた自身の旅のお手伝いをするのに有益であることを望んでいます。

## 質問と課題

1. 誰かに哲学とは何であるかを説明するとき、あなたならどうしますか?
2. 哲学は重要だと思いますか?はいの場合、なぜですか?いいえの場合、なぜですか?
3. いくつかの倫理的な質問を列挙してください。
4. あなたの質問が規範、応用、またはメタ倫理のどれであるかわかりますか?
5. 応用倫理学、規範倫理学、メタ倫理学の間につながりはありますか?最初に勉強するのが最も良いとあなたが思う倫理学のタイプはどれですか?また、最後に勉強するのが最も良いと思うのはどれですか?
6. 思慮深い理由と道徳的な理由の間の違いは何ですか?
7. 「である/べきである」の隔たりによってなにが意味されていますか?倫理的な質問を議論するときにこれを覚えておくことが重要なのはなぜですか?
8. 科学は倫理的議論に(もしあるとしたら)どのような役割を持っているのでしょうか?
9. 思考実験とは何ですか?なぜそれらは哲学者にとって有用になりえるのでしょうか?
10. 「道徳的な問題に関しては、非常にさまざまな見解があるため、道徳的な真実はあり得ない。」あなたはこの議論の筋道をどう考えますか?

## 参照文献

Hospers, John, An Introduction to Philosophical Analysis, 4th ed. (New York and London: Routledge, 1997), https://doi.org/10.4324/9780203714454