# カント倫理学

> その恐ろしいタイトルにもかかわらず、カントの「道徳の形而上学の基礎づけ」は本当に素晴らしい小さな書物の1つである。この本は、その大きさに対してほとんど滑稽なまでに不釣り合いな影響を人間の思考に及ぼしている。^[H. J. Paton, ‘Preface’ in I. Kant, Moral Law, p. 7.]

## カント倫理学入門

イマヌエル・カントは、1724年に東プロイセンのケーニヒスベルクで生まれ、そこで1804年に死去しました。カントは、科学、芸術、倫理、宗教、自己、現実など世界のあらゆる面について、私たちがどのように考えるかに対して革命的な変化をもたらしたことで有名です。彼はあらゆる時代の中でも最も重要な思想家の1人であり、これはカントが本当にひどい著述家であるという事実によってさらに顕著なものとなります。彼の文章は専門的な言葉でいっぱいで、非常に長く、信じられないほど難解です。あなたに警告しておきます!

カントは啓蒙主義の時代(1685–1815年)における合理主義的な作家です。私たちは、私たちの感覚から、そして理性の能力を通して知識を得ることができる、と彼は考えています。これは、彼の一般的な哲学的アプローチが、私たちが先験的(ア・プリオリ)に知ることができるものを尋ねることによって始まる、ということを意味します。

これは彼の仕事を理解する上で重要ですが、それはまた、倫理学に関する彼の著作のことを少し奇妙なものに見せます。私たちは、たとえば数学などとは異なり、倫理学の研究では、世界の中の私たちの周りで起こっていることに目を向けるべきだと考えています。しかし、カントは倫理的な考え方について考えるにあたって、彼の目を「内側に」向けることによって始めます。

カントは、これをやることで、人々が何らかの行動が正しいあるいは間違っていることを認識するようになると信じています。その認識にとっては、私たちがどのように感じるかは関係なく、またいかなる結果が生じるかも関係ありません。カントにとって行動とは、その行動が彼が「定言命法」と呼ぶものを尊重するならば正しいものです。たとえば、嘘をつくことは定言命法を尊重することに失敗するため、それは間違っており、それは、私たちが嘘をつくことについてどう感じるかや、私たちが実際に嘘をついたならば何が起きるかとは関係なく間違っています。正しかったり間違っていたりするのは、結果ではなく行動です。これは、カントの理論が目的論的ではなく、義務論的であることを意味します。それは私たちの目的/目標/結果ではなく、私たちの義務に焦点を当てています。

しかしながら、道徳性は感情や結果ではなく理性に基づいているという考え方については、何か直観的なものがあります。我が家のペットの猫、スパルタンを考えてみましょう。彼はベッドカバーの下で爪とぎをしたり、鳥にニャーと鳴いたり、自分のしっぽを追いかけたりといった行動をとっています。今度は私の娘ベスを考えてみましょう。彼女は妹の世話をしたり、ホームレスを助けたりといった行動をとっています。

スパルタンの行動は道徳的ではない一方、ベスの行動は道徳的です。スパルタンの思考と行動は、彼の欲望と性向によって引き起こされます。彼は自分がそうすることを望むときには食べて、遊んで、眠りますが、彼にとってみればなんの理由付けもありません。対照的に、ベスは彼女が持っているさまざまな理由、つまり妹やホームレスの世話をする理由を思案することができます。

そこで私たちは、私たちがある種の欲望を持っているためではなく、私たちが合理的であるというまさにそのために、人間が道徳的存在であると考えるかもしれません。私たちは「後ろに下がって」、私たちが何をしているのか、そしてそれはなぜかを熟考する能力があります。カントは確かにそう考えており、彼はこの洞察を彼の出発点としています。

## いくつかの重要な考え方

### 義務

カントの倫理学における主な仕事は、「人倫の形而上学」(1797年)と「道徳の形而上学の基礎づけ」(1785年)です。どちらも特定の状況について実践的な助言を与えるものではなく、むしろカントは、合理的な熟考を通して、道徳性の最上の原則を確立しようとしています。

彼は「義務」の概念から始めます。これはやや古めかしい用語ですが、その背後にある考え方はよく聞いたことがあるはずです。あなたの友人があなたに対して、自分は妊娠していると言いましたが、あなたが彼女の秘密を守ると約束するように頼んでいるところを想像してください。その後の数週間、この好奇心をそそるちょっとしたゴシップがあなたの口先まで出かかりますが、あなたは約束のために誰にも言わないでいます。私たちが(本当に)やりたいと望むことに関係なく、私たちに求められることとして私たちが認識している物事があります。これこそが、カントが義務によって意味したものです。

しかし、これは疑問を提起します。私たちが正しいことをするように私たちを動かすものが欲望でないなら(本当に強い欲望であっても)、それはいったい何なのでしょうか?私たちの例では、ゴシップへの強い欲望にもかかわらず、私たちが約束を守っているのはなぜでしょうか?カントの答えは「良い意志」です。

### 良い意志

カントは、良い意志に対して次のような特徴付けをします。良い意志とは効果に関係なく良いものです:

> 良い意志は、それがもたらす効果や達成のために良いのではなく、いくつかの提案された目的を達成するのに適しているために良いのである。それはその意志のみを通じて良いものである。すなわち、それ自体で良いのである。^[I. Kant, Moral Law, p. 40.]

良い意志はまた、何の留保もなしに良いものです。

> この世界においては(この世界の外ですら)、良い意志を除いては、何の留保も無しに良いものとして受け取られることができる何らかのものを思い描くのは不可能である。[Ibid., p. 39.]

カントは何を意味しているのでしょう?では、行動を良いものとするであろうとあなたが考えるもの、たとえば幸福、喜び、勇気などの中からあなたが好きなものを選んでください。そして、それらの特徴を持つ行動がその行動を悪いものとしてしまうような状況をあなたが考えることができるかどうか、自分自身に聞いてみてください。

それはあるようです。猫を蹴るときに幸福になる人を想像してみてください。または拷問に喜びを見出す人。または連続殺人犯であって、彼女の勇気によって白昼堂々と子供を誘拐することできる人。そのような場合には、幸福、喜び、勇気は行動を悪いものとします。カントは、1つのこと、すなわち良い意志を除いて、どのようなものであっても全てのものについてこのような考え方を繰り返すことができると考えています。

良い意志とは、他のなにものとも違って無条件に良いものであり、良い意志を良いものとするのは、その他の態度や、結果や、行為主体の特性ではなく、ただその意志だけです。カントでさえ、これはずいぶんと奇妙な考え方のように聞こえると思っています。そこで、どうやったら彼(と私たち)は、良い意志というものがそもそも存在すると確信することができるのでしょうか?

マハトマ・ガンディー(1869–1948年)によるインドの独立のための非暴力の抗議を考えてみましょう。彼は平和的に立っていましたが、イギリスの警察は彼を殴りました。これは、反撃するという圧倒的な欲望があったにちがいないケースです。しかし、彼はそうしませんでした。カントは、このタイプの行動の中で、私たちが(彼が言うところの)「宝石のように輝く」良い意志を「見る」と主張するでしょう。^[Ibid., p. 40.]このようなひどい暴力に直面している際のこのような力強さを見ると、私たちは謙虚になり、カントが言うその道徳的価値を認識することができます。明らかに、すべての行動がガンディーのものと同じくらい重要なわけではありません!しかしながら、カントは、対立する欲望にもかかわらず実行されるこのような行為は、良い意志によるものだと考えています。そのような行動(あなたは他に何か思いつきますか?)を考慮することは、私たちが良い意志が存在することを認識できるということを意味します。

## 義務のために行動することと、義務に従って行動すること

義務と良い意志の性質について上で述べたことから、私たちは、カントが良い意志から行動することは義務のために行動することであると言う理由を理解することができます。私たちは、別なように行動したいという欲望にもかかわらず、行動します。カントにとってこれは、義務のために行動することは、ある行動が道徳的価値を持つことができる唯一の方法であるということを意味します。私たちは、私たちの行動が義務のために実行されるには何をしなければならないかを以下で見ていきます。しかしながら、私たちがこれをやる前に、私たちはこの道徳的価値についての点に関してきちんと明確にしておく必要があります。

あなたが友人と歩いているところを想像してみてください。あなたは通りで誰かがお金をせがんでいるところを通り過ぎます。あなたの友人は泣き始め、財布を取り出して、その物乞いにいくらかのお金を与え、あなたに向かって、自分はその貧しい男にひどく共感を感じたので彼を助けずにはいられなかった、と伝えます。

カントにとって、あなたの友人の行動にはなんの道徳的価値もありません。なぜなら、彼がお金を渡すように動かしたものは、義務というよりむしろ共感であるからです!彼は義務に従って行動しています。しかしながらカントは、そのような行動を道徳的な行動と言うのは正しくないかもしれないが、そのような行動は価値があるものなので、あなたの友人は称賛されてしかるべきだと考えています。

この点をより明確にするために、カントは、他人の苦しみに対してなんの同情もなく、彼らを助ける性向がない人を考えるよう私たちに求めます。しかし、これにもかかわらず:

> …それでも、彼は自らの死人のような無感情さから涙を流し、なんらの性向も持ち合わせていないような行動をするが、しかし、義務から生じたときにのみ、初めて彼の行動は真正な道徳的価値を持つ。^[Ibid., p. 43.]

私たちの友人とは対照的に、この人は義務のために行動しているので、その行動は道徳的です。ただし、私たちは注意しなければなりません。カントは、私たちに感情的に荒れ果てたロボットになるように言っているわけではありません!彼は、私たちが道徳的に行動する前に、私たちは同情、共感、欲望、愛、性向を取り除く必要があると言っているわけではありません。そのようなことは、カントの道徳哲学をばかげた役立たずのものにしてしまうでしょう。

カントがなぜこれを言っていないかを見てみましょう。他人に何かを与えるなどの行動を考えてください。私たちは、もし行為主体がそうしたいと望んでいなかったとしても、他人に何かを与える行為が行われたかどうかを尋ねるべきです。答えが「はい」の場合、その行為は道徳的価値があります。これは、行為主体が実際にそのような欲望を持っているときでも一貫しています。カントの質問は、行為主体が欲望を持っているかどうかではなく、何が行為主体を行動するように動かしたかです。もし彼らがその欲望のために行動した場合、彼らは義務に従って行動しており、彼らの行動は道徳的価値を持ちません。もし彼らが義務のために行動し、そしてたまたまそのような欲望を抱えていた場合、彼らの行動は道徳的価値があります。

## 定言命法と仮言命法

私たちがカントに同意し、義務のために行動したいならば、私たちは何をすべきでしょうか?彼の答えは、私たちが道徳の法を尊重して行動しなければならないということです。彼は実際にこれがどのように機能するかの2つの例を持っています。それは、嘘をつくことと自殺についてです。私たちは第13章で嘘をつくことについて見ていきます。また、カントの自殺の例については、私たちはこの章の最後で考察することにします。しかしながら、それを行う前に、カントが道徳の法を尊重して行動することについて話すときに、カントが何を念頭に置いているかを私たちは知っておく必要があります。

道徳の法とは、彼が「定言命法」と呼んでいるものです。彼はこれに3つの定式化があると考えています。

> CI-1:…あなたがその格率を普遍的な法にし得るように、と同時に普遍的な法にするように、その格率に従ってのみ行動せよ。^[Ibid., p. 15.]

> CI-2:そのために、あなたは人間性(あなた自身の人格の中にあるものと、他の人の人格の中にあるもの)を、決して単なる手段としてではなく、常に同時に目的として使用するように行動せよ。^[Ibid., p. 66.]

> CI-3:…すべての理性的な存在は、彼の格率を通じて、あたかも常に彼が目的の普遍的な王国の立法者であるかのように行動しなければならない。^[Ibid., p. 21.]

私たちはこれらを順番に検討し、これらがどのようにリンクされているかを示します。それでは、CI-1を考えてみましょう。

カントの考え方は、私たちがこの「テスト」を使用して、どのような格率が道徳的に許容されるかを見るということです。もし私たちがそれに従って行動するならば、私たちは義務から行動しており、私たちの行動には道徳的価値があります。それでは、これが何を意味するのか見てみましょう。

まずは、「定言」および「命法」が何を意味するかは、検討しておく価値があります。命法とは単なる命令のことです。「部屋を掃除しなさい!」は、私が毎週土曜日に娘に与える命法です。「この門の前に駐車しないでください!」は、我が家の隣人の門に貼ってある命令です。「あなたの心と精神と魂をすべて込めてあなたの神を愛しなさい」というのは聖書からの命令です。

「定言」の部分はどうでしょうか?もしある命令が定言によるものであれば、人々は、それに従うことについて彼らがどう感じるかに関係なく、また結果がどうなるであろうかや、誰が彼らに対してそれに従うように言ったかや言っていないかに関係なく、それに従うべきです。たとえば、「赤ちゃんの皮を剥がすな」という命令は定言的です。あなたはこれをするべきではないですし、そして、これがあなたの人生の野望であったり、あなたが本当にそれをやりたがっていたり、あるいはあなたの教師があなたにそれをするように言ったり、といった事実は完全に無関係です。

これを、仮言命法と比較してみましょう。もし私が娘に自分の部屋をきれいにするように言うならば、これは仮言的です。これは、彼女が部屋をきれいにすべきかどうかは、彼女と私についての条件に依存しているからです。もし彼女が清潔な部屋について気にしていなければ、そして彼女の父が何を考えているのかについて気にしていなければ、彼女が彼女の部屋を掃除するべきであるということは真実ではありません。ほとんどの命令は仮言的です。たとえば、「勉強しなさい!」というもの。あなたは、あなたについてのある種の事柄が真実である場合にのみ勉強するべきです。たとえば、あなたが良い結果を出すことを気にかけていること、あなたが試験に合格したいこと、などです。

カントは、道徳的な「べき」 — たとえば「あなたは嘘をつくべきではない」 — は定言的であると考えています。それらは、人々がそれらについてどのように感じているかにかかわらず、人々に対して適用されます。

私たちが次に必要なのは、「格率」という考え方です。これは比較的単純であり、以下の例を通じて最もよく分かります。私が虚偽の約束をするかどうかを考えているところを想像してみてください。もしかしたら、私があなたに返済するという虚偽の約束をすることによって、あなたからお金を貸してもらえる可能性が高くなる、と私は思っているのかもしれません。その場合、私の格率は「私が虚偽の約束をすることで恩恵を受けられるときにはいつでも、私はそうするべきだ」というようなものになります。

自分が落ち込んでいると感じているために私は運動することに決めた、ということを想像してみてください。そこでは私は、「私が落ち込んでいると感じるときにはいつでも私は運動するだろう」という格率に基づいて行動していると言えるかもしれません。ある格率は、私たちが行動するための一般原則またはルールです。私たちは、一連の格率を決定して、おそらくそれらを書き留めて、それに従って生きていこうとするのではありません。むしろ格率とは、私たちがある行動のことをそれらの言葉を使って考えたことがあるかどうかにかかわらず、その行動を理解することができるような原則またはルールのことです。

## 定言命法の第1の定式化

これらのこまごまとしたことを、CI-1との関連でまとめてみましょう

> …あなたがその格率を普遍的な法にし得るように、と同時に普遍的な法にするように、その格率に従ってのみ行動せよ。^[Ibid.]

CI-1が規定する「テスト」は次のとおりです。行動することについてあなたが考えている格率を思い浮かべて、そして、あなたが(i)それが普遍的な法になると考えることができるかどうか、あるいは(ii)それを普遍的な法とさせることができるかどうかを尋ねてください。もしある格率が(i)か(ii)のいずれかに失敗した場合、あなたはその格率にしたがって行動する正当な理由はなく、それを行うことは道徳的に許容されません。もしある格率がCIテストに合格した場合は、道徳的に許容されます。

カントは、CI-1テストが、何が道徳的で何が道徳的でないかに答えを出す方法であると言っているわけではありません。おそらく、私たちは、非道徳的であってこのテストに合格する、たくさんの格率を考えることができます。たとえば「私が退屈なときに私はテレビを見る。」

同様に、彼は、ある格率が普遍化できないなら、それは道徳的に許容されないと言っているわけでもありません。いくつかの格率は数学的に不可能です。たとえば、「私が運動しに行くときにはいつでも、私は平均時間よりも長くそれを行うだろう。」全員が「平均」以上に何かをやるということは考えることができないので、この格率は普遍化することはできません。

最後に、格率は普遍的な法とされることができなければならない、ということを覚えておく必要があります。これは重要なことです。なぜなら、「もしあなたの名前がジルで、あなたの身長が5フィート11インチならば、あなたは嘘をついていい」といった格率は、あなたが名前をジルとすることができず、あなたの身長を5フィート11インチにすることができないために普遍化することができません。格率は普遍的な法とすることが可能でなければならず、これが成立するためには、格率は少なくとも実際に起こることが可能でなければなりません。これは、名前、身長、場所などのより特定的な詳細を追加するだけで、私たちはどのような格率もCI-1テストに合格させることができるのではないかというよくある懸念が破綻することを示します。これは非常に抽象的なものです(私たちがカントの仕事について何と言ったか覚えていますか!)。1つの例を考えてみましょう。

## 完全な義務と不完全な義務

借金を確実にするために虚偽の約束をするという例を思い出してください。この格率は、「そうすることによって恩恵を受けられるときにはいつでも、私は虚偽の約束をするべきである」です。問題は、私がこの格率を普遍的な法と考えることができるか、あるいは、この格率を普遍的な法にさせることができるかどうかです。

私はできないでしょう。もし全員がこの格率に従ったならば、私たち全員は、皆がそうすることで恩恵を受けられるならば全員が虚偽の約束をすることができると信じることになります。カントは、そのような状況は考えられないと思っています。なぜなら、約束をするというまさにその考え方が、信頼に依拠しているからです。しかし、「それがあなたに恩恵をもたらすときはいつでも、あなたは虚偽の約束をすることができる」が普遍的な法になれば、そこには信頼などなくなり、それゆえ約束をすることも起こりません。そのため、約束をすることと嘘をつくことの考え方を単純に考慮するだけで、私たちはこの格率がテストに合格しないことがわかります。そして、私たちはその格率を普遍化することができないので、虚偽の約束をすることは道徳的に許容できなくなります。これは、原則として、誰もが同じ理由で推論の線をたどることができるため、すべての状況において、すべての人々にとって普遍的に真実です。

(i)で落第した格率は、カントが概念上の矛盾と呼ぶものであり、そして、(i)で落第するということは、カントが完全な義務と呼ぶものに対して私たちが取り組んでいることを意味します。私たちの例では、私たちは虚偽の約束をしないという完全な義務があることを示しました。

もう1つの別の例を考えてみましょう。お金を必要としている人が私たちにお金を求めているが、私たちは彼らを助けないと決断するところを想像してください。この場合、私たちの格率は、「誰かがお金を必要としており、お金を求めてきたときにはいつでも、彼らにお金を与えてはいけない」というものです。これはCI-1テストに合格しますか?

いいえ、これはCI-1テストに落第します。この格率が(i)に合格するというのは正しいですが、貧しい人々に与えないということは、お金を手放すというまさにその考え方を脅かすことはありません。カントは、これについて考える人は誰でも、この格率が(ii)に落第し、それゆえ、それは道徳的に許容されないことがわかる、と考えています。理由は以下の通りです。

あなたが将来お金が必要になるかどうかを知ることはできません。また、もしあなたがお金が必要になれば、おそらくあなたは助けてもらいたいと望むでしょう。そのようなケースでは、あなたは、「人々はお金が必要な人を助けるべきではない」という格率は普遍的な法となるべきである、とするかどうかについて、あなたは一貫性がなくなります。なぜならあなたは、人々が将来においてお金が必要な人、つまりあなたを助けることを望むであろうからです。

だから、私たちは、「誰かが困っているときはいつでも、彼らを助けない」という格率を普遍的な道徳の法にさせることができません。これもやはり、誰もがたどることができる思考プロセスであり、それは、この道徳的主張がすべての状況においてすべての人々にとって普遍的に真実であることを意味します。(ii)に落第した格率は、カントが意志における矛盾と呼ぶものであり、(ii)で失敗するということは、カントが不完全な義務と呼ぶものに対して私たちが取り組んでいることを意味します。

CI-1は単純に「もしみんながそれをやったらどうなるの?」と尋ねているだけではない、ということを認識しておくことが絶対に重要です。CI-1は功利主義の一形態ではありません(第1章を参照)。カントは、人々がそれをしたら、世界はひどい場所になってしまうので、虚偽の約束をするのは間違っている、と言っているわけではありません。むしろカントは、その格率が普遍的な法になることを私たちが考えることができるのか、そうさせることができるのか、について尋ねています。

## 定言命法の第2の定式化

第2の定式化(CI-2)は以下の通りです:

> そのために、あなたは人間性(あなた自身の人格の中にあるものと、他の人の人格の中にあるもの)を、決して単なる手段としてではなく、常に同時に目的として使用するように行動せよ。^[Ibid., p. 66.]

カントはCI-1とCI-2が同じコインの2つの面であると考えていますが、正確にはそれらがどのように関連しているかは学問的な議論の問題です。非常に簡単に言えば、CI-2はあなたが人を使用するべきではないと言っています。なぜなら、もしあなたがそうするならば、あなたは彼らを理性的な行為主体として扱うことに失敗しており、これは道徳的に間違っているからです。

たとえば、もし私があなたに知らせることなくあなたのエッセイを使用した場合、私はあなたを理性的な行為主体として扱っていません。私はあなたのエッセイについてあなたに尋ねて、あなたが私にそれを使わせることを自由に選ぶようにすることもできたはずです。しかし、私があなたに尋ねなかったことを考えると、私はある意味であなたの代わりに選択をしたので、あなたを理性的な行為主体として扱いませんでした。ここで、カントによれば、私は常にあなたを手段ではなく目的として扱うべきです。私は常にあなたを自由で理性的な行為主体として扱うべきです。

そのため、カントの理論は、人々の尊厳を尊重する方法を持っています。私たちは、人々のことを、人種、ジェンダー、教育、育ちなどではなく、彼らが理性的な行為主体であるという根拠に純粋に基づいて、尊敬と敬意をもって扱うべきです。このことからあなたは、カントの理論が「権利」について話すことを可能にする、ということがわかります。もし誰かが権利を持っているならば、彼らはジェンダー、教育、育ちなどにかかわらず、この権利を持っています。たとえば、ジルは、彼女が人間であるために言論の自由の権利を持っています。その結果、彼女の所在場所、個人的な状況、関係の状態、政治的な見方などを変更したとしても、その権利は消えません。結局のところ、彼女は人間であることをやめることはありません。

重要なこととして、CI-2は、あなたが誰かのことを手段または目的のどちらかとして扱うと言っているわけではありません。私は誰かのことを手段として扱うことで、彼らを目的として扱うことができます。たとえば、あなたがタクシー運転手になることを自由に決めたとします。もし私が、空港に連れて行ってもらうように頼むことによって、あなたを手段として使うとすると、私はあなたを目的としても扱うことになります。しかし、カントは、私があなたを理性的な行為主体として尊重しているので、これが道徳的に間違っているとは信じていません。結局のところ、あなたはタクシー運転手になることを選んだのです。もちろん、もし私があなたの車に乗り込んで、あなたの頭に銃を突きつけ、空港に連れて行くように頼むならば、私はあなたを目的として扱ってはおらず、むしろ専ら手段としています。これは間違っています。

## 定言命法の第3の定式化と要約

定言命法の最後の定式化は、CI-1とCI-2の組み合わせです。これは、私たちに対して、CI-1で行動する人々だけで構成されている王国を想像するように求めています。彼らは、普遍的な法になることができないような格率によっては決して行動しません。このような王国では、人々は人々のことを目的として扱うでしょう。なぜなら、CI-2はCI-1に合格するためです。これが、CI-3がしばしば「目的の王国」定式化と呼ばれる理由です。

> …すべての理性的な存在は、彼の格率を通じて、あたかも常に彼が目的の普遍的な王国の立法者であるかのように行動しなければならない。^[Ibid., p. 21.]

要約すると、カントは、行為が義務のために行われた場合に限り、行為には道徳的価値があると考えている、ということを私たちは見てきました。行為主体は、彼らが道徳の法を尊重して行動しているならば、義務のために行動しています。彼らはそれを、定言命法の定式化の1つに従うことによって行います。

その結果、カントは、行為は結果や欲望とは無関係に、普遍的な形で間違っていたり正しかったりすると考えています。もし嘘をつくことが間違っているならば、それはすべての事例で間違っています。このことすべてから、私たちは、ありとあらゆる状況についての道徳的なルールを教えてもらうことはできないということが導かれます。そして、カントは、そのようなものは私たち自身が理性的に考えることによって見つけ出すように私たちに委ねられている、と信じています。

カントの倫理学について書かれた多くの書籍や学術誌の記事があり、現在も増え続けています。彼は道徳性の本質について深く核心を突く洞察力を持ち、人間であることとは何なのかについてのいくつかの基本的な疑問を提起します。カントの道徳理論は個々の個人的状況、人種、ジェンダー、民族性に目をつぶったものであるため、彼の理論は過激なまでに平等主義です。誰もが道徳の法の前では平等です!

これに関連して、彼の理論は個人の権利、そして関連して、彼らの尊厳を尊重します。私たちの権利の概念を捉えようとするどのような理論であっても、権利とは状況が変化した場合でも消滅しないものであるという考えを尊重できる必要があります。ジルには生きる権利があります。そこで話は終わりです。私たちは、「もし…ならば」ジルは生きる権利を持っており、この空白部分を記入しなければならない、とは言いません。これがまさに、カントの理論が私たちに与えてくれるものです。CI-1は例外を持たない格率を生成し、CI-2は私たちがすべての人を彼ら自身として常に目的として扱い、決して目的のための手段としてのみ扱うべきではないと教えてくれます。それは、たとえば、私たちはジルを殺すべきではない、ということを私たちに教えており、そして、これはどんな状況においても当てはまります。

しかし、カントの仕事が提起した多くの難しい質問があります。私たちはこれらのいくつかを以下で考察します。しかしながら、この本の中で議論しているすべての哲学的な考え方と同様に、カントの仕事はまだきちんと生きていて、世界中に擁護者を抱えています。私たちがこれらの懸念へと向かう前に、私たちはカントが自殺に関して与える例を取り上げてみます。

## 自殺に関するカント

カントは、種々のとげのある例を取り上げることで悪名高いです。彼が言及しているものの1つは自殺です(もう1つは嘘をつくことであり、13章を参照のこと)。これは感情的になる話題であり、精神衛生や宗教についての質問につながっています。カントの見解の魅力は、彼の定言命法を感情によらずに適用する能力です。彼の枠組みは、私たちが問題に「つながれ」、答えを「引き出す」ことを可能にするでしょう。これがどのように機能するのか見てみましょう。

カントは、自殺は常に間違っていると考えており、自殺を試みる人に対しては非常に厳しい言葉を持っています

> そのように行動し、人間の本性を尊重せず、自分自身のことを物として扱う者は、誰であろうとも自由意志の対象物となる。私たちは、彼のことを獣や物のように自由に扱い、私たちが馬や犬にしているように娯楽として使うことができる。なぜなら、彼はもはや人間ではないからである。彼は自分自身のことを物として扱い、自分自身の人間性を捨てており、彼は他人が彼の人間性を尊重することを期待することはできない。^[I. Kant, Lectures on Ethics, 27; 373.]

しかし、なぜ彼はこう考えるのでしょうか?これはカントの定言命法とどのように適合しますか?それでは、最初の2つの定式化を見てみましょう。

思い出しておくべき基本は、カントにとっては、すべての自殺へと駆り立てる動機が「邪悪を避ける」ことであるということです。これによって彼は、人生における苦しみ、痛み、そしてその他の否定的な結果を避けることを意味しています。すべての自殺の試みは、私たちは私たち自身を愛しているため、私たちに起こるかもしれない「邪悪を避けたい」という事実によるものです。

私が自殺することを決めたと想像してください。私の動機について今述べたことを考えると、これは私が次の格率に基づいて行動するであろうことを意味します:「私は、自己愛から、私の人生の続く期間が約束する満足よりも脅かす邪悪のほうが大きいときには、私の人生を短縮する、ということを私の原則とする。」^[I. Kant, Grounding for the Metaphysics of Morals, Ak IV, 422]

CI-1に従うと、ここでの疑問は、この格率を普遍化することが可能かどうかということになります。カントはそうは思いません。彼にとって、すべての理性的な行為主体が、自己愛の結果として、彼らの持続する存在が約束する満足よりも脅かす邪悪のほうが大きい時には、自分自身を破壊することができるようにするには、私たちはどうしたらよいのかは、明らかではありません。カントにとっては、自己の破壊につながるような自己愛は矛盾です。したがって、彼は、私たちは自分たち自身に対して、自殺をしないという完全な(不完全ではなく)義務を負っていると考えています。そうすることは道徳的に間違っています。以下はカントが述べたことです:

> 生の促進[自己愛]を刺激するように機能するのとまさに同じ感情を用いて生を破壊[自殺]するような法を持つ自然のシステムの中では、人は矛盾を一度に見る。そのため、そのようなものは自然のシステムとしては存在しないだろう。したがって、そのような格率は、おそらく自然の普遍的な法として保持することはできず、その結果、すべての義務の最上の原則に完全に反している。

ここでは、CI-1との関連で、ちょっとおかしなことに気づくでしょう。普遍化の要点については無関係のように見えます。カントは、自己愛から自分自身を破壊させるようにすることは矛盾であるとだけ言えばよかったかもしれません。この点を普遍化するよう考慮することを私たちに要求することによって、追加されるものは何もないようです。それが矛盾であるという主張に対して重みを付け加えるものではありません。

第2に、それは実際にはまったく「矛盾」ではありません!それは、嘘つきの約束の例とは異なります。この例では、約束というまさにその概念が、信頼に依拠しているように思われます。対照的に自殺の場合、「矛盾」は、どちらかというと、自殺しようとする人の動機に関するカントの仮定の副産物のように思えます。したがって、もし私たちが、自殺は自己愛によって駆り立てられる必要がないという可能性を許容するならば、私たちは「矛盾」を避けることができます。もしこれが真実ならば、「矛盾」はないでしょう。したがって、自分自身を殺さないという義務のことを(もしそのような義務があるとして)、「完全な」義務と呼ぶのは間違っているようです。そのため、最初の定式化は、カントに自殺は道徳的に間違っているという結論を与えません。

第2の定式化に移りましょう。これは、カントの自殺を試みる人々に対する厳しい評価を私たちが理解するのに役立ちます。彼はそのような人々を「対象物」、「獣」、あるいは「物」と呼んでいることを思い出してください。それでは、獣や対象物や物と、人間との違いは何でしょうか?答えは、私たちには理性があるということです。カントにとって、私たちの合理性は基本的な価値があるということを思い出してください。もし誰かの行動が他人の合理性を認識していない場合、彼らは何か道徳的に間違ったことをしています。これは、彼らを単に私たち自身の目的のための手段として扱うことになります。これらすべてを考えると、カントが何を言おうとしているのかがわかると思います。彼にとっては、自殺するということは、あなた自身を何らかの目的 — すなわち痛みや苦しみなどを避けるという目的 — のための単なる手段として扱うことであり、それそのものを目的として扱ってはいません。あなたは自分自身のことを、理性という贈り物を持つ人間としてではなく、「獣」、「物」、「対象物」として扱っています。これは道徳的に間違っています。

さらに、もしあなたがこれを行うならば、理性的な人間として尊敬をもってあなたを扱う人たちは、あなたは他人がそのようにあなたを扱うこともまた望んでいるのだと結論づけることができます。なぜなら、もしあなたが理性的であるならば、あなたは他人を対象物、獣、物として扱うことができる格率を普遍化してもよいと考えなければならないからです。したがって、彼らはあなたを獣、対象物、物として扱うことができ、そしてその上でまだ依然として理性的な行為主体として尊敬をもってあなたを扱うことができます。自殺を試みることに関しては、あなたは自分の合理性を無視しているため、あなたの行動は間違っています。あなたは目的のための単なる手段として自分自身を扱っています。

しかし、最初の定式化のように、これは非常に弱いです。あなたが自殺を試みるなかで、なぜあなたがあなた自身を目的のための単なる手段として扱っているのかは不明です。あなたは、自殺を考えることによってあなたの合理性を尊重していると考えているのかもしれません。カントが人を目的のための手段として扱うこと(たとえば、タクシー運転手)は時々うまくいくと言っていることを思い出してください。あなたがそれらの方法で人々を扱うということについて人々が同意を与えた場合には、それはうまくいきます。その場合、自殺はタクシー運転手のケースのようであるかもしれません。私たちは私たち自身を目的のための手段として扱うことを自由に決断しました。そのため、私たちは、自らを理性的な行為主体として扱っており、自殺をすることによって何か道徳的に間違ったことをするわけではありません。

カントは、ほかにもいくつか自殺が間違っていることについて語っていますが、それは「定言命法」とはリンクしていません。たとえば、彼は、人間が神の財産であり、それゆえ私たちの生は私たちが消滅させることを選べるようなものではないと話しています。しかしながら、ここでは私たちはこれについて議論する必要はありません。

カント学者の間では、カントの自殺に反対する議論は、そのままでは失敗しているという合意があります。しかし、自殺に反対するより説得力のある議論の出発点として、カントの考え方を使用する人もいます。たとえば、J・デイヴィッド・ヴェレマン(Velleman 1999)およびマイケル・チョルビ(Cholbi 2000)を参照してください。

## 問題と対応:対立する義務

すべての状況において道徳的な義務が適用されるならば、私たちが対立する義務を持っているときには何が起きるでしょうか?あなたがナチス政権下のドイツにおいて何人かのユダヤ人を地下室にかくまっていると想像してください。そして、SSの役人があなたの家のドアをノックして、あなたがユダヤ人を隠しているかどうかを尋ねると想像してみてください。カントの理論は私たちに何をするように言うでしょうか?私たちの義務は、嘘をつかないことです。これは、私たちがSSの役人に私たちの秘密を告げるように道徳的に要求されることを意味するのでしょうか?もしこれが結論なのであれば、カントの理論は道徳的に嫌なものになります。

しかしながら、カントの理論の中の要件は真実を伝えるということではなく、単に嘘をつかないという要件です。嘘をつくとは意図的な騙しについてのことであり、この例では嘘をつかない方法があるかもしれません。たとえば、私たちが単純に黙っていることのように(第13章を参照)。

この例において私たちはこのような方法で対応するとしても、おそらく私たちはそれを許さないような例を設計することができます。たとえば、もしかしたら私たちは法廷にいて、SSの役人が私たちに宣誓を求めます。この例では、黙っていることは選択肢にはならないでしょう。ユダヤ人の居場所を明らかにすることは道徳的に間違っているように見えるため、これは確かにカントの理論に不利に働くように思われます。

しかし、カントの主要なポイントとは、カントが個別の状況の特徴を考慮に入れる必要があると考えていることです。彼は、私たちの前にあるものに対して何の注意も払わずに、私たちが一般的なルールを考えなしにただ適用することを望んでいません。そのため、ピーター・リックマンはこのような事例のタイプについて次のように書いています:

> …複数の定言的/道徳的な原則がこの状況に関連していることは明白であるようだ。確かに、私たちは真実を述べるべきである。しかし、私たちはまた、無実の人を危害から守る義務も持ってはいないのだろうか?さらに、私たちは邪悪と戦う義務を持ってはいないのだろうか?私たちはここで、価値観の対立に直面している。残念ながら、私が知る限り、カントにはこの問題についての明確な議論はない。しかしながら、より小さな邪悪をより大きな邪悪と区別するという彼の一般的なアプローチが適用されるべきであると仮定することができる。カントなら、嘘をつくことは決して正しくはないが、場合によってはそれはより小さな邪悪かもしれない、と言うのではないかと私は考えている。^[P. Rickman, ‘Having Trouble with Kant?’, https://philosophynow.org/issues/86/Having_Trouble_With_Kant]

だから、ここでのポイントは、このような例はカントの理論を「ノックダウンする」批判であるということではなく、カントの理論には曖昧なところがあり、これらの特定の種類のケースには指針を与えない、ということです。実際、これは、私たちに道徳性の最上の原理とそれを進める一般的な方法を与える一方で、それぞれの状況で何をすべきかを決めることは私たちに委ねられているという点で、私たちはこれを彼の理論の利点だと考えるかもしれません。それを行うことができるかどうか、特に彼の道徳理論の他の側面と一致する方法でそれを行うことができるかどうかについては、読者が考えるように残しておきます。

## 問題と対応:直観の役割

カントの理論に対して突き付けられている最も一般的な批判の1つは、それが単に直観に反しているということです。たとえば、彼にとっては、嘘をつくことはその結果にかかわらず、すべての事例において道徳的に許容されないものです。しかし、私たちは、これが道徳的に嫌な立場であることを示す思考実験を生み出すことができるようです。

しかしながら私たちは、カントの擁護のために、なぜ私たちは直観を道徳理論のテストの形式として使うべきなのかを尋ねるかもしれません。直観は気まぐれで信頼できないということで悪名高いです。たとえあなたが思いつくことができる最も奇妙な見解を選んだとしても、その見解が「直観的」であると感じる人がどこかの時代にいるかもしれません。そのため、もしカントの理論が直観に反するような結果につながるとして、私たちはどのように心配するべきなのでしょうか?これは、この本を読むときに、あなたの心の最前線にとどめておくべき、より一般的な方法論的問題を提起します。直観は、道徳理論の形成とテストにどのような役割を(もしあるとして)果たすべきでしょうか?

## 問題と対応:定言命法とエチケット

カントは、私たちが行うよう道徳的に求められることは、理由の問題であると主張します。もし人々が正しい方法で論理的に考えるならば、彼らは、たとえば、嘘をつくことが間違っていることを認識します。しかしながら、たとえばフィリッパ・フット(1920–2010年)のような何人かの哲学者は、この理由とのつながりを懸念しています。フットの異議申し立ての強みは、彼女は道徳性が定言命法のシステムであると同意しますが、彼女はこれは必ずしも理由によるものではないと述べていることです。

フットはエチケットの例を使って彼女の議論を動かします。^[P. Foot, ‘Morality as a System of Hypothetical Imperatives’.]エチケットのルールは定言命法のように見えますが、理由によっては根拠づけられていません。例を考えてみましょう。私は大学時代にスポーツマンの友人がいました。彼は多くのチームに所属しており、彼の専攻はスポーツと運動であり、もしほんの少しでも時間があけば、彼は走るか、自転車に乗るか、プールで泳ぐかしていました。驚くべきことではありませんが、彼はいつもトラックスーツとトレーナーを着ていました!

大学2年目に、私たちの共通の友人が亡くなりました。大きくて正式の葬儀が手配されました。私の友人は、彼のトラックスーツとトレーナーでこの葬儀に行くことに決めました。私はこのことについて彼に尋ねたところ、彼の反応は、彼はそれを着るのが好きだからということでした。しかしながら、少なくとも私の考えでは、彼の欲求に基づいたこの理由は、彼が実際にはトラックスーツを着用するべきではないという事実を変えるものではありませんでした。フットはこれに同意するでしょう。そしてフットは、エチケットのルールは誰かが持つであろう特定の欲求に依拠しないため、定言的であると考えています。

しかしながら、たとえそれらが定言的であったとしても、フットはエチケットのルールは理由のルールではないと考えています。もし私たちが正しく論理づけて考えた場合でも、私たちが葬儀でトラックスーツを着用するべきではないと認識したり、(エチケットの他のルールを考えるために)三人称で書かれた手紙に対して一人称で返信するべきではないと認識したり、食事をとっている間にディナーテーブルに足を載せるべきではないと認識したりするとは、私たちは考えません。それは、単に正しい考え方の問題ではなく、むしろ共有された文化的実践の一部としてこれらの「べき」を認識することです。

これはカントが間違っていることを示すわけではありませんが、カントに対して挑戦を投げかけます。つまり、私たちは、道徳的な「べき」の定言的性質が単に共有された文化的実践の一部ではなく、理由に基づいたものであると考えるための独立した理由が必要です。この挑戦に対応するためには、カント主義者は、道徳的な「べき」の特定のケースでは、私たちは(制度的な実践ではなく)理由をもって定言的な性質を基礎づける良い議論を持っているという主張を提出しなければならないでしょう。

## 問題と対応:道徳性の領域

カントは、道徳性の領域は単に理性の領域に過ぎないと考えています。そして、私たちが理性的に考えることのできる行為主体である限りは、私たちは義務と権利を持ち、人々は私たちのことを尊厳をもって扱うべきです。これの裏面は、人間以外の動物のような非理性的な行為主体には権利がなく、カントによれば、私たちは彼らのことを好きなように扱うことができるということです!

ここでのカントの理論への挑戦は、道徳性の範囲が理性の範囲よりも大きく見えるということです。私たちには非理性的な行為主体に対する道徳的義務がある、と人々は考えています。誰かが猫を蹴っていると考えてください。私たちは、彼らが道徳的にこれをすべきでないと考えるかもしれません。しかしながら、カントの理論はこれを裏付けるものではありません。なぜなら、私たちが知っている限り、猫は理性的な行為主体ではないからです。このように動物を扱うことは間違ったことではないにもかかわらず、カントはやはり私たちはそうすべきではないと考えています。なぜなら、もし私たちがそうした場合、私たちは人間をそのように扱う可能性が高くなるであろうからです。

## まとめ

カントの道徳理論は非常に複雑で、その表現はひどいものです。しかしながら、それはとても影響力があり深遠です。ある体系の構築者として、カントの仕事は理性的な熟考から始まり、そこから彼は完全な道徳システムを発展させようと試みます。

彼は義務の概念から始めます。彼は、私たちが義務のために行動することを可能にするものは良い意志であり、良い意志は無条件に良いものであることを示しています。もし私たちが義務のために行動したいのであれば、私たちは道徳的な法の尊重から行動する必要があり、これは定言命法に従うことになります。カントは、定言命法に従うと、行為主体は道徳的に許容されるものに収束するだろうと主張します。したがって、カントは絶対的かつ客観的な道徳的真理について話すことができます。

## 学生によくある間違い

* 義務に従って行動することと、義務のために行動することを混同する。
* カントの理論には感情の入る余地がないと考える。
* カントの定言命法は、「もし誰もがそれをしたらあなたはどうなりますか?」という質問に要約することができると考える。
* 定言命法が功利主義の一形態であると考える。
* カントは、誰かをある目的のための手段として扱うことは決してできないと信じている、と考える。

## 検討すべき問題

1. あなたの人生について考えてください。あなたは自分に「やるべきこと」があると思いますか?
2. あなたの欲望や性向に関係なく、あなたがするべきことがあると思いますか?
3. 定言命法と仮言命法とは何ですか?あなたはエチケットのルールが定言的だと思いますか仮言的だと思いますか?
4. カントならSSの役人の事例にどのように返答するでしょうか?
5. あなたが誰かをある目的のための手段としてだけ扱うかもしれないいくつかの例を考えることができますか?
6. 死刑はCI-2テストに合格するでしょうか?
7. CI-2はどのようにして売春に関係するでしょうか?カントはそれが道徳的に許容されると言うだろうと思いますか?(第10章も参照)。
8. なぜカントの理論は人々の権利を尊重するのに適しているのでしょうか?
9. あなたは、私たちが動物に対する道徳的な義務を負っていると思いますか?カントなら何と言うでしょうか?
10. 道徳理論を評価する上で直観はどのような役割を持つべきだと思いますか?

## 重要な用語

ア・プリオリ

定言命法

義務論的

義務

平等主義

良い意志

仮言命法

格率

合理主義

権利

## 参照文献

Cholbi, Michael J., ‘Kant and the Irrationality of Suicide’, History of Philosophy Quarterly, 17.2 (2000): 159–76.

Foot, Philippa, ‘Morality as a System of Hypothetical Imperatives’, The Philosophical Review, 81.3 (1972): 305–16, https://doi.org/10.2307/2184328

Kant, Immanuel, Moral Law: The Groundwork of the Metaphysics of Morals, Translated and analysed by H. J. Paton (Oxford: Routledge, 2013).
<br>[「プロレゴーメナ・人倫の形而上学の基礎づけ」、土岐邦夫・野田又夫・観山雪陽訳、中央公論新社、2005年]

―, Lectures on Ethics (Cambridge: Cambridge University Press, 1997).
<br>[「カントの倫理学講義」、小西国夫・永野ミツ子訳、三修社、1968年]

Rickman, Peter, ‘Having Trouble with Kant?’, Philosophy Now, freely available at https://philosophynow.org/issues/86/Having_Trouble_With_Kant

Velleman, J. David, ‘A Right of Self-termination?’, Ethics, 109.3 (1999): 606–28, https://doi.org/10.1086/233924

―, Beyond Price: Essays on Birth and Death (Cambridge: Open Book Publishers, 2015), https://doi.org/10.11647/OBP.0061; freely available at https://www.openbookpublishers.com/reader/349
