# アクィナスの自然法理論

> 恩寵は自然の姿を破壊するのではなく、それを完全なものとする。^[T. Aquinas, Summa Theologica, I, I:8, http://www.summatheologica.info/summa/parts/?p=1]

> それらは法律の要求が彼らの心に書かれていること、彼らの良心もまた証拠を持っていること、そして彼らの思考は時には彼らを非難し、別の時には彼らを擁護しさえすることを示している。^[T. Aquinas, Romans, 2:15.
]

## アクィナスの紹介

トマス・アクィナス(1225–1274年)は、知的・宗教的な革命者であり、偉大な哲学的、神学的、科学的発展の時代に生きていました。彼は、その時代にはカルトであるとみなされていたドミニコ会の一員であり、当時の最も偉大な知識人の1人、大アルベルト(1208–1280年)の教えを受けていました。簡単に言えば、アクィナスは当時、きわめて影響力のあったプラトンの思想を離れ、その代わりに、科学、自然、神学にアリストテレスの考え方を導入したいと望んでいました。

アクィナスは信じられないほどの量を執筆しました — 実際に、彼が認定された奇跡の1つは、彼が書いた量でした!彼の最も有名な作品は「神学大全」で、これは約3500ページに及んでおり、神の存在の証明など、多くの魅力的で深遠な洞察を含んでいます。この本は、1960年代に至るまでカトリックの考えの根本的な基盤として残っていました!でも、心配しないでください。私たちは、いくつかの重要な考え方にだけ焦点を当てます!それは、特にI-II巻、質問93–95です。

## 自然法理論を動機づける:エウテュプロンのジレンマと神の命令理論

なぜ私たちが盗んだり姦淫​​したりするべきではないかということについて、宗教的な人からのありえそうな答えは、「なぜなら、神が私たちに禁じているからです。」あるいは、もし私たちが、なぜ私たちは隣人を愛し、慈善にお金を払うべきなのかを尋ねるならば、その答えはおそらく「なぜなら、神がそれを命じるからです。」何が正しく何が間違っているかと、神が何を命令し何を禁じているかとの間にこのつながりを描くことは、神の命令理論(DCT)と呼ばれるものです。

このような説明に対しては、エウテュプロンのジレンマと呼ばれる強力かつ影響力のある挑戦があります。その名前は、プラトンのエウテュプロンでこの挑戦が最初に提起されたことに由来しています。ジレンマは次のように進みます。

あるものが正しいから神はそれを正しいと命令したのか、あるいは、神がそれを命令したからそれは正しいのか、です。もしあるものが正しいから神はそれを命令したのならば、神の命令がそれを正しいものとすることはなく、神の命令は私たちに何が正しいものであるかを教えてくれるだけです。これは、なぜ何かが正しいのかを説明することに関して、単に神が説明の中から抜け落ちることを意味しています。

一方、もし神が何かを命令したからそれは正しいとすれば、何もかもが正しくなってしまうかもしれません。子供を殺したり、教会に火を放つことが、道徳的に受け入れられることになるかもしれません。しかし、もし道徳理論がそれを言うならば、それは理論が間違っているかのように見えます。

ほとんどの有神論者は第1の選択肢を拒否して、この第2の選択肢を選びます — 神の命令は何かを正しいものとします。しかし、彼らは、それが道徳性を行き当たりばったりのものにするという問題に直面しなければなりません。この「恣意性の問題」と時に呼ばれるものは、アクィナスを含む多くの人々が神の命令理論をあきらめている理由です。

それでは、アクィナスにとっては、道徳性に関して神は(もしあるとしたら)どのような役割を持っているのでしょうか?彼にとって、神の命令とは、何が正しいもので何が間違っているものかを決定するのではなく、実際のところ、私たちが何が正しいもので何が間違っているものかを理解するのを助けるためにあります。つまり、アクィナスは上記で述べたエウテュプロンのジレンマの最初の選択肢を選びます。しかし、これは明白な疑問を提起します:もし何かを正しいものあるいは間違ったものにするのが神の命令でないならば、何がそうするのでしょうか?神はただ説明から落ちてしまうのではないですか?これが彼の自然法理論が登場してくる場所です。

## 自然法理論

アクィナスの自然法理論には4種類の法律が含まれます:永久法、自然法、人定法、神定法。これらの4つの法と、それらが互いにどのように関係しているかを理解する方法は、永久法を通じてであるため、まずはそこから始めましょう…

「永久法」によって、アクィナスは、すべてのものに対する神の合理的な目的と計画のことを意味しています。そして、永久法は神の心の一部であるため、それは常に存在しており、常に存在することになるでしょう。永久法は、単にある時点で神が書くことを決めた何かではありません。

アクィナスは、すべてのものが目的を持っており、計画に従っていると考えています。彼は、アリストテレスのように、目的論者です(ギリシャ語の用語テロス(telos)は、対象物の目的、目標、狙い、あるいは真の最終的な機能と私たちが呼ぶようなものを指します。)(第3章を参照;功利主義のような目的論的な倫理学理論と混同しないように)。彼は、あらゆる物体がテロスを有していると信じています。ドングリはオークへと成長するテロスを持っています。目は見るというテロスを持っています。ネズミは食べることと繁殖することというテロスを持っています、等々(これはセックスに関する彼の見解に結びついています。第10章を参照)。もし何かがその目的/計画を達成するならば、それは永久法に従っていることになります。

アクィナスは、何かがその目的/計画を達成する限りにおいて、それは良いものであると考えています。これは常識に合致しています。「良い」目とはよく見えるもので、ドングリは、強いオークの木に成長するならば良いものです。

しかし、人間についてはどうなのでしょうか?良い目は見ることができるものであるように、そして良いドングリは成長するものであるように、良い人間は…?何になるものですか?私たちは、この文章をどうやって終わらせましょうか?あなたはどう思いますか?

アクィナスはその答えは理性であり、それが私たちをネズミや岩から区別するものだと考えています。私やあなたにとって人間として正しいことは、理性に従って行動することです。もし私たちが理性に従って行動するならば、私たちは自然法に参加しています。

もし私たちがみな理性に従って行動するならば、私たちはみな、いくつかの包括的な一般ルール(アクィナスが主たる教訓と呼ぶもの)に同意するでしょう。これらはすべての合理的な行為主体にとって絶対的かつ拘束力があり、このためアクィナスは相対主義を否定します。

最初の主たる教訓は、良いことは追求されるべきであり、行われるべきであり、邪悪は回避されるべきである、ということです。彼はこれが私たちのすべての意思決定の指針となる原理であると考えています。

これを荷ほどきする前に、「法」が何を意味するのかについて少しのことを明確にしておくのは価値があります。私たちがクルードというゲームをプレイしており、私たちは殺人犯の身元を突き止めようとしていると想像してください。そこには、ボードを動き回る方法、カードを扱う方法、殺人者を明らかにする方法などに関するルールがあります。これらのルールはすべて書き留められており、参考にすることができます。

しかしながら、ゲームを遊ぶにあたっては、他のルールがあり、それらはあまりにも明らかであるために、書き留められたり話されたりすることはありません。そのようなルールの1つは、このゲームで行われる主張が真であり、かつ偽であることはできない、ということです。もし殺人犯がプラム教授であれば、殺人犯がプラム教授ではないということは真にはなり得ません。これらは、合理的な人が単純に思考することによって認識できる内部のルールであり、他のルール(あなたは殺人犯の身元について1つの推測しかできない等)のように外部のものではありません。アクィナスが自然法を語るとき、彼は内部のルールを意味しており、外部のルールは意味しません。

自然法は、私たちが参考にするために書き留められた外部の一組のルールを生成するのではなく、むしろ、合理的な行為主体が単に合理的であるおかげで認識できるようになる一般ルールを生成します。たとえば、アクィナスにとっては、それはあたかも私たちが良いことを追求し、邪悪を避けるべきかどうかを確認する必要があるというのではなく、それは私たちが物事についてすでに考えている方法の一部であるにすぎません。アクィナスは主たる教訓のいくつかの例を挙げています:

1. 人間の命を保護し、保存せよ。
2. 子孫を再生産し、教育せよ。
3. 神を知り、崇拝せよ。
4. 社会に生きよ。

これらの教訓は、主たるものです。なぜなら、それらはすべての例においてすべての人々にとって真実であり、自然法と一貫しているためです。

アクィナスはまた、彼が「二次的な教訓」と呼ぶものを生み出すような、彼が人定法と呼ぶものを導入しています。これらには、高速道路では時速70マイル以上で運転しない、人を誘拐しない、自転車に乗るときに常にヘルメットを着用する、誰かの銀行口座にハッキングしないなどのことが含まれるでしょう。二次的な教訓は、私たちの理性によって生み出されるのではなく、政府、団体、クラブ、社会などによって課されます。

二次的な教訓に従うことは常に道徳的に容認できるとは限りません。それらは、自然法と一致しているときにのみ、道徳的に容認できます。もしそれらが自然法と一致して入れば、私たちはそれらに従うべきです。もしそうでなければ、私たちは従うべきではありません。これがなぜかを見てみるために、例を通じて考えてみましょう。

「もしあなたが女性で、サウジアラビアに住んでいるならば、あなたは車を運転することは許されません」という二次的な教訓を考えてみましょう。アクィナスは、この二次的な教訓は、恣意的な差異(ジェンダー)に基づいて人々を異なる方法で扱うため、実際的には非合理であると主張するでしょう。彼は、もしサウジアラビアの権力者の男性が実際に本当に懸命に考えれば、彼らもまたこの法律が道徳的に間違っていると認識するだろうと推論するでしょう。これは、アクィナスがこの人間の法律は自然法に適合しないと考えるだろうということを意味します。したがって、男性は運転ができ、女性は運転できないという法律に従うことは道徳的に間違っています。そのため、それは二次的な教訓として提示されていますが、自然法に従っていないため、それはアクィナスが見かけ上の良さと呼ぶものです。これは、彼が実際の良さと呼ぶような、自然法に従っている二次的な教訓とは対照的です。

主たる教訓とは違って、アクィナスはすべての状況においてすべての人々にあてはまる一組の二次的な教訓が1つだけ存在するということを約束していません。米国では道路の右側を運転する法律があり、英国では道路の左側を運転する法律があるということは、アクィナスの考えと矛盾することはありません。なぜなら、道路を運転するための正しい側が1つだけあると考える実際的な理由がないためです。

私たちは、私たち自身で主たる教訓を発見することはそれほど得意ではないことは明らかであり、その結果、アクィナスは、私たちがすべきことは人々と話し合い、相互作用することだと考えています。私たちの実際の良さ — 自然法に従うような私たちの二次的な教訓 — を発見するためには、私たちは社会の一部である必要があります。たとえば、キリスト教徒と話をして一緒に暮らすまでは、「キリスト教徒を二級市民として扱う」ことは、良い二次的な教訓であると考えるかもしれません。私たちが社会の中で他の人のことをより多く考え、より多く話をすることができるようになればなるほど、より良くなります。「社会の中で生きる」ことがそれ自体で主たる教訓となるのは、この理由のためです。

しかし、自然法や主たる教訓と二次的な教訓について私たちがすでに述べたものを見てみると、私たちは神が必要ないと思うかもしれません。もし私たちが合理的な熟考によってこれらの主たる教訓を学ぶことができるならば、神は単にこの物語から脱落します(上記のエウテュプロンのジレンマを思い出してください)。

この物語には動く部分がたくさんあるため、ここで要約しておきましょう。私たちはいま、永久法(あらゆるものにとっての神の計画/目的)、自然法(私たちの永久法への参加で、主たる教訓へと導くもの)、人定法(自然法についての真実をとらえるために人間が作り出した特定の法で、二次的な教訓へと導くもの)を手にしています。そして、ついにアクィナスは神定法を導入します。

啓示によって発見される神定法は、人定法(合理的な熟考を通じて発見され、人々によって創造されたもの)の神にとっての同等物と考えるべきです。神定法とは、神が恩寵をもって私たちに与えるのに適していると考えるものであり、「秘儀」、すなわち私たちが聖書の中で見つける神によって与えられたルールのことです。たとえば、十戒です。しかし、なぜ神定法を導入するのでしょうか?私たちは十分な法を持っていると確かに感じます。以下は、アクィナスの答えを説明する物語です。

数年前、私はある教会の牧師と話していました。彼は、既婚の男性が、浮気を終わらせるかどうかについて彼のアドバイスを求めるために訪れたという事例について私に語ってくれました。その男の理由は次のようになものでした — 「私はとてもうまくいっている浮気をしており、私たちはどちらも非常に愛しあっており、神は間違いなく私にとっての最良を望むでしょう!私たちがこんなにも幸せならば、これが間違っていることなどあるのでしょうか?」

これに応えて、牧師は聖書の十戒を開き、姦通を犯すのは間違っているという戒めを指摘しました。一件落着。この話の要点は簡単です。私たちは、私たちがするためにもっともな理由があると考えるものについて混乱し、誤解する可能性があります。このために私たちは、私たちを導くために神の心を実際に知っている人、そして神自身よりもよく知る人を必要とします。これが神定法で明らかにされているものの正確なところです。

あるいは別の例を考えてみましょう。私たちは、友人を許すことは難しく、敵を許すことはほとんど常に不可能だと認識しています。私たちは、怒ったり、恨みを抱いたりするような権利を持っていると自分自身に伝えます。これこそが人間ではないですか?しかしながら、これらの人間的な理由は、永久法の歪みです。私たちには、許しのためにいくつかの指針が必要です。そして、敵を含む他人を許すべきであると私たちに伝える神定法がそれなのです。人定法と神定法に従うことは、私たちが私たちの目的や計画を達成し、真に幸せになるのを助けてくれます。

## アクィナスの自然法理論のまとめ

アクィナスにとって、すべてのものには機能(テロス)があり、やるべき良いこととはその機能を達成する行為です。ドングリや目のようなものは、自然にそれをします。しかしながら、人間は自由であり、したがって正しい道を見つけるための指針が必要です。その正しい道は推論によって見つけ出され、「内部の」自然法を生み出します。自然法に従うことによって、私たちは永久法の中にある私たちのための神の目的に参加します。

しかしながら、自然法に由来する主たる教訓は、良さを追求し邪悪を避けるなどの非常に一般的なものです。そのため私たちは日々のふるまいを実際に導くことができる二次的な教訓を作り出す必要があります。しかし、私たちは間違えやすいので、これらの二次的な教訓を時に誤解し、時に正しく行います。それらが間違っているときは、それらは私たちの見かけ上の良さを反映しているだけです。それらが正しいときは、それらは私たちの実際の良さを反映しています。

最後に、私たちがどれだけ良くあろうとも、私たちは有限で罪深いために、私たちはこれまでのところ合理的な熟考でやっていくことしかできません。私たちはいくつかの明示された指針を必要とし、これは神定法の形で表れます。そのため、エウテュプロンのジレンマに戻ってしまいます。神定法を通じた神の命令は、実際のところ道徳的に容認できるものを明らかにする方法であり、道徳的に容認できるものを決定するものではありません。アクィナスは神の命令理論を拒絶します。

## これを実践に移す:二重の結果のドクトリン(DDE)

私たちがこれまでに述べたことが実際に機能するかもしれないことを示すいくつかの例を考えてみましょう。自殺を考えている人を想像してみてください。これは道徳的に容認できるでしょうか?人間の命を保存し、保護するのは自然法の一部であることを思い出してください。明らかに自殺は人間の命を保存し、保護するものではありません。それゆえ、自分自身を殺すことは不合理であり、私たちの生命のための神の計画の一部となることはできません。したがって、それは道徳的に容認できません。

誰かがレイプによって妊娠した後に中絶を考えていると想像してみてください。同じ理由が適用されます。私たちは人間の命を保存し、保護するべきであり、したがってこの場合の中絶は道徳的に間違っています。

しかしながら、これから私たちが見るように、アクィナスは、罪のない人を殺すことが道徳的に容認できる場合があると考えており、したがって胎児を殺すことが道徳的に容認できる場合があるかもしれません。しかし、これはどのようにして正しくなることができるのでしょうか?これは命を守ることについての主たる教訓に違反しないのでしょうか?答えは、アクィナスにとって、行動とは私たちが外部的に行うことについてのものだけではなく、私たちが内部的に行うこと(つまり、私たちの動機)についてのものでもあることを理解することです。この区別によって彼は、たとえば、無実の人を殺すことが道徳的に容認できるようになることを示すことができます。

これを明確にするために、アクィナスは彼の最も有名な考え方の1つ、「二重の結果のドクトリン」を導入します。これがどのように機能するか見てみましょう。

> 身体的、性的、感情的に虐待をする家庭で育った子供を想像してみてください。彼は頻繁に命の恐怖を感じ、ある時には数日間も家に閉じ込められています。ある日、父親が酔っており、彼のことを虐待しようとしているときに、彼はすばやくキッチンナイフをつかみ、父親の動脈を切りました。彼の父親は出血し、数分で死にました。あなたはこの息子が何か間違ったことをしたと思いますか?

多くの人は、彼は道徳的に間違ったことは何もしていないと言いますし、実際には、彼はその行動を褒められるべきだとまで言う人もいるかもしれません。アクィナスについてはどうでしょうか?彼は何を言うでしょうか?

自然法が「命を保存し、保護する」ものであるとするならば、彼はこの行動は道徳的に間違っていると言うだろうと、私たちは考えるかもしれません。しかし実際には、彼はこの息子の行動が道徳的に間違ってはいないというでしょう(アクィナスは神学大全(II–II, Qu. 64)で自己防衛について論じています)。

では、なぜこの父親を殺そうとする息子は、主たる教訓とは直接矛盾することがないのでしょうか?アクィナスは、外部の行為(父親が殺されたという事実)と内部の行為(動機)の違いを検討するよう私たちに求めます。

私たちの例では、その行動は息子の内部的な行動のために自己防衛の1つであり、このために、アクィナスはこの殺人が道徳的に容認できると考えるでしょう。この区別と結論は、アクィナスの二重の結果のドクトリンのために可能となります。二重の結果のドクトリンは、ある行為が4つの条件を満たしていればそれが道徳的に容認できると述べています。もしそうでなければ、道徳的には容認できません。

1. 第1の原則は、その行為が良いものでなければならないということです。
2. 第2の原則は、その行為が結果の前に生じなければならないということです。
3. 第3の原則は、その意図が良いものでなければならないということです。
4. 第4の原則は、それが深刻な理由のためでなければならないということです。

これは抽象的なので、私たちの例に戻ってみましょう。この息子の行為は自分の命を救うために行われました。そのため、それは良いことです — 私たちは(1)をチェックすることができます。さらに、彼の命を救う行為がまず最初に生じました — 私たちは(2)をチェックすることができます。この息子は、自分の命を救うために、最初に父親を殺すようには行動しませんでした。そうすることは、良いことをもたらすために邪悪を行うことになってしまうため、決して道徳的に容認できません。この息子の意図は、彼の命を保存し、保護することであったため、その意図は良いものでした — (3)をチェック。最後に、その理由は彼の命か父親の命かといったように深刻なものでした — (4)をチェック。

その行為が4つの原則をすべて満たしていることを考えると、その行為が人を死に至らせるものであり命を守るという主たる教訓に反しているように見えたとしても、それはDDEと一致しており、したがって道徳的に容認できるものです。

私たちは対照的な事例を描き出すことができます。自衛のために自分の父親に切りつける代わりに、この息子は殺しを計画していると想像してみてください。彼は最高の日、最高の時間を見つけ出し、彼の父親が部屋の窓から落ちて死ぬ原因となるような仕掛け紐を設置します。この行動はDDEの4つの基準を満たしていますか?まあ、だめでしょう。なぜなら、この息子の意図は、自分の命を救うことよりも父親を殺すことですから、私たちは(3)にバツ印をつけなければなりません。

私たちは既に、アクィナスにとって自殺は道徳的に許されないということを見てきました。それでは、あなたが自分自身を死へと導くことを知っている行動をとることは、道徳的に間違っていることを意味しますか?いいえ。あなた自身の死という外部の行為は同じであったとしても、内部の行為(意図)は異なる可能性があります。ある行動は自然法によって外部と内部の両方で判断されます。

ある兵士が彼女の兵舎に投げ込まれた手榴弾を見る場合を想像してください。彼女はそれの信管を抜くか、またはそれを捨てる時間がないことを知って、彼女は手榴弾の上に自分の身体で覆いかぶさります。それは爆発して彼女を殺しましたが、彼女の兵舎にいる他の兵士を救いました。これは間違っているのでしょうか、正しいのでしょうか?アクィナスは、DDEを考えると、これは道徳的に容認できると言います。もし私たちが内部と外部の両方でこの行為を判断するならば、その理由がわかります。

彼女がその行動によって確実に何が起こるかを予見していたとしても、その意図 — 内部の行為 — は、自分自身を殺すことではありませんでした。行為そのものは、仲間の兵士を救うために良いものです(1)。順序は正しく、彼女は、良いことを起こすために悪いことをしてはいません(2)。その意図は良いものであり、それは彼女の仲間の兵士を救うことです(3)。その理由は深刻なものであり、人々の命を懸念しています(4)。

これを、自分自身で爆発を起こすことによって自殺することを決断した兵士と対照させてみてください。その意図は良くないものであり、DDEはこの自殺の行動を許しません。

最後に、ある女性が妊娠しており、手術不能な子宮癌も患っていると想像してください。医師には2つの選択肢があります。1つは、子宮を取り出して母親を救いますが、胎児は死ぬでしょう。あるいは胎児を成長させて健康に出産させますが、女性は死ぬでしょう。この場合、アクィナスは何を言うでしょうか?DDEを使うと、彼は癌を取り除くことが道徳的に容認できると言うでしょう。

その行動は癌を取り除くことです。それは胎児が死ぬという予見可能な結果を​​持っていますが、それは意図されているものではありません。その行動 — 癌を取り除くということ — は良いものです(1)。癌を除去する行為は、胎児の死の前に生じます(2)。女性の命を救うという意図も良いものです(3)。最後に、それは女性と胎児の生と死についてのものであり、その理由は深刻です(4)。

そのため、これは医師の行動が胎児の死をもたらすケースではありますが、DDEを介して示されるように、アクィナスにとってこれは自然法理論を通じて容認できるものとなるでしょう。

## 自然法理論についてのいくつかの考え方

私たちがアクィナスの自然法理論を通じて考えるときに考慮すべき多くのことがあります。神が存在するかどうかについての問題など、私たちが提起できる明確な問題がいくつかあります。もし神が存在しないならば、永久法は存在しないので、理論全体が崩れ落ちます。しかしながら、私たちは良い哲学者として、常に慈悲の原則を守って活動するべきであり、私たちの相手は合理的だと認めるべきであり、彼らの議論の可能な限り強力な解釈をとるべきです。そこで、議論のために神が存在すると仮定しましょう。アクィナスの理論はどれほど説得力がありますか?私たちが取り上げることができるものは数多くあります。

アクィナスの理論は、もし何かが「自然」であれば、つまりもし何かがその機能を果たしているならば、それは道徳的に受け入れられるという考え方に基づいて機能しますが、自然に関する数多くの未解決の問題があります。

私たちは、なぜ「自然である」ことが重要なのか?、と問うかもしれません。私たちは、「自然」ではないが完全に受け入れられるもの、そして、自然ではあるが受け入れられないものを考えることができます。たとえば、服を着て、薬を飲んで、ボディピアスをすることは自然ではありませんが、私たちはそれらの事柄が道徳的に間違っていると言いたいとは思わないでしょう。

他方では、私たちは、暴力が不誠実なパートナーに対する自然な対応であるとみなすかもしれませんが、そのような暴力は道徳的に容認できないとも考えています。したがって、私たちが、単に自然なものとそうでないものを発見することによって、あるものが道徳的に容認できるか否かを発見することができる、というのは真実ではありません。

この心配はちょっと脇に置いておいてください。アクィナスは、繁殖は自然であり、したがって繁殖は道徳的に受け入れられると考えていることを思い出してください。これは、繁殖につながらないセックスは道徳的に受け入れられないことを意味します。アクィナスは、もしセックスが妊娠につながらなければそれは間違っているとは言っていません。結局のところ、タイミングが正しくないことがあります。彼の主張は、もしセックスが妊娠につながる可能性がないならば、それは間違っているということです。しかしながら、この留保があったとしても、これは同性愛や避妊などのたくさんのことが道徳的に間違っていることを意味するでしょう。私たちはこれを、アクィナスの道徳的枠組みを再考する理由として捉えるかもしれません(これらの明らかな問題について、私たちは第10章でより詳しく議論します)。

しかし、倫理に対するこのアプローチ(およびアリストテレスのアプローチ)の中心には、より根本的な心配があります。つまり、それらは、すべてのものが目標(テロス)を持っていると考えています。ここで、いくつかのものを考えれば、これはもっともらしいかもしれません。目やドングリなどのものは、成長すること、見ることといった明確な機能がありますが、人間はどうなのでしょうか?これはちょっと明確ではないようです!人間は(私たちの個人的な部分ではなく)、本当にテロスを持っていますか?確かにいくらかの哲学者 — たとえばシモーヌ・ド・ボーヴォワール(1908–1986年)のような実存主義者 — は、人間本性のようなものはなく、人間の機能や目標などのようなものはないと考えています。しかし、もし私たちが、人間が目標を持っているということを確信しないのであれば、この倫理に対する全体的なアプローチには欠陥があるようです。

次に、私たちはDDEについての質問を取り上げてみましょう。中絶についての例に戻ります。アクィナスにとって、たとえそうする中で胎児は死ぬと私たちが知っていたとしても、子宮を取り除くことは道徳的に容認できます。道徳的に受け入れられないのは、子宮を取り除くことにより胎児を殺すことを意図することです。最初に読んでみたところでは、これは理にかなっているようです。私たちはDDEが何を言おうとしているのか直観的な感覚を持っています。しかしながら、私たちがそれをより詳細に検討してみると、それは明快からは程遠いものです。

ふたりの医師が(見かけ上は)全く同じことをしていると想像してください。彼らはふたりとも子宮を取り除き、胎児は死にます。ひとりは — 胎児が死ぬであろうことを十分に知りながら — 子宮を摘出することを意図しており、もうひとりは胎児を殺すことを意図しています。DDEがアクィナスの理解する方法で機能するためには、この意図の違いはふたりの医師の間の道徳的な違いになります。しかしながら、本当に道徳的な違いがあるのでしょうか?あるという答えに対して圧力をかけてみるには、何かをすることを意図するということは何を意味するとあなたが考えるかを、自分自身に尋ねてみてください。もし最初の医師が「私は胎児を殺すことを意図していなかった」と言ったら、私たちはこれを理解することができますか?結局のところ、もしあなたが彼女に「子宮を取り出す中で胎児が死ぬことを知っていましたか?」と尋ねたら、彼女は「はい、もちろん」と言うでしょう。しかし、もし彼女がこれを行い胎児が死んだとしたら、彼女は(何らかの意味で)胎児を殺すことを意図していなかったのでしょうか?だから、この問題は、心の本質と、私たちがどのように意図を理解するかについての複雑な質問を提起します。

最後に、私たちは、自然法を使って実際に何をするべきかを見つけ出すのはどれくらい簡単なのかを疑問に思うかもしれません。私たちは、私たちの道徳理論が私たちの生を生きていく中で私たちに方向性を与えてくれることを願うでしょう。それこそがまさに道徳理論の役割だと私たちは思うかもしれません。しかし、それはこの場合にはどのように機能するのでしょうか?

アクィナスにとって、もし私たちが合理的に熟考すれば、私たちは進むべき正しい道にたどり着きます。もしこれが自然法と神定法に沿うものならば、それは道徳的に受け入れられます。それがその線から外れるものであれば、そうではありません。ここでの前提は、私たちがより多く考えると、私たちはより合理的になり、より収束していくだろうということです。私たちはみな、正しいことと間違っていることについて同様の見解を持ち始めるようになるでしょう。しかし、これは楽観的すぎませんか?非常に頻繁に、友人や同僚との広範な熟考や冷静な討議の後でさえ、私たち合理的な行為主体がすべきことは私たちには明らかではありません。私たちはみな、人々が合理的であることを知っていますが、私たちは道徳的な問題に関して彼らと意見を異にします。そして数学のような明らかに合理的な領域でさえ、最高の数学者たちは同意することができません。合理的な行為主体として私たちが自然法と神定法に沿うようになるだろうということについては、私たちは懐疑的になるかもしれません。

## まとめ

アクィナスは知の巨人です。彼は膨大な数の話題をカバーする信じられないほどの量を執筆しました。彼の影響は大きいです。彼の中心的な考え方は、人間が神によって理性を持つように創造されたということです — それが私たちの機能です。もし私たちが理性に従って行動するならば、人間は道徳的に正しいことを行っており、もしそうでなければ、道徳的に間違ったことを行います。

アクィナスは信じられないほど微妙で複雑な思想家です。たとえば、二重の結果のドクトリンは、私たちが「行動」、「意図」、「結果」によって実際に意味するものについて、私たちに熟考を促します。彼の仕事は依然として議論され、研究されており、神の命令理論を拒絶するキリスト教倫理の中で、いまでも通常は中心的役割を果たしています。

## 学生によくある間違い

* アクィナスが神の命令理論家であると考える。
* 永久法は神が書くことを決めたものであると考える。
* 自然法が科学の法則、たとえば、熱力学の法則であると考える。
* すべての「法」が絶対的であると考える。
* 私たちは二次的な教訓に従うことを常に道徳的に求められていると考える。
* アクィナスは、すべての状況においてすべての人々にあてはまる一組の二次的な教訓が1つだけ存在することを約束していると考える。

## 検討すべき問題

1. もし神が存在するならば、あなたは何が — もしあるとして — 正しいものと間違っているものに関係しなければならないと思いますか?
2. 私たちは神の性質を引用して、「恣意性」のジレンマに答えるかもしれません。なぜこの答えが問題含みになるのでしょうか?
3. 永久法とは何ですか?
4. 自然法と主たる教訓とは何ですか?
5. 人定法と二次的な教訓とは何ですか?
6. 神定法とは何ですか?
7. 良い目は見ることができるものであるように、そして良いドングリは成長するものであるように、良い人間は…?何になるものですか?私たちは、この文章をどうやって終わらせましょうか?
8. 人々はしばしば何が「自然」かについて話します。彼らはこれによって何を意味していると思いますか?道徳的な理論における「自然」の概念はどれくらい有用なのでしょうか?
9. 記述的な主張を考えてください。規範的な主張を考えてください。なぜ1つのものからもう1つのものへと移ることが問題になりかねないのでしょうか?
10. もし人々が十分に長い時間考えた場合、何が道徳的に正しく、何が間違っているかについて収束することがあると思いますか?
11. 二重の結果のドクトリンとは何ですか?
12. 何らかの目的をもたらすことを意図することと、あなたの行動がその目的をもたらすことを知りながら行動することの間の違い — もしあるとして — は何ですか?

## 重要な用語

見かけ上の良さ

ア・プリオリ

ア・ポステリオリ

永久法

外部の行為

自然法

主たる教訓

実際の良さ

二次的な教訓

内部の行為

二重の結果のドクトリン

## 参照文献

Aquinas, Thomas, Summa Theologica, freely available at http://www.summatheologica.info/summa/parts/?p=1
<br>[「神学大全」高田三郎・山田晶・稲垣良典ほか訳、創文社、1960年～2012年]

―, Romans (Commentary on the Letter of Saint Paul to the Romans)

Plato, Euthyphro, translated by Benjamin Jowett, freely available at http://classics.mit.edu/Plato/euthyfro.html
<br>[「エウテュプロン・ソクラテスの弁明・クリトン」、西尾浩二・朴一功訳、京都大学学術出版会・西洋古典叢書、2017年]