# フレッチャーの状況倫理

> すべての人は、自分自身による条件や結果の推定に従って自らで決断しなければならない… ^[K. E. Kirk, Conscience and its Problems, p. 331.]

> 人々は法の庇護のもとで転げまわったり縮こまったりするのを好む。^[J. F. Fletcher, Situation Ethics.]

## 状況倫理の紹介

「状況倫理:新しい道徳性」の序文の中で、ジョセフ・フレッチャー(1905–1991年)は、彼が倫理的な非システムと呼んでいるものを展開しています。彼の本は、戦後期における一般的な権威に対する不満を正当化したため、大衆の間で「嵐」を巻き起こしました。それが書かれたときには、婚外性交を持つこと、同性愛者であること、または中絶をすることは間違いではないというような、いくつかの過激な主張をしていると見られました。とはいえ、フレッチャーの仕事は今では哲学界で広く議論されることもなければ尊敬されてもいません。それは不当に議論され、独特であり、いくつかの古い考え方を作り直しています。

この本は宗教の装いをしています — フレッチャーは「アガペー」のような宗教的用語を使用し、ルドルフ・ブルトマン(1884–1976年)のような有名な神学者を引用しています — が、その中心的な考え方はどのような特定の宗教の真理にも頼っていません。彼が述べるように、彼の議論は、「…神学的な…信仰と関係する特別なことは何もない。」^[Ibid., p. 15.]

フレッチャーは、この倫理的な「非システム」状況主義と聖書の物語が、この本の一般的なポイントを例示するだろうと言っています。マルコによる福音書第3章第1–6節では、イエスがユダヤ教の会堂で手のなえた男を癒したと語られています。これは、すべての人のためのイエスの愛を示すと私たちが考えるであろう行為です。しかしながら、彼が安息日にこの癒しを行い、ユダヤ人の法は安息日には誰も働いてはならないと言っているために、パリサイ人は彼に対して文句を言います。

フレッチャーの仕事は、もし行為がいわゆる道徳の法に反していたとしても、それらがどのようにして道徳的に容認され得るかを示す試みです(もしあなたが既にアリストテレスに関する第3章を読んでいるのであれば、あなたはこれについての答えを既に持っているかもしれません)。フレッチャーは、イエスの行為は、ユダヤ人の法に反しているとしても、道徳的に受け入れられると言っています。なぜなら、彼は最も大きな愛をもたらしたからです。

## フレッチャーの全体的な枠組み

フレッチャーは、倫理学には「律法主義」と「無律法主義」という2つの魅力のない見解があり、それらの間に存在する「状況主義」という1つの魅力的な見解がある、と述べています。

### 律法主義

律法主義のシステムに従っている人は、状況に敏感になることなく道徳的なルールを「盲目的に」遵守している人です。フレッチャーはここで、行動は結果にかかわらず正しかったり間違っていたりすると主張する単純な心を持った義務論者を思い浮かべています。たとえば私たちは、すべての状況で真実を伝えるべきです。たとえそれが、何百万人もの人々が死ぬことを意味していてもです。

さまざまなキリスト教の宗派は律法主義的です。たとえば、彼らの共同体の中の人が病気になっているときに、輸血などの医学的支援を拒否する人がいるかもしれません。なぜなら、彼らはそれが神の命令に反していると考えるからです。あるいは、イスラム教の律法主義の例を考えてみてください(キリスト教の宗派と同じように、これらの例は明らかにいずれの宗教も完全に代表するものではありません)。2002年、サウジアラビアの宗教警察は、アッラーの意志に反する「不適切な」服を着ていたために、少女たちを燃えている建物から救出することを拒絶しました。目撃者の1人は、3人の警察官が、「彼女たちがアバヤを身に着けていなかったので、学校から逃げるのを防ぐために、若い女の子たちを殴っていた」のを見たと述べました。^[‘Saudi Police “Stopped” Fire Rescue’, BBC News, http://news.bbc.co.uk/1/hi/world/middle_east/1874471.stm]15人の女の子が死亡しました。

### 無律法主義

もう1つの極端には、無律法主義(「無」は反することを意味し、「律法主義」は法律を意味します)があります。これは、ある行為主体はある状況に応じて彼または彼女が望むものを何でも行うことができるという見解です。それは人々がいつでも自由に自分が望むものを選ぶことができるということを言っているために、フレッチャーはこれを「実存的な」見解と呼びます。人々の行動を制限すると思われる法律や規則は、彼らに単に安心を与えようとするものです。なぜなら、彼らは絶対的な自由を恐れているためです。もし無律法主義が正しく、もし行為主体が何かが正しいと信じている場合、それはそうなります。無律法主義は、道徳的な行為主体が不規則かつランダムであり、予測不可能であり、どのような決定もその場しのぎであることを意味します。そこには法律や指針となる原則はなく、ただ行為主体とその良心、そして彼ら自身が取り込まれていることに気づくような制度だけがあります。

### 中道の倫理:状況主義

私たちは、律法主義と無律法主義によって可能性が埋め尽くされていると考えるかもしれません。もし私たちが道徳の法を拒絶するならば、私たちは法律のない道徳的なアナーキーを余儀なくされるのではありませんか?フレッチャーはそうは思いません。

フレッチャーは道徳的な法があると言っており、彼は無律法主義を拒絶します。しかし、道徳の法はただ1つだけあるので、彼は律法主義を拒絶します。フレッチャーの1つの道徳の法とは、私たちが最も多くの人に最も大きな愛情をもたらすように常に行動するべきであるということです(「アガペー計算」)。そのため、フレッチャーの状況主義は目的論的です。それは、ある行動が正しいか間違っているかを決定するであろう結果へと向けられています。

もちろん、あらゆる目的論的理論は、状況の詳細を見るように私たちに求めます。私たちがベンサムとミルの功利主義について話した第1章を思い起こしてみてください。そのため、フレッチャーの見解はユニークではありません。彼の見解を異なったものとさせるのは、「愛」(あるいは彼が呼ぶようにアガペー)の中心性です。

フレッチャーは、道徳的な原則があり得ると考えていますが、それらは法とは異なると考えています。原則は文脈に敏感であり、愛を最大化することに関する1つの法から派生した一般化です。たとえば、私たちは殺人をするべきでないという道徳的原則を持っているかもしれません。これは原則です。なぜなら、私たちは、殺人は最も大きな愛をもたらさないために、一般的に殺人は間違っていると考えるであろうからです。しかしながら、これは法ではありません。なぜなら、フレッチャーにとって、殺人はあらゆる状況において間違っているというわけではないからです。これは第1章の規則功利主義の議論と似ています。

たとえば、核攻撃を止めるための情報を得るには、テロリストの子供が殺害されなければならないという状況が生じるかもしれません。フレッチャーは、これは私たちが殺人をしてはならないという原則に従うべきではなく、むしろ最も愛を大きくするようなことを行う、つまりこの場合には殺人を行うような状況であると言うでしょう。私たちは、普遍的な法からは、原則しか導くことができず、他の普遍的な法を導くことはできません。フレッチャーは次のように述べています。「普遍から普遍を引き出すことはできない。」^[J. F. Fletcher, Situation Ethics, p. 27.]

これは、フレッチャーにとって、場合によっては十戒を破ることが道徳的に受け入れられることがあることを意味します。実際、彼はもう少し強いことを言っており、何らかの状況ではこれらの戒めを破るのが私たちの義務であると述べてます。彼は、状況主義には4つの基礎となる原則があると考えています。

## 状況主義の4つの基礎となる原則

### 原則1:実用主義

状況主義者は実用的な戦略に従います。それは何を意味するのでしょうか?それはフレッチャーがプラグマティストであるという意味ではありません。「プラグマティズム」は、ジョン・デューイ(1859–1952年)、チャールズ・パース(1839–1914年)、ウィリアム・ジェームズ(1842–1910年)などが採用した、非常に限定されたよく練り上げられた哲学的立場です。フレッチャーは、彼の理論がこれらの見解に関連づけられることを望んでおらず、この種の「プラグマティズム」の含意をすべて拒絶しています。

彼の見解を実用的にするものは非常に単純です。彼が道徳的な見解に感じる魅力とは、抽象的なもの(たとえばカントの定言命法(第2章参照))の中に何をすべきかを見出すのを試みることではなく、むしろ道徳的な見解がどのようにそれぞれの実際の生活状況において行動に表されるのかを探求することです。

### 原則2:相対主義

彼の無律法主義に対する拒絶と、道徳性の1つの最高原則の受容とがありながらも、フレッチャーは驚くべきことに自分自身のことを相対主義者と呼んでいます。これは、彼が、(私たちが何が正しく何が間違っているかを単純に選ぶことができるという意味での)相対主義者であるということは意味しません。むしろ、それは人々に対して、すべての人々にとってのすべての文脈における「法を定める」ことをやめさせようとする懇願です。もし状況が異なるならば、結果が異なり、それに応じて何をするべきかも変わることになります。これは、プラグマティズムに関する彼の考え方のように、非常にシンプルで洗練されていない考え方です。フレッチャーは、何が正しく何が間違っているかが私たちの状況に関連しているということを意味しているに過ぎません。

### 原則3:実証主義

彼の「実証主義」の使用の仕方は、同じ名前の哲学的な考え方と同じではなく、むしろそれは:

> 神学者における信仰の命題のように、倫理におけるいかなる道徳的判断または価値判断も決断であって、結論ではない。それは論理の力によって到達される結果ではなく、選択である… ^[Ibid., p. 47.]

だから、唯一の法とは愛を最大化するものであることをどのようにして彼が正当化するのかについて挑戦されたとき、フレッチャーはできないと言うでしょう。それは論理や推論の結果ではなく、むしろ私たちが行う決断です。それは「神学者の信仰」のようなものです。

### 原則4:人格主義

愛は人々によって経験されるものです。したがって、人格主義とは、もし私たちが愛を最大化するには、私たちはある状況の中でその人のこと — ある状況におけるその「誰か」 — を考える必要がある、という見解のことです。このことをまとめて、フレッチャーは次のように述べています:

> 愛とは、人々の、人々による、人々のためのものである。物事は使われるべきものである。人々は愛されるべきものである…愛する行為は許容される唯一の行為である。^[Ibid., p. 51.]

これらが「4つの基礎となる原則」です:実用主義、相対主義、実証主義、人格主義。

## いかにして、何をするべきかを見出すか:名詞としてではない、動詞としての良心

フレッチャーにとって、「良心」は何をすべきかを見出すための役割を果たします。彼は、「良心」とは名詞ではなく動詞であると言います。これは複雑に聞こえますが、実際にはそうではありません(良心についての複雑で洗練された議論は第9章を参照してください)。

最初に、フレッチャーが良心は「名詞ではない」と言ったときに、彼が何を意味しているのかを考えましょう。良心は内部の能力の名前でもなければ、内部の「道徳的なコンパス」のようなものでもありません。これは、人々が良心を考える典型的な方法であり、漫画ではよく悪魔と天使が誰かの肩に座って彼女の耳にささやく描写があります。

フレッチャーにとっての良心は、むしろ動詞です。いじめっ子たちが私たちの友人にいやがらせのテキストを送って笑っているのが聞こえてきて、私たちは彼が目にする前にそのテキストを削除するために彼の電話をチェックするかどうかを決定しようとしている、というところを想像してみてください。良心についての古い「名詞」の見解は、私たちをこれについて抽象的に考えさせたり、おそらく理由を考えさせたり、あるいは聖霊や、守護天使などからの指針を求めさせたりするでしょう。

フレッチャーによれば、これは間違っています。代わりに、私たちは状況の中にいる必要があり、状況を経験する必要があり、そして私たちは体験することを行う(したがって「動詞」)必要があります。もしかしたら、私たちは友人の電話を手に取るのが正しいと結論づけるかもしれませんし、もしかしたら、そうはしないと結論付けるかもしれませんが、何が起ころうとも、その結果は事前に知ることができません。私たちの良心が私たちにやらせるであろうことは、私たちがこの世界に生きているときに明らかになるものであり、安楽椅子に座った熟考から明らかになるものではありません。

## 状況倫理の6つの命題

フレッチャーは彼の理論に6つの命題(特徴)を与えています。

### 1つの「もの」だけが本質的に良いものである。すなわち、愛であり、他の何物でもない

本質的に良いものが1つあります。それは文脈にかかわらず良いものであり、つまり愛です。もし愛が良いものであるならば、最も多くの愛をもたらすものに関して、行動は正しいものとなるか間違っているものとなります。ベンサムの快楽計算(第1章を参照)に反響するように、フレッチャーは、彼がアガペー計算と呼んでいるものを擁護します:

> アガペー計算とは、可能な限り最大の数の隣人にとっての、隣人の厚生の最大量。^[Ibid., p. 95.]

ここで彼は「愛」よりも「厚生」について語っていることに注意してください。フレッチャーがなぜこれを行うのかといえば、彼が(重要なことに)感情や欲望を抱くことについてではない愛を理解する方法のためです。私たちはこれについて以下で議論します。

### キリスト教徒の決断における支配的な規範は愛であり、他には何もない

私たちが最初の命題で見たように、私たちがするべきことを決める唯一の方法(支配的な規範)は、愛をもたらすことです。フレッチャーにとっての「愛」には専門的な意味があるため、私たちは注意する必要があります。

フレッチャーは、愛によって古代ギリシャ語の「アガペー」を意味します。アガペーは非常に特別な意味を持っています。まず初めに、それが何ではないかを見ておくのが簡単です。それは、私たちが友人や家族に持っているであろう気持ち(これは兄弟愛(フィレオ)としてもっとうまく表されます)ではありません。それは、私たちが他人に向けて感じるかもしれない性愛的な欲求(エロース)でもありません。

アガペーとはむしろ態度であり、感情ではありません。それは、見返りには何も期待せず、誰に対しても特別な配慮はしません。アガペーは、敵のことを、友人、兄弟、配偶者、恋人と同じ方法で考慮します。私たちの現代の文脈と人々が典型的に「愛」を語る方法とを考えると、それを「愛」と呼ぶことはおそらく役に立たないでしょう。

典型的には、人々は、愛について強烈な感情を経験するものとして書いたり考えたりします。漫画では、あるキャラクターが恋をしているときには心臓が胸の中から飛び出したり、「愛している」人々は誰かについて「考えるのを止めることができない」ため、物事に集中できないと描写されたりします。

これはフレッチャーにとって愛が意味するものではありません。キリスト教の文脈では、アガペーとは、神が私たちにどのように関係しているかに現れている愛のタイプです。キリストの処刑を執行する人のことを彼が赦すと言った中でのキリストの愛を考えてみてください。あるいは、より現代的な例を考えてみてください。1993年2月、ミネソタ州ミネアポリスのあるパーティーで、ジョンソン夫人の息子ララミーン・バード(20歳)は、16歳のオセア・イスラエルとの口論の後で頭を撃たれました。その後、ジョンソン夫人は息子の殺人犯を赦し、彼がその犯罪のために17年間の刑に服した後、彼女の隣の家に引っ越してくるよう誘いました。彼女は彼の行動を大目に見たわけではありませんし、その行動の恐怖を忘れることはないでしょうが、彼女は息子の殺人者を確かに愛しています。その愛はアガペーです。

### 正義は分配された愛に他ならないため、愛と正義は同じであり、他の何物でもない

フレッチャーにとって、実際上では私たちが遭遇する道徳的問題は、一方の「正義」と他方の「愛」との間の明白な緊張にまで要約することができます。最近の話を考えてみましょう:

> ラッパーのG Depとして知られているトレヴェル・コールマンは、ニューヨークのヒップホップシーンで人気が急上昇しており、P DiddyのBad Boyレコードレーベルと契約を結んでいました。彼には妻のクリスタルと双子の男の子もいました。

> しかし、カトリック教徒として育てられ、常に信仰を保持していたトレヴェルは、18歳の時、強盗を犯して男を撃ったというひどい秘密がありました。彼は自分の犠牲者に何が起こったかを知りませんでしたが、17年後の2010年に、彼はもはや罪悪感に耐えることができず、警察に行きました — ヒップホップ界の人間にとってはほとんど想像もできない一歩です。

> コールドケースのファイルを調べた警察によて、ジョン・ヘンケルの事件が明らかになりました。彼は1993年にハーレムの街角、トレヴェルが彼の犯罪を犯したというまさにその同じ場所で射殺されていました。彼は現在、ヘンケルの殺人のために15年間の懲役刑で服役中です。しかし、彼には後悔はありません。「私は神とともに正しいことを望んだ」と彼は言います。

> トレヴェルの選択は、十代の少年たちを自分で育てなければならない妻クリスタルにとって、おそらく耐えるのが最も難しいでしょう。

これは、家族の「愛」と正しいことをすること、つまり「正義」との間に想定される緊張として表現することができます。フレッチャーは、他のほとんどの道徳的な問題がこのように考えられると考えています。慈善団体に与えられた食糧を配分する最良の方法が何であるか、または戦争地域でトリアージ看護師がどのように働くかを決定しようとしているところを想像してみてください。このような場合、私たちは問題を次のように表現できるかもしれません。私たちは公平に配分したいのですが、どのようにこれを行うべきですか?

フレッチャーは答えは簡単だと言います。公正にまたは公平に行動するということは、正確には愛のうちに行動することです。「愛は正義であり、正義は愛である。」^[Ibid., p. 89.]

### 私たちが隣人のことを好きであろうとそうでなかろうと、愛は隣人の良さを願う

これは自明です。私たちが上で述べたように、アガペーは愛することのできないものを愛する営みの中にあります。それで、私たちの敵に関連して:

> キリスト教の愛は、私たちが良さや邪悪さ、さらには優劣の感覚を失う、または放棄することを私たちに求めない。しかしながら、それは単に、私たちが彼らを評価し、私たちが彼らを好きか否かにかかわらず、彼らは私たちの隣人であり、愛されるべきものであると主張するだけである。^[Ibid., p. 107.]

### 目的だけが手段を正当化するのであり、他には何もない

義務論的なアプローチを直接拒絶する中で、フレッチャーは、私たちがとるどのような行動も、その結果とは独立している行動とみなされるならば、文字通り「無意味でわけのわからないもの」であると言います。真実を伝えるなどの行動は、それ自体を超えた目的のためにのみ手段としての地位を獲得します。

### 愛の決断は規範的ではなく状況に応じてなされる

倫理的な決断は、ほとんどの場合型にはまったものではなく、グレーな領域に存在します。状況を検討する前に決断を下すことはできません。フレッチャーはアリゾナ州の女性の例を挙げています。彼女は「サリドマイドを服用していたために障害のある赤ちゃんを生む」かもしれないことを知りました。彼女は何をすべきでしょうか?愛のある決定は、すべての中絶が間違っていると述べた法律によって与えられるものではありませんでした。しかしながら、彼女はスウェーデンに行き、そこで中絶をしました。たとえその胚に欠陥がなかったとしても、フレッチャーによれば、彼女の行動は「勇敢で責任があり正しい」ものでした。なぜなら、彼女はその状況の詳細に照らして最も大きな愛をもたらすように行動していたからです。

## フレッチャーの状況主義に伴う問題

フレッチャーの状況主義は、絶望的なまでに混乱しており混乱させる道徳理論です。フレッチャーの仕事は、自明に真である主張をあたかもそれらが深い哲学的洞察であるかのように表現する厄介な傾向があります。

最も一般的なレベルでは、フレッチャーは権威へ訴えかけるという誤謬を犯しています。これは、単に誰かが — 通常は「権威」のある誰かが — それを支持していると言うことによって、議論が強化されていると考えるという誤りです。

フレッチャーは、有名な神学者からの引用を多く使用し、議論の代用としてアリストテレスのような有名な哲学者に言及します。残念ながら、単に他人に訴えかけるのは議論ではありません。このアプローチが役に立たないことを知るには、次の言葉を考えてください。「ゲイリー・リネカーがそう言うんだから、Walkersのスナック菓子は健康なんだ。」

フレッチャーの仕事の至る所にある別の懸念は、特に「愛」と「状況」の2つの中心的な考え方を扱うときに、彼は単に不明瞭で不正確であるということです。

ある場所では、彼は愛が「態度」であると語ります。他の場所では、彼はそれのことを終点として私たちがもたらすべきものだと言います。どちらなのですか?愛とは、それによって私たちが行動するような愛のある「態度」なのですか?それとも、特定の結果をもたらすことについてなのですか?

なぜこれが問題になるのかを見てみるために、私たちがアガペーの態度から行動するものの、しかし、その結果が1つの大きな死と破壊となる場合を考えてみましょう。私たちが、フレッチャーが呼ぶように良い「良心」で行動するとしましょう。しかし、私たちの行為は恐ろしい悲惨な結果をもたらします。フレッチャーによれば、私たちは正しかったのですか間違ったのですか?それは明らかではありません。

もし私たちがしたことが「間違っている」と彼が言うならば、アガペーは態度として考えられるべきではなく、むしろ結果のいくつかの特徴と考えるべきである、ということでいいでしょう。この読み方は、もちろん彼のアガペー計算に沿っています。さて、それでは、悪魔が憎しみや悪意から行動していると想像してください。しかし、彼は知識が不足していたために、たまたま世界に膨大な量の愛をもたらしました。この悪魔は道徳的に正しい方法で行動しているのでしょうか?「アガペー計算」を使用すると、答えは「はい」です。ここで、フレッチャーによると、悪魔は正しいことをしているのでしょうか?それは明らかではありません。

「状況に依存しているので私たちは決断できません!」という言葉は使い物にならないことに注意してください。なぜなら、私たちは、たった今その状況の詳細をあなたに伝えたからです。もしあなたがより多くの情報を必要とする場合には、ちょっとそれを考え出して、質問の内容を書き直してください。そのため、フレッチャーが「愛」によって何を意味するのかは明確ではありません。また、彼が「状況」によって意味するものも明確ではありません。

もしあなたが状況主義に関する本を書くとしたら、これらの概念の明確で広範な議論を予期することでしょう。しかしながら、彼の主要な文章ではそれについての議論はなく、これは重要な省略となっています。この問題が実際にどれほど厄介であるかを見るには、以下を考慮してみてください。ある政治家が立ち上がって、「現在の状況を鑑みると、私たちは税金を引き上げることが必要だ」と言います。私たちの最初の反応は、おそらく「どんな状況?」になるでしょう。ここでのポイントは、単純に言えば、「状況」によって何が意味されるかを知る明確な方法はないということです。私たちがどのような状況においても検討することを選ぶものは、私たちを動機づけているものは何か、私たちの気質は何であるか、私たちが持っている議題は何であるかに依存してくるでしょう。

道徳的な例を考えてみましょう。末期症状の患者が死にたいと望んでいます。この状況を考えると、私たちは何をすべきでしょうか?ここでのポイントは、「この状況」の中で考慮されるものと、考慮されないものは、私たちによってすでに重要であると考えられているものに依存するということです。私たちは、彼の宗教的見解や、彼が面倒を見ている3匹の猫がいるという事実を考慮していますか?病気の種類、死の種類、彼が後に残す人たち、司法制度に与えるであろう影響、医療従事者への影響などについてはどうですか。

そのため、私たちがするべきことを実際に見つけ出す方法として、私たちは「その状況において何が最も多くの愛をもたらすかを尋ねる」べきであるというフレッチャーの処方は、まったく役立たずです。これでは、ある人が1つのやり方で状況を見て、別の人が別のやり方で状況を見るかもしれないということが、もっともらしく思えることになり、私たちが何をすべきかについて2つの異なる主張を得ることになります。フレッチャーの説明によれば、あなたはそれでOKだと思うかもしれません。しかし、彼が無律法主義(相対主義)を拒絶していることを思い出してください。

実際、フレッチャーの説明についてたくさんの懸念事項を生じさせるのは簡単なことです。これは、彼の理論が、非常に粗削りな形態の功利主義に基づいているからです。私たちが第1章でいくつかの問題を示唆した箇所を見て、単純に「幸福」をアガペーに置き換えてみてください。ここに1つの例があります。

功利主義は直観に反していると非難されています。もし私たちが父親か5人の見知らぬ人を溺れることから救うことができるならば、功利主義者は、5人の幸福は1人のものよりも良いので、私たちは見知らぬ人たちを救うべきだと主張するでしょう。しかし、見知らぬ人たちではなく愛する人を救うことは、立派なことであり、理解できるものではないでしょうか?

状況主義者はまったく同じ問題を抱えることになるでしょう。私たちは、5人の見知らぬ人を救うことが、あなたのお父さんを救うよりももっと「愛」をもたらすだろうと想像するかもしれません。その場合、私たちはあなたのお父さんではなく見知らぬ人たちを救うべきです。しかし、見知らぬ人たちではなく愛する人を救うことは、立派なことであり、理解できるものではないでしょうか?

私たちが功利主義に関して挙げた多くの問題に対して、このような置き換えを単純に繰り返すことができます。つまり、それは「あまりにも多くを要求」し、そのため、フレッチャーにとってとても多くの問題を生じさせます。

私たちは、グレアム・ダンスタンがフレッチャーの本に関してガーディアン紙に書いた記事から、次の引用をあなたに残しておきます:

> フレッチャー教授が彼の本を書いたことを許すのは簡単ではないが、可能である。なぜなら彼は、寛大で好感の持てる人だからだ。それを出版したことについて、SCM Press社を許すのはもっと難しい。

## まとめ

フレッチャーの状況倫理は、宗教的信者たちがその見解を1960年代の急速に変化し微妙になった道徳的・政治的景観に合わせることを可能にしたために、人気を博しました。フレッチャーの立場は、神の愛、アガペーへの中心的なコミットメントを有しています。ふるまい方の道徳的指針としてのアガペーへのこの中心的な焦点によって、フレッチャーは、(もたらすアガペーの量に基づいて)ある行動は1つの文脈で正しいかもしれないが、別の文脈では間違っていると主張することができます。実際、フレッチャーは、時に私たちが道徳的に求められることは十戒を破ることであると考えています。

この理論がどれほど人気があったとしても、それは哲学的に洗練されておらず、私たちはそれを理解しようと試みればすぐに問題にぶつかります。しかし、彼の立場は学ぶ価値があります。なぜなら、(それが単にカリキュラム上にあるからというだけでなく!)、献身的なキリスト教徒/ユダヤ教徒/イスラム教徒などが、私たち自身がはまり込む多様な状況に応じて、道徳的な質問への答えを考慮するであろう概念的な可能性を開くためです。

## 学生によくある間違い

* フレッチャーの「実証主義」の使用とエイヤーの「実証主義」の使用とを混同する。
* フレッチャーが「プラグマティスト」であると考える。
* 状況倫理は、あなたが望むことを何でもすることを許すと考える。
* 愛は感情についてのものだと考える。
* フレッチャーが「良心」によって「道徳的なコンパス」を意味していると考える。

## 検討すべき問題

1. なぜフレッチャーの本は出版時にとても人気があったのだと思いますか?
2. もし宇宙人が地球を訪れて「愛とは何ですか?」と尋ねたら、あなたはどう答えますか?
3. 状況主義と「功利主義」とは、もし異なるとしたら、どのように異なるでしょうか?
4. もし私たちが愛から行動するならば、それは私たちがどのようなこともすることができることを意味しますか?
5. 良心は名詞ではなく動詞であると言うことは何を意味しますか?あなたは、私たちが良心を持っていると思いますか?もしあなたがそう思うならば、私たちはそれを動詞と考えるべきでしょうか?または名詞と考えるべきでしょうか?
6. なぜフレッチャーは、彼の理論が「事実に基づき、経験に基づき、データに敏感で、探求的である」と言っているのですか?
7. あなたはキリスト教徒がフレッチャーの理論をどう判断すると思いますか?
8. あなたは「状況」が何を意味すると思いますか?
9. フレッチャーは「実証主義」によって何を意味していますか?
10. 「権威に訴えることの誤謬」とは何ですか?あなたは自分自身の例を挙げることができますか?
11. 功利主義への1つの挑戦を選び、その挑戦を状況主義に向けたものとして改変してください。

## 重要な用語

アガペー

アガペー計算

エロース

律法主義

実用的

良心

帰結主義

## 参照文献

Fletcher, Joseph F., Situation Ethics: The New Morality (Louisville and London: Westminster John Knox Press, 1966).
<br>[「状況倫理:新しい道徳」小原信訳、新教出版社、1971年]

Kirk, Kenneth E., Conscience and Its Problems: An Introduction to Casuistry (Louisville: Westminster John Knox Press, 1999).

‘Saudi Police “Stopped” Fire Rescue’, BBC News (15 March 2002), freely available at http://news.bbc.co.uk/1/hi/world/middle_east/1874471.stm