# (PART\*) 第2部 メタ倫理学 {-}

# メタ倫理学の理論

> しかし、人が倫理的な判断を下すと一般的に言われるあらゆる場合において、関連する倫理的な言葉の機能は純粋に「感情的」である。これは特定の対象物についての感情を表現するために使用されるが、それらについては何の主張もしない。^[A. J. Ayer, ‘A Critique of Ethics’, p. 21.]

**\*警告\***

純粋に長さの点で、この章はこの教科書の他のどの部分よりも長いです。さらに、この章には、この章に特有の重要な用語が多数含まれています。したがって私たちは、この章は単に1回の授業で読んだり、検討したり、詰め込んだりするべきではないとアドバイスしておきます。

むしろ私たちは、あなたがこの章の特定の節を選択することをお勧めします。これはおそらく、あなたの授業要綱や私たちがこの章の最後に提示した課題によって知ることができます。そして1回の授業では、それらの節に取り組んでください。さらに、この章の最後にある「検討すべき問題」の最初のものは、メタ倫理学を通じたあなたの旅の導きとして特に役立つでしょう。この章に出てくる考え方は、基本的には、本書の他の部分よりも複雑であるということはないです。その幅広さは、もし適切に管理されるならば、おじけづくようなものではありません。

## メタ倫理学:はじめに

接頭辞「メタ」は、ギリシャ語の「超えて」から派生したものです。したがって、メタ倫理学は、規範倫理学や応用倫理学において考慮されるトピックを超えた研究の一形態です。私たちが序文で述べたように、これらの倫理研究の間の違いは、サッカーの試合に関わるさまざまな参加者というフィッシャー(Fisher 2011)が提唱しているアナロジーによってうまく捉えられるということを思い出してください。

* 応用倫理学は、私たちの生活の特定の領域で私たちがどのように行動すべきかについての研究です。私たちはどのようにして、(この教科書で聞き覚えのある例を使用するなら)肉食、安楽死、窃盗のような問題に対処するべきでしょうか。サッカーのアナロジーを使うと、応用倫理学者は、サッカーの選手がフィールドでボールを蹴るのと同じように、哲学的なボールを蹴ります。良い応用倫理学者は、ゴールを記録し、私たちの人生の特定の部分で私たちの道徳観を変えるように説得する特定の議論を提供することによって、成功を収めるかもしれません。
* 規範倫理学は、功利主義やカント倫理学など、私たちのふるまい方を支配する一般的な道徳的ルールを提供する理論の作成に焦点を当てています。規範倫理学者は、サッカー選手というよりは、ゲームがどのように行われるかを支配するルールを設定する審判のようなものです。たとえば、ピーター・シンガーは、応用された倫理的議論を、彼の選好功利主義(第1章で議論されている)の規範的枠組みの中で進めることに焦点を当てています。
* メタ倫理学は、どのようにして私たちが倫理に取り組むかを研究するものです。したがって、メタ倫理学者は、審判や選手というよりも、サッカー解説者にもっと似た役割を担っています。メタ倫理学者は、彼ら自身で実践的な議論を進めるのではなく、つまりボールを蹴るのではなく、倫理的な試合がどのように行われているかを評価し、コメントします。たとえば、メタ倫理学者は、サッカー解説者が特定の戦術やセットプレーの妥当性について発言するように、倫理的言語の意味と妥当性についてコメントするでしょう。

完璧である人などおらず、そのために、あなたたちの一部は熱心なサッカーファンではない可能性があります。この可能性を尊重するために、ここでは、メタ倫理学が何に相当するのかについてサッカーに基づかない説明をします。メタ倫理学的な結論は、特定の状況において、私たちがどのように倫理的に行動すべきか、あるいは、どんなタイプの決断が道徳的に正しいのかを教えてはくれません。代わりに、メタ倫理学は、倫理学研究(規範レベルと応用レベルの両方で)がどのように機能するかに関する質問に焦点を当てています。いくつかの典型的なメタ倫理学的な質問とは:

* 私たちが何かが「道徳的に良い」と言うとき、私たちは何を意味しますか?
* もし「安楽死が道徳的に間違っている」という主張が真実なら、なにがそれを真実にするのですか?
* もし道徳的主張が時には真実である場合、これらの道徳的真実にアクセスするために私たちはどのような方法を用いますか?

あなたは、メタ倫理学的な議論がどのように行動するかに関する具体的な指針を提供することを期待するべきではなく、メタ倫理学的な議論が規範的または応用的な行動を導く道徳理論の基礎を批判することを期待するべきです。

## メタ倫理学の価値

ある以前の同僚は、かつて、メタ倫理学は完全に、そして腹立たしいほど無意味だと示唆しました — 学術のための学術であると、彼女は考えていました。しかしながら、メタ倫理学的な議論が、規範倫理学や応用倫理学のものと同じくらい尊敬すべきものであり、価値があると考えることができる理由は十分にあります。

メタ倫理学を支持する要因の1つは次のとおりです。もし倫理学が良いふるまい方に根本的に関係していたり​​、アリストテレス(彼の理論は第3章で詳述されています)のように良い性格に関係していたりするならば、「良い」というのが正確には何であるかを正しく理解することが望ましいと思われます。

同様に、加算または減算のような基本概念が何を意味するのかを最初に理解することなく、応用数学を試みようとは考えないでしょう。また、血液、心臓、肝臓のような用語の意味を確信することなく、人に手術を試みようとは考えないでしょう。良さを理解する — それは何か、私たちはどうやってそれにアクセスするか — は、哲学的な議論の単なる抽象的なトピックではなく、良好な倫理学的研究の根本的な前提のように思われます。

## 認知主義 vs 非認知主義

メタ倫理学の良好な研究の鍵は、「メタ倫理学の地図」を構成するさまざまな主要な専門用語の差異を理解することです。メタ倫理学の理論は、認知主義と非認知主義、実在論と反実在論の間の議論のどこに位置するかに関して、(少なくとも私たちの目的のために)分類することができます。したがって、あなたがこれらの2つの議論を理解することは、メタ倫理学の理論を理解し評価するための前提条件です。この節では、私たちは認知主義者と非認知主義者との間の議論について扱います。

もしあなたが道徳的認知主義者であれば(ここから先はこの「道徳的」という接頭辞が仮定されます)、あなたは道徳的な言葉の意味について特定の見解と、道徳的発話の背後にある心理学について特定の見解を持っています。意味に関係する認知主義の前者のバージョンは、意味論的認知主義の議論で捉えられています。一方、心理学に関係する認知主義の後者のバージョンは、心理学的認知主義の議論で捉えられています。この章の残りで論じるように、認知主義はこれらの2つの立場を組み合わせたものです。

### 意味論的認知主義

意味論的認知主義(実在論と混同しないでください)は、私たちが「殺人が間違っている」または「他者を助けることは正しい」という形態の道徳的主張をするときには、私たちの主張は真か偽になり得る(哲学者が真偽の区別が可能である(truth-apt)と呼ぶもの)ということを示唆しています。意味論的認知主義者によれば、私たちの道徳的な意見を真または偽にするものとは、それらが世界の具体的な道徳的側面を正確に見つけ出している否か、あるいは言及しているか否かです。したがって、意味論的認知主義者は、私たちの道徳的言語のことを本質的に記述的であるものとして見ます。私たちは、世界の純粋な道徳的特徴を記述しようとしています。私たちの記述が正確な場合には私たちの道徳的主張は真であり、不正確な場合には偽です。

この立場は、決して議論の余地がないわけではありませんが、実際には聞こえるように単純なものです。ニュースリポートの中の文の意味についての意味論的認知主義者を考えてみましょう。記者が「被告は裁判所に入り、氏名と生年月日を陳述した」と言うときには、この発言は真偽の区別が可能なものとなります。それは、真であるか、あるいは偽であるかの記述が可能になるような類の発言となります。この発言が真か偽かは、世界の特徴の記述としてのその発言の正確さによって決定されます。もしその発言が特定された世界の特徴に正しく言及しているならばそれは真実になり、そうでなければ偽になるでしょう。意味論的認知主義者にとっては、もし「殺人が間違っている」という発話が本当に殺人に関連する間違いという道徳的な特徴を見つけ出している場合には、それは真実であり、そうでなければ偽である、というのはそれと同じ状況です。

重要なこととして、意味論的認知主義は、道徳的主張は真偽の区別が可能なものであること — 真か偽になれること — を示唆するにすぎない、ということを心に留めておいてください。意味論的認知主義は、それ自体では、道徳的主張が実際に真実であるかについて何も示唆していません。それを別の方法で言えば、認知主義は世界に実際に存在するもの(つまり、実在論 vs 反実在論 — 下記参照)とは何の関係もありません。そうではなくて、それは純粋に道徳的な発言の意味を説明する理論です。

### 心理学的認知主義

心理学的認知主義(実在論と混同しないでください)は、私たちが道徳的な発言を発するとき、他のどのようなタイプの非信念的な態度でもなく、何らかの信念に対して声を与えているという見解です。だから、私が「レスター・シティーが2015–2016年のプレミアリーグで優勝した」という発言をするとき、私はこれが起こったという私の信念を表明しています。心理学的認知主義者によると、私が「殺人が間違っている」または「他者を助けることは正しい」などの主張をするときにも、私はある信念を表明しています。

ここから、意味論的、心理学的な認知主義は、認知主義的立場を形成するために集合すると考えられます。これは合理的な考え方です。なぜなら、私たちは、ある信念は真か偽であり、世界について言及するようなものであると仮定するため、真偽の区別が可能な発話を信念の表現であると考えるのが最も自然だからです。倫理学において、認知主義者は、道徳的な発言が真偽の区別が可能な信念(これは、どの程度正確に世界を記述しているかによって真か偽かが決まります)を表明すると主張します。認知主義者によると、道徳的言語と道徳心理学は、科学、ニュースジャーナリズム、またはノンフィクションの歴史書などの他の多くの分野に共通する言語や心理学と特に異なるわけではありません。

あなたは、ここまであれこれ言ってきたことが一体何についてなのか疑問に思っているかもしれません。認知主義が道徳的言語とそれに関連する心理学に関しては、常識的な立場であると言うのはおそらく公平なことでしょう。当然のことながら、倫理的主張は真偽の区別が可能であり、私たちが倫理的信念を表明しているならば、一体何のために私たちは規範倫理学や応用倫理学に取り組むのか?、とあなたは思うかもしれません。リチャード・ジョイス(1966年-)は、認知主義と私たちの道徳的発話に関して、「…もし何かが[真偽の区別が可能な、信念-状態の]主張の束のように歩き回って話していれば、それは[真偽の区別が可能な、信念-状態の]主張の束である可能性が高い」、と示唆して、この見解をとっています。^[R. Joyce, The Myth of Morality, p. 14.]

### 意味論的非認知主義

意味論的非認知主義は、その認知主義的ライバルの妥当性を考えると、望ましくない立場であるように思われます。意味論的非認知主義者によると、私たちが「殺人が間違っている」などの文章を発話するとき、私たちは世界のいかなる道徳的な特徴をも記述しようとしているのではなく、単に態度や感情 — この場合にはおそらく嫌悪や怒りのような — を表現しているに過ぎません。態度は真偽の区別が可能なものではないため、真か偽になり得るようなもののタイプではありません。それらは真実を目指すものではなく、世界のどのような特徴をも記述したり、言及しようとはしていません。たとえば、あなたが仕事にいらだって「ああーー!」と叫ぶときに何が起こるかを考えてみましょう。これは態度の表現であり、世界を記述するものではなく、真偽の区別が可能なものでもありません。そのため、意味論的非認知主義者は、私たちの道徳的発話は、「被告が裁判所に入った」というようなものよりも、「ああーー!」というようなものに似ていると主張します。それらは非記述的で、真偽の区別が可能なものではない表現です。

### 心理学的非認知主義

心理学的非認知主義は、ラルフ・ウェッジウッド(1964年-)によって記述されている(しかし、擁護されてはいない)見解です。ウェッジウッドによれば、心理学的非認知主義者は、真偽の区別が可能なものではない表現の背後にある心理学は、「信念」に基づいて理解されるのではなく、「…欲望、選好、感情、意図など」に基づいて理解される、と考えています。^[R. Wedgwood, The Nature of Normativity, p. 37.]

あなたのいらだちによる「ああーー!」という叫び声は、あなたの仕事が悩ましいという信念を表明していません — 人々はあなたが悩まされていると受け取るでしょうが。そうではなくて、最もありえそうなことは、その叫び声は、あなたの仕事が終わってほしいという欲望や選好を表明しているということです。そのような精神状態はかなり一般的であり、平凡なものです。それは単に、それらが信念の状態とは異なっているということです。

この点から非認知主義を議論するとき、それは意味論的要素と心理学的要素の両方を組み合わせた立場として理解されるべきです。非認知主義者によると、私たちの道徳的発話は、真または偽となることができず、信念の表現というよりは、態度/選好/欲望/感情などの表現です。「ああーー!」という叫び声に「偽」と言うことによって反応するのが誤りであるのと同じように、道徳的な発話に対して「真」または「偽」と言うことによって反応することは、その道徳的な表明の意味を適切に理解することに失敗するでしょう。したがって、非認知主義者は、道徳的発話が何を意味し、道徳的談話がどのように機能するかに関する私たちの共通の見解に対するかなり過激な理解を示唆しています。この後で、特定の非認知主義的視点を説明・評価しますので、あなたは、私たちの通常の理解についてのこの改訂の望ましさを自分自身で判断することができます。

## 実在論 vs 反実在論

メタ倫理学の理論の道を分ける第2の重要な分岐点は、道徳的実在論と道徳的反実在論の間の選択です(認知主義と同様に、ここから先はこの「道徳的」という接頭辞が仮定されます)。これまでのように、これらの幅広い立場を理解することは、この章の後半で説明する具体的なメタ倫理学の理論を理解し、批判する上で不可欠です。

### 実在論

実在論とは、存在するものについての見解です。それは、道徳的な性質が人間とは独立して存在し、世界の中に見つけ出すことができるという見解です。ある行動が「サリーカの行動」「暴力的な行動」「意気消沈させる行動」などの性質を持つことができるように、それは「道徳的に間違った行動」であるという性質を持つ可能性があります。ピーター・レールトン(1950年-)は、心から独立した道徳的真実が世界に存在すると信じるために、「荒涼として、荒れ狂った道徳的実在論」と呼ばれるかもしれない立場を支持していると自ら述べています。^[P. Railton, ‘Moral Realism’, p. 165.]

倫理学における実在論は多少議論の余地がありますが、地理学における実在論ははるかに議論の余地が少なく、倫理学における実在論的見解の参考になるかもしれません。地理学者がオンタリオ湖の水について話すとき、「地理学的実在論者」は、そのような水が存在し、独立して客観的に存在するさまざまな特性および性質(温度、深さなど)を有すると信じています。その温度についてのいかなる人間の信念にもかかわらず、その水は特定の温度を有するでしょう。同様に、倫理学においても、実在論者はある種の道徳的な性質や事実が存在し、それらは個々の人々の心や信念に独立して客観的に存在すると考えています(少なくとも、私たちの議論に関連のあるレールトンのような実在論者たちはこれを信じています)。重要なことに、実在論者は、誤りの可能性を信じています — 「殺人が間違っている」ということが殺人を間違ったものにすることはないと信じています。殺人を間違ったものとするのは、殺人行為に関連する、間違いについての実際の道徳的な性質(客観的かつ心から独立したもの)の存在でしょう。

### 反実在論

反実在論は単純に実在論の否定です。反実在論者は、心から独立した客観的で道徳的な性質の存在を否定します。したがって、道徳的反実在論者は、それらの存在を単に否定するという点で、ドラゴンや妖精についての反実在論者に似ています。

反実在論者は非認知主義者である傾向があります(そうである必要があるわけではないです)が、非認知主義者が私たちの道徳的発話は真実を目指すと信じていないことを考えると、この事実は驚くべきことではありません。しかしながら、次の節では、どのようにして認知主義、非認知主義、実在論、反実在論が組み合わされて特定のメタ倫理学の理論を形成するかに関する、メタ倫理学の地図をより具体的に描きます。

## メタ倫理学の地図

認知主義、非認知主義、実在論、反実在論の幅広い説明は、特定のメタ倫理学の見解を理解するために以下のように分類することを可能にしてくれるので、重要です。以下のいずれかが意味をなすかを見る場合には、あなたはこれらの用語の意味を学ぶ必要があります。メタ倫理学の地図を描くことは、この目的のために非常に役立つかもしれません。

### 認知主義かつ実在論である理論の例

道徳的自然主義

道徳的非自然主義(たとえば、直観主義的な実在論の説明)

### 認知主義かつ反実在論である理論

道徳的錯誤理論

### 非認知主義かつ実在論者である理論

私たちは、この見解を保持する1人の人間しか知りません:カハネです。^[G. Kahane, ‘Must Metaethical Realism Make a Semantic Claim?’]

### 非認知主義かつ反実在論である理論

情緒主義

指令主義

このように概説された広範な立場の間の自然な仲間関係は、認知主義と実在論、そして非認知主義と反実在論です。もし私たちが道徳的な発話で真実を目指すならば、私たちが言及しようとしており、正確に記述しようとしている特性が存在すると考えることは理にかなっています。

しかしながら、もし私たちの道徳的な発話が真実を目指していないならば、それはそのような道徳的な特性が存在しないという見解とうまく並ぶでしょう。(そうでなければ、なぜ私たちはそれらを記述しようとしないのですか?)

離れたところにある理論は、私たちの道徳的発話は真偽の区別が可能な信念の表現であるという認知主義的見解と、世界に実在論的な客観的道徳的性質がないという見解とを組み合わせた、道徳的錯誤理論です。したがって、道徳的錯誤理論家は、私たちの道徳的な発話は常に、あらゆる状況において偽であると信じています。これは議論の余地のある見解であり、第10節と第11節でより深く探究されています。

## 認知主義かつ実在論である理論1:自然主義

自然主義者は、私たちの通常の道徳的信念の少なくとも一部を真実とするような道徳的な性質が世界にはあると主張しています。意外なことではありませんが、自然主義者はまた、これらの道徳的性質は、非自然的ではなく完全に自然の性質であるとも考えています。この主張を理解するためには、私たちは、哲学的・倫理的自然主義者が「自然」という言葉によって実際には何を意味しているのかをよりよく把握する必要があります。

倫理学における自然主義者は、道徳的性質が、たとえば科学で議論され検討される特性と同じくらい自然であると考えています。したがって、「濡れている」という性質は、「磁性がある」といったより複雑な性質と同じくらい、完全に自然な性質です。これらの性質は、科学者が調査することができ、超自然的で自然科学の研究を超えるようなものではありません。

ギルバート・ハーマン(1938年-)は、「…私たちは、科学によって明らかにされたのと同じように、事実の世界において、価値と義務[道徳性]の場所を見つけることに集中しなければならない」と示唆しています。^[G. Harman, Explaining Value and Other Essays in Moral Philosophy, p. 79.]もし殺人が道徳的に間違っているという性質を持っている場合、この性質は、科学によって明らかにされたのと同じように事実の世界に適合するならば自然なものです。

サイモン・ブラックバーン(1944年-)(彼自身は実在論者ではありません)は、自然主義へのこのコミットメントの望ましさと目的を概説しています。彼はこのように言っています:「問題は、倫理学のための余地を見つけること、あるいは、私たちが生息しており、私たちがそのうちの一部であるような幻滅させるような非倫理的秩序の中に倫理学を置くことである。」^[S. Blackburn, Ruling Passions, p. 49.]

そのため、道徳的自然主義は、神々、観念論的形態などに基づく非自然的な正当化に頼ることなく、倫理学における実在論と真実を擁護することを望んでいる人々に語りかけます。自然主義者は、通常の科学の非神秘的な世界に道徳的性質を適合させることを目指しています。

功利主義は、メタ倫理学的な自然主義によって支えられている規範倫理学的な理論です。ジェレミー・ベンサムとジョン・スチュアート・ミルは、(もしあなたが第1章を覚えているなら、)最も多くの人に最も大きな喜び/幸福を促進する行為(または一連の規則)として道徳的な良さを定義しました。それゆえ、功利主義者は、良いということを完全に自然な性質として見なします。なぜなら、喜びについて、神秘的、魅惑的または超自然的なものは何もないからです。科学者は、神経の発火または心理的説明によって喜びを完全に理解することができます。

さらに、フィリッパ・フットとロザリンド・ハーストハウスの両者は、徳倫理学(第3章にてアリストテレス形式で論じました)を、自然主義的なメタ倫理学の枠組みの中に配置しようとしています。

ハーストハウスによれば、人類は生存、生殖、楽しみ/苦痛からの自由、グループ内での適切な機能的役割の所持、の4つの特定の目的を達成するならばうまく機能しています。合理的な存在として、私たちはこれらの目的を達成するために役立つ性格の特性や気質を判断することができ、そのような性格の特性や気質は有徳なものとなります。したがって、そのように定義された徳倫理学は、自然主義に基づく規範的な理論です。なぜなら、何かを良いものとするもの、または有徳にするものは、私たちの心理学、ふるまい、生物学および社会的動力学と関係する自然な要因によって完全に決定されるからです。功利主義と同様に、徳やそれに関連する道徳的良さを説明するために、神秘的なものや超自然的なものは必要とされません。

自然主義は相対主義につながるでしょうか?ハーマンは、自然主義が、(もし正しいとすれば、)当然私たちを道徳相対主義に導き、道徳的絶対主義から離れさせると主張しました(これらの理論は第1章でより具体的に議論されています)。ハーマンは、もし倫理的な指針と規則が本質的に絶対的であれば、偶発的な状況や偶発的なライフスタイルに関係なく適用する必要があることを示唆しています。たとえば、もし「殺人が間違っている」という主張が絶対に真であれば、いかなる特定の状況要因にかかわらず殺人は間違いでしょう。しかしながら、もし道徳的性質が自然な性質であれば、自然の性質は事例ごとに異なることがあるという事実のために、相対主義はより意味をなすかもしれません。

たとえば、「ロンドンはパリの北にある」ということは、ある時点で大陸プレートが移動し、これらの都市が互いに対する相対的な位置を移動することができるかもしれないため、絶対的な真実ではありません。また、「オーストラリア沿岸の一部にはサンゴ礁がある」ということも、人間の活動と気候変動がこの自然の事実を変えるかもしれないので、絶対的な真実ではありません。同様に、自然な性質が「殺人が間違っている」という主張を真実にするならば、この自然の性質は、生み出された喜びの量、あるいは他の変更可能な自然要因に基づくように見えるかもしれません。道徳的な性質が自然の性質であるならば、行動が絶対に間違っているというわけではなく、代わりにそれらの自然の性質の変更可能な存在に比較して間違っているのかもしれません。

マイケル・スミス(1954年-)は、ハーマンの主張を拒絶し、自然主義は、それ自体では、道徳的相対主義者と道徳的絶対主義者との間の議論とは無関係であることを示唆しています。スミスは、絶対主義者と相対主義者は人間の行動の合理性や妥当性に関する質問が異なり、これらの質問は倫理学における自然主義や非自然主義の立場をとることによっては解決することはできないと主張します。

スミスにとって、絶対主義者と相対主義者の議論に関連する重要な質問はア・ポステリオリなものではなく、ア・プリオリなものであり、これは、それらの議論が世界をテストすることを伴わない方法によって分析され、調査されなければならないということを意味します。したがって、道徳的性質の自然的または非自然的な状態を決定するために世界をテストすることでは、相対主義者と絶対主義者の間のア・プリオリな相違を解決することはできません。

## 自然主義への異議

G・E・ムーアは、認知主義と実在論の支持者でした。しかしながら、ムーアは自然主義者ではなく、非自然主義者であり、道徳的性質が自然の性質であるという考え方に反対していました。道徳的性質を自然の性質として特定することに対するムーアの異議は2つに分かれていました。第1に、彼は道徳的性質が根本的に単純なものであると考え、第2に、彼は道徳を自然なものと特定することが、彼が「開かれた質問の議論」と名付けたものに失敗すると考えていました。

単純さからのムーアの自然主義への最初の反対は、道徳的性質と色彩的性質との類比に基づいています。ムーアによると、黄色の概念は、他の概念や性質に関しては説明できないという点において、根本的に単純な概念です。複雑な性質の例として、馬の考え方を考えてみましょう。馬の概念はより単純な部分に還元することができるので、この動物と接触したことのない人に対して馬を説明することができます。典型的には褐色をしている哺乳動物で、特定の器官および特定の寸法を有しています。明らかなやり方で、馬の概念は、より単純な構成要素に分解することができます。

ムーアは、黄色の概念についても同じことが真であることを否定しています。黄色はより単純な構成要素に分解することができない単純な概念なので、この色は視覚的に接触したことのない人に説明することができません。黄色はただ黄色であり、それをより簡単な言葉で説明するために言えるようなことは何もありません。ムーアは、同じことが道徳的性質について真実であると言います。ムーアによると:

> もし私が「何が良いものですか?」と尋ねられたら、私の答えは、良いものは良いものである、というものであり、それでこの問題は終わりだ。あるいは、もし私が「良いとはどのように定義されますか?」と尋ねられたら、私の答えは、それは定義することができない、というものであり、それがそれについて私が言わなければならないことのすべてだ。^[G. E. Moore, ‘The Open-Question Argument: The Subject Matter of Ethics’, p. 35.]

これに基づくと、ムーアは、道徳的性質が自然の性質に還元されることを受け入れることはできません。なぜなら、それは道徳的性質が根本的に単純ではないことを意味するであろうからです。たとえば、功利主義者は喜びの観点から良さを定義し、良さを喜びへと還元します。ムーアは、道徳的自然主義者が他の自然の性質の観点から単純な道徳的性質を基礎づけようとしている点で間違いを犯していると示唆しています。

現状では、ムーアの良さと黄色の類比は多少の議論を引き出しますが、十分な堅牢性を欠いています。しかしながら、ムーアの「開かれた質問の議論」は、より形式的に彼のポイントの核心をついています。

ムーアは、私たちが「慈善事業へお金を出すことは良い」などの想定上の道徳的主張を取り上げることを示唆しています。ムーアは私たちが自然主義者の先導に従い、良さに対して「喜び」などの何らかの自然の性質を挿入することを示唆しています。今、私たちは「慈善事業にお金を出すことは喜びである」という主張を持っています。良さと喜びとの間のこの同一化は、自然主義者が良さについて思い描いているかもしれない同一化のタイプです。

しかしながら、ムーアによれば、喜びを生み出しているものが実際に良いかどうかについての開かれた質問が残っています。もし良さが実際に喜びに還元されたとしてもそれが有意義ではないかもしれないという意味で、この質問は依然として意味があります。結局のところ、独身男性の概念は未婚の男の人という概念に還元することができるため、独身男性が未婚の男の人であるかどうかを意味があるように問うことはできません。したがって、もしこの功利主義的なスタイルの自然主義者が良さと喜びの同一化について正しいのであれば、喜びをもたらす行為が道徳的に良い行為であるかどうかを尋ねることは意味のある質問 — 開かれた質問 — ではありません。それでも、たとえ私が行動Aが喜びをもたらすと言われたとしても、行動Aが良いかどうかは依然開かれたままのように見えます。

ムーアは、道徳的性質の自然の性質へのどのような還元への試みも、「この行為は、示唆された自然の性質を所有している」が「それは良い行為ですか?」という形で意味のある開かれた質問を残すであろうと示唆しています。ジュリア・タナーは、実際の開かれた質問の議論の現代的な例を提供しています:

> ある人は、進化してきたものが良いものと同じであると考えるかのように話します。したがって、たとえば、資本主義は、それが単なる「適者生存」の表現であり、「適者生存」は良いものであるということに基づいて正当化されるかもしれません。ムーアによれば、そのような議論をすることは、良さがそれ自体ではなく(「適者生存」のような)他のものとして定義されているため、自然主義的な誤謬を犯しています。^[J. Tanner, ‘The Naturalistic Fallacy’, http://www.richmond-philosophy.net/rjp/rjp13_tanner.php]

タナーは、この自然主義的な誤謬に言及します。これは、道徳的性質を自然の性質へ還元しようとする誤りに関するムーア自身の用語です。示唆された自然の性質が実際に良いものであるかどうかは常に意味のある形で問うことが可能であるため、そのような還元の試みはすべて失敗するでしょう。この質問が開いているならば、良さは示唆された自然の性質と同等ではありません。「開かれた質問の議論」を、自然主義的な誤謬を犯した人を探し出すサーチライトとして考えてみてください。

ムーアの議論は、良さの自然主義的な還元に向けられていますが、良さの非自然主義的な還元に対しても同様に強力であるということは注目に値します。良さの概念をたとえば「神が望むもの」に還元するいかなる試みも失敗するでしょう。なぜなら、「これは神が望むものなのですが、それは良いものですか?」という問題は、開かれているように見えるからです。明らかに、この非自然的な還元は自然主義的な誤謬の例ではありませんが、もしあなたが、ムーアのように、良いことが根本的に単純な概念であると信じるならば、もはやそれは受け入れられないでしょう。

## 認知主義かつ実在論である理論2:非自然主義

ムーアの自然主義に対する批判は、彼自身のメタ倫理学的な見解の状況を説明します。ムーアによれば、道徳的な性質は実際に存在しますが、それらは根本的に単純な非自然的性質です。非自然的が何を意味するのかを理解するための最良の方法は次のとおりです。もし良さが非自然的であれば、それは科学のような自然の性質を特定するのを助ける経験的な手段によって私たちが発見可能な種類の性質ではありません。どのようにして私たちが非自然の性質を知るかは、検討している特定の理論に依存します。しかしながら、典型的には非自然主義者は、私たちが道徳的な感覚を介してこれらの単純で非自然的な性質の存在を直観すると考えています。したがって、直観とは、道徳的性質がどのようなものであるかではなく、私たちが道徳的性質をどのように発見するかについてのものですが、典​​型的には非自然主義者もまた直観主義者です。

リチャード・プライス(1723–1791年)は、真実が、「いかなる推論のプロセスも一切使用せずに」得られたときに直観的であると示唆しました。^[R. Price, ‘A Review of the Principle Questions in Morals’, p. 159.] もっと現代的には、W・D・ロス(1877–1971年)は、私たちは「証明を必要とせずに、あるいはそれ自体を越える証拠を必要とせずに」自明の道徳的真理を直観すると示唆しました。^[W. D. Ross, The Right and the Good, p. 29.] 1つの例が、非自然的な道徳的性質を直観するこの方法をより明瞭にしてくれるでしょう。

ベッキーは、新しい医療技術の使用を通じて人生で初めて音が聞こえるようになった女性に関するBBCのニュースレポートを見ています。ニュースでは、この人が非常に救われたためにバングラデシュで難聴を抱えている貧しい子供たちにこの技術を届けるためのドキュメンタリーを作ったことを指摘しています。リポートと関連するインタビューを見ながら、ベッキーは、医師がこの女性の難聴の治療法の研究と実施において道徳的に良い方法で行動しており、彼女もまた他の人が音を聞けるようになるのを助けることによって道徳的に良く行動しているという事実を直観します。道徳的な良さはこの状況の中で自明であり、ベッキーがそれを特定するために彼女の推論の能力を使う必要はありません。良さの性質は、彼女の道徳的感覚によって拾い上げられます。

W・D・ロスは、私たちが直観することができるさまざまな自明のプリマ・ファシエな義務があることを具体的に示唆しています(プリマ・ファシエとは、ここでは、一見して明らかであることを意味します)。その義務とは、私たちのふるまいを導くはずであるが、ときには他の競合する義務によって覆されることもあるものです。ロスは、他人に害を与えない、嘘をつかない、約束を守るなどの義務の概要を述べています。ロスは、これらの義務が自明であるために、それらの正式に経験的・論理的な擁護は、適切でないと示唆しています。私たちは、特定の状況でどのように行動するかという観点のみから、私たちは嘘をつくべきではないという主張を議論することはできません。

もしあなたが直観主義者かつ実在論者であれば、これは「開かれた質問の議論」と自然主義的な誤謬の両方を切り抜ける道を提供するかもしれません。直観主義者は、道徳的な性質は根本的に単純で非自然的であり、私たちの道徳感覚を介する不安に開かれていると主張します。私たちが道徳的な言葉を発する時、私たちはそのような性質の存在を正確に記述しようとするとともに、時には、私たちは、世界の中におけるこれらの非自然的性質の存在に正しく、適切に言及します。私たちが適切に言及するとき、私たちは真の道徳的表明をしています。

## 直観主義への異議

直観主義は、「開かれた質問の論論」と「自然主義的誤謬」を迂回する道を提供し、その結果、現代において多くの賛同者(たとえば、ラルフ・ウェッジウッド)を有しています。しかしながら、基本的な直観主義への異議を予想するのは特に困難ではありません。

まず、直観主義は、道徳的な相違を説明するときに苦労すると考えられるでしょう。もし道徳的な真実が自明であり、直観されるものならば、なぜムーアとロスのような直観主義者を自認する人たちの間でさえも、根本的に異なる倫理的見解を持っているのですか(ムーアは目的論者ですが、ロスはプロト-カント的な道徳的真理を直観しています)。

これに対応して、ロスは、私たちが持つ他の能力が世界の特徴を正しく理解するために成熟とチューニングを必要とするのと同じように、私たちの直観的な感覚にも一定の道徳的成熟が必要であると示唆しています。事実、サミュエル・クラーク(1675–1729年)は、なによりも、愚かさが私たちの直観が道を見失う原因となり、これが道徳的な相違が続くことを説明するかもしれないと示唆しました。もし私たちがもう少しだけ愚かでないならば、私たちの直観的な道徳感覚はより信頼できるものになるのに!

さらに、関連する注記として、私たちはそのような直観的な道徳的判断がどのようにして適切に検証されるのか疑問に思うかもしれません。もしあなたが検証原理 — 幸運にも宗教的言語のユニットで出会うことになるでしょう — を支持するならば、あなたは経験的に検証できない(真または偽を判断するために世界に対してテストされた)表明、あるいは定義によって真とされた表明は無意味であると信じることになります。

もし道徳的判断が非自然的性質についての直観的に支持された判断であるならば、ムーアとロス(2つの例を挙げるならば)のどちらが良さを正しく直観しているのかについて、私たちがどのように検証することができるかは明確ではありません。確実なこととして、私たちは経験的な手段を使って世界の非自然的性質の存在をテストすることはできないでしょう。したがって、検証主義者は、(もし直観主義が正しいならば、)道徳的な表明は、私たちがそのような表明を検証することができないために無意味であると示唆するかもしれません。

最後に、相違というテーマに戻ると、私たちは直観が非常に信頼できないため、それらは、心から独立した、客観的で非自然的な道徳的性質の存在に声を与える判断ではなく、私たち自身の感情や個人的な信念を表現する非合理的な道徳的判断としてよりよく理解される、という証拠を提示するかもしれません。

トロッコ問題の標準的な倫理的ジレンマへの反応を考えてみましょう。最初のバージョンでは、線路上にいる5人の人を救うために車両の方向を変えることができますが、そうすることで、方向が変わった車両の線路にいる1人の人を殺すことになります。2番目のケースでは、車両の前にかなり恰幅の良い紳士を押し出して死なせることにより車両を止めて、線路にいる5人の人を救うことができます。ほとんどの回答者は、第1のケースでは1人を犠牲にして5人を救うことを好みますが、第2のケースでは5人を犠牲にして1人を救うことを好みます。もし私たちの直観が道徳的判断を下すときにそうも異なるものを指し示すのであれば、私たちの合理性以前の直観的応答は客観的真理の熟考などではなく、感情やもともと持っていた信念の表現であると仮定する方がよいのではないでしょうか?

おそらく、道徳的な成熟度や愚かさに基づく反応がここでも当てはまるでしょうが、それは、異なる人のグループの意見の相違を説明する場合よりも、そのような事例についての相異なる個人的な直観を説明する時のほうが難しいかもしれません。

J・L・マッキー(1917–1981年)もまた、直観主義への批判を提供しますが、それらはマッキー自身の道徳的錯誤理論の説明に繋がるために、次の節で探求します。これまでと同じように、直観主義者が提案されてきた批判に対して彼らの理論を妥当性をもって擁護しているかどうかを判断することは、あなたに委ねられています。

## 認知主義かつ反実在論である理論1:道徳的錯誤理論

これまでのところ、私たちは、認知主義が実在論に関連している傾向があることを見てきました。マッキーは、彼の道徳的錯誤理論でこの傾向を破ります。マッキーは、私たちの道徳的な発話は、真偽の区別が可能な信念の表現であることを受け入れていますが、実在論を否定しています。そうすることで、マッキーは、真偽の区別が可能な信念が真実である可能性を否定します。なぜなら、世界の道徳的な描写は、道徳的な性質を持たないような世界を正確に描写することが決してできないためです。

マッキー自身の言葉では、「道徳的判断を下す大部分の人々は、とりわけ、客観的に規範的なものを指し示していると暗黙に主張しているが、これらの主張はすべて偽である。」^[J. L. Mackie, Ethics: Inventing Right and Wrong, p. 35.]規範的という言葉によって、マッキーは行動を導くものを意味しており、マッキーは行動への客観的な指針(私たちの言葉では道徳的性質)が実際に存在することを否定しています。

マッキーの見解は驚くべきことであり、もし道徳性が完全に偽であるならば、私たちはどうやって生きるべきなのかについてのたくさんの疑問が浮上します。これらの議論は興味深いものではありますが、この章のためにはなりません。その代わりに私たちは、マッキーの理論のことを、その含意が真であるとみなすのではなく、ありのままを説明し、評価しなければなりません。ある議論が、憂鬱にさせたり解放感をもたらしたりするような含意を持つことは、その理論を多かれ少なかれ正確にするわけではありません(とはいえ、たとえ最高の哲学者でさえもそのような誤った思考に陥りやすいというのは驚くべきことでもあります)。

マッキーの反実在論は、以下の2つの議論によって支持されています。マッキーの議論は、自然主義的実在論および非自然主義的実在論の両方に向けられていることは明らかにしておくべきです。

### 相対性からの議論

実在論に対するマッキーの最初の異議は、道徳的相違の深さに対する彼の理解から構築されているので、前の節で提供された直観主義への異議の1つと何らかのものを共有しています。マッキーは、科学や歴史などの他のもっともらしい実在論的な学問分野では、種々の見解は時間とともに真実の周りで融合し始め、相違は少なくとも部分的には克服されている、ということを示唆しています。

これらの学問分野では、真の知識に障壁があり、科学者や歴史家が、時には、彼ら自身の過ちではなしに、事実を知ることができないために、意見の相違が生じます。しかしながら、時には事実が明確になり、その結果として相違が減ることもあります。

しかし、倫理学では、哲学者たちが2000年以上前に議論していたのと同じ問題、「いつ戦争は容認されるのか」や、「いつ約束を破ることができるのか」などの質問に対して、依然として相違があります。もし道徳的真理が本当に存在し、実在論が正しいとすれば、私たちは現在までにそれらの真理のいくつかを見つけていると期待すべきではないでしょうか?したがって、マッキーは、倫理学における意見の相違 — 合理的な手段を通じて解決することができないような深い相違 — のことを、実在論が間違っているという証拠として見ています。議論を決着させるための道徳的な事実は存在しません。さもなければ、少なくとも現在までにそれらの議論のいくつかは決着していたでしょう!もちろん、もしいくつかの道徳的な議論が決着しているとあなたが思うなら、あなたはそれを使ってこのマッキーの議論を批判することができます。

### 奇妙さからの議論

マッキーによる2つ目の反実在論的な議論は、彼の最も有名な話です。道徳的な性質は、 — 自然的であろうと非自然的であろうと — 行動を導くものであると考えられています。もし殺人が間違っているというのが真であれば、私たちはたとえそう望んでいたとしても、殺人をするべきではありません。同様に、慈善団体へ寄付することが正しいというのが真であれば、私たちはたとえそう望んでいなくても、慈善団体へ寄付するべきです。道徳性とは、その中核では、たとえ私たちが殺人を好んでいたり慈善団体への寄付を憎んでいたとしても単純に無視することができないような、行動への理由を提示することになっています。しかしながら、道徳性のこの側面は、メタ倫理学的なレベルで問題を提起します。

デイヴィッド・ヒューム(1711–1776年)は、彼が「である-べきである」の隔たりを語った際に、道徳性の行動を導く質に関する潜在的な問題を認識していました。ヒュームによると:

> 私が今までに遭遇したすべての道徳性の体系において、著者は普通の推論の方法でしばらく前進し、そして、神の存在を確立したり、人間の事柄についての観察を打ち立てたりしているのを、私はいつも[見てきた]。突如として、私が[驚きをもって]見るのは、命題の通常の結合(である、またはでない)の代わりに、私は、べきである、またはべきでないに結びついた命題と出会う。この変化は知覚できないが、しかしながら、最後の結論のものとなっている。^[D. Hume, A Treatise on Human Nature, http://www.davidhume.org/texts/thn.html]

ヒュームは、私たちがなぜ、そしてどのようにして、そのケースが何であるかの表明から私たちがどのように行動すべきかについての表明へと移行するのか疑問を呈しています。私たちは、道徳性以外の分野では「である」と「べきである」の間のようなつながりを作りません。馬がグッドウッド競馬場で走っているという事実は、それ自体では、それに対してどのように行動するかに関する「べき」を与えてくれません。一方、道徳的な性質があるという事実は、ふるまいに関してそのような「べきである」をあなたに与えるように思われます。これはどのようにして説明することができるのでしょうか?

ヒュームはこの説明のための彼自身の提案を持っており、これは第12節で概説されています。しかしながら、マッキーは、彼自身の方向でこのヒューム的な心配を取り上げます。マッキーは、そのような行動を導く質を持っており、それそのものであるために「べきである」を提供するような性質そのものは、非常に奇妙な性質であるだろうということを示唆しています。彼は「[もし]客観的価値観[道徳的性質]があるならば、それらは、宇宙にあるどのような他のものともまったく異なる、非常に奇妙な種類の実体または質または関係であるだろう」と言っています。^[J. L. Mackie, Ethics, p. 38.]

マッキーは、もし私たちがこのような奇妙で完全に固有の実体の存在を前提とせずに道徳的思考を説明することができれば、私たちはよりうまくやれるだろうと考えています。より単純な説明は、不思議な性質に存在を与えるのではなく、そのような性質などなく、私たちの道徳的信念は文化的、個人的な信念を反映しているということを単に示唆するものです。たとえば、私たちは、直接的証言に基づいてはエイリアンや幽霊が存在することを示唆しないのと同様に(酔っ払いや疲れに基づく競合的説明はもっと説得力があるように見える)、おそらく、私たちがそれらについてたまたま話をしたからといって、道徳的な性質が存在することを認めるべきではないでしょう。

確かに、道徳的な性質の奇妙さについての不平を通じた反実在論への支持は、ヒュームの分岐を考慮することによりさらに支持されます。

ヒュームは知識を2つの種類に分けました — 考え方の関係から得られた知識と、事実から得られた知識です。「2 + 2 = 4」のような知識の主張、または「三角形は3つの角を持つ」などのさまざまな幾何学的主張は前者の方法で確立され、「今日、アラステアは青いシャツを着ている」のような知識の主張は後者の方法で確立されます。

知識のタイプのこの分割は、ヒュームの分岐と呼ばれますが、道徳的な知識の主張は分岐のどちらの側にも当てはまらないようです。道徳的な知識は、単に考え方の関係から導き出すことはできません(それは、幾何学的または数学的真理のようではないでしょうし、私たちの感覚を通じた世界でのテストなしにア・プリオリに推論することもできません)。

しかしながら、上記で言及された「である-べきである」の隔たりを考慮すれば、道徳的な知識は、事実から単純に導き出すこともできません(ア・ポステリオリな、感覚に基礎を置く、世界における、科学的な経験的観察は、何であるかを明らかにするもので、何であるべきかを明らかにすることはありません)。もし道徳的な知識がヒュームの分岐のどちら側にも当てはまらないならば、道徳的な知識は完全に独特な方法でアクセスされる完全に独特なタイプの知識であるか、あるいは、おそらくよりありえそうなこととして、道徳的な知識は実際には存在しないか、のどちらかとなります。しかし、もし私たちが道徳的な性質が存在することを知ることができないならば、私たちは実在論者になるべきではありません。

ヒュームであれば、確実に、彼の有名な分岐の適用に基づいて道徳的な性質が存在するという考え方を否定していたでしょう。しかしながらヒュームは、(マッキーのような)認知主義と反実在論ではなく、非認知主義と反実在論を好むということを忘れないでください。

同様のテーマで、マッキーは、奇妙な道徳的性質と接触するために私たちが必要とするような、理解についての奇妙な方法に言及することによって、奇妙さからの議論を強化します。マッキーは、奇妙な道徳的性質にアクセスするために私たちは特別な道徳的能力を必要とするであろうことを示唆しています。マッキーは、このような奇妙な道徳感覚の存在を認めている直観主義者の正直さに感心していますが、彼は、世界の実在論的な道徳的性質にアクセスするための根本的に異なる能力の存在を信じることに成功の見込みがあるとは考えていません。

前と同じように、もし私たちが奇妙な性質の存在を認める必要なしに私たちの道徳的な信念を説明できるならば、なぜ奇妙な性質を把握するための奇妙な方法の存在を認めなければならないのでしょうか?マッキーによれば、道徳的実在論は、不必要に奇妙な形而上学(存在するもの)と、不必要に奇妙な認識論(存在するものを知る方法)を必要とします。これらの理由から、マッキーは反実在論者です。

## 道徳的錯誤理論への異議

実在論者はマッキーに対するさまざまな反応を持っています。第1に、実在論者は、道徳的な性質が「である-べきである」の隔たりを橋渡しするために奇妙であるという結論に同意し、受け入れるかもしれません。あるいは、彼らはそのような奇妙さが問題であることを単に否定するかもしれません。実際、直観主義者は、その根本的な単純さと他の性質への還元不可能性のために、道徳的な特性の一意性を喜んで受け入れるでしょう。一方、自然主義者は、なぜ他のものと異なるものが問題とみなされるべきなのか、単に疑問に思うかもしれません。少なくとも何らかの意味で、すべてのものが他のすべてのものと異なるのではありませんか?さらに、道徳的相違の重要性と深さに関するマッキーの見解も批判されることがあります。

たとえば、A・J・エイヤー(1910–1989年)は、道徳的な相違は、非道徳的な事実をめぐる相違がある場合にのみ存在すると感じていました。この観点から、マックスとイーサンは、屠殺場に送られた動物がどれだけの苦痛にさらされるかという非道徳的な事実について意見を異にするというだけのために、肉食の道徳性に関して意見を異にします。もし非道徳的な事実がすべて明らかであれば、彼らの意見の相違はもはや存続しないでしょう。したがって、エイヤーは、マッキーが示唆するほどには道徳的な相違が深いものでも浸透しているものでもないと感じるでしょう。

道徳的な相違に対する別の反応は、道徳的進歩という考え方を擁護することです。私たちが奴隷制度、性差別、人種差別などの悪いことに関する真実と接触してきたために、道徳的な相違が時間の経過と共に実際に減少したと主張したい誘惑にかられることがあるかもしれません。道徳的錯誤理論は、いかなる道徳的真実をも否定することによって道徳的進歩の可能性を否定します。進歩には正しい答えが必要とされます。もしあなたが、倫理学の中で進歩がなされている、おそらく人権として特定される形でなされていると信じるならば、あなたは道徳的錯誤理論に同意しない理由を持っています。

道徳的錯誤理論も非常に反直観的です。それは、あなたの道徳的な信念はすべて虚偽であり、種々の性質を世界の中に存在させる道徳的真実などないために、それらは決して真実とはならない、ということを言っています。それは、殺人が道徳的に間違っているわけではないことを示唆しています(しかし、道徳的に正しいわけでもありません!)。また、慈善事業に寄付をすることが道徳的に正しいわけではないことを示唆しています(しかし、道徳的に間違っているわけでもありません!)。倫理学には見つけるべき真実がないことを考えると、私たちは、誤った道徳的言語を完全に放棄すべきだと思うかもしれません — なんとも極端なメタ倫理学的な結論です!

しかしながら、もしあなたが道徳的言語と心理学の正確な説明として認知主義を受け入れるものの、客観的で、心から独立した道徳的事実や性質が実際に世界に存在するということを受け入れるのが困難であると思うのならば、道徳的錯誤理論はこうした見かけのコストを払う価値があるかもしれません。

## 非認知主義

非認知主義者のための具体的な理論的選択肢の説明と評価に先立って、非認知主義をより一般的に支持するいくつかの言葉を提供しておくことはやっておく価値があります。

もしあなたが、反実在論的な議論に感銘を受けたが、錯誤理論家となりたくないのであれば、マッキーに従うのではなくて、認知主義を否定することをしてみる価値があるかもしれません。実際に、これは反実在論者の大多数がやっている傾向のあることです。したがって、非認知主義者は、世界の道徳的な性質の欠如を心配しないでしょう。なぜなら、彼らは、私たちの道徳的発話がそのような性質を取り上げようとする試みであることを否定するからです。

反実在論を支持するだけでなく、ヒュームの「である-べきである」の隔たりを特定することは、非認知主義の有益な証拠とみなされるかもしれません。もし道徳的な発話が彼らに行動を導くような力をもたらすならば、これは、道徳的な発話が記述的な信念だからではなく、態度、感情または気持ちの表現であるからかもしれません。この考えは、ヒュームの動機づけ理論を考慮すると、確実にヒュームが念頭に置いていたものです。ヒュームは、信念は動機づけにおいて不活発であるため、信念それだけではふるまいを動機づけることができないと主張しました。心理的状態としての信念の機能は、世界の動機づけにおいて中立的な説明を提供することです。信念は、私たちが「である」と信じているものを語り、それ自体で私たちを行動へ導くことはありません。ヒュームによれば、実際に行動するために動機づけられるには、信念は私たちの頭の中の欲望と結びついていなければなりません。次の事例は、ヒュームの主張を明確にしてくれるでしょう。

リズは、すぐに彼女の友人たちがバーベキューのために訪れると信じています。しかしながら、リズは友人たちに料理を提供するという欲望に欠けており、行動しません。リズの信念は、それだけでは彼女の行動を動機づけるものではなく、また動機づけることもできません。今、状況を変えて、リズの心理に自分の友人たちに料理を提供したいという欲望を加えたとしたら、リズは行動するよう動機づけられ、とても楽しい豪華な宴会を準備するでしょう。したがって、ヒュームは、私たちの行動の説明には欲望が必要だと主張します。

それで、なぜこれが非認知主義の擁護に関係があるのでしょうか?まあ、人が道徳的なフレーズを発するときには、もしそのフレーズが誠実に発話されたならば、彼らは動機づけられるでしょう。たとえば、もし私が「慈善事業に寄付をすることは、そうする余裕がある人にとっては、道徳的に要求されることだ」という言葉を発するならば、もし私がそうすることができるならば私は慈善事業に寄付をするよう動機づけられている、とあなたは予想するでしょう。もし私がその状況で慈善事業に寄付をしないことを選んだ場合、あなたは私の道徳的発話の誠実さに疑問を呈するかもしれません。

道徳的発話、および関連する道徳的な動機づけは、お互いに非常に強く結びついているようです。ここで、もし道徳的な発話が道徳的な信念の表現であったならば、私たちは、道徳的な信念に加えて、私たちが道徳的であると信じることをするという継続的な欲望の存在を認める必要があるでしょう。しかしながら、もし道徳的発話がそのもので道徳的欲望であった場合、私たちの心理の中に追加の信念を加える必要はありません。もし「慈善事業に寄付をするのは道徳的に正しい」という言葉が、みんなが慈善事業に寄付をするべきだという私の欲望を単に表現したものであれば、私たちの道徳的発話と私たちの動機づけが互いにうまく追従する傾向がある理由を説明するのはきわめて簡単です。私たちの道徳的発話は、単に私たちの道徳的欲望の表現です!しかし、私たちの道徳的判断が単に私たちの欲望の表現であるという主張は、まさに非認知主義です。

## 非認知主義かつ反実在論である理論1:情緒主義

A・J・エイヤーおよびC・L・スティーブンソン(1908–1979年)は、情緒主義の擁護者でした。情緒主義とは、20世紀初期の時代にかなりの影響力を誇ったメタ倫理的見解です。情緒主義によると、殺人が間違っているという道徳的表明は、単に殺人という行為に対する感情の表出です。それは、本質的に殺人に対する否定的な「ブーイング」に形式的な言語による声を与えたものです。実際に、情緒主義は「ブーイング/フレー」のメタ倫理学理論と呼ばれています。私たちが何かが道徳的に間違っていると主張するとき、私たちはその行動にブーイングし、私たちが何かが道徳的に正しいと主張するとき、私たちはその行動をフレーと応援します。これは、道徳性と動機づけの間のつながりを説明しています。私たちは道徳的な言葉を使用するときに、動機づけにおいて不活発な道徳的信念を表現するのではなく、動機づけに関連のある感情的な嫌悪感や感情的な承認を表現しています。

エイヤーは、彼自身は言語についての検証主義者ではありますが、非認知主義者かつ反実在論者として、道徳的発話がそれらの真理値を決定するために経験的に検証可能であったり、あるいは現実世界のテストに開かれていたりすると率直に示唆することはできなかったとしても、道徳的発話が意味を持つことを否定したくはありませんでした(この見解では、道徳的発話は、世界を描写しようとする真偽の区別が可能な信念ではありません)。したがって、エイヤーは、道徳的な発話は感情的な意味があると示唆しました。エイヤーは、「お金を盗むことが間違っている」という主張について話す際に、これは単に「…それに対する私の道徳的な不支持を明示する行為だ。それはまるで、私が「君がそのお金を盗んだ」と独特の恐ろしいトーンで言ったり、あるいは何らかの特別な感嘆符を付けて書いたようなものだ」と述べています。^[A. J. Ayer, ‘The Emotive Theory of Ethics’, p. 106. ]そのため、道徳的な判断は、たとえ世界の記述ではなくても、感情を意味のあるように明らかにします。したがって、情緒主義は、道徳的価値観や道徳的判断のためのいくつかの意味が保存されるので、虚無主義にまっすぐ突き進むことはありません。これに基づくと、私たちは道徳的な言語の使用をやめるべきであるという考え方に強みはありません。

さらに、スティーブンソンは、「正しい」「間違っている」「良い」「悪い」といった道徳的な言葉について、それらは承認と不承認という意味で感情的な意味しか持たないことを示唆しました。したがって、「ブーイング」が真偽の区別が可能でないために、私たちは「ブーイング」が偽であると言うことができないのと同じように、私たちは「窃盗が間違っている」という形の言語学的ブーイングが真実であるとも虚偽であるとも言うことができません。スティーブンソンは、このように、情緒主義は道徳性の「磁力」を捉えていると主張しました — 私たちの道徳的発話は、私たちの動機づけを支える感情の表出であるため、私たちの道徳的発話は、私たちの動機づけの跡をたどります。

## 情緒主義への異議

初期の人気にもかかわらず、情緒主義は今日では評判のよい立場ではなく、過度に、そして役に立たないほど単純化された形の非認知主義であると広く考えられています。私たちはここで3つの異議を検討します。

第1に、心理的なレベルでは、情緒主義は正しいとは感じられないでしょう。私がある行動が正しかったり間違っていたりすると示唆しているときは、私は真であるような主張をするように自分自身を持っていくとともに、(自分の頭の中の道徳的な信念を反映して)私が世界をどのように受け取っているかを反映するような主張をするように自分自身を持っていきます。私は、自分のことを非常に学問的かつ間接的なやり方によってある行動に対してブーイングしているとはみなしません。私たちは、道徳的な言葉を発する時に私たちが何を意味しているかということに関して、言葉の意味についての抽象的な哲学化が私たち自身の心理的な熟考を打破すべきかどうかを疑問に思うかもしれません。私が「テロリズムは道徳的に間違っている」と言ったときに私が何を意味しているかを、エイヤーやスティーブンソンのほうが私自身よりもよく知っているというようなことはあるのでしょうか?もしあなたが真偽の区別が可能で記述的な道徳的判断を下すようあなた自身を持っていくならば、彼らはあなたよりよく知ることができるのでしょうか?

第2に、私たちの道徳的な発話の中には、まったくもって感情的ではないように見えるものもあります。たとえば、シャーロットは「税金を払うのを避けることは間違っている」と感じるかもしれませんが、この判断についてはかなり憂鬱になります。もし私たちが認知主義者であれば、この感情的な分離は簡単に説明できます。シャーロットは、彼女の心や彼女の欲求から独立した道徳的な事実があると信じており、この事実が彼女を憂鬱にします。しかしながら、彼女が税金を避けたいという欲望を心に抱いているときに、シャーロットの「税金を避けることへのブーイング」を情緒主義がどのように説明するのかはすぐには分かりません。もしかしたら、私たちは自分自身の感情について二次的な感情を持てるのかもしれません(シャーロットは、自分が税金を避けることを否定的に感じることを悲しんでいます)。あるいは、シャーロットは他人が税金を避けるべきではないと感じる一方で(彼らにブーイング)、彼女はそのように行動することで幸せなのかもしれません(彼女自身の税金回避にはフレーと応援)。しかしながら、もしあなたがこれらの反応を追求しようとするならば、これらの反応のどちらも慎重な表明と擁護を必要とします。

最後に、私たちは道徳的な相違に戻ることができます。安楽死の問題について、ウィリアムとウェンディの間に誠実な道徳的な相違があると考えてみてください。ウェンディは、少なくともいくつかのケースでは安楽死は道徳的に正しいと言いますが、ウィリアムはすべての状況において安楽死は道徳的に間違っていると言います。ウィリアムとウェンディは、科学者や経済学者、あるいはコンピュータ技術者が彼ら自身の心とは無関係な実質的に正しい答えについて相違があるのと同じように、論理と理性を介して意見の相違を見せるかもしれません。

しかしながら、ひとたび事実が合意されたら、情緒主義者はこの相違を安楽死に関する一連の感情的なブーイングとフレーに還元しなければならず、そこでは真実は決して道徳的発話の目的とはなりません。道徳的な議論は事実に関するものではなく常に感情に関するものであり、合理的な手段ではなく感情的な手段によってのみ動かされると示唆することは、そのような議論の中で道徳的な理由が非常に慎重に用いられているように見えるという点を考慮すれば、論争を引き起こす主張です。確かに、道徳的議論における情緒主義者の説明は、道徳的な議論は、他の学問分野における真実に基づいた意見の相違というよりも、どのアイスクリームの味が最高であるかという議論(チョコレートにブーイング、バニラにフレー)のほうにより共通していると示唆しているように見えます。もしこれが、道徳的な議論がどのように記述されるべきかに関して私たちが信じるようなものではない場合、情緒主義には問題があります。リチャード・ブラントが示唆しているように、「倫理的な表明は、情緒的な理論がそうであると言っているようなものには見えない。」^[ R. Brandt, Ethical Theory: The Problems of Normative and Critical Ethics, p. 226.]ブラントは、上記の議論のように、道徳的な発話とは、私たちが真偽の区別が可能となるように取り上げるものであり、それらの道徳的な発話の情緒主義的解釈とは対照的であると感じています。

前にある情緒主義への異議は、情緒主義と道徳的な相対主義の間のありえるかもしれないつながりを強調しているように見えるかもしれません。しかし、だまされてはいけません。第1章にあるように、相対主義者は、絶対主義者とは反対に、いかなる状況においても絶対に真実であるような道徳的主張はないと考えているということを思い出してください。具体的なタイプの相対主義者として、文化的相対主義者は、「殺人が間違っている」という主張は、ふるまい方についての異なる文化的基準に応じて、いくつかの文化的状況においては真実である可能性があり、別の文化的状況においては虚偽である、ということを示唆するかもしれません。したがって、文化的相対主義と情緒主義は、絶対的な道徳的真実は存在せず、道徳的表現は絶対的で心から独立した真実を反映しているのではなく、文化的に支持された特定の話者の感情を反映している、といった同じ基盤的信念の組み合わせを有しているという示唆がなされるかもしれません。

しかしながら、これは間違いです。情緒主義とは反対に、文化的相対主義者は、たとえそのような相対主義者が絶対的な道徳的真理が存在すると考えていなくとも、実在論的な道徳的真実の形を信じる傾向があります。文化的相対主義者は、倫理的判断がしばしば個人的かつ文化的に支持された感情を反映すると認めるかもしれない一方で、彼らは、良さのことを、所与の社会の文化的基準によって本質的に決定または固定されるような真正な性質であると定義します。

したがって、もし「殺人が間違っている」が私の文化に対して真実であるならば、それはまだ真実です。そのため、たとえ他の人々の社会にいなくても、少なくとも私の社会の境界内では、もし私が「殺人は受け入れられる」と主張すれば、私は誤解されます。この真実は、文化に対して絶対的ではなく、相対的ですが、文化的相対主義者はそれが存在し、私たちの道徳的表明がそのような真実を記述しようとしているということを受け入れています。一方で、情緒主義者は、明らかに、私たちの道徳的表明が、たとえ相対主義的であったとしても、実在論的な道徳的真理の記述の試みであるということを受け入れません。

## 非認知主義かつ反実在論である理論2:指令主義

R・M・ヘアは熱心な非認知主義者であり、反実在論者でしたが、単純な情緒主義の立場の擁護者ではありませんでした。その代わりに、ヘアはメタ倫理学における指令主義者でした。

指令主義者として、ヘアは、私たちの道徳的発話が単純な感情的な承認と不承認以上のものを表明していると感じていました。代わりに、私たちの道徳的な発話は、他者が私たちの道徳的判断に従って行動するための主観的な指示を表しています。したがって、たとえば、もしウィリアムが「安楽死は道徳的に間違っている」と主張した場合、この発話は、ウィリアムが他の人に対して安楽死の支持または決定をやめるように求めていることを意味します。したがって、指令主義は、道徳的真実の主張に頼ることなく、道徳的発話の行動を導く本質を捉えようとしています。

指令主義はまた、情緒主義よりも道徳的な相違をよりよく説明するように思われます。なぜなら、指令主義は、道徳的な発話の行動を導く規範的な強みが道徳的な表明の意味の中に基本的に組み込まれていることを示唆しているためです。さらに、おそらく決定的なことに、指令主義は、実在論的な道徳的真実や実在論的な道徳的虚偽の主張を呼び出す必要なしに、正当に他の人物の道徳観を批判することも可能にします。次の例を考えてみましょう。

クリスティーナは、「殺人は普遍的かつ絶対的に道徳的に間違っている」と主張しています。指令主義者によると、これは記述的な信念ではなく、誰も殺人すべきではないというクリスティーナの非認知主義的な態度の反映です。しかしながら、もしクリスティーナが後に「この恐ろしい独裁者を殺害することは道徳的に受け入れられる」という言葉を発するとしたら、私たちはクリスティーナの矛盾を批判することができます。一方では、彼女は誰もが殺すべきではないことを望み、他方では、恐ろしい独裁者の殺害を望んでいます。指令主義者によれば、彼女に対する批判を正当化するのは、クリスティーナが虚偽の道徳的主張をしていたということではなく、彼女が他の人に指示する行動に矛盾があることです。したがって、私たちはクリスティーナに対して「虚偽だ!」と叫ぶことはできませんが、「矛盾している」と叫ぶことはできます。これは、少なくとも、道徳的な相違に何らかの真正な意味を取り戻し、正当かつ合理的に他人の道徳的主張を批判する方法を提供するかもしれません。指令主義は、これに基づいて、非認知主義的かつ反実在論的なメタ倫理学理論に関して、しばしば情緒主義のステップアップとして見られます。

## 指令主義への異議

指令主義への挑戦の多くは、情緒主義に関して提出された挑戦から引き継がれています。指令主義者は、少なくとも、もし私たちが世界の道徳的性質について真偽の区別が可能で記述的な主張をしているとするならば、なぜ彼らが私たちの行う道徳的な表明の意味を私たちよりもよく知っているのかを説明しなければなりません。

さらに、私たちは、指令主義が情緒主義よりも道徳的な相違の質をよりよく捉えていることを受け入れるかもしれませんが、指令主義者によって提供される道徳的な相違の考えが十分であることを否定するかもしれません。結局のところ、矛盾というのが、私たちが道徳的に相違する人たちに言うことができる最も重大な異議なのでしょうか?指令主義は、「異なる人種的な背景を持つ人を殺すことは道徳的に容認される」と信じる人種​​差別主義者が何か虚偽の言葉を発していると示唆することを、私たちに認めるものではありません。実際、人種差別主義者が道徳的に一貫した見解を保持している限り、彼の立場を批判する根拠は全くありません。もし私たちが、人種差別主義者や性差別主義者や他の道徳的に嘆かわしい人々の道徳観に対峙するときに、 — 適切で合理的で実在論的な正当性をもって — 「虚偽だ!」と叫ぶ能力を保持することが重要だと感じるならば、指令主義は私たちが必要とする道具を提供しません。もちろん、指令主義者は、私たちが実在論が正しいことを望むという理由だけで実在論が正しいと主張することはできないと返答するかもしれませんし、指令主義は、好むと好まざるとにかかわらず、実際に私たちの道徳的判断の意味の適切な理解であると返答するかもしれません。繰り返しますが、これはあなたが自分で判断すべきことです。

## まとめ

この章において、もっと多くのことを言うことができます。メタ倫理学理論は、規範倫理学と同様に多様で微妙なものであり、単一の章ですべてのものに公正な機会を与えることは不可能です。キャサリン・ウィルソンは、これらの問題に関するあなた自身の一人称の見解にたどり着くための挑戦を反映したメタ倫理学の研究書を書いています。^[C. Wilson, Metaethics from a First Person Standpoint, https://www.openbookpublishers.com/reader/417]しかしながら、私たちは、これらの理論を明確に概説し、そのような公正な機会を提供をするために、この各駅停車の旅に可能な限り努力してきました。認知主義と非認知主義、実在論と反実在論の間の議論のどこに座るかを決定し、より一般的には、メタ倫理学が、倫理学の研究の規範倫理や応用倫理部門と比べてどれほど重要であるかを決定することは、あなたに委ねられてます。

## 学生によくある間違い

* 評価に取り組もうとする前に、主要な用語の意味と理論の性質をしっかりと把握するように章を細分化しないこと。
* 認知主義、非認知主義、実在論、反実在論を混同する。
* 奇妙さによる訴えを誤解する。
* 開かれた質問の議論のメカニズムを説明する際に、意味のある質問をすることの重要性を忘れている。
* 類推を適切に使用しない — 他の実在論/自然主義/認知主義/非認知主義の学問分野と例を考え、それらを倫理学と比較する。
* 直観主義者によって提供される意見の相違についての説明を無視する。
* ある立場の批判を別の立場の支持に結びつけない。たとえばムーアの自然主義に対する攻撃は彼の直観主義的見解を説明しており、マッキーの実在論に対する攻撃は彼の反実在論的立場を正当化する。
* 明らかな規範の問題または応用の問題に直接対処していないために、説明を助けるような例を使用しない。

## 検討すべき問題

1. あなた自身のメタ倫理学の地図を作成できますか?フローチャート方式の図を描いてみてください。まず、認知主義と非認知主義を分岐させ、その後に関連する理論を続けてください。自信を持って描けたならば、次は、弱点や強みを地図に追加してみてください。私たちは、この作業を優れた学習の助けとしてお勧めします!^[素晴らしいメタ倫理学の地図については、以下を参照してください。 A. Miller, An Introduction to Contemporary Metaethics, p. 8.]
2. 情緒主義は相対主義に支持を与えますか?
3. 自然主義は絶対主義に支持を与えますか?
4. 何かが奇妙であること(マッキーの言葉の意味で)は、それが存在する可能性を低くしますか?
5. 道徳的な相違は、反実在論に支持を与えますか?
6. 哲学者は、あなたが意味することについてあなたが知っている以上のものを知ることができますか?
7. メタ倫理学は規範倫理学または応用倫理学と同程度に重要ですか?
8. 道徳的判断が非自然的な性質に関するものであれば、それらは無意味ですか?もしそれらが非認知的であればどうですか?
9. 私たちは何が正しいか間違っているかを常識に基づいて知るだけですか?これは直観主義を支持しますか?
10. あなたは自然の道徳的性質の別の候補を持つような、開かれた質問の議論の別の例を挙げることができますか?
11. 道徳的進歩などというものはありますか?これはメタ倫理学の観点から何を示唆していますか?
12. 非認知主義者は、道徳的な相違を適切に説明することができますか?
13. 動機づけについてのヒューム的な説明とは何ですか?なぜそれは非認知主義を支持するのですか?


## 重要な用語

ア・プリオリ

ア・ポステリオリ

反実在論

認知主義

経験的

自然主義的な誤謬

非認知主義

規範的

指令主義

プリマ・ファシエ

奇妙

実在論

相対主義

意味論的

真偽の区別が可能

検証主義

## 参照文献

Ayer, A. J., ‘A Critique of Ethics’, in Ethical Theory, ed. by Russ Shafer-Landau (Oxford: Blackwell, 2007).

―, ‘The Emotive Theory of Ethics’, in Ethics: Essential Readings in Moral Theory, ed. by George Sher (London: Routledge, 2012), pp. 103–10.

Blackburn, Simon, Ruling Passions (Oxford: Oxford University Press, 1998).

Brandt, Richard, Ethical Theory: The Problems of Normative and Critical Ethics (Englewood Cliffs: Prentice Hall, 1959).

Fisher, Andrew, Metaethics: An Introduction (Oxford: Routledge, 2011), https://doi.org/10.1017/upo9781844652594

Harman, Gilbert, Explaining Value and Other Essays in Moral Philosophy (Oxford: Clarendon Press, 2000).

Hume, David, A Treatise on Human Nature (London: John Noon, 1739), freely available at http://www.davidhume.org/texts/thn.html
<br>[「人性論」、土岐邦夫・小西嘉四郎訳、中央公論新社、2010年]

Joyce, Richard, The Myth of Morality (Cambridge: Cambridge University Press, 2001), https://doi.org/10.1017/cbo9780511487101

Kahane, G., ‘Must Metaethical Realism Make a Semantic Claim?’, Journal of Moral Philosophy, 10.2 (2013): 148–78, https://doi.org/10.1163/174552412x628869

Mackie, J. L., Ethics: Inventing Right and Wrong (New York: Penguin, 1977).
<br>[「倫理学 : 道徳を創造する」、高知健太郎[ほか]訳、晢書房、1990年]

Miller, A., An Introduction to Contemporary Metaethics (Cambridge: Polity, 2003).

Moore, G. E., ‘The Open-Question Argument: The Subject Matter of Ethics’, in Arguing About Metaethics, ed. by Andrew Fisher and Simon Kirchin (London: Routledge, 2006), pp. 31–47.

Price, Richard, ‘A Review of the Principle Questions in Morals’, in The British Moralists 1650–1800, ed. by D. D. Raphael (Oxford: Clarendon Press, 1969), pp. 131–98.

Railton, Peter, ‘Moral Realism’, The Philosophical Review, 95.2 (1986): 163–207, https://doi.org/10.2307/2185589

Ross, W. D., The Right and the Good (Oxford: Oxford University Press, 1930), https://doi.org/10.1093/0199252653.001.0001

Tanner, Julia, ‘The Naturalistic Fallacy’, The Richmond Journal of Philosophy, 13 (2006), freely available at http://www.richmond-philosophy.net/rjp/rjp13_tanner.php

Wedgwood, Ralph, The Nature of Normativity (Oxford: Oxford University Press, 2007), https://doi.org/10.1093/acprof:oso/9780199251315.001.0001

Wilson, Catherine, Metaethics from a First Person Standpoint (Cambridge: Open Book Publishers, 2016), https://doi.org/10.11647/OBP.0087; freely available at https://www.openbookpublishers.com/reader/417