# (PART\*) 第3部 応用倫理学 {-}

# 安楽死

> 彼の敵はそれをあからさまに言う。シンガーは、障害のある乳児を殺すことはOKだと言っている。シンガーは、深刻な損傷を負った人間は類人猿と同等であると言っている。シンガーは、彼自身の母親を殺すことはOKだろうと言っている。これらの非難は、彼らの口の両側から吐き出される。私が話をしたある神学者は、軽蔑したように言った「ピーター・シンガーは最も基本的な人間の本能を取り上げて、その存在を抹消するよう論じようとしている。彼は私たちに何を期待しているのだ、彼を抱き締めることか?」^[J. Hari, ‘Peter Singer: Some People are More Equal than Others’, http://www.independent.co.uk/news/people/profiles/peter-singer-some-people-are-more-equal-than-others-551696.html]

## 安楽死入門

人生に確実なものは2つしかない — 死と税金だ、という古い格言があります。後者の道徳性はそれ自体興味深い話題ですが(そしてあなたは、何らかのインスピレーションのために第8章で議論されている問題を参照することができるでしょう)、この章で焦点を当てるのは前者に関連する問題の道徳性です。具体的には、私たちは安楽死(「慈悲の殺害」と呼ばれることもあります)を取り巻く倫理的な問題を考慮します。

## 重要な用語

安楽死の語源は、この用語の意味を明らかにするのに役立ちます。ほとんどの立派で尊敬できる哲学的用語のように、安楽死(euthanasia)は古代ギリシア語に根ざしています。これは、「よい」を意味する「eu」と「死」を意味する「thanatos」という用語の組み合わせに基づいています。安楽死とは、それがなければはるかにつらい死に直面するかもしれない人にとって、良い死を提供しようとする行為であり、したがって「慈悲の殺害」を意味する言葉です。

安楽死のさまざまな種類を分類するための種々の方法があり、それらの分類に自信を持って慣れておくことが重要です。

### 自発的安楽死

自発的安楽死は、ある人が将来の苦しみを避けるために、自分の人生を終わらせるような選択を自らしたときに起こります。

### 非自発的安楽死

非自発的安楽死は、安楽死させられようとしている個人が自分自身で決断を下すことができないために、早過ぎる死および慈悲殺に関する決断が他人によってなされた場合に起こります。この安楽死の形態は、最も一般的には幼児や昏睡状態の患者に関連しており、彼らは年齢や状態の性質上、自分自身で決断を下すことができません。

上記は、決断を下す人の観点からの安楽死のタイプの区別を提供します。さらに、私たちは人生を終わらせる際の方法に基づいて安楽死のタイプを区別することができます。

### 能動的安楽死

もしある人が能動的に安楽死させられたという場合、それは、彼らの死が自然の原因ではなく、(もっともありえそうな方法として)致死的な注射や自発的に致命的な組み合わせの薬物を飲むことを通した外部の介入によって引き起こされたことを意味します。

### 受動的安楽死

受動的安楽死は、ある人が生き続けることを可能にするかもしれない治療から意図的に離脱することによって死ぬことを許されたときに起こります。したがって、受動的に安楽死させられた人は、たとえ生き続けるための方法が利用可能であっても、自然の原因によって死ぬことが許されます。たとえば、生命維持装置をオフにした人は、自然な原因によって死にますが、自然な原因が働くことを可能にするという決断の結果としてのみ死亡することになります。

自発的かつ受動的である安楽死が特に一般的というわけではありませんが、安楽死は、ここで並べた方法と意思決定者のどのような任意の組み合わせによっても行われる可能性があります。安楽死の形態の合法性は国によって異なります。ベルギーは自発的かつ能動的な安楽死を許していますが、英国ではそうではありません。

次の2つの節では、さまざまな形態の安楽死に賛成あるいは反対する意見についての議論を基礎づけるであろう、2つの異なる形態の医療上の悩みを概説します。応用倫理学の問題として、実用的かつ現実世界の要因に照らして倫理的主張をすることが重要です。

## ケース1:永続的な植物状態

人間は、生物学的に自分の存続を支えることができるものの、周りの世界と意味のある心理的な相互作用がないときに、永続的植物状態(以下、PVSとします)にあります。英国の国民保健サービス(NHS)によると、PVSの患者は、目で物体を追うことも、声の音に反応することもできず、認識できる感情の兆候も現われません。植物状態は、その状態が1年以上続き、医師が回復の見通しはもっともらしくないと判断するときに、永続的なものとなると定義されています。PVSの分類は粗悪で腹立たしいものに見えるかもしれませんが、患者の身体的状態と心理的状態との違いについてのメッセージは厳しいものです。

米国では、テリー・シアボが心臓発作の結果として脳が酸素欠乏を被ったときにPVSとなりました。彼女は心臓発作を切り抜けましたが、彼女の夫は最終的に、彼女の持続的な状況が望ましくなく、死ぬことを許される方が良いとの見解にたどり着きました。

英国では、1989年のヒルズボロのサッカー場の事故の犠牲者であったトニー・ブランドの両親が、彼らの息子がPVSとなった後に、息子の命に関する同様の決断を下しました。トニー・ブランドの両親は、息子が衰弱した状態で存在し続けるのではなく、「尊厳をもって死ぬ」ことが認められるようにキャンペーンを行いました。このような場合の家族の感情的な混乱については想像を試みることしかできず、テリー・シアボの両親が、テリーが死ぬのを許されることがないように、最終的に義理の息子と法廷闘争を戦うこととなったことに言及しておく必要があります。

PVSの患者の安楽死の道徳性を考えるとき、私たちは非自発的安楽死のみを検討すべきであることは明らかです。それは、そのような患者は明らかに、彼らの将来の利益に関する自発的な類の決定をすることができないという事実のためです。簡潔のために、私たちは、そのような患者が彼らの能力を失った時のために書いた、そのような状態に陥った場合の彼らの望みを説明しているような、患者からの関連した意向を表明する手紙がないと仮定します。しかしながら、あなたは、そのような手紙の道徳的な含意を検討することは有益であると気付くかもしれません。その手紙は、患者がPVSであるときにも道徳的に尊重されるべき自発的決断を提供するでしょうか?

## ケース2:不治であり末期的な病気

最終的に死をもたらすであろう不治の病と診断された患者を想像してみてください。この患者は、時間とともに症状が進行するにつれて、通常の生活を送る能力が低下し、身体的苦痛が増すことを知っています。あなたは、人にこのような不幸な影響を与えるかもしれない病気や症状の範囲を自分自身で想像することができます。

PVSの患者とは異なり、この例における患者は自分自身で安楽死を求める能力を保持しているので、これらのケースは自発的安楽死を取り巻く道徳的問題を強調することができます。ここでも私たちの議論を簡単にするために、安楽死を受けるという自発的な決定をする能力について、患者が適切または不適切な心理状態にあるかどうかに関して、どこに線を引くことができるかを私たちは考慮しませんが、これもまた、さらなる道徳的思考の価値があるであろう問題です。

## 安楽死賛成派:議論1

この節では、私たちは安楽死の道徳的な容認可能性に賛成する最初の議論を検討します。この議論は一般的な議論であり、非自発的および自発的な形の安楽死の両方に適用することができるでしょう。しかしながらこの議論は、もし妥当であれば、この節の最後で議論される理由から能動的安楽死が受動的安楽死よりも道徳的により容認できると示唆するように見えます。

この最初の議論は、人生の質からの議論として分類することができます。この比較的簡単な考えによると、時として人生が死よりも実際に好ましくない場合があります。そのような機会において、人生の質が非常に恐ろしいものであるため、人が死ぬことによって「より良く」なれるならば、安楽死は道徳的に正当化されるでしょう。明らかに、何が価値のある人生とみなされるのかに多くのことがかかってきます。第1章から福利に関する節を思い出してもらうと、ある人の人生の質を測る基準を提供しようとするさまざまな哲学的立場が存在します。たとえば、快楽主義者は、人生の質は人がどれくらいの幸福/喜びを経験するかにかかっていることを示唆するでしょう。欲望満足理論の支持者は、人生の質が、人の欲望がどれだけ多く満たされているかによって決まることを示唆するでしょう。客観的なリスト理論家は、人生の質は、人が持っている客観的に価値のあるもの(たとえば、知識や愛を含むがこれに限定されないもの)の数に依存すると示唆するでしょう。

人がこれらの意見のどれを支持するにしても、あるいは他の要因を人生の質の決定要因として理解しているとしても、PVSの人は彼らの極端な心理的限界のために、ひいき目に見たとしても生活の質が存在しないことはほとんど疑うことができません。ジョナサン・グローバー(1941年-)は、何らかの形の意識が人生の質にとって必要であることを示唆して、こう言っています:

> 私は、たとえ無意識であっても生きているということが、本質的に価値のある[どのように生きているかの形態に関係なく価値のある]ものだと考えている人に反論する方法を持ち合わせてはいない。しかしそれは、私たちのケースにおいて、永久的な昏睡状態の生活が決して死より好ましいものではないと思う人にとっては、魅力的ではないように見える見解である。主観的な観点からは、この2つの間で選択するようなものはなにもない。^[J. Glover, Causing Death and Saving Lives, p. 45.]

幸福やその他の能力を奪われているために、PVS患者の人生は生活の質に関してよくても完全に中立で、悪ければ否定的なもののようであり、それはおそらくなんらかの肉体的苦痛の経験に依存するものです。PVSの患者は、重度の発作や他の苦しみを経験した人のように、単に寝たきりになっているというだけではありません。彼らは典型的な人間に備わっている顕著な心理的性質を欠く生物学的実体となっています。これはPVSの人々のパートナーや親の一部(決して全員ではありません)の人が、患者の人生を終わらせることに賛成する理由の一端を説明するかもしれません。

ダイアン・プリティーの事例は、人生の終わりに近づいている末期の病気の人の人生の質を考えるときに得るところの多いものです。ダイアン・プリティーは運動ニューロン疾患に苦しんでおり、精神的には成熟したままでしたが、時間が経つにつれて彼女の症状が悪化し、彼女は即時かつ過度の苦痛を伴うことのない死が許されるべきだと要求するようになりました。どの時点かをはっきりとラベル付けすることはできないでしょうが、悪化しつつある末期の病気を有する者の多くが、彼らの肉体的苦痛のためや、楽しんだり、欲望を満たしたり、客観的に価値のある良いものを獲得したりできないために、人生の質が存在しないか否定的となる時点に達するであろうというのは、極めて可能性が高いように思われます。私は、死ぬことを許してほしいという望みをダイアン・プリティーが表明しているのを若いティーンエイジャーとして聞いて、誰かがもう一度日の出を見たり、もう一日生きることを望まないような地点にどのようにしてたどり着くのか疑問に感じたことを思い出します。私が思うに、こういった質問は、彼女の重度のうつ病に対してよりも、彼女の日常的な存在に対して共感することについての私の無能力さを反映していました。

したがって、もし私たちがPVSにある患者、または末期の病気の最終段階に近い患者の人生の質に焦点を置くとするならば、私たちは人生の質が負になるか、あるいは意味を持たなくなる時がくることを認めてもよいでしょう。もし私たちが認識できるような生活の質がない生命には価値がないということを示唆するならば、安楽死は道徳的に正当なものに見えるかもしれません。

もしあなたが生活の質からの議論は納得できるものだと思うならば、能動的安楽死は受動的安楽死よりもはるかに道徳的に擁護可能であると判断することができます。結局のところ、安楽死が道徳的に容認できるものであるという判断は、耐荷重判定のように見えるかもしれず、そこでは方法の選は道徳的な問題というよりも実用的なものとなります。実際、この文脈では、受動的安楽死は全世界の中で最悪のように見えるかもしれません。

ピーター・シンガーによれば、「死を[道徳的に容認される行為として]選んだならば、私たちはそれが可能な限り最良の方法でやってくるのを確実にするべきである。」^[P. Singer, Practical Ethics, p. 186.]もし私たちが人生の質に関心を持ち続けているならば、可能な限り最良の方法は、臓器が活動停止する前に痛みを伴わずに患者を眠らせるようにデザインされた致命的な注射や、または同じ効果を持つ飲用可能な液体の選択であるように思われます。自然の経過が飢餓、脱水または二次感染へと向かう場合、可能な限り最良の方法は、自然がその経過を辿るようにするために生命維持装置をオフにしたり、積極的な治療を撤回することを含むように思われません。これらの受動的に見える死を生じさせる効果は痛み止めによって管理できるかもしれませんが、シンガーの比較的単純な考えは、もし死が道徳的に望ましいとみなされるならば、なぜ受動的ではなく単に能動的に死を提供しないのだろうか?、というものです。

さらに、もし私たちが状況倫理の学者ジョセフ・フレッチャー(第5章で概説されています)の考え方を思い出すならば、(死が道徳的に望ましいと仮定して)受動的に死が起こるのを許すことが、積極的に死をもたらすよりも、実際のところ愛が少ないのかどうかについて疑問に思うかもしれません。相対主義的な規範倫理学の理論として、状況倫理は、どのような形態における安楽死の道徳的容認可能性についても絶対的な指針を提供していません。状況に固有の実践的かつ実用的な判断が、個々のケースの道徳的判断の基礎を形成する必要があります。しかしながら、患者の死が実際に私たちの望みである状況において、いかにして愛情のある能動的な安楽死が実際に存在するのかを考えることは重要です。

## 安楽死賛成派:議論2

私たちが安楽死 — 自発的と非自発的な形の両方で — を支持するために提供できる第2の議論は、資源使用からの議論と名付けることができます。前の議論は、患者の視点とそれに付随する人生の質を利用することにより安楽死の道徳的容認可能性を擁護しようとしていましたが、この議論はもう少し距離を置いているように見え、あなたはそれのことを強み、あるいは弱みと思うかもしれませんし、そうではないかもしれません。

ピーター・シンガーによると、重度障害があり、苦しんでいる小さな幼児(彼らの将来に関するいかなる希望も表明することができません)の非自発的安楽死は、以下の理由で正当化される可能性があります:

> 障害のある幼児の死が、幸せな人生についてのより良い見通しを持つ別の幼児の誕生につながる場合、障害のある幼児が殺されるならば、幸福の総量はより大きくなるだろう。^[Ibid., p. 163.]

シンガーの示唆は冷淡に聞こえるかもしれません。もしあなたが無垢な命を殺すことを絶対的な道徳的間違いと見なすならば、あなたはすぐに彼の主張が倫理的な境界線を越えていると見なすでしょう(安楽死に対するこのような異議は後の節で検討されます)。しかしながら、今のところは、シンガーの主張を額面通りに受け止めましょう。選好功利主義者(この理論についてのさらなる詳細は第1章で入手可能です)として、シンガーは、そのような場合にどのように行動するかについて、関係する個人の人生の質に基づいて彼の判断を下します。したがって彼の見解では、障害のある幼児は、彼らの代わりに生まれるであろう健康な幼児よりも人生の質が低いでしょう。なぜなら、前者ではなく、後者がより大きな選好の満足を得ることができるためです。したがって、私たちは健康な子供が生まれる状況を道徳的にもたらすべきです。

もし私たちが、PVSにある人や、末期症状の終わり近くで苦しんでいる人たちの人生の質が低いと仮定するならば、限られた医療資源を彼らの存在を維持することに費やすのは、その資源を他の場所に費やすよりも、道徳的に望ましくないと私たちは考えるかもしれません。この種の議論は、義務論者ではなくむしろ目的論者に訴えるでしょう。なぜなら、このような議論は、義務よりも結果に基づいた行動に対して道徳的価値を帰するからです。この状況では、PVSの患者に資源を費やすことの結果は、他の疾病の効果的な治療や将来の世代に役立つ医療研究への資金供与に同じ資源を費やすほどにはプラスにはならない可能性があります。

一部の金銭上の数字が、このありえそうな議論の筋道を示すかもしれません。マディソン郡の記録によると、クリスティーナ・マクレー(PVSの患者)には1年あたり平均25万ドルの医療費がかかっていました。^[Madison-St. Clair Record, http://madisonrecord.com/stories/510564252-nursing-expert-testifies-that-plaintiff-s-bills-could-be-8-4-million]もし私たちがPVSの患者が有しているであろう人生の年数を、現在存在しているPVSの患者の数とともに考慮するならば、そのような個人が生きるように保つコストはより明確になります。もし医学が時には困難な決定を下すことであるならば、なぜそのような患者の(少なくとも家族の支持がある)非自発的安楽死が望ましいと考えられるのかが明確になるかもしれません。さらに、高価な治療を伴う将来の苦しみに直面しているような人生の質の低い患者が自発的に安楽死を要求した場合、彼らの死は、苦しみを非常に減らすことのできる他の患者に資源をよりうまく振り向けることを可能にするでしょう。
病気にかかっていたり苦しんでいたりする、あるいは弱っている患者を治療する際における、この種の資源配分計画に不快感を持つ人に対しては、すでに目的論的な推論および人生の質に基づいた推論に照らして国家保健サービスの決定が行われているということに言及しておく価値があります。NHSは、財務計画と治療費の決定を行う際にQALYを利用します。QALYとは、質調整生存年(Quality Adjusted Life Year)の短縮形であり、関係する患者への利益に関して異なる治療費の利点を考慮するように設計された測定値です。もし潜在的な治療が患者を痛みから解放し、日常の活動を行うことができるようにする場合(これはやや大まかな定義ですが、私たちの目的にとっては十分です)、この結果が期待される年には1の値を与えることができます。引き続く各年に対して、治療の予想される持続的な影響に応じて、0と1の間の値が与えられます。このようにして、異なる患者の異なる形態の治療に支出を割り当てることは、支出の決定に対してより良い結果がどこで得られるかという観点から情報を与えるために、共通の基準に対して客観的に計算することができます。

したがって、資源の使用からの議論は、医学的意思決定に情報を与えるQALYの使用を拡張するものです。もし、回復するかもしれず、人生の質の向上を助けることができるような患者の治療にお金を費やすことの肯定的な結果が、死にたいと望んでいる人や、人生の質が低下している人、あるいはPVSにある人を生かし続けることにお金を費やす結果よりも大きいならば、前者に対する支出は後者に対する支出よりも道徳的に擁護可能です。あなたはここでもまた、資源が限られている世界の中で、PVSの患者を生かし続けることと、他の患者の人生の質を向上させるかもしれない治癒法や治療の研究に投資することのどちらが愛することであるかを検討することができます。

## 安楽死賛成派:議論3

私たちが提供する安楽死に賛成する最後の議論は、個人の自主性からの議論であり、この応用倫理的な領域で最も強力であると見なされている議論です。この議論は、人々が自分自身の意思決定をする権利を持つべきであり、自分自身の人生の道筋を決めることができるべきだという、かなり説得力のある仮定から進みます。もし自分自身の道を選ぶ権利が人生に当てはまるならば、いつどのように死ぬのかという選択に関してはなぜこれが当てはまらないのでしょうか?

おそらく、個人的な自主性と意思決定の権利の最も有名な哲学的な支持者は、ジョン・スチュアート・ミルでした。第1章で議論したように、ミルは危害原理を明らかにしました。それは、ある人の生活に対する政府による唯一の正当な干渉は、その人が他の人に害を与えるのを止めるものです。他のすべての干渉は正当化されません。もしあなたがこの原則に同意する場合、あなたは、安楽死を自発的に要求している人は、彼らの死が他の人に害を及ぼさない限り、死ぬ権利を否定されるべきではないと考えなければいけないようです。もし私たちが感情的害を割引するならば(私たちが行う多くの普通の事柄は他の人に感情的な害を及ぼしているように見えるため — たとえば、別の求職者にかわって職を得るなど)、苦しみがあまりにも極端になってしまう前の慈悲殺を求める終末期の患者の死が、他の人に肉体的害をもたらすというような状況を思い描くのは簡単ではありません。したがって、もし私たちが個人が正しいと見なすように行動する力および道徳的権利を信じる場合、身体的に他人を傷つけない限りにおいて、私たちは自発的安楽死は道徳的に正当化されることを認めなければならないようです。シンガーがその立場を要約しています:

> …自主性の尊重の原則は、合理的な主体が、強制や干渉から自由な自らの自主的決定に従って、自分自身の人生を送ることを認めるよう私たちに告げている。しかし、もし合理的な主体が自発的に死ぬことを選ぶのであれば、自主性を尊重することは、彼らが選択したことを行えるように彼らを助けることである。^[P. Singer, Practical Ethics, p. 195.]

PVSの患者は明らかに死ぬ方法を選択することができないため、私たちは、上記では特に自発的安楽死について話してきました。もし私たちがPVSの条件が発生する前に書かれた意向を表明する手紙という先に述べた可能性に戻るなら、いくつかの場合には非自発的安楽死もこれに基づいて正当化されるかもしれません — もちろん、そのようなケースは自発的な安楽死の一種のように思われますが。

しかしながら、もし私たちが無能力となったときに、愛する人たちが自分たちのために他の重要な医学的決断を下してくれると信じているならば、おそらく同じことがこの文脈で適用されるべきであり、非自発的安楽死は、ある人が他の人のために選択したものを適切に尊重することによって正当化されるかもしれません。このような方法で個人の自主性の理論を家族の自主性にまで拡張できるかどうかを検討するのはあなたの役目です。

## 安楽死反対派:議論1

ここまで私たちは、安楽死賛成派の議論についてのみ概説してきました。実際のところ、受動的安楽死が望ましくないことに関するシンガーの示唆のために、私たちは実際には能動的安楽死の議論しか提供していません。いまや、安楽死反対派と能動的安楽死反対派の議論に公正な機会を与える時間です。

安楽死への最初の異議は、生命の神聖さからの異議と呼ばれることがあります。生命の神聖さの倫理は、通常、宗教的な思考、特にキリスト教的な思考に基盤を持っています。本質的に、生命は聖なるものであるという信念は、それはあらゆる状況において価値があるということを意味するようなタイプの、生命の絶対的価値を示唆しています。グローバーの以前の言葉では、それは、生命はあらゆる質的な側面に優先する内在的価値を持っているという見解です。この節で説明する生命の神聖さの理論家と支持者にとって、人生の質に関する問題は決して生命の究極の価値と値打ちを損なうことはありません。

質に関係なく、すべての命は保存する価値があるという見解を持つことは必ずしも宗教的である必要はありません。非宗教的な人は、非自発的安楽死によって取り去られることがなく、また、自発的な安楽死の文脈では個人的な宣言によって無効にされることのない生命の絶対的な権利について話すことを好むかもしれません。しかしながら、より頻繁には、この見解は聖書を参照することによって支持されています。私たちは聖書で、神は「われわれのかたちに、われわれにかたどって人を造」ろうと言われた、ということを教えられます。^[7]

^[7] Genesis 1:26, https://www.biblegateway.com/passage/?search=Genesis+1%3A26-28&version=NIV

さらに、私たちの体は神聖なものであり、神の聖霊を含んでいると記述されています。「あなたがたは神の宮であって、神の御霊が自分のうちに宿っていることを知らないのか。もし人が、神の宮を破壊するなら、神はその人を滅ぼすであろう。なぜなら、神の宮は聖なるものであり、そして、あなたがたはその宮なのだからである。」^[1 Corinthians 3:16–18, https://www.biblegateway.com/passage/?search=1 Corinthians+3&version=NIV]これらの引用は、私たちの体の神聖さとその神聖さの原因 — すなわち神をかたどった私たちの創造と、私たちの中に神の御霊が存在すること — を明らかにするだけでなく、生命を奪う人たちに対する罰も明らかにします。これは安楽死を処置する医師に関連するでしょうか?

人生の質からの議論と資源の利用からの議論は、長引く人生の苦痛と潜在的に高くつく結果を考慮すると、その本質において公然と目的論的ですが、生命の神聖さからの議論は、殺人を避ける義務に関連しているため、その本質において義務論的です。マザー・テレサは、生命の神聖さの見解を中絶と安楽死の両方に結びつけて、この倫理的立場の魅力を述べました:

> 私にとって、生命とは人間に対する神からの最も美しい贈り物です。したがって、中絶と安楽死によって生命を破壊する人々と国家は最も貧しいものです。私は合法や違法ということを言っているのではありません。私は、生命を殺すために人間の手を持ち上げるべきではないと思います。なぜなら、生命とは私たちの中にある神の生命であるためです。^[J. Chaliha and E. Le Joly, The Joy in Loving, p. 174.]

すべての人間の生命は、子宮内にあろうとPVSであろうと、殺害(殺害の一形態としての安楽死を含む)が倫理的に許されないような神聖で神により授けられた価値があります。

安楽死問題に関するカトリックの教えの背後には、神聖な生命の概念があります。1980年のカトリック信仰宣言は、明確かつ本質的に絶対的です:

> …何人たりとも、彼自身・彼女自身のために、あるいは彼・彼女のケアに委ねられた別の人のために、この殺害の行為を求めることは許されない。また、彼・彼女は、明示的にも黙示的にもそれに同意することはできない。また、いかなる権威も、正当性をもってそのような行動を推奨する、あるいは許可することはできない。なぜならそれは、神聖な法の違反の問題であり、人間の尊厳に対する侮辱であり、生命に対する犯罪であり、そして人道に対する攻撃であるからである。^[Sacred Congregation for the Doctrine of the Faith, ‘Declaration on Euthanasia’, http://www.vatican.va/roman_curia/congregations/cfaith/documents/rc_con_cfaith_doc_19800505_euthanasia_en.html]

言葉はやや複雑ですが、重要な点はこの章のこれまでの私たちの議論で与えられています。生命は神聖であり、そのため、自発的に要請されたものであっても、他人のために非自発的に勧められたものであっても、安楽死は道徳的に許されません。いかなる立法者も、道徳的な理念に導かれれば、慈悲の誤った感覚によって動機づけられたものであろうとそうでなかろうと、このタイプの殺害を道徳的に推奨することは決してできません。

## 安楽死反対派:議論2

キリスト教への献身を前提にした、安楽死に対する関連した異議は、価値のある苦しみからの異議です(すべてのキリスト教徒が、程度の問題はあれども、このタイプの異議を擁護するわけではないことに留意してください)。1980年のカトリック信仰宣言に戻りましょう。この文書は、こう述べています:

> しかしながら、キリスト教の教えによると、苦しむこと、特に人生の最後の瞬間に苦しむことは、神の救いの計画において特別な場所を占めている。それは実際にはキリストの受難の分かち合いであり、神の意志への従属として神がもたらした贖罪の犠牲との融合である。^[Ibid.]

したがって、もし誰かが苦痛を避けるために安楽死を要請したとしても、その要求は、1人の人間から神の計画の要素を奪うものであるため、認められるべきではありません。人生の終わりの苦しみの経験は、その人をキリストの経験の分かち合いへと近づけます。これは、キリスト教徒が緩和ケア(生命を永らえようとする試みではなく、人が人生の終わりを迎えるにあたって個人を可能な限り快適な状態にするようなケアの一種)に反対することを意味するものではありません。しかしながら、それは、人生を自然な終わりまで見なければならない理由を説明し、なぜそれを短くすることが道徳的に間違っているとみなされるのかを説明します。

## 安楽死反対派:議論3

考慮すべき第3の安楽死反対派の議論は、滑りやすい坂の議論(くさびの議論と呼ばれることもあります)と名づけることができます。この異議は、生命の神聖さ、または殺してはならないという義務論上の義務に関するいかなる見解も必要としません。実際には、滑りやすい坂の異議は本質的に目的論的なものであるとともに、抽象的に見たときには、あるいは孤立して見たときには、何らかの場合において安楽死が望ましいことがあることの拒絶を要求することさえもありません。

滑りやすい坂の異議は、もし安楽死がいくつかの状況で合法になる場合、実際には道徳的に望ましくないような状況で安楽死が合法かつ容認されることにつながるかもしれない、というものです。このような異議の強さを知るために、資源配分と個人の自主性の観点から表された以前の安楽死賛成派の議論を検討してみましょう。

もし資源が他の場所に回されればより良くなるという時に目的論的な立場から安楽死が正当化できるならば、私たちが単に自発的安楽死と非自発的安楽死ではなく、強制的安楽死をも正当化するの止めるものは何かあるでしょうか?もしお金と時間がある患者よりも別の患者に費やされることでより良くなることに基づいて安楽死が正当化されるならば、なぜ患者自身または患者の家族からの許可が必要なのでしょうか?

もし道徳性が結果によって決定され、結果が安楽死を正当化するならば、私たちは同意なしに人々を安楽死させるような危険な斜面を滑り落ちていくように見えます。結局のところ、もしあなたが目的論者(おそらく、行為功利主義者)であれば、あなたはすでに特定の行動に対する絶対的な規則に関する考え方をあきらめていることでしょう。したがって、生命が神聖であるか、あるいはそうでないかには異論があり、もしそうでないならば、私たちは明らかに道徳的な動機から出発したとしても、道徳的にまったく擁護できないように思われる状況にたどり着いてしまうことがあります。

さらに、もし人がいつ人生を終わらせるかを選ぶことができる程度に個人の自主性が尊重されるならば、身体的には健康であるものの重度のうつ病の人が自発的な安楽死を選ぶことを止めるものは何ですか?ほとんどの人は、精神保健的な必要性のある患者の自殺を可能にすることは、PVSの患者や終末期の患者の安楽死とは非常に異なるものとして見るかもしれませんが、しかし、もし個人的な自主性が安楽死を正当化するならば、私たちはどのようにして、ある人は死を選ぶことが認められ、別の人は認められないような十分に強い線を正当性をもって引くことができるのでしょうか?ここでもまた、個人的な自主性が重要であるか、それともそうではないかについては、反論されるかもしれません。もし私たちが、ある人が人生を終わらせることを可能にするならば、彼らが後の段階で彼らの人生の価値について異なる視点(彼らがまだ生きていたら持つかもしれないような)にたどり着くことは決してないことは明らかです。この問題については、ある人の選好や、それらは何らかの心理テストやカウンセリングに向かうときにだけ道徳的な意味を帯びているのどうかに関する第1章の議論を再検討する価値があるかもしれません。関連する考え方はリチャード・ブラントによるものです。

さらに、安楽死の反対者はしばしば、あるグループの人々が安楽死させられると、他の人々が同じ選択肢をとるよう圧力を感じ始める可能性があることを示唆しています。非自発的な安楽死が認められ、その結果、法的、道徳的、文化的に超えてはいけない一線が超えられると、高齢の患者は家族の負担にならないように、というプレッシャーを感じるのではないでしょうか?金銭的に裕福な高齢者は、財産が自分自身の治療に費やされるのではなく、蓄積した富を子供たちに相続させることを認めるようなプレッシャーを感じるのではないでしょうか?非自発的安楽死を少数の場合とはいえ認めることは、時間が経つにつれて、私たちが滑りやすい坂を下って、他の選択肢を検討する理由がないために物事がそのままであれば生き続けることにかなり満足している他の多くのタイプの患者に対する、道徳的に擁護できない安楽死に至るかもしれません。

もちろん、滑りやすい坂の異議に対する簡単な返答は、ある1つの事実における変化がどこか他の場所での示唆されるような否定的な変化に必ずつながることを単純に否定することです。否定的な結果が起こらないであろう時に、なぜ法律の変更によるそのような結果を考えるのですか?実際に、いくつかの滑りやすい坂の議論は、何らかの政策の変化にはありえそうな否定的な結果が必然的に伴わなければならないという考え方を前提とするならば、論理的な誤謬になります。しかしながら、そのような方法でこの異議を「藁人形」にするべきではありません(つまり、反論するのが簡単になるような弱いやり方でそれ言い表すべきではありません)。滑りやすい坂の異議は、否定的な結果が確実なものではなく、あり得そうであることを示唆しています。したがって、この異議に対する返答は、もっともらしく合理的な異議の構造を故意に虚偽表示して品位を落とすのではなく、むしろ、あり得そうな否定的結果の問題に対処することで行うべきです。安楽死に関する法律がおそらく世界で最も自由なベルギーでの状況を研究することは、規則功利主義の適用を考慮するのと同様に、この考え方を支持したり、反対したりするための良い基礎を提供するはずです。^[次の記事は、ベルギーにおけるその法律の使用を強調しています: ‘Belgian Convicted Killer with “Incurable” Psychiatric Condition Granted Right to Die’, https://www.theguardian.com/world/2014/sep/16/belgium-convict-granted-right-to-die]

## 安楽死反対派:議論4

第4の安楽死反対派の異議は、現代の治療法からの異議です。この異議は、2つの異なった、しかし関連を持つように類似している考え方を結びつけます。まず、末期症状の人やPVSの人を安楽死させることは、そうでない場合よりも早くその人たちを殺し、その結果、彼らの病状に対する治療を受けるために生きる機会を人為的に排除することを示唆するでしょう。たとえ治癒ではないにしろ、少なくとも安楽死された人々は、彼らの苦しみを和らげるであろう治療法の前進の恩恵を受けることはありません。

さらに、緩和ケアの現代的進歩を考えると、人生の終末期のケアは非常に進んでいるため、苦しみを避けるための安楽死は必要なく、人生の質の面でも正当化することはできないと主張できるかもしれません。安楽死させられていない深刻で悪化しつつある病気を持つ人は、苦しみを大幅に減らすために、熟練した医療専門家によって彼らの症状と苦痛を注意深く管理してもらうことができると考えるのは、ありえそうなことです。

これらのタイプの異議に対して、シンガーは、もし安楽死が合法化されたならば、生きたままであれば治療を受けられたかもしれないような人々が死ぬ可能性があることを認めています。しかしながら、彼はこう主張します:

> 私たちは、安楽死が合法化された場合に起こり得る非常に少数の不必要な死に対して、安楽死が合法化されない場合に実際に末期的な病気にかかっている患者が苦しむであろう非常に大きな痛みと苦痛を対置しなければならない。^[P. Singer, Practical Ethics, p. 197.]

結局のところシンガーは、安楽死は早く死んだ人が逃した喜びよりも多くの苦痛を止めるであろうと示唆しています。緩和ケアがこの異議によって示唆された程度まで苦痛を減らすことができるかどうかは、議論を進めるために現代的な証拠を必要とする経験的な主張であるように思われるので、あなたはより深い研究と検討をすることを望むでしょう。

## 認めることと行うこと

ジェームズ・レイチェルズ(1941–2003年)は、安楽死の議論の中で認めることと行うこととの間の区別の想定された道徳的重要性を要約しています:

> 能動的安楽死および受動的安楽死の間の区別は、医療倫理にとって極めて重要であると考えられている。この考え方は、少なくとも一部のケースでは、治療を停止して患者が死ぬのを認めることは許されているが、患者を殺すために設計されたいかなる直接的な行動をとることも決して許されないということである。この教義は、ほとんどの医師によって受け入れられているようだ。^[J. Rachels, ‘Active and Passive Euthanasia’, p. 511.]

したがって、レイチェルズによれば、彼の論文が書かれた時代 — そしてそれ以来イギリスにおける文脈はあまり大きくは変わっていないように見えます — のほとんどの医師は、患者が死ぬのを認めることは許されると考えているが(私たちの定義では受動的安楽死)、たとえ患者が安楽死を要求したり、あるいはそれが彼らの利益になるとみなされたりしても、患者を殺すこと(能動的安楽死)は許されないと考えているようです。

この区別の妥当性は、第4章で論じられている規範的な自然法の道徳理論から導き出される、二重の結果のドクトリンを考慮することによって支持されます。自然法の倫理の章から、人間にとっての主たる教訓は生命を保存することである、ということを思い出してください。これよりも強力かつより絶対的に安楽死に反対する道徳的指示はないと、私たちは考えるかもしれません — アクィナスの自然法の立場によるカトリックの背景と、生命の神聖さの倫理の文脈におけるカトリックの見解への以前の言及を考慮するならば、なおのことです。この主たる教訓から派生した二次的な教訓は、人為的な生命の短縮の道徳的な容認可能性を確かに否定しているようです。しかしながら、自然法理論家は、安楽死の議論において微妙な立場を取ることができます。

自然法理論家は、二重の結果のドクトリンを介して、抽象的にはたとえ道徳的に許容されないとみなされるであろう結果をもたらすとしても、ある行動を道徳的として記述することができます。もしある行為が道徳的に良いことを行いたいという欲求によって導かれているものの、悪い効果という予見可能ではあるが意図しない結果をもたらすならば、この行為は、その悪い効果が目的とされておらず、その悪い効果が良い効果を上回らず、その悪い効果が悪さそれ自体の直接の原因ではない限りにおいて道徳的なものです。もしこの短いコメントが不明瞭である場合には、自然法に関する章の二重の結果のドクトリンの関連する議論を振り返っておくことが重要です。

さて、このドクトリンを安楽死の文脈に直接適用してみましょう。ある医師は、患者が長く生きることはなく、非常に苦しんでいることを知っているかもしれません。この医師は、痛みを抑えるために複数の鎮痛剤を処方することができますが、これには、この薬剤の副作用の結果として患者を死なせるという予見可能ではあるが意図しない効果が伴います。実際、別の医師は、苦しみを引き起こすのを避けるために痛み止めの治療法を提供することを単に控えるかもしれませんが、これには患者が非介入の結果として死ぬという予見可能ではあるが意図しない結果があります。これらの行動は道徳的に間違っているわけではない、と自然法理論家は言います。なぜなら、死は直接的に意図されたものではなく、むしろ痛みの軽減という道徳的に良い目的が直接的に意図されているからです。したがって、患者の苦しみを減らすように彼らを人為的に殺すために、致命的な組み合わせの薬物を提供することによって能動的な安楽死に関与する医師は、道徳的に間違っています(「苦痛の軽減」の良さが、殺害の悪さによって直接的に達成されているためです)。一方、意図していないが予見可能な死という結果が伴うものの、苦しみを和らげるために治療を停止した医師は、道徳的に正当に行動しています(「苦痛の軽減」の良さが、痛みを伴う治療を行うことによらずに達成される — 死は比較として受け入れられる副作用であるためです)。

レイチェルズとシンガーの両者は、この議論において、認めることと行うこととの区別、そして二重の結果のドクトリンにほとんど時間を割いていません。レイチェルズはこう言っています:

> もしある医師が人道的な理由からある患者が死ぬようにした場合、彼は人道的な理由で患者に致命的な注射をしたのと同じ立場にある…もし医師の(患者の死に介入しないという)判断が正しいものであるならば、使用される方法はそれ自体では重要ではない。^[Ibid.]

一方、シンガーは次のようにコメントしています。「私たちは、私たちの意図をある1つの結果ではなく別の結果に単純に向けることによって、責任を避けることはできない。もし私たちが両方の結果を予見するならば、私たちは、私たちがすることの予見される結果に対して責任を負わなければならない。」^[P. Singer, Practical Ethics, p. 183.]シンガーは、より多くの労働者を雇うためにお金を節約しようとしている企業の例を挙げています。この結果は良いものであり、上司たちがリサイクル代のお金を節約するように行動するよう動機づけますが、それは地元の川を汚染するという予見されるが意図していない結果を伴います。シンガーはこう言います。もし私たちが予見可能な結果を​​無視したことに関してその会社を許さないとしたら、私たちは、私たちが安楽死の文脈において死を許したことの責任を免れると実際に信じることはできません。

二重の結果のドクトリン、そして自然法の倫理全般の安楽死の議論への適用は、注意深く、そして規範的理論そのものを概説する前の章の観点から検討されるべきです。シンガーとレイチェルズの両方からの攻撃にもかかわらず、自然法と二重の結果のドクトリンは多くの支持者を保持しています。もし道徳的結果が帰結のみよりも大きなものに基づくものとみなすならば、このアプローチは、シンガーのような選好功利主義者が与えるものよりも大きなメリットがあるように見えるかもしれません。これはあなたが判断することです。

## まとめ

安楽死は深淵な意味を持つ応用的な道徳の話題です。この道徳的な議論が成功した場合、文字通り人生を短縮または延長する法律上の変更につながる可能性があります。この議論には、うつ病患者の能動的安楽死の容認可能性、怪我をする以前の治療や死についての要求の重要性、医療資源を配分する最善の方法、人々が自分自身の身体と無能力となった家族の身体に行使することができる力など、私たちが口先だけで賛同するが実践はしないような多くの曖昧さがあります。更なる問題は、J・デイヴィッド・ヴェレマンの仕事などの中で議論されており、私たちは、以下の参照文献を有用で興味深い文献のガイドとして提案しておきます。^[J. D. Velleman, Beyond Price: Essays on Birth and Death, https://www.openbookpublishers.com/reader/349]しかしながら、私たちは、安楽死のさまざまな方法やそれらの方法が採用されるであろうさまざまな文脈に対して、あなたが賛成と反対の双方の重要な議論を説明し、評価することに自信をつけたことを願っています。

## 学生によくある間違い

* 滑りやすい坂の異議を本来のものよりも単純にしてしまう — 確実な将来の結果でなく、ありえそうな将来の結果に焦点を当てる。
* 宗教的でないということは、生命の神聖さにあっさりと反対するのに十分である、とそっけなく示唆する。人生は非宗教的理由からも絶対的価値があるかもしれず、これはきちんと取り組むべき考え方です。
* 人生の質の議論を、適切に取り組むことなく単に宗教的信念のために却下する — 苦しみに直面しているとしても命を引き延ばすべきであるという考え方は、適切な擁護を必要とします。
* 安楽死への適用における二重の結果のドクトリンを誤解する — 自然法の倫理に関する章で得られたより詳細な知識を念頭に置いてください。
* 安楽死賛成派の見解は必ず世俗的であり、安楽死反対派の見解は必ず宗教的であると考える。すべての選択肢は開かれたままです。

## 検討すべき問題

1. 人生を生きる価値のあるものとするのは何ですか?価値のない人生はありますか?
2. 二重の結果のドクトリンは倫理的に意味があるべきですか?許可することと行うことの間には道徳的な違いがありますか?
3. 幇助された自殺とは何ですか?それは安楽死とは異なるものですか?
4. もし安楽死が道徳的に受け入れられる場合、受動的安楽死は容認される方法とみなされるべきですか?
5. この文脈で、滑りやすい坂の異議を阻止できますか?ベルギーの安楽死法の発展に関連させて回答してください。
6. 規則功利主義は、滑りやすい坂の異議を切り抜ける唯一の目的論的理論ですか?
7. 資源配分からの議論について、道徳的に不快なことはありますか?もしあるならば、それは何ですか?
8. もしあなたが安楽死法を起案しているならば、それはどのようなものになりますか?
9. 生命の神聖さの倫理は21世紀の医学において何か役割を果たすべきでしょうか?
10. 安楽死の道徳性は、利用可能な緩和ケアのレベルなどの経験的な要因によって決定されますか?
11. うつ病患者は安楽死が許されるべきですか?個人の自主性は、私たちが常に尊重しなければならないものですか?もしそうでない場合、いつ、それは尊重されるべきでないのですか?
12. 強制的安楽死(人の望みに反する安楽死)はどのような状況であれば正当化されることがあるのでしょうか?

## 重要な用語

二重の結果のドクトリン

緩和ケア

永続的植物状態

福利

生命の神聖さ

藁人形

## 参照文献

‘Belgian Convicted Killer with “Incurable” Psychiatric Condition Granted Right to Die’, the Guardian (16 September 2014), freely available at https://www.theguardian.com/world/2014/sep/16/belgium-convict-granted-right-to-die

Bible, New International Version, freely available at https://www.biblegateway.com/

Chaliha, Jaya, and Le Joly, The Joy in Loving: A Guide to Daily Life with Mother Teresa (London: Penguin, 1996).
<br>[「日々のことば」、いなますみかこ訳、女子パウロ会、2009年]

Glover, Jonathan, Causing Death and Saving Lives (London: Penguin, 1990).

Madison-St. Clair Record, freely available at http://madisonrecord.com/stories/510564252-nursing-expert-testifies-that-plaintiff-s-bills-could-be-8-4-million

Hari, J., ‘Peter Singer: Some People are More Equal than Others’, freely available at http://www.independent.co.uk/news/people/profiles/peter-singer-some-people-are-more-equal-than-others-551696.html

Sacred Congregation for the Doctrine of the Faith, ‘Declaration on Euthanasia’, freely available at http://www.vatican.va/roman_curia/congregations/cfaith/documents/rc_con_cfaith_doc_19800505_euthanasia_en.html

Singer, Peter, Practical Ethics (Cambridge: Cambridge University Press, 2011), https://doi.org/10.1017/cbo9780511975950
<br>[「実践の倫理 新版」山内友三郎・塚崎智監訳、昭和堂、1999年]

Rachels, James, ‘Active and Passive Euthanasia’, Biomedical Ethics and the Law, 5 (1979): 511–16, https://doi.org/10.1007/978-1-4615-6561-1_33

Velleman, J. David, Beyond Price: Essays on Birth and Death (Cambridge, Open Book Publishers, 2015), https://doi.org/10.11647/OBP.0061; freely available at https://www.openbookpublishers.com/reader/349