# ビジネス倫理

> ビジネス倫理などというものはない。
> ---ジョン・マクスウェル

> お金しか稼がないビジネスは、貧しいビジネスである。
> ---ヘンリー・フォード

## ビジネス倫理入門

ビジネスとは何ですか?クリスチャン・エイドはビジネスですか?マクドナルドは?大学はどうでしょうか?これは答えるのが難しくて複雑な質問ですが、私たちは、ビジネスとは利益のために商品やサービスを購入し販売する組織であるという主張から始めましょう。

もし私がお店から何冊かの本を買うならば、それらは商品であり、ビジネスは利益を得ます。もし私が空港に行くためにタクシー運転手にお金を支払うならば、それはサービスであり、私はタクシー会社の利益を増やします。

では、クリスチャン・エイドはビジネスではないのでしょうか?マクドナルドが明らかにビジネスであるのに対して、クリスチャン・エイドには、商品やサービスを購入する「顧客」は間違いなくいません。しかし、大学はどうでしょうか?まあ、これははるかに難しく、より論争の的になる質問であり、あなたが検討するように最後の項目に掲げておきました。どのようなビジネスであっても、その規模に関わらず、その重要な機能は、利益のために商品やサービスを販売するということです。

関係性が存在するために倫理が生じてきます。つまり、もし関係性がある場合には、その関係性の中で私たちはどのように行動すべきかという正当な質問が存在します。ビジネスでは、多くの異なる関係性が存在するため、私たちはこれらの関係のそれぞれについて倫理的な質問をすることができます。以下はいくつかの例です。

(a)ある企業は、株主 — その会社の株式を所有する人々 — との関係性を持っています。しかしながら、もし株主が労働者の賃金を減らしてより大きな配当を得ることを望む場合、彼らは何か道徳的に間違ったことをしているのでしょうか?結局のところ、彼らは間違いなく、ある意味では、その企業を「所有している」と言われており、彼らがそれに望むことを行うことができます。

(b)ある企業は、顧客 — 商品とサービスを購入する人々 — との関係性を持っています。たとえば、もしある企業が、利益を増やすためにラベルに記載されている健康アドバイスの量を意図的に減らした場合、その企業は何か道徳的に間違ったことをしているのでしょうか?

(c)ある企業は、従業員との関係性を持っています。もしある企業が、育児休暇を廃止することによって生産性を高めることができると認識した場合、それを行うことは道徳的に間違っているでしょうか?逆に、もし従業員が疑わしい行為に関与して、その後「内部告発者」になった場合、彼女は何か道徳的に間違ったことをしているのでしょうか?

(d)ビジネスと環境との関係性に関連して生じる倫理的な疑問もあります。もしある企業が新しい工場を開設し、地域経済が必要としていた後押しを提供するものの、それは自然保護区に工場を建設することによってのみ行うことができるという場合、それは何か道徳的に間違ったことをしているのでしょうか?

(e)また、企業活動によって影響を受ける別の人たちもいます。たとえば、携帯電話会社が新しい電話塔を設置して、それが地域社会に聞こえるような低音ノイズを発する場合、この会社は何か道徳的に間違ったことをしているのでしょうか?

もちろん、企業は常に倫理的な意思決定をしてきました。1847年の工場法以前の工場における労働条件は、たとえ当時には認識されていなかったとしても、確実に道徳的に間違っていました。

これは、あらゆるビジネスの宣伝材料で全面的に表示された「価値観と倫理」の声明をあなたが目にするような現在とはかなり対照的です。「価値観と倫理」という言葉を話さないことは、ビジネスの実践としては非常に悪手です。この文脈でよく使われる言葉は、ある会社における「企業の社会的責任」(CSR)です。私たちは、CSRを「[…]すべてのステークホルダーに経済的、社会的、環境的利益をもたらすことによって持続可能な発展に貢献するビジネスアプローチ」を意味するものとして受け取ることができます。^[‘FT.com/Lexicon’, Financial Time, http://lexicon.ft.com/Term?term=corporate-social-responsibility--(CSR)] 明確なCSRを持つ企業の良い例はボディ・ショップ社であり、この会社は1988年に「倫理的取引イニシアティブ」の創設メンバーになりました。^[倫理的取引イニシアティブの詳細を知るにはhttp://www.ethicaltrade.orgを見てください]

現在では、CSRの観点から最も良い企業、最も倫理的な企業を顧客に知らせる倫理的ランキングが数多くあります(たとえば、フォーブスの「世界で最も倫理的な企業」)。^[See K. Strauss, ‘The World’s Most Ethical Companies 2016', http://www.forbes.com/sites/karstenstrauss/2016/03/09/the-worlds-most-ethical-companies-2016]

今や、企業が「倫理」声明を出すのが規範となっていますが、会社が倫理的であることは、おそらく非合理的です。これはなぜでしょうか?以下の基本的な議論を検討してみてください。

1. ある企業の目的は利益を上げることです。
2. ある企業が顧客を引き付けることができれば、その企業は利益を上げることができます。
3. 現在の状況(少なくとも西洋の)では、ある企業が倫理的に見える場合、その企業は最も多くの顧客を引き付けるでしょう。
4. ある企業が、実際に倫理的となるのではなく、倫理的に見えるようにする場合には、より多くの利益を上げることになります。なぜなら、単に見た目上倫理的になるのではなく、本当に倫理的となるのには、実際により多くのコストがかかるからです。

したがって、(1)-(4)を踏まえると、ある企業は、実際に倫理的になるのではなく、単に倫理的であるように見せかける方が、より合理的なようです。

もちろん、上記の議論から生じる多くの疑問があります。たとえば、私たちは見破られること(すなわち、倫理的に見えているが実際にはそうではない)の潜在的なコストを考えることができるかもしれません。それは、最初から実際に倫理的になるコストをはるかに上回る可能性があります — したがって(4)は拒絶されるかもしれません。しかしながら、単に倫理的に見せかけるだけにして、実際に倫理的になるための長くて、しばしば高価なプロセスをたどらない、という選択肢の大きな魅力は残っています。当然のことながら、企業が倫理的であるかどうか、それが外見を繕っているのか、それとも単にシニカルなマーケティング手段であるかどうかというのは、開かれた経験的な疑問です。

この章では、私たちは企業倫理のいくつかの分野を、功利主義とカント的な義務論という規範理論のレンズを通して見ていきます。

## 雇用主と従業員

> 1992年、マイク・アシュレイはスポーツ・ダイレクト社を設立しました。この会社は急成長し、イギリスで最大のスポーツ小売業になるとともに、ヨーロッパでも有数のスポーツ小売業になりました。しかしながら、2016年に、従業員に対する極めて厳しい労働慣行と見なされるものが暴露され、労働者が最低賃金を支払われていなかったことが明らかになりました。ある従業員は、「もし4時間に1回以上の頻度でトイレに行くと、私たちはマネージャーのオフィスに呼び出され、質問された」と主張しています。「私はやめるまで6日しかもたなかった。」^[D. Avis, ‘Sports Direct: Former Employees Speak Out’, http://www.bbc.co.uk/news/uk-36864345] 従業員は仕事の後で店を出るときによく検査され、時には服を脱がされて下着姿にされました。従業員は1分遅刻すると15分の額の賃金を没収されました。「ゼロ時間契約のもとでは、私は時には10日間連続して1日10時間働くことがあった。他の週には、1週間に1回だけ3時間のシフトが与えられた。ルーチンはなかった。」^[Ibid.]

スポーツ・ダイレクトは何か道徳的に間違ったことをしていたのでしょうか?これをもっと扱いやすくするために、彼らのふるまいの違法性を脇に置いておきましょう。彼らは彼らの慣行の中では何も違法なことはしていなかったと想定しましょう。

これを踏まえると、私たちは、彼らが道徳的に間違ったことを何もしていないと思うかもしれません。結局のところ、従業員はこの会社で働くことを強制されてはいませんでした。彼らは自分の机に鎖で縛り付けられてはおらず、出口へ行くことを拒絶されたわけでもありませんでした。従業員は囚人や奴隷ではなく、この会社で働くことを選んだ合理的な人間でした。従業員は単に契約書の「細かい文字」の注意書きを読み落としていたというのがもっともらしく思われます。この場合、なぜこの企業が何か間違ったことをしていたと考えるのでしょうか?

「行為功利主義者」(第1章参照)にとっては、ある行為が他のどのような行為よりも幸福をもたらす時、かつその時に限り、その行為は道徳的に正しいということを思い出してください。そのため、おそらくスポーツ・ダイレクトは道徳的に間違ったことは何もしていませんでした。

スポーツ・ダイレクトの場合、安価なスポーツ製品を所有することで幸せを得た何百万人もの人々が、約27000人の従業員の悲惨さと不幸を上回っていた可能性があります。この場合、スポーツ・ダイレクトが、彼らが実際にやっていたような方法で従業員を扱うことは道徳的に受け入れられるものでした。

さらに、行為功利主義者は、一般的な「権利」、特に「従業員の権利」を相手にしません。しかしながら、ほとんどの人はスポーツ・ダイレクトがしたことはたとえ合法であったとしても道徳的に間違っていると考えるであろうし、人々はこの会社が実際にやっていたような方法で行動するべきでなかったと判断するであろう、と私たちは思っています。

それはおそらく、たとえ私たちが行為功利主義者であるとしても、私たちはこの結論を導く必要はないとも言えます。これはミルが、満足している豚より不満足な人間である方が良いと言ったからです。彼は「より高い」喜びと「より低い」喜びがあると考えていました。人間だけがより高い喜びを経験することができ、人間以外の動物はそれができません。

ミルは、喜びは定性的な「快楽」計算にだけ頼るべきではないと主張します。もし私たちがより高い・より低い喜びを導入するならば、私たちはスポーツ・ダイレクトがしたことが道徳的に間違っているという直観を尊重することができます。ミルは、より高い喜びとより低い喜びが質的に異なっていると考えました。もしこれが真実ならば、私たちは、公平に扱われている数万人の従業員のより高い喜びは、新しいテニスラケットを手にしたり、最新の流行のトレーナーを所有したりする100万人の人々のより低い喜びよりも大きいと考えるかもしれません。

さらに、帰結主義理論はまた、幸福や喜びといった言葉ではなく、厚生や選好などの他の言葉で、「効用」を説明しています。そして、厚生帰結主義者あるいは選好帰結主義者は、スポーツ・ダイレクトがしたことは、その行動が厚生および/または選好を最大化しなかったため、道徳的に間違っていると結論付けるかもしれません。しかし、この主張を調査することは、この章の範囲をはるかに越えてしまいます。

行為功利主義から離れると、「従業員を公正に扱う」というルールが功利主義的な立場から正当化されるため、規則功利主義者はスポーツ・ダイレクトの行動が道徳的に間違っていると主張するであろう、と私たちは考えることができます。つまり、人々は典型的には、この規則が順守されている場合は、そうでない場合よりも、より幸せになるでしょう。したがって規則功利主義者は、スポーツ・ダイレクトは疑いようもなくその従業員を公正に扱わなかったため、スポーツ・ダイレクトがしたことは道徳的に間違っていると結論づけるかもしれません。

次に重要なことは、功利主義者が特定のビジネス慣行が道徳的に正しいか間違っていると考えるのは、言葉で言うほど明確ではないということを認識することです。むしろそれは、状況の詳細や、私たちが立場に応じてどのように喜び、幸福、福利、選好などを最大化するべきか、ということに依存します。

功利主義者についてはこれだけにしておいて、カント主義者はどうなのでしょうか?(第2章を参照)さて、カント主義者は義務と定言命法という用語で話をします。カント主義者にとって、誰かを目的のための手段としてのみ扱うことは、常に道徳的に間違っています。

一見したところでは、これは、従業員を目的(利益)のための手段として扱う際にスポーツ・ダイレクトがまさに行ったことだ、と私たちは考えるかもしれません。しかし、これはそれほど単純ではありません。もしそれが真実ならば、すべての企業は利益を上げるために従業員を使っているので、すべての企業が何か道徳的に間違ったことをしていることになってしまいます。

私たちは、カントが言っていることについてもう少しきちんと考える必要があります。カントは、企業は人々を目的のための手段として利用できないと言っているのではなく、重要なことは、企業が人々を合理的かつ自由なものとして扱っているかどうかということです。

私たちが自分自身の目的のためにタクシー運転手を使用していたとしても、タクシーを利用することは道徳的に間違っていません。これは、私たちがタクシー運転手にお金を支払い、彼らは自発的にこの手段-目的関係に参入してくるからです。同じことが、企業の従業員にも言えるでしょう。確かに、マクドナルドや、フォードや、ボディ・ショップが従業員を目的のための手段として利用しているのは事実ですが、彼らは従業員にお金を支払い、従業員は仕事の契約へと自由に参入してくるため、これは容認できるものです。

おそらく、カント主義者はスポーツ・ダイレクトが違うと言うでしょう。なぜなら、スポーツ・ダイレクトは、搾取の一形態を実践したためです。スポーツ・ダイレクトのために働く人々は、非常に多くの場合、社会の最貧層の人々です。これは、彼らは選ぶことができるような仕事を沢山は持っていないことを意味し、彼らは仕事をやめてもすぐに別の仕事を見つけることができません。さらに、仕事をやめることによって彼らは家賃を支払うことができず、通りに放り出され、関係性が壊れるといったさらに悪い状況に陥ることがあるかもしれない、と想像できます。

この場合、私たちは、従業員がスポーツ・ダイレクトで働くことを実際に自由に選択しているのかどうか疑問に思うかもしれません。もしそうでないならば、スポーツ・ダイレクトは従業員にお金を支払っているにもかかわらず、その従業員を目的のための手段として扱っています。この場合、カント主義者は、そこで起こっていることは道徳的に間違っていると言うでしょう。私たちが以下で他の問題を検討する際には、私たちはカント主義者の立場の他の特徴を見ていきます。

## 企業と顧客

顧客が商品やサービス、彼らの周りの世界、そして彼ら自身について、どのように考えるかに対して、企業が直接的な影響を与えることができるのは明らかです。もし彼らができないのであれば、彼らは毎年数百万ポンドもの額を広告に費やしたりはしないでしょう!しかし、それを踏まえた上で、彼らは信頼される立場にあります。この信頼からは、会社がどれだけの量の情報をどのような形で顧客に提供すべきかに関する問題が生じます。

> 2011年にある裁判所の判決で、銀行がかつて誤って販売した支払い保障保険(PPI)は「無能かつ無効」であると判断され、銀行は何百万人もの人々に補償しなければならないと判示されました。銀行がPPIが詐欺であることを知っていたことは疑いようもありませんが、PPIの販売を止めることは彼らの関心事ではありませんでした。なぜなら、それは「儲かる商品」だったからです。PPIを売るために、銀行は「セーフティネット」を約束して顧客の不安につけこみました。PPIは、病気や失業により収入が減少した場合、人々の借入金を肩代わり返済することを約束していました。

ここでは、顧客に向けた企業の行動が道徳的に間違っているケースを考えることができます。しかし、私たちはどうすればこのことを説明できるでしょうか?まあ、それを説明する1つの明白な方法は信頼です。消費者団体「Which?」で働いていたダグ・テイラーはこう述べています。「私たちは、人々がPPIを誤って売りつけられていることはずっと知っていましたが、それでも私たちはその規模を知って驚きました。まるで、営業担当者が手数料を追いかけて、上司は利益を追いかけているように見えます。顧客への責任感はどこにいったのでしょう?」^[G. Wearden, ‘How the PPI Scandal Unfolded’, https://www.theguardian.com/business/2011/may/05/how-ppi-scandal-unfolded]

しかし、この「責任」はどれほどの距離にまで到達するのでしょうか?顧客にバランスのとれた「正直な」視点を与えることは、企業の利益 — もうけを上げること — では当然ありません。コンピュータの広告に「これは非常に高価です。あなたはおそらくラベルを購入しているだけです。統計によれば、あなたはおそらくゲームや、文書作成や、ウェブサーフィンのために、この性能の5％ほどしか使わないだろうと言われていることをあなたは自覚しておくべきです。」といったことが書いてあったならば、この広告は売り上げの面では会社に多くをもたらすことは多分ないでしょう。このようなやり方で正直でバランスをとることを企業に強制するのは不公平なようです。

しかし、一方では、会社はうそをつくことができません。これは、もちろん、「馬肉」スキャンダルや他の「食品詐欺」のケースが非常に議論を呼ぶようになった理由です。^[‘Horsemeat Scandal: Where Did the 29% Horse in your Tesco Burger Come From?’, the Guardian, https://www.theguardian.com/uk-news/2013/oct/22/horsemeat-scandal-guardian-investigation-public-secrecy]人々が馬肉を食べることを選ぶこともあるでしょうが、彼らがそれを食べるように騙されたときには問題が発生する可能性があります。これは、食品会社が意図的に嘘をついた、または利益のために顧客を騙したケースです。

しかし、嘘をつくとは何でしょうか?まあ、それは誰かが真実を伝えるのに失敗したことではなく、むしろそれは、意図的な騙しを伴うことです。しかし、なぜ企業は嘘をつくことを避けるべきなのでしょうか?

行為功利主義の説明を見ると、企業が嘘をつくのが常に間違っているのはなぜなのかを言うことはかなり難しくなります。おそらく、行為功利主義者にとっては、企業が嘘をついて顧客の信頼を搾取することは常に道徳的に間違っているとは限りません。もし嘘をつくことによって、企業が嘘をつかないときよりもより大きな幸福を生み出すならば、企業が嘘をつくことは道徳的に受け入れられます。

私たちは、規則功利主義者にとっても同じ結果が得られるだろうとは思わないでしょう。もっともらしいルールとは、「あなたが嘘をついたことが見つかる合理的な理由があれば、信頼される立場で嘘をついてはいけない」ということです。もしこれが功利主義的な根拠によって正当化されるならば、企業が顧客に嘘をつくことは容認できないでしょう。しかし、規則功利主義者の説明であっても、時には企業が嘘をつくことが道徳的に容認されることがあるというのは事実です。

これはカント主義者のアプローチとは対照的です。思い出してもらいたいのは、カント主義者にとって、嘘をつくことは常に道徳的に間違っています。人が嘘をつくべきではないことは、すべての状況において事実です。カントはこのことを示すために定言命法を使用しています。 PPIの事例を再検討してみましょう。銀行の社長が、「もし利益が上がるならば、顧客に嘘をつく」という格率が普遍的な法となることを望むことは、非合理的でしょう。なぜなら、もしこれが普遍的な法であれば、企業には全く信用がなくなり、利益も企業もなくなってしまうだろうという理由から、これは非合理的です。それは自滅的で非合理的です。カント主義者の立場では、PPIが販売された方法は道徳的に間違っていたように見えます。

## 企業と環境

上記で議論したように、企業の社会的責任について話すのは企業の間の共通言語となっています。言い換えれば、企業は利益という目標だけでなく、社会全体の課題に踏み込んでいくという目標に対しても働きかけます。通常は(徹底的にというわけではありませんが)、これは企業が環境に対して倫理的責任を負うことを意味します。これには、化粧品を動物でテストしないことや、会社が使用しているリサイクル不可能なビニール袋の量を削減することなどが含まれます。

しかし、なぜ企業が環境に対する義務を持つべきなのでしょうか?もしある企業が法律の範囲内で操業しているものの、環境にやさしくないセメントを工場建設に使用している場合、どうしてこれが問題になるのでしょう?なぜ企業は、より環境にやさしいという理由だけで潜在的により高価な製品を使用して、利益を減らすのでしょうか?

環境は企業にとって最大の懸念事項の1つであり、しばしば彼らが強く批判されている分野であることは間違いありません。これは、他の倫理的問題の多くと同様に、比較的新しい現象です。過去には、利益の名において、企業は環境に関して彼らが望むことを行うことができました。そこには、世界があまりにも広大な場所であるので、一企業が池を汚染したり、緑地を採掘したりといったことは、物事の壮大な仕組みの中では実際には問題にならないという見解がありました。しかし、グローバル化の進展、科学の進歩、そして私たちがつながりあった共同体に住んでいるという事実によって、人々は、企業が環境に影響を及ぼすことができ、実際に環境に影響を及ぼしていることを認識するようになりました。気候変動とオゾン層の穴がこのゆっくりとした認識の主要な例です。

私たちは1つの例を通していくつかの問題に焦点を当てることができます:

> 2000年、ルーマニアに大雪が発生し、ダム崩壊が起こりました。このダムは、10万立方メートルのシアン化物で汚染された水を貯めていました。この水はいくつかの農地に流出したのち、ソメシュ川へと流れ込みました。この流出で死んだ人はいませんでしたが、水生生物の大量死を招き、その事故はチェルノブイリ以降でヨーロッパ最大の環境災害と呼ばれています。シアン化物の汚染水は、オールル鉱山会社による金採掘の副産物でした。

この会社は何か道徳的に間違ったことをしましたか?それは何らかの違法行為をしたかもしれません。おそらく、適切な負荷テストを実行することを省略したか、あるいはおそらく、安全性に関する文書を偽造していました。しかし、たとえその会社が違法なことを何もしていなかったとして、それは何か道徳的に間違ったことをしましたか?

21世紀においては、私たちの答えは「明らかにイエスだ!」となると、私は思っています。しかし、私たちはこの考えに何か実質を与えることができますか?何が本当に間違っているのでしょうか?結局のところ、私たちは毎年、食糧のために数十億の魚や水生生物を意図的に殺しています。

もし私たちが功利主義者であれば、私たちは何を言うでしょうか?私たちは環境権について話すことはできません。なぜなら、そこには権利がなく、もし私たちが功利主義者であれば、やはりなぜこれが道徳的に間違っていたのかを示すことが難しいと気づくでしょう。とりわけ、宝石、コンピュータ、エレクトロニクス、歯科、医学などで使用されているために、製造された金は多くの幸福をもたらすかもしれない、と私たちは考えるかもしれません。魚、植物、およびその他の水生生物は、人間と比較して高いレベルの喜びや幸福を有しておらず、すべての条件が同じだとすると、それは倫理的に間違ったことではありません。もちろん、他のケースと同様に、これはケースの詳細をどのように記述するかに依存しますが、功利主義は私たちが期待していたほど明確ではないようです。

カント主義者にとって、私たちは合理的な行為主体に対する道徳的義務を持っているだけなので、環境は合理的な行為主体ではないため、環境に対する企業の道徳的義務などというものはありません。これは、ビジネスが環境に向かって望むことを何でもすることができるとカントが信じていることを意味するものではありません。

もしある企業が環境を目的(利益)のための手段として扱う場合、彼らは特定の種類のふるまいを形作っており、このふるまいは企業が人間を目的のための手段として扱うことにつながる可能性があります。そして、それは間違っています。そのため、環境を搾取することはカント主義者にとっては道徳的に間違っているわけではありませんが、それは、人々を搾取することの可能性を正当化し、したがって高めます。これは道徳的に間違っています。

## ビジネスとグローバル化

世界は小さくなりつつあり、世界中の人々とふれあい、働くことがますます容易になっています。過去には英国の企業は英国の中のいくつかの都市を見渡していればよかったでしょうが、今や企業には国際的な機会が増えています。これは、非常に多くの新しい倫理的な問題をもたらしますが、ここではそれらの問題に私たちの道徳理論を適用することはせずに、私たちはそれを読者に任せておきます。この節の目的は、いくつかの問題についてあなたが考え始めるようにすることです。

ナイキ、Gap、M&S、H&M、ウォルマート、ネスレ、そしてさらに多くの企業が児童労働を利用していると暴露されています。これは、児童が使用された国では違法ではないかもしれませんが、人々はそれが非常に間違っていると考えます。しかし、そうなのでしょうか?農民であるカメルーン人の父親からのこの引用を考えてみましょう:「[児童労働]は、子供が両親を助けるために行う家庭の仕事の一部とみなされている。私は、これを児童虐待だとは思っていない。なぜなら、私たちは彼らの学費を払うためのお金を稼いでいるからだ。」^[F. Wijen, ‘Banning Child Labour Imposes Naive Western Ideals on Complex Problems’, https://www.theguardian.com/sustainable-business/2015/aug/26/ban-child-labour-developing-countries-imposes-naive-western-ideals-complex-problems]

私たちは、地方の農村部の経済が児童労働の利用に完全に依存しており、そのため、児童労働の画一的な禁止は多数の人々の生計に直接的な悪影響をもたらすであろうことを理解することができます。しかし、「西洋の理想」はどの程度、単純に独特であるのでしょうか?完全な禁止があるべきなのでしょうか、それとも次のようなことなのでしょうか:

> グローバルな禁止[…]は、子供たちの経済的役割について西洋の考え方を課すことによって、他の文化に対する軽蔑を示している。より賢明な方針は、実践される措置の実際の結果を正当に考慮する目標を絞った発展的アプローチと組み合わせて、人道的な労働条件の基本ルールを適用することだろう。^Ibid.ここ以後、特に断りのない限り、強調は私たちによるものです。]

また、別の問題を検討してみましょう。私たちが言ったように、企業をより環境にやさしくする動きが起きたのはごく最近のことでした。英国の産業革命の間、そのような要件はありませんでした。ここで、「発展途上」国の企業を考えてみましょう。彼らはしばしば非常に貧弱なインフラや、彼らの事業の環境に対する影響をよく理解していない状態から始めようとしています。実際には、西洋諸国は企業に環境基準を課すことにより、そのような企業の発展を実効的に阻害し、彼らの破綻につなげている可能性があります。もしケニアの農民が単に農作物を生産するだけでなく、より高価な「環境にやさしい」方法でそうしなければならない場合、その農民はその状況でやっていくのに苦労するでしょう。いかなる権利があって、西洋の企業が他の貧しい国の企業にこれらの環境基準を課すのでしょうか?

グローバル化の増加に伴う倫理的問題の他の多くの例があります。一般に、これらは文化の衝突があるときに発生します。たとえば、いくつかの文化は賄賂を用いることによって機能しています。その文化の中では、企業は何をすべきでしょうか?西洋の企業が女性を二級市民として扱う文化の中に所在地を置いているときはどうでしょうか?この企業はどのようにして女性の従業員を扱い、首尾よく事業を行うべきでしょうか?そして一般的な質問とは、私たちは、非西洋の文脈に対して西洋のビジネス倫理をどの程度まで課すことができるか — そもそもできるのか — ということです。

## まとめ

「ビジネス倫理」というラベルは比較的新しいものです。いまや、顧客は企業がどのように「倫理的」であるかに非常に敏感であり、企業による道徳的な不正行為のいかなる兆候であっても、利益の低下につながります。これは、実際に倫理的になること — 単に倫理的にみせかけるのではなく — にインセンティブがあるかどうかという一般的な疑問につながります。

私たちがまだ取り組んでいない1つの質問は、企業が存在するために必要な環境である資本主義は、それ自体で不道徳なのかどうかということです。マルクスや他の多くの人たちは、私たちがより多くのお金とより多くの物質的な財を追求するように導くシステムが、人間が開花するのを押しつぶし、阻害するだろうと確信しています。

もし私たちの人間としての機能が、健康であるために時間を費やすこと、友人や家族と一緒にいること、趣味や技能を発達させること、自分自身を教育することなどを伴うのであれば、資本主義の「利益のために」という考え方は、私たちがこの役割を果たすことを許していないと見ることができます。

> 資本主義の本質は、自然を商品に変換し、商品を資本に変換することだ。生き生きとした緑の土は死んだような金のレンガに変わり、少数の人のための贅沢品と、多数の人のための有毒な鉱滓のボタ山が残る。輝く大邸宅は、掘っ立て小屋の町のはてしない広がりを見落としており、その中では、絶望して堕落した人間が麻薬、テレビ、武装勢力にによって抑え込まれている。^[M. Parenti, Against Empire.]

おそらくビジネスへの最も倫理的な対応とは、まずは資本主義的なビジネスのゲームを拒否し、「ビジネス」が意味するものと「ビジネス」がどのように行動するべきかを再考することです。

## 学生によくある間違い

* 法律的な問題と道徳的な問題を混同する。
* カントが、私たちは人々を手段として使うことは決してできないと言っている、と考える。
* 均等な機会とはすべての人を同じように扱うことを意味すると思い込む。
* ある文化から来た一部の人が、その文化のすべての人を代表して話すことができると思い込む。

## 検討すべき問題

1. 大学はビジネスだと思いますか?
2. ビジネスと会社の違いは何だと思いますか?
3. 企業の倫理および/または価値観の声明の例をいくつか探してください。彼らは何と言っていますか?あなたはそれらについてどう思いますか?
4. あなたの学校の倫理/価値観の声明を書いてください。
5. 企業が倫理的であることは非合理的であるという主張について、あなたはどう考えますか?
6. 広告のいくつかの例を探してください。それらが顧客に何を伝えているのか、あなた自身の言葉で説明してください。それは意図的な騙しですか?それは嘘をついていますか?
7. あなたは従業員であり、賄賂の申し出を受けたと想像してください。功利主義者は私たちがどのように行動するように指示するでしょうか?カント主義者はどうでしょうか?ビジネスで賄賂を受け取るのは常に間違っていますか?
8. いくつかの職場のルールはあらゆる文化において真実と思われます — たとえば、暴力を使うな、など。他のもの(おそらく服装規定に関するものなど)は、そうではありません。それでは、倫理的なビジネス実践の一部になるべき価値観と、単なる西洋のビジネス実践の特殊な特徴である価値観との間で、私たちはどのようにして判断するのでしょうか?
9. ビジネスは、彼らが将来の世代のために残す世界について気にかけるべきなのでしょうか?結局のところ、未来の世代というものは存在していません。
10. 資本主義はどのくらい不道徳だと思いますか?
11. 資本主義が不道徳であると考えるなら、どのような代替案が存在しますか?なぜ提案された代替案は道徳的に受け入れられるのでしょうか?
12. あなたは、パレンティによる最後の引用についてどう思いますか?功利主義者とカント主義者はこの引用について何と言うと思いますか?

## 重要な用語

財

サービス

ステークホルダー

企業の社会的責任

内部告発

資本主義

## 参照文献

Avis, D., ‘Sports Direct: Former Employees Speak Out’, BBC News (22 July 2016), freely available at http://www.bbc.co.uk/news/uk-36864345

‘FT.com/Lexicon’, Financial Time, freely available at http://lexicon.ft.com/Term?term=corporate-social-responsibility--(CSR)

‘Horsemeat Scandal: Where Did the 29% Horse in your Tesco Burger Come From?’, freely available at https://www.theguardian.com/uk-news/2013/oct/22/horsemeat-scandal-guardian-investigation-public-secrecy

Parenti, Michael, Against Empire (Saint Francisco: City Lights Books, 1995).

Strauss, K., ‘The World’s Most Ethical Companies 2016', Forbes, freely available at http://www.forbes.com/sites/karstenstrauss/2016/03/09/the-worlds-most-ethical-companies-2016

Wearden, G., ‘How the PPI Scandal Unfolded’, the Guardian (5 May 2011), freely available at https://www.theguardian.com/business/2011/may/05/how-ppi-scandal-unfolded

Wijen, F., ‘Banning Child Labour Imposes Naive Western Ideals on Complex Problems’, the Guardian (26 August 2015), freely available at https://www.theguardian.com/sustainable-business/2015/aug/26/ban-child-labour-developing-countries-imposes-naive-western-ideals-complex-problems