# 良心

> 良心の呵責とは、犬が石に噛みつくように、愚かなものである。
>
> ---フリードリヒ・ニーチェ

## はじめに

私たち一人ひとりは、いつだって、私たちの良心について話してきました。私たちは「良心の痛み」を感じたかも知れませんし、あるいは、望んでもいないのに良心が「口出し」してきたかもしれません。私たちは友人に対してかなり楽しみながら嘘をついたり、たまたま支払いをせずに何かを持って店を出てしまったりするかもしれませんが、私たちの良心によって、私たちは友人に打ち明けたり、道で立ち止まり、振り返って店へ戻ったりします。

宗教の信者、政治家、有名人から、普通の人々まで、あらゆる立場の人々が「良心」について話します。私たちは、望まない何かをやらせようとして彼らを悩ませるために自身の良心を非難する人のことを聞いたことがあるかもしれません。人々は、良心が特定の政治的行動（たとえば戦争）に異議を唱えていると感じていることのために、「良心的忌避者」と名づけられることがあります。抗議者は、彼らの「良心の自由」の侵食を嘆くかもしれません。そして、私たちは、歴史を通してそして世界各地から、東洋と西洋の両方の多くの非キリスト教徒の宗教的伝統において「良心」と非常に似た概念を見つけることができます。^[See P. Strohm, Conscience, p. 18, for a good overview of this.]

しかしながら、良心の性質は曖昧であり、したがって、良心に関する哲学的議論は複雑であり、長い歴史を持っています。それは、哲学的心理学、宗教の哲学、認識論、心の哲学、応用倫理学、規範倫理学、およびメタ倫理学の問題を引き出します。

この章では、私たちは2つの良心の理論について概説します。1つはアクィナスの説明を利用するものであり、もう1つはジークムント・フロイト(1856–1939年)のものを利用します。フロイトは典型的には哲学者としては見なされませんが(彼は心理学者です)、彼の説明は、私たちが「良心」と呼ぶこのものについて哲学的に考えることを可能にするいくつかの洞察を私たちに提供してくれます。

## 良心の歴史

21世紀においては、良心は単に宗教的思想であるとは考えられていません。しかしながら、少なくとも「西洋」においては、「良心」の話は、プロテスタントとカトリックの両方の宗派の採用によって普及しました。この節では、私たちは、いくつかの一般的な特徴を引き出すために「良心」がどのように使用されているか、そして使用されてきたかを見ていきます。

「良心」は、プロテスタント宗教改革における最も有名な演説の1つで役割を演じました。チャールズ5世によって異端と非難され、撤回を強要されていたマルティン・ルター(1483–1546年)は、自分の立場を表明し、こう述べました。「私はここに立ち、ここ以外のどこにも私は立つことができない」、そして、「私は何も撤回することができないし、そうすることはない。なぜなら、良心に反することは決して安全でもなければ、有徳でもないからだ。」ルターは、彼の前にいる強力な人々の相当な圧力の下でさえも、神により与えられた彼の良心が、彼が撤回することを許さないと信じていました。あるいは、もっと最近の例を考えてみましょう。

公民権運動の政治的混乱の最中に、脅迫にさらされており、彼の見解を変えさせようとする絶え間ない圧力を受けていたマーティン・ルーサー・キング・ジュニアは、こう述べました:

> しかし、良心は質問を問いかける。それは正しいのか?そして、安全でもなく、賢明でもなく、人気もない立場を取らなければならない時が来る。しかし、それは正しいがために、その立場を取らなければならない。^[M. L. King Jr., ‘A Proper Sense of Priorities’, http://www.aavw.org/special_features/speeches_speech_king04.html]

そして、良心は強力です。それは、人々が生死に関わる危険へと身を置き、「立ち上がり、主張し」、自己利益に反して行動するようにできるようです。

しかし、良心を語るのは聖人や英雄だけでなく、良心は、これまでに生きていた中でも最も忌まわしく道徳的に嫌悪を催させる人、人種差別主義者、殺人犯、暴君、独裁者によっても引用されています。たとえば、ベティナ・スタングネスが「イェルサレム以前のアイヒマン:大量殺人者の未知の人生」^[S. Benhabib, ‘Who’s on Trial, Eichmann or Arendt?’, http://opinionator.blogs.nytimes.com/2014/09/21/whos-on-trial-eichmann-or-anrendt]の中の、ナチスの最も悪名高い役人の内なる人生についての議論で述べたように、「良心とは単にある人が『住んでいる父祖の地の道徳性』に過ぎず、それをアイヒマンは『血の声』とも呼んでいた。」

良心は、男性でもよく、女性でもよく、その両方でもよく、そのどちらでもなくてもよく、それは1つの声でもよく、多数の声でもよく、それは宗教的考え方、人種差別的考え方、高尚な考え方、あるいは人間の腐敗のゴミための中に見つかる考え方を反響することができます。良心はどの任意の年齢でも発達させることができ、どの年齢でも消散することがあります。それは「語らない」こともあれば、「語る」こともあり、選択の言語を持ち合わせていません。これらの観察のすべては、さらに多くの観察と質問を残します。

良心が果たすと私たちが考える(少なくとも)3つの関連する機能があるようです。第1に、良心は、私たちの生活のための指針として私たちが何をすべきかを教えてくれます。第2に、それは道徳的知識の源です。つまり、私たちは「私はペンを盗むことが間違っていると知っている。なぜなら私の良心が私にそう教えたからだ」と言うかもしれません。第3に、それは動機づけとして考えられるかもしれません。つまりそれは、物事が困難であったり、命を脅かすものでさえあるときであっても、私たちが実際に椅子から飛びあがって、特定のやり方で行動するようにさせるものかもしれません。

明確にするために、たとえば「私の良心は、精神的に病気の人を殺して国を助けなければならないと言っている」と述べる暴君を考えることによって、これらの機能の最初の2つの違いを見ることができます。明らかに、これは彼女の良心が彼女にどのように行動すべきかを伝えているケースです。しかし、私たちが精神的に病気の人を殺すことは道徳的に間違っていると考えているために、この場合には、彼女の良心が何が正しく何が間違っているかの知識を彼女に与えているとは言いたくありません。したがって、良心は私たちに指針を与えてくれるが、知識は与えてくれないということが真実かもしれません。

同様に、逆のことも真実と思われます。つまり、私たちは何が正しく何が間違っているかを知っているにもかかわらず、それをするよう導かれない、ということです。この苦境はシェイクスピアが次の有名な引用でとらえたものです:「良心は私たちすべてを臆病者にする」(Hamlet 3.1.78–82)。

別の点を考えてみましょう。良心とは、自分自身に関して、つまりあるものについてどのように「感じる」かに関して、内向きに熟考するものであるという点で主観的です。それは、世界にある一連の規則や法律を眺めることではありません。私たちは、もし友人や、司祭や、政治家や、イマームが何をすべきかを伝えたならば私たちが感じるであろうものとは異なるようなかたちで良心を経験します。もちろん、良心は「内向き」ですが、それは良心が私たちに語るとされていることを私たちが単に作り上げている、ということと同じではありません。たとえば、私たちは何が正しく何が間違っているかは神に依拠していると考えるかもしれませんが、私たちは良心を通して何が正しく何が間違っているかを知るようになるとも考えています。

最後に、「良心」という言葉は、18世紀半ばにおいてようやく現代の道徳的意味に公式化された(たとえば、プラトンやアリストテレスは良心の話をしていません)ということは注目に値します。しかしながら、ある用語が現代的であるからといって、あるいは用語がどのように使用されているかについて意見の相違があるからといって、それは考え方そのものが新しいことを意味するものではないことに注意してください。

「分子」と「原子」という言葉は最近の発明であり、それらが発展する中では異なるものについて話すのに使われたかもしれず、科学界の内部で意見の不一致を生じさせたという点を考慮してみてください。これはそれだけでは分子や原子などというものがないという結論を導くわけではありません。したがって、「良心」という用語の欠如、そして「良心」が何を意味するかについての意見の相違は、良心が単なる「発明」に過ぎないことを意味するものではありません。これらの点をすべて念頭に置いて、良心に関する重要な思想家の一人であるアクィナスを考えてみましょう。

## 良心に関するアクィナス

第4章を思い出してもらうと、アクィナスは自然法理論を発展させました。基本的な考え方は、私たちは理性(彼がラティオ(ratio)と呼ぶもの)を通して、私たちが生きるべき所定の教訓を認識することができるということです。アクィナスは、思考と内省への信頼は聖書に明らかにされていると考えています:

> それらは、法の求めることがその中心に書かれていること、それらの良心が証言をしていること、そしてそれらの思考が時にはそれらを非難し、また別の時には擁護していることを示している。^[T. Aquinas, Romans, 2:15.]

パウロ — そしてアクィナス — にとって、「良心」は時には人を非難し、時には人を擁護する証言をすることに注目してください。アクィナスにとって、良心とは、道徳的に中立であり、それは単純に「証言」し、それは「道しるべ」であり、そして結局のところ道しるべは物事に関する意見を述べません(アクィナス「神学大全」、第1部、質問79、13項参照)。

明確にしておくと、アクィナスは良心のことを道徳的知識の源ではなく、指針として受け取りました。これは、アクィナスが、ルターや宗教改革後の思想家とは違って、良心が誤りを犯しがちなものとしてとらえていたことを意味します。アクィナスにとっては、良心は私たちを間違った方向へ動かす/道を誤らせる可能性があるため、私たちが良心に従うのは間違っているかもしれません。アクィナスにとって良心とは、普遍的な原則(永久法/神定法)を実際の実生活の状況に適用する行為です。

アクィナスは、「良心」のことを「知識の活動への適用」と明示的に定義しています(神学大全、I-II、I)。ですから、もしアクィナスにとっての良心が知識の活動への適用についてのものであれば、これは私たちがどのようにしてこの知識を得るのかという問題を提起します。これはもう1つの重要な専門用語が導入されるところです。それはシンデレシス(synderesis)です。シンデレシスは良心と同じものではなく、永久法/神定法を理解するための心の生得的な能力 — 彼が心の習慣と呼んでいるもの — のことです。良心の役割は、シンデレシスの内容として発見された主たる教訓を適用することです。

シンデレシスのより良い理解を得るには、2つの場所を結ぶ最も早い道を見つけようとしている人のことを考えてみてください。合理的な熟考を通して、彼らはそれが直線の道であることを発見するでしょう。この「熟考を通して認識すること」は、アクィナスがシンデレシスについて語るときに彼が念頭に置いているものです。アクィナスにとって、シンデレシスは(良心とは異なり)誤解されることがありません。人間は、良心(シンデレシスではなく)が誤りを犯すときに間違ったことをする、アクィナスは考えています。これは、アクィナスの説明においては、良心の失敗というものが明確に考えられる必要があることを意味します。

アクィナスにとって、良心は、永久法/神定法を適用する方法についての無知のために誤りを犯します。永久法/神定法を適用する方法には2つのタイプがあります。理性を用いることにより克服することができる無知(克服できる無知)と、理性を用いることによっても克服することができない無知(克服できない無知)です。克服できない無知では、人が今以上によりよく知ることができないときに、何らかの間違ったことをします。克服できる無知では、人が今以上によりよく知るべきであるときに、間違ったことをします。しかし、これがどのようにして良心に関係するのでしょうか?

2人の人が銃砲店に入るところを想像してください。最初の人は犯罪記録を持たず、警察や学校でトラブルになったこともなく、精神疾患の記録もありません。彼は、どこからどう見ても、模範的な市民です。この人は銃を買って殺傷事件を起こしに行きます。この店のオーナーは、彼女の良心に従うことにより、道徳的に何ら間違ったことをしていません。なぜなら、彼女の無知は克服できないからです。この殺傷事件がありえそうな結果であったという示唆は何もありませんでした。

これは、基本的な経歴調査で見つかるであろう暴力的な犯罪記録を持っているにもかかわらず、銃を購入することができた人とは対照的です。この場合、彼女自身の良心に従う銃砲店のオーナーは、何か道徳的に間違ったことをしています。なぜなら、この事例では、彼女の無知は克服できるものだからです。

結論として、アクィナスは、すべての人がシンデレシスを通して正しいことと間違ったことを確実に知ることができると考えています。しかしながら、私たちがこれについて絶対確実であったとしても、私たちはこの知識を適用する際に誤りを犯す可能性があり、実際に犯します。この知識をどのように適用するかを私たちに伝え、私たちを行動させるのは、私たちの良心(コンシェンティア:conscientia)です。それは無知によって間違う可能性があります。避けることのできた(克服できる)無知は、私たちの行動が道徳的に間違っていることを意味します。私たちが避けることのできなかった(克服できない)無知から派生した誤りは、私たちの行動が道徳的に間違っていないことを意味します。

次の節では、私たちは、フロイトが良心について何を言っているのかを考察し、彼がそれをどのようにして神学的ではなく心理学的な概念として再概念化し、そうすることで、私たちはそれを本質的に良い概念として受け入れるべきではないと主張したことについて説明します。

## フロイトと良心

フロイトは、心理学者として、また精神分析の立役者として最もよく知られています。彼は議論の余地があり、ほとんどの哲学者と心理学者は、彼が提示した考え方を拒絶します。しかしながら、彼の考え方は信じられないほど影響力があり、実際に彼の名前は「フロイト的言い間違い:Freudian slip(うっかりした失言の意味)」という形で私たちの日常会話に入り込んでいます。フロイトの多くの考え方の中で、彼の心の構造の概念化は、良心に関する彼の見解にとって鍵となります。彼は、心は3つの部分、すなわちイド、自我、超自我を含むものとして考えることができると思っています。フロイトによる良心についての説明は、これらの間の関係として理解されます。

フロイトにとって、イドとは私たちの原始的な衝動、つまり食べ物、セックス、飲み物への基本的な欲求のコレクションであり、心の最も古い部分です。イドは適切に公式化されたり理解されたりすることはできず、フロイトはそれをカオスに似せています。それは、本能的、感情的、非論理的なものです。私たちはイドを構成するすべての衝動をリストアップすることはできません。なぜなら、私たちはそれらにアクセスできないからです。フロイトはイドを記述するうまい方法を持っています。彼はそれを「…煮えたぎる興奮でいっぱいになった大釜」と呼びます(SE, XXII.73)。私たちはイドの内容についてはほとんど何も言うことができませんが、フロイトはイドの衝動を理解するのに役立つ一般的な原則があると考えていました。それは、彼が「快楽原則」と呼ぶものです。これは、イドの衝動を特定し統一するものとは、苦痛を避け、快楽を追求することである、という主張です。

ここで、非常に幼い子供であれば、快楽原則によって駆り立てられることはOKかもしれません。彼らはチョコレート菓子を口に入れるために一心に這い回り、他の何物にも関係なく母乳を渇望します。しかしながら、私たちが成長するにつれて、私たちはすぐに私たちのイドの原始的な本能にしたがって行動することができないことを認識します。なぜなら、私たちは、私たちが生きる社会空間の中で自分自身を舵取りしなければならないからです!境界線、制裁、結果を理解しなければなりません。世界の中で正常に活動するためには、私たちは、意識的に熟考し、推論する必要があり、最終的には本能的な行動を遅らせ、状況を「天秤で量る」ことをしなければなりません。率直に言ってしまえば、イドの歯止めがきかない人は、社会で受け入れられなくなり、身体的、社会的、情緒的に孤立することになるでしょう。この取り締まる役割を果たすものが、フロイトが「自我」と呼ぶものです。

しかし、もし私たちがイドと自我だけを持っているならば、なぜ私たちが単に快楽原則に従わないのかは不明です。つまり、自我は合理的に熟考するかもしれませんが、それはイドに対して天秤を釣り合わせるような何かを必要とします。私たちは自我が何をしているのかを監視する権威が必要です。この権威は、フロイトが超自我と呼ぶものです。

私たちの人生の最初のころには、私たちの両親は、(社会、宗教指導者などとともに)、私たちがしてよいこととしてはいけないことを教え、規則を破ったことについて私たちを叱ります。私たちは年を取るにつれてこれらのことを内面化し、権威の声として「それらを聞きます」。あなたの母親がいつも、テーブルの上にあなたの肘を乗せないようにと言っており、あなたがこのルールを内面化したと想像してみてください。そうすると、あなたがもっと年をとって、もはやあなたの母親と一緒に住んでいないときでも、あなたの「超自我」の声が権威をもって語ります — 「肘をテーブルからおろしなさい!」これらはフロイトによる心の構造の非常に基本的なものです。私たちの自我は、イドの原始的な衝動と超自我からの権威の声とのバランスをとります。

どこに良心が入ってくるのでしょうか?フロイトにとって、良心とは、自我に対処するために超自我がとる形式です。親(社会/宗教)のルールと規制からもたらされた内面化された権威が自我を制御するとき、それは「良心」として理解されます。私たちの最後の例では、テーブルから肘をおろすように私たちに伝えるのは、私たちの「良心」です。

ここで、私たちの良心は、私たちが達成できないものをしばしば求め、これが罪悪感を引き起こす、ということに気づいてください。フロイトにとって、良心は「良心の呵責」と同義語として考えることができます。私たちの自我は、罪悪感を通じて、私たちが良心と呼ぶ超自我の形によって処罰されます。さらに、フロイトは、超自我がイドに適切に対処できないとき — 快楽原則が抑圧されているとき — 、それは彼が神経症と呼ぶものを形成すると言います。

あなたはまた、アクィナスとフロイトとの間の違いを見ることができるようになっているでしょう。第1に、明白な点は、フロイトにとって良心は神の声ではないということです。第2に、アクィナスとは異なり、フロイトは良心が、悪く、破壊的で、役に立たないこともあり得ると考えています。良心とは、自我が超自我の権威を経験する方法です。しかし、超自我は私たちの経験を通じて到達されます。そして、当然のことながら、私たちは、親が窒息させるような、過度に権威主義的で、よそよそしく、冷ややかで、つらく当たり、暴力的で、虐待的であるような、本当にひどい経験をしているかもしれません。このような場合、良心もまた、窒息させるような、過度に権威主義的で、よそよそしく、等々となるでしょう。フロイトは、私たちが良心を取り除くことができる、あるいはそうすべきであるとは考えていませんが、彼は、私たちが健全な懐疑的な態度でそれを扱うべきだと考えており、それは、超自我の期待に達しなかったことによる自我の罰である「呵責」によって卑屈に追従させられるべきではないと彼が考えていたことを意味します。良心は、神によって霊感を与えられた良さのための力ではなく、しばしば私たちの非理想的なしつけの産物です。

## フロイトの心理性的発達理論

心理性的発達理論は、生まれてから死ぬまでの性的な発達についての理論です。フロイトは、発達の面で一生涯の全体を見た最初の思想家でした。フロイトは、私たちが発達するにつれて、さまざまな段階を経ると考えました。それぞれの段階で私たちのリビドー(性的な衝動)は異なるものに焦点を当てています。もし私たちがある段階を完全に通過するのに失敗したり、ある段階へ戻ったりしたならば、問題が発生し、私たちはその段階に関連付けられた領域に固執するようになる可能性があります。これは私たちの関係にとって深刻な問題となり、精神疾患の根底にある原因となる可能性があります。

第1段階は、出生から約1歳半までの口唇期です。この段階は、赤ちゃんがものを口に入れることや、噛んだり、吸ったり、しゃぶったりすることから快楽を得るところです。たとえば、生まれたばかりの赤ちゃんは母乳により育てられます。そして、赤ちゃんが成長するにつれて、彼らは口にものを入れることを通じて世界へ進み、探索します。この段階では、赤ちゃんは他人に非常に依存していることに注意してください。フロイトによれば、この段階で私たちは世界についての情報を得るだけでなく、私たちはイドも満たします。好きなだけ多く噛んだり、しゃぶったりできる赤ちゃんは、イドによって導かれています。フロイトは、喫煙、ガムを噛むこと、過食症などの行動を、この段階を適切に通過せずにイドの良好な発達を妨げたことによって起こると説明しました。

約1歳半から3歳までの次の段階は、肛門期です。ここでは、トイレに行くことを制御することによって快楽が得られます。この段階は、自分の体の制御を得ることについてのものであり、それは膀胱や腸を制御すること(トイレ訓練を受けること)から始まります。自我が発達するのはこの時期です。彼らの身体のこのような制御は、子どもたちにとって誇りと快楽の源です。この段階を適切に通過しない行為主体は、時に「肛門性格」と呼ばれることもあります。なぜなら、フロイトによれば、彼ら — 過度に制御しすぎているか、あるいは制御することのできない乱雑な人 — は、自分の排泄物を放出したくないか、またはどこで、いつ排泄物を放出するかを気にしないためです。

約3歳から6歳までの発達の次の段階は、男根期であり、そこでは子どもが自分の生殖器を発見し、また重要なこととして、それは男性と女性で異なるものです。フロイトが考えるには、この段階は私たちがエディプスコンプレックスとエレクトラコンプレックスを発展させるところです。問題のある男根期は、後の人生での親密さの問題を引き起こすでしょう。

次の段階である潜在期は、6歳から思春期の初めまでです。この段階は、リビドーが「潜伏する」または隠れるため、身体の快楽についての段階ではありません。これは、性的欲求が抑圧され、新しい性的欲求が現れない段階です。この段階では、女の子たちは女の子の役割を学ぶために女の子と遊び、男の子は男の子の役割を学ぶために男の子と遊びます。子供は社会的な世界をどのように進むかを学びます。困難な潜在期は、関係性の問題や人のジェンダーへの理解につながります。

リビドーはその後、最後の段階で再び現れます。この段階は私たちの死まで続き、フロイトは成熟した性器期と呼んでいます。これは、個人が男性と女性の違いを認識するだけでなく、性的関係、より一般的には喜びと幸福の追求に従事する欲求を示している場所です。人々は性的に活発になり、恋に落ち、結婚します。これは、私たちが完全に発達した良心を獲得する段階です。

## まとめ

「良心」という概念は、常に「良心」という用語で呼ばれてきたわけではありませんが、何千年もの間、さまざまな文化に出現してきました。現代のキリスト教の正統な教義は、それを普及させ、神の声や指導に関連してそれを特徴づけました。アクィナスは、良心とは私たちが知っていることをどのように適用するかを理解するための方法だと考えました。アクィナスの見解では、私たちの良心は間違うことがあり、私たちを間違って導くかもしれません。私たちの良心が「間違っている」とき、私たちは — 克服できる無知を通じて — 非難に値するかもしれませんし、または — 克服できない無知を通して — 非難に値しないかもしれません。

フロイトは、良心が良いことのための力であるとはあまり納得しておらず、良心は神とは何の関係もないと確信しています。フロイトにとって、良心は良いか悪いかのどちらかです。私たちは、私たちの心が3つの部分、すなわち、イド、自我、超自我を持っていると考えることができます。フロイトにとっての良心は、自我を抑えようとしているときに超自我がとる形です。それは権威の声として内面化されています。超自我は、ルールに従うことについてのものですが、それらのルールは「高み」から来るものではなく、私たちが経験してきたしつけに由来しています。ですから、もし私たちが抑圧的なしつけをされていれば、超自我 — 良心の声 — は抑圧的なものになります。フロイトが心理性的発達と呼ぶものを通して、私たちは心の3つの特徴を発達させます。もし私たちが正しく発達しなければ、私たちは固執したり抑圧的になったりし、神経症を形成し、最終的には精神疾患になります。フロイトは、これが正常の方法で心理性的な段階を通して対処することによって回避できるものであり、そして心理性的なカウンセリングを通して治療できると考えました。

## 学生によくある間違い

* 良心(conscience)を意味するときに意識(conscious)と書いてしまう。
* シンデレシスと良心を混同する。
* 知識の源としての良心と、指針としての良心とを混同する。
* フロイトが、良心が常に悪いと考えていると思う。
* アクィナスにとって良心とは何が正しく何が間違っているかを知る方法であると考える。
* 良心という言葉が新しいものであるために、良心それ自体が現代の発明であると考える。

## 検討すべき問題

1. あなたは自分が良心を持っていると思いますか?それはあなたに何を伝えますか?
2. シンデレシスと良心の違いは何ですか?
3. 究極的にはすべての人が — もし彼らが正しく推論すれば — 正しいことと間違っていることを知っていると思いますか?
4. 克服できると克服できないとの違いは何ですか?克服できない知識と思われるものの大部分は、実際には克服できるものではないですか?私たちはもっと頑張る必要があるのではないですか?
5. 良心にとってのありえそうなさまざまな役割とは何ですか?
6. 良心は道徳的に悪いことになり得ますか?
7. なぜフロイトは、私たちが良心を聞くことについて慎重を期す必要があると考えるのですか?
8. フロイトの良心の説明は、彼の心理性的発達理論にどのように関連していますか?
9. フロイトの心理性的発達理論についてあなたはどう思いますか?
10. フロイトの心理性的発達理論について、重要な段階とそれに付随する特性の表を作成してください。
11. 良心を持つ動物やロボットについて話すのは理にかなっていますか?もしそうでない場合は、なぜですか?
12. 良心はこの先1000年の間も私たちの人生を形作ると思いますか?

## 重要な用語

快楽原則

イド

自我

超自我

シンデレシス

克服できる無知

克服できない無知

心理性的発達理論(口唇期、肛門期、男根期、潜在期、成熟した性器期)

## 参照文献

Aquinas, Thomas, Summa Theologica, freely available at http://www.newadvent.org/summa/
<br>[「神学大全」高田三郎・山田晶・稲垣良典ほか訳、創文社、1960年～2012年]

―, Romans (Commentary on the Letter of Saint Paul to the Romans).

Benhabib, Seyla, ‘Who’s on Trial, Eichmann or Arendt?’, The New York Times (21 September 2014), freely available at http://opinionator.blogs.nytimes.com/2014/09/21/whos-on-trial-eichmann-or-anrendt

Freud S. and Freud A., Complete Psychological Works of Sigmund Freud (New York: Random House, 2001).

Giubilini, Alberto, ‘Conscience’, The Stanford Encyclopedia of Philosophy, Winter 2016 ed., edited by Edward N. Zalta, freely available at https://plato.stanford.edu/archives/win2016/entries/conscience/

King, Martin Luther, ‘A Proper Sense of Priorities’, 6 February 1968, Washington, D.C., freely available at http://www.aavw.org/special_features/speeches_speech_king04.html

Strohm, Paul, Conscience: A Very Short Introduction (Oxford: Oxford University Press, 2011), vol. 273, https://doi.org/10.1093/actrade/9780199569694.001.0001