# 嘘をつくこと

> 私は、あなたが私に嘘をついたことに怒っているわけではない。私は、今からあなたを信じることができないことに怒っている。
> 
> ---フリードリヒ・ニーチェ

## はじめに

嘘をつくこととは何ですか?嘘をつくのは常に間違っていますか?時には嘘をつくことは容認されますか?もしそうなら、嘘をつくことをOKにする条件は何ですか?人間はお互いにやりとりをするようになって以来、嘘や真実に関するこの種の質問に取り組んできました。真実と信頼は私たちの社会の働きの鍵です。事実、嘘をついた人々は、制裁を受け、非難され、処罰されます。私たちは、嘘によって引きずり降ろされた政治家の例をたくさん知っています。ニクソンとその後のウォーターゲート事件はよい例です(また、政治家に関する最後の節も参照してください)。子どもたちは「嘘をついてはいけない」と教えられており、宗教指導者や宗教の文書は嘘をつくことを非難し、関係性についてのガイド本はあなたのパートナーに嘘をつかないことの重要性を語っており、等々。私たちは、これらの質問のいくつかを検討することから始めて、この本でこれまで議論してきた考え方のいくつかを、嘘をつくことにあてはめます。

## 嘘をつくこととは何ですか?

いくつかの例を考えてみましょう。あなたがそれらを読むときには、嘘が関わっているかどうかをあなた自身に尋ねてみるべきです。

1. ある友人が、あなたが昨年の休暇の際に行った場所を聞いてきます。あなたは「ケンブリッジ」と言い、彼らはそれを英国のケンブリッジであると理解しましたが、あなたは実際にはマサチューセッツ州ケンブリッジのことを指しています。
2. あなたは小学校の子供たちに化学を教えています。あなたはサッカーボールを持って、「原子とはまさにこれのようなものです…」と言います。
3. あなたは本当にひどい1日を過ごしています。あなたはパートナーと別れ、家の鍵を紛失し、友人に怒鳴りつけられたところです。あなたは廊下で知り合いに会いました。彼らは「調子はどうだい?」と言い、あなたは「おかげさまで良いですよ、あなたは?」と言います。
4. あなたのおばあちゃんは年金を貯めて、ウールを買って、あなたに上着を編んでくれました。あなたはそれが嫌いです。彼女があなたのところを訪れるので、あなたはそれを出しておきます。彼女は微笑んで、「それで、あなたは気に入ってくれたかしら?」と尋ねます。あなたは「もちろん、おばあちゃん、私のことを考えてくれてありがとう」と返事をします。
5. あなたは数学のテストを受けています。ある質問はsin²x + cos²xの答えを聞いています。あなたは「10」と答えます[答えは「1」です]。
6. 最近離婚した人が結婚指輪をつけ続けています。
7. あなたは聖書を中国に密輸しています。国境で、警備兵がトラックに何を積んでいるかをあなたに尋ねてきました。あなたは実際に何百冊もの聖書を持っているので、「ああ、何百冊もの聖書だよ」と言います。警備兵はこれが冗談だと​​思って、通ってもよいと手を振ります。

では、あなたはどう思いますか?これらのケースは嘘をついていますか、いませんか?順番に取り上げてみましょう。

(1)あなたにとって友人を誤解させる意図がないので、これは嘘の範疇には入りません。

(2)は、もう少し難しいものです。厳密に言えば、原子はサッカーボールのようなものではありません。たとえば、それらは、大部分は空間です。そして、カーステン・ウォルシュとエイドリアン・カリー^[K. Walsh and A. Currie, ‘Caricatures, Myths, and White Lies’, p. 424.]が述べているように、「真実、つまりすべてを含み、真実以外の何物もないもの、は決して教師の根本原理ではない。」これは、科学や歴史、化学などのすべての詳細に入り込むことは単純に不可能だからです。しかし、これはあなたがクラスに嘘をついているということを意味しますか?私たちはその答えが「はい」だと思っています。実際、教えることにはすべて嘘をつくことが含まれます。もちろん、これが正しいか間違っているかについては、私たちは後で立ち戻ります。

(3)与えられた返答が標準的な質問に対する標準的な答えと一般的に考えられるために、おそらくこれは嘘をつくことに分類されないでしょう。質問した人はほとんどの状況でこの返答を期待しています。

(4)これは、嘘をついていることが明らかなケースのようです。あなたのおばあちゃんによって直接質問されたので、あなたは彼女をまっすぐ見て、そして嘘をつきます。それで、これが間違っているかどうかは、私たちが以下で検討することです。私たちは、「小さな白い嘘」(たわいない、罪のない嘘の意味)という、このような場合にぴったり当てはまるフレーズを持っているように見えます。

(5)これは、嘘をつくというケースではなく、むしろ単に数学が苦手であるように見えます。それは確かに誤っていますが、嘘は関わっていません。

(6)これは嘘をつくケースになる場合があります。結婚指輪をつけていることは誰かが結婚していることを示すものだと私たちが理解しているような社会的文脈の中では、あなたが結婚していないときに結婚指輪をつけるのは、嘘をついているケースのように見えます。

(7)警備兵への返答ではあなたは完全に正直だったため、これは嘘をつくケースのようには見えません。しかしながら、もし欺く意図があった場合には、これは当てはまらないでしょう。しかし、現状では(7)は嘘をつくケースではありません。

それでは、私たちはこれらの簡単な例から何が得られますか?

嘘をつくこととは、単に何か虚偽のことを言うだけではありません。それは、数学についての(5)のケースが私たちに示すものです。

嘘は話すこと以外のことを伴うことがあります。それは文章、象徴および記号を含むことがあります。それが(6) — 結婚指輪 — が私たちに示すものです。

(3)のようなケースでは、たとえ私たちが虚偽であると知っていることを言ったとしても、騙す意図がないため、必ずしも嘘とはみなされません。

それこそが、(4)の「うん、あの上着が好きだよ、おばあちゃん」が嘘となる理由です。あなたは、あなたが上着を好きだという誤った信念をおばあちゃんが受け取ることを意図しています。

最後に、聖書の密輸のケースでは、この人が真実を伝えること — 「はい、トラックには聖書があります」 — によって、警備兵がトラックには聖書がないという誤った信念を形成するであろうということを知っている場合には、それは嘘をついたとみなされるでしょう。だから、何かが嘘になるためには、欺くための意思が重要になりますが、言われたことが虚偽である必要はありません。

もちろん、これらの主張はすべて議論の余地がありますが、少なくとも道徳的な問題について考えるための出発点を与えてくれます。

最後に、余談として、私たちが自分自身に嘘をつくことができるかどうかは、議論の余地があり、哲学的に興味深い質問です。私たちはここではこれについて議論しませんが、「自分自身に嘘をつかない」という言葉は、心理学者、自己啓発の本、カウンセラーなどが使用する一般的なフレーズです。それは、ある時点で考慮するに値する真に興味深い質問ですが、ここではありません。

私たちはいまや、このような道徳的な疑問を枠組みづけることができます。あなたが虚偽であることを知っているような信念を誰かが受け取るように意図するのが道徳的に容認できるのであれば、それはいつですか?

この本ですでに議論されているいくつかの理論のレンズを通して、この質問を考えてみましょう。

## 功利主義

(第1章を)思い出してもらうと、帰結主義には2つの特徴があります。第1に、「良さ」(幸福、喜び、福利、選好など)の定義と、良さに関連する正しい行動と間違った行動についての考察です。特に、もしある行動が最大の幸福、喜び、福利、選好の満足などをもたらす場合、そしてその場合のみに、その行動は正しいものです。

第2の特徴は、計算の中では誰もが等しいとみなされることです。つまり、あなたの良さは私の良さと同じくらい重要であり、それは他のどの人の良さとも同じだけ重要です。

この2つの主張から、文脈にかかわらず道徳的に正しかったり間違ったりするような行為というものはないということになります。だから、私たちは嘘をつくことは間違っているとは言えません。なぜなら、嘘をつくという行為は、それを行わない場合よりもより少ない良さをもたらす場合にのみ間違っているからです。もし、私が虚偽であると信じている信念をあなたが採用するように私が意図しているけれども、そうすることによって、そうしなかった場合よりもより大きな良さを生み出すならば、私は正しいことをしています。

功利主義は、いくつかのケースでは直観的に見えます。たとえば、ある兵士が捕らえられて拷問されているものの、彼女は依然として嘘をつき続けていて、同盟国の暗号を破る方法を知らないと言っています。そしてそうすることによって、彼女は数十万人もの命を救うということを想像してみてください。この場合、人々は彼女が嘘をついているのは正しいと信じます。真実を伝えることの恐ろしい結果を考慮すると、彼女は嘘をつくことが道徳的に要求されます。しかしながら、直観はどちらの方向にも働き、時には嘘をつくことを要求されるのが道徳的に直観に反していると考えられるケースがあります。

「マクロスキーの保安官」として知られているH・J・マクロスキーの有名な例を考えてみましょう。^[McCloskey, ‘A Non-Utilitarian Approach to Punishment’.]

> 町で重大な犯罪が起こり、保安官が深刻な暴動を阻止しようとしているシナリオを想像してみてください。彼は、この暴動が破壊、傷害、そしておそらく死をももたらす可能性が高いことを知っています。問題は、彼には手がかりがないことです。彼は誰が犯罪を犯したのかについてほんの少しもわかりません。しかしながら、彼は町に嘘をついて無実の男を犯人に仕立てあげることによって、これらの暴動を防ぐことができます。その男がいなくて不自由する人は誰もおらず、彼は町で嫌われています。もし彼が、この無実の男に罪を着せて刑務所に入れ、犯罪を犯したのはこの男だと町の人々に信じさせたならば、町は鎮まり、人々は暴動を起こさないでしょう。帰結主義者は、この場合、罪のない男が投獄されることを意味するとしても、保安官が嘘をつくことが道徳的に要求されていると判断するでしょう。これは、嘘をつくことが時には道徳的に要求されるということを帰結主義者が述べるという事実が、直観に反する結論につながる可能性がある、ということを示しています。

ありふれたケースを考えてみましょう。もしあなたがおばあちゃんに嘘をつくことで、最高の結果がもたらされる時には(つまり、彼女が幸せで、あなたが幸せで、彼女は自分を幸せにするような編み物を続け、等々)、嘘をつくことは道徳的に容認されます。しかしながら、帰結主義者は私たちが嘘をつくべきであると言うだろう、ということに注意してください。嘘をつくことは、単に容認されるだけでなく、私たちは嘘をつく道義的義務を負っています。

もちろん、功利主義者は新しい問題が発生するのを防ぐために、起こりうる結果や結末についてより深く考えてみるべきです。保安官の例を考えてみましょう。真犯人が罪を告白することによって、最初から真実が語られた場合よりも悪い結果がもたらされるかもしれません。いまや、暴動が起こるだけでなく、法執行機関への信頼もなくなります。だから、実際には、嘘をつくと悪い結果がもたらされるかもしれず、それは嘘をつくのは間違いであることを意味します。

あるいは、おばあちゃんの例を考えてみてください。もしあなたの兄が、あなたが嘘をついたことをおばあちゃんに告げるならば、これは、彼女は再び孫のことを信じることはできなくなり、編み物をあきらめるかもしれず、もともと上着について真実を伝えていた場合よりも彼女を不幸にしてしまうことを意味すると想像することができます。

しかしながら、功利主義においては行動そのものとして正しい行動や誤った行動というものはないため、嘘をつくという行為は間違ったものでも正しいものでもないということが導かれます。ですから、「功利主義者は、嘘は間違っていると考えるか?」との質問には、「それは場合による」という答えになります。

## カント主義者と嘘

対照的に、カント主義者(第2章参照)は、行動はそれそのものとして間違っているか、あるいは正しいかであると主張します。そのため、彼らは、最初に良さを定義し、次に正しい行動と間違った行動を定義するのではなく、まず最初に正しいことと間違ったことを定義します。彼らがどのようにこれをするかは、彼らがどのようなタイプの義務論者であるかに依存するでしょう。カント主義者は、正しさと間違いを理性の上に基礎づけます。特に、私たちは、カントの定言命法の1つのバージョンを導入しました。私たちは、これを使って、カント(そして実際にはすべての義務論者)が、あらゆる場合において嘘をつく行為が間違っていると考えていることを示すことができます。たとえその結果が、10億人の人、自分自身の母親、あるいは子供の孤児院を救うことであったとしてもです。

私たちが紹介した他のカント主義の定式では、嘘が間違ったものとして出てくることもある、というのは言及しておく価値があります。カントは、私たちは常に他人のことを彼ら自体で目的として扱うべきであり、決して目的のための手段としてのみ扱うべきではないと言いました。私たちは、これが嘘をつくことを間違ったものにするということがわかります。なぜなら、もし私たちが誰かに嘘をついているならば、私たちは彼らを彼ら自体で目的として扱っているのではなく、彼らの手から特定の決定を奪い取ることによって彼らができることをコントロールしているからです。それは、私たちが基本的に、私たち自身の目的のために彼らをだますことが許されるべきだと言っているようなものです。私たちは彼らを合理的な行為主体として扱っているわけではなく、カント主義者にとってはこれは常に道徳的に間違っています。

これは直観に反するように見えるかもしれませんし、実際にそうです。しかしながら、もし私たちが嘘をつくことの定義に再び着目すれば、もしかしたらそれほど直観に反するものではないかもしれません。兵士のケースに戻りましょう。彼女は軍事暗号のために拷問されていると想像してください。何十万人もの人々が死ぬという結果を止める1つの方法は、単に何も言わなければいいようです。そして、私たちの定義を考えれば、何も言わないことは嘘をつくことではないでしょう。そのためカント主義者は、彼女が秘密を明らかにしなければならないというもっともらしくない結論を支持しないかもしれません。沈黙を保つことは、嘘をつくことと同じではありません。

さらに、真実を伝えるさまざまな方法があることは覚えておく価値があります!あなたのおばあちゃんに対して「あなたが私の上着を一生懸命作ってくれたことには本当に感謝してるし、私の友達はそれがすばらしい上着だと思うだろうけど、それは実際には私のスタイルではないので、本当にごめんなさい」と言うことは、「いや、それは気に入らない」と言うよりも不快さが少ないように思えます。

ですから、嘘をつくことが実際には何を意味するかをより深く考えることによって、嘘をつくことを検討する際において、カントの理論の不快さをより少なくするような方法が(たぶん)いくつかあります。それでも、私たちが嘘をつくことを道徳的に容認できると思うケースがあることは否定できませんが、カント主義者にとってはそのようなケースはありません。

このことを言うのはカント主義者だけではないことに注意してください。他の義務論的な理論も同様でしょう。たとえば、神の命令理論です。この理論は、神が命令しているか禁止しているかに基づいて、行動が正しいか間違っているかが決まると言っています。もし神が、嘘をつくことは間違っていると言うならば(そして、少なくとも主要な一神教の宗教では、神はそう言っています)、それはそうであり、話はそこで終わります。あるいは、カトリックの神学者アクィナスを検討してみてください。

## 政治的文脈についてのいくつかの最後の考え

私たちがこれを書いている時に、ドナルド・トランプが米国の大統領に選出されました。あなたが彼の政策に同意するかどうかにかかわらず、興味深いことは、大統領選挙キャンペーンが行われた方法です。特に、上述した最初の主張、すなわち公職に就きながら嘘をつくことは何があっても避けなければならないことであるという主張が、深刻な懸念にさらされていることです。しかしながら、トランプは真実に気を留めず、無関心であるように見えます。したがって、一部の人々は、彼が「ポスト真実」の時代の先駆けとなったと示唆しています。^[See http://www.dailywire.com/news/4834/trumps-101-lies-hank-berrien for 101 of his lies.]この時代は、一部には、ソーシャルメディアサイトでの虚偽のニュース記事の伝播のせいで作り上げられたようです。これが非常にいきわたっているため、Facebookや他のソーシャルメディアグループは、人々に対して「フェイクニュース」を警告する方法に取り組んでいます。

したがって、あなたのために残された質問は、政治的な「ポスト真実」の時代において、嘘をつくことについて話すことは意味があるとあなたが思うかどうかです。トランプが「何百万もの人々が違法に投票したために、私は一般有権者の得票数で勝っていた」と言うとき、これは嘘でしょうか?私たちは、「これは真実でしょうか?」ということを言っているわけではありません。なぜなら、これは明らかに虚偽だからです。私たちが言っていることは、「嘘の概念が時間の経過とともに変わったと思いますか?」ということです。嘘の概念に共通観念がなくなるほどに政治的景観が劇的に変わったのでしょうか?関連したこととして、嘘をつくことの道徳的な地位とは何でしょうか?もし政治家や有権者が真実を気にしないのであれば、これは(少なくとも政治的な場面で)嘘をつくことの道徳的な地位に影響を及ぼしますか?私たちはここではこれらの質問に答えるつもりはありませんが、それらは(もし私たちが思い出す必要があるのであれば)嘘をつくことの道徳的な地位が地方、国家、国際レベルで非常に重要であること示しています。

## まとめ

哲学者は、多くの問題で、私たちが重要な用語で何を意味するのかを尋ねることから始めるのが好きです。ひとたび私たちが「嘘をつくこととは何ですか?」という質問をすると、その問題は複雑で不明確であることがすぐに分かります。嘘をつくことは、ただ単に虚偽を言うことを意味するのではなく、むしろ、あなたが実際には虚偽であると考えているときに、他の人に対してあなたが主張していることは真実であると信じさせるようにすることです。

私たちがこれまでこの本で見たさまざまな理論は、「嘘をつくことは間違っていますか?」という問いに対して異なる答えを持っています。功利主義者は「それは場合による」と言います。つまり、嘘をつくことの結果が真実を伝えるよりも良いならば、私たちは嘘をつくことが道徳的に要求されます。義務論者 — たとえばカント主義者や神の命令理論家 — は、嘘をつくことは常に間違っていると考えます。嘘をつくことが道徳的に容認されるであろう状況はまったくありません。

帰結主義者と義務論者の返答はどちらも、直観に反した主張につながるようです。これに対応する1つの可能な方法は、嘘の定義をもう一度見直し、嘘に関する道徳的問題への直観に反する応答が生じるのは、嘘をつくとは何であるかについての誤った理解または不完全な理解のためであると主張することです。

最後に、私たちは、直観を捉えるという要求を単に拒否するかもしれません。私たちは単に、私たちの直観の方がずっとひどいと言うかもしれません!私たちは、政治分野における真実と嘘についてのいくつかの一般的な考え方をまとめることでこの章を終えました。

## 学生によくある間違い

* カントが、私たちは常に真実を伝えるべきだと言っていると考える。実際には、彼は嘘をつくのは間違っていると言っています。
* 功利主義者が、嘘が喜びにつながるならば、嘘をつくことは道徳的に容認できると言っていると考える。
* 意地悪であることと不道徳であることを取り違える。
* 人が嘘をつくには言葉が必要だと考える。

## 検討すべき問題

1. この章の冒頭の(1) — (7)を読んでください。あなたはこれらが嘘をついているケースだと思いますか、そうでないと思いますか?あなたの答えの理由を教えてください。
2. あなたは嘘をつくことが道徳的に容認できるときがあると思いますか?それはいつ?
3. ロボットは嘘をつけるでしょうか?
4. 地元の町の交差点に「誕生日おめでとう、キース。今日で40歳!」という看板があります。それは1年ほどそのままにされていました。これは嘘をついていることになりますか?
5. あなたは「自分自身に嘘をつく」ことについて話すのが理にかなっていると思いますか?もしそうなら、これは私たちの定義をどのように変えるでしょうか?
6. あなたのこれまでの答えを反映させると、あなたは私たちの「嘘をつくこと」の定義に同意しますか?それとも、それは修正が必要だと思いますか?
7. 帰結主義者が、私たちが嘘をつくことが道徳的に要求されると言うであろう例を挙げてください。
8. 嘘をつくことが道徳的に間違っているかどうかという疑問に対する規則功利主義者と行為功利主義者の反応は、どのように異なるでしょうか?
9. 義務論者が、私たちは嘘をつくべきではないと言うであろう例を挙げてください。
10. もしあなたが嘘をつくことに対する義務論的なアプローチか、帰結主義的なアプローチかのいずれかに進まなければならないとしたら、それはどちらでしょうか?
11. 私たちは「ポスト真実」の時代に生きていると思いますか?もしそうならば、それは、私たちが嘘をつくことをどのように考えるかについて、何らかの変化(もしあるとして)をもたらしますか?

## 重要な用語

嘘

マクロスキーの保安官

規則功利主義者

義務

「ポスト真実」

## 参照文献

McCloskey, H. J., ‘A Non-Utilitarian Approach to Punishment’, in Philosophical Perspectives on Punishment, ed. by Gertrude Ezorsky (Albany: State University of New York Press, 1972), 119–34.

Walsh, Kirsten and Adrian Currie, ‘Caricatures, Myths, and White Lies’, Metaphilosophy, 46.3 (2015): 414–35.