# 模擬的な殺害

> あなたは知識を避けることができるか?できない!あなたはテクノロジーを避けることができるか?できない!倫理や、あなたの個人的な信念や、すべてのことにもかかわらず、物事は進展していく。^[J. Delgado, quoted in John Horgan, ‘The Forgotten Era of Brain Chips’.]

> テクノロジー:あまりにきちんと世界を整えるために、私たちがそれを体験する必要のない技巧。^[M. Frisch. Homo Faber: A Report.]

## はじめに

倫理とは、私たちがどのようにしてこの世界で生きていくかや、どのようにしてお互いに交流するかについてのものです。「模擬的な」殺害が、まあ、「模されている」とすれば、私たちはそれが倫理的配慮の範囲外にあると考えるかもしれません。しかしながら、この章ではこの主張に挑戦していきます。あるシナリオが「現実」ではないということを単に認めるということは、それが倫理的なものとして考えられるべきではないということを意味しません。私たちは、この本で見てきたさまざまな倫理学理論が模擬的な殺害について何を言うかを通じて考えていきます。この章では、マイケル・レイスウィング(1971年-)とゲイリー・ヤングの仕事に頼ります。^[M. Lacewing, ‘Simulated Killing’, http://documents.routledge-interactive.s3.amazonaws.com/9781138793934/A22014/ethical_theories/Simulated killing.pdf. See in particular Garry Young’s Ethics in the Virtual World: The Morality and Psychology of Gaming.]

模擬的な殺害は数多くのことを意味することがあり、まず最初はそれが何でないかを言う方が簡単でしょう。明らかに、模擬的な殺害は実際の殺害ではなく、またそれは、殺害の記述や表現でもありません。そのため、J・K・ローリングによるヴォルデモートの死の描写は、模擬的な殺害とはみなされず、カラヴァッジオによる洗礼者聖ヨハネの斬首を描いた絵画もそうはみなされません。しかしながら、殺害を含む映画、たとえばシンドラーのリストの中で演じることや、舞台上でティボルトを殺すロミオを演じること模擬的な殺害とみなされるでしょう。さらに、コンピュータゲームとバーチャルリアリティの出現に伴い、模擬的な殺害に対する興味深く、そしておそらく道徳的に異なる次元が現れています。具体的には、現代のテクノロジーは、私たちすべてがシミュレーションの一部となるのを手伝うことができます。

もちろん、このトピックを取り巻く想定される倫理的な心配への反応の1つは、単純なものかもしれません — 「成長しろ!」世界では多くの恐ろしいこと — 現実のこと — が起こっています。貧困、拷問、巨額の負債。それらは、倫理学者としての私たちが自分たち自身で関心を持つべきものです。対照的に、これらの模擬的なものは単にエンターテイメントです。映画の殺害シーンの後、俳優たちは家に帰るでしょう。ロミオとジュリエットの俳優たちはほこりを払ってお酒を飲みに出かけ、コンピュータのモニター上のピクセルは変更され、電荷によって再形成されます。実際には誰も傷ついていません!

しかしながら、こういったよりそっけない姿勢に対抗するために、いくつかの例を考えてみましょう。それらを読むときに覚えておくべきことは、この「誰が気にするんだよ、それは現実じゃない!」という態度が正しく見えるかどうかです。そして、もしそうでないならば、それはなぜなのでしょうか?

1. 地元の高セキュリティ刑務所には多数の児童殺人犯たちが収容されています。彼らはしばしば暴動を起こし、大規模な破壊や苦しみを引き起こします。しかしながら、刑務所長は、暴動を止めるある方法を提案しています。ほとんど費用はかからずに、それぞれの受刑者には、自分が好むように子供を殺す幻想をバーチャルに体験することを可能にするバーチャルリアリティヘッドセットが与えられます。実験では、この没入型の性質が安全弁のように働き、受刑者たちが静かで有益になり、教育や地域社会のプログラムに参加することを望むようになることが示されています。彼らはヘッドセットを与えられるべきですか?
2. 軍隊では、兵士を訓練するために非常に現実的なコンピュータゲームを使用するのが一般的です。兵士が現在シリアで戦っている一方で、現実的なロシアと米国の兵士、現実的な地図、モスクなどの民間人の場所を備えたシリアの訓練シミュレーターが販売されている、といった状況を想像してみてください。これに何か間違ったところはありますか?
3. ビデオゲームであるコール・オブ・デューティー:モダン・ウォーフェア2の1つのレベルの一環として、あなたはロシアのテロリストに成りすまして、モスクワ空港で民間人に向けた銃の乱射に参加することが期待されています。もしあなたがこのレベルをプレイしているならば、あなたは何か道徳的に間違ったことをやっているのですか?
4. 2015年6月、「ヘイトレッド」と呼ばれるビデオゲームがリリースされました。このゲームの目的はシンプルで、できるだけ多くの一般市民を殺すことです。ゲーマーは、街の中でキャラクターを制御して、銃撃し、火をつけて、車ではね、爆破し、罪のない人をランダムに殺害します。(同様に論争の的になっているのは、スーパーコロンバイン虐殺RPGです!ここではプレイヤーがエリック・ハリスとディラン・クレボルトをプレイし、コロンバイン高校の虐殺を再現します。)そのようなゲームをするのは道徳的に間違っていますか?

興味深いのは、この章を読んでいる皆さんの多くにとって、(1) — (4)の一部またはすべてが不快であると思われるということです。おそらく、道徳的に好ましくないものですらあるでしょう。

この章では、私たちは、異なる道徳的な理論と、それらがどのようにこの直観をとらえるかを見ていくことから始めます。次に、私たちが模擬的な殺害を観察する事例のタイプについて検討します。私たちは、これらの問題に関連する有名な哲学的問題である悲劇のパラドックスを強調することで終わります。

## 功利主義と模擬的な殺害

功利主義にとって、いかなる行為も、行為自体としては、正しいか間違っているということはありません。だから、私たちは、他人を殺すようにプレイすることが間違っているとは言うことができません。私達が焦点を当てなければならないのは、模擬的な殺害の特定の例でどのくらいの幸福が作り出されたかです。

幸福の量に関するこの質問をするにあたっては、私たちは(1) — (4)には何も間違ったことがないと結論づけるかもしれません。結局のところ、受刑者、コール・オブ・デューティーやヘイトレッドのプレイヤーは楽しみを得ているためにそこには多くの幸福があり、誰も傷つくことはないためにそこには不幸がありません。実際に、もし誰かがこれらのゲームをプレイするのを止めると、不幸が増えるかもしれないと想像することができます。おそらく、彼らがビデオゲームをプレイするのを阻止するような人は、周囲の人の生活を悲惨なものにしたり、うつ病に陥らせたりするのかもしれません。実際には、功利主義によれば、コンピュータゲームで殺人者をプレイすることは、ある人々にとっては道徳的にするべきことなのかもしれません。何らかの状況によっては、そのようなゲームをプレイすることは彼らの義務であるかもしれません。

これを述べたうえで、問題が経験的なものであることに気づいてください(すなわち、それはア・プリオリではなくア・ポステリオリに回答される質問です)。もし模擬的な殺人で殺人者をプレイすることがそれをしないよりも多くの不幸につながる場合、殺人者をプレイするのは間違っています。しかし、なぜそのような模擬的な殺人は不幸をもたらすのでしょうか?

もしかしたら、殺人者をプレイすることで、人々は暴力行為にもっと傾くのでしょうか?おそらく、それはプレーヤーがより共感したりや信頼したりすることをできなくさせ、それによってプレーヤーが他の人に害を及ぼす可能性がより高くなることにつながるかもしれません(マコーミックが「リスク増加行為」と呼ぶものです^[M. McCormick, ‘Is it Wrong to Play Violent Video Games?’, p. 279.])。あるいは、もしかしたら、模擬的な殺害をプレイすることによって、プレイヤーは自分自身と他者の両方に害を及ぼすかもしれない方法で暴力行為に対して鈍感になるのでしょうか?

ヤング(Young 2014)は、これらの主張に関連する証拠が混在していることを報告しています。ゲームをする人がおそらく既に暴力の素因を持っているような場合には、殺人者をプレイすることは彼女を暴力と危害へとつなげるでしょう。そのため功利主義者は、この人がそのようなゲームをするのは道徳的に間違っていると言うかもしれません。一方で、プレーヤーが「通常の」気質を有しているような他の場合では、ビデオゲームで殺人者をプレイすることは悪影響を及ぼさない可能性があります。その場合、それは道徳的に間違っているわけではありません。

そのため、功利主義にとって、もしリスク増加行為とゲームで殺人者をプレイすることとの間に明確な関連があるならば、私たちはそのようなゲームをプレイすることが道徳的に間違っていると言うことができるかもしれません。けれども、証拠はこの主張を支持していません。しかし、殺人者をプレイすることを考える際には、さらに検討することがあります。第1章から思い出してほしいのですが、ベンサムとミルは、彼らの「幸福」へのアプローチにおいて異なっています。ベンサムは有名な主張をしています:

> 偏見を別にすれば、プッシュピンのゲームは音楽と詩の芸術と科学と同じ価値がある。もしプッシュピンのゲームがより多くの喜びをもたらすならば、それはそのどちらよりも大きな価値がある…もしプッシュピンのゲームよりも詩と音楽が優先されるにふさわしいならば、それは、それらが、喜ばせるのが最も困難な個人を満足させるために計算されたものであるからに違いない。^[J. Bentham, An Introduction to the Principles of Morals and Legislation, pp. 206–07, http://www.econlib.org/library/Bentham/bnthPML18.html]

「プッシュピンは詩と同じくらい良い」ので、ベンサムは、ビデオゲームで殺人者をプレイすることを他の喜びと同じように扱うでしょう。しかしながら、あなたは、ミルはこれがそれほど正しくはないと考えており、プッシュピン(あるいは、私たちの場合では、コール・オブ・デューティー/ヘイトレッドなどで殺人者をプレイする)は、私たちが詩などの他の活動から得る喜びと同等の価値のものではおそらくないと考えている、ということを思い出すでしょう。

多分、殺人のプレイに含まれる喜びに関して効用計算を行うときには、私たちは、上記で強調した経験的な質問だけでなく、そのような喜びが高いものか低いものかを考慮する必要があります。私たちは、それがより低い喜びであると合理的に結論付けるでしょう(これは議論の余地がありますが)。ミルは、バーチャルな殺害の幻想を映し出すことによる受刑者が得た喜びは、量が少ないだけでなく、絵画教室に参加する、あるいはアートギャラリーを訪れることよりも質が低いと主張するかもしれません。

もちろん、より高い喜びとより低い喜びの区別を導入することが、必ずしもビデオゲームで殺人者をプレイすることが道徳的に間違っているという結論につながるわけではありません。私たちは、コール・オブ・デューティーのようなゲームをプレイすることは、実際にはより高い喜びにつながると主張するかもしれません(あなたはできますか?)。あるいは、私たちは、そのような活動をより低い喜びとして考えるのは正確であるとしても、それでも、場合によっては、これらのゲームで殺人者をプレイするのが正しいという結論を維持することに同意するかもしれません。

それぞれの場合において、功利主義が考慮しなければならないことがさらにあります。たとえば、模擬的な殺害をプレイしている人のタイプだけでなく(彼らは暴力的な気質を持っていますか?)、模されている殺害のタイプも重要になります。おそらく、殺害のシミュレーション方法(殺害される人の年齢、人種、性別や、死ぬ方法)が重要です。たとえば、非常に性的な特徴の強い模擬的な殺害はゲームをする人に害をもたらす可能性が非常に高いかもしれません。あるいは、対照的に、ビデオゲームで制服を着た兵士を模擬的に殺害しても、人々の態度や行動は変化しないかもしれません。シンプルな点は、「模擬的な殺害」についての功利主義的な質問は、私たちがまず状況の正確な詳細を突き止めた場合にのみ答えることができるということです。

ヤングはこの節を終了するのに良い場所です:

> 私たちはビデオゲームの利点について非常に良い考え方を持っている。それらの経済的影響は、ゲームをする人にもたらす娯楽の時間数と同様に定量化可能である。GTA[グランド・セフト・オート]だけで、2008年までに6600万本以上のゲームを売り上げており、少なくともそれだけ多くの人々がゲームの暴力から娯楽を引き出しているという証拠である。他の著しく批判を受けた暴力的なゲームもまた、通常は、販売数のトップにある。多くの教育上の利点もある。視覚的な知覚能力、手と目の協調、およびゲームによる他の運動技能の改善は、十分に立証されている。困難さは、これらの利益がゲームの何らかの害に対してどのくらい重みづけされるべきかを決定することだけにあるが、これは功利主義の理論に内在する問題であり、暴力的なゲームに反対するものとして考慮されるべきではない。^[G. Young, Ethics in the Virtual World: The Morality and Psychology of Gaming, p. 131.]

## カント倫理学と徳倫理学のアプローチ

私たちは、これらの2つの理論を一緒に置きます。なぜなら、ビデオゲームで殺人者をプレイすることについて、それらの理論が最終的に言わなければならないことは、似通っているからです。具体的には、それらの理論が、殺人者をプレイすることが正しいと考えるか間違っているかと考えるかは、そのプレイがゲームをプレイする人をどのように変化させるかについての経験的データに直接依存することになります。

第2章から、カントは、動物が非理性的であるため、私たちは動物に対する道徳的義務がないと言ったことを思い出してください。しかし、これは、私たちが動物を残酷に扱うことができるということを意味しない、と彼は主張しています。これは、もし私たちが動物を残酷に扱うならば、私たちは合理的に行動することができなくなり、他の人に対して道徳的な義務を負っている分野で私たちの義務を放棄することになるかもしれないからです。単純に言えば、それは私たちが道徳的存在であることを悪化させます。アリストテレスは同様のことを言うでしょう。つまり、動物の「権利」のために動物に危害を加えることは間違いではありませんが、それは正しい徳のタイプ、たとえば、感受性、共感、思いやり(この議論については第14章を参照)を発展させるのに役立たないので間違っています。

この動物の倫理への回り道のポイントは、ビデオゲームで殺人者をプレイすることの道徳性が同じように扱われるだろうということです。もし殺人者をプレイすることによって、私たちがより理性的でなくなり、他者に対する義務を見定めることができなくなるのであれば、カントはそれを避けるべきだと言うでしょう。しかし、上記のように、経験的な証拠は確定的ではないので、これは未解決の問題です。

徳理論に移行すると、もし殺人者をプレイすることで私たちがあまり有徳ではなくなる — たとえば、あまり勇気がなくなり、共感しなくなり、感受性が減るなど — ならば、徳理論家は、これが私たちが正しい時に正しいことを正しい態様で行う能力を少なくさせると主張します。これは、殺人者をプレイをすることは避けるべきであることを意味します。そのため、「アリストテレス主義者やカント主義者は、ビデオゲームで殺人者をプレイするのは間違っていると思うだろうか?」という問いには、「直接ではない。それは、プレイをすることと道徳的な行為主体としての私たちへの影響との関連性に依存する」という答えとなります。

## 映画と演劇

この章では、私たちは模擬的な殺人が映画や演劇で行われていることを指摘することから始めました。これには、模擬的な殺害を見ること、または殺害を演じることが含まれることに注意してください。そのようなキャラクターを演じることは、(私たちが思うに、)私たちの読者にはあまり直接的な関連性がありません。ともあれ私たちは、映画や演劇で殺人者を演じることを、ビデオゲームの場合でやったのと同様に扱うことができるであろうと示唆しておきます。もちろん、舞台や映画で殺人者を演じることがビデオゲームで殺人者をプレイすることとは心理的にどのように異なるかを尋ねると、さらに複雑な問題が生じる可能性があります。しかしながら、私たちは問題が依然として根本的には同じであることを示唆しておきます。異なるのは、私たちがどのように経験的なデータを抽出するのか — 私たちが問う必要があるのはどのような経験的な質問か — ということだけです。たとえば、もしかしたら、(偽の)ナイフや銃を物理的に手に握ることは、私たちが実際のナイフや銃を保持する可能性を高く(あるいは低く)させます。また、もしかしたら、(演技上で)撃たれたり(演技上で)出血している人々を見ることは、私たちを実際の血液と死により敏感に(あるいはより鈍感に)します。そしておそらく、これはビデオゲームでナイフを使用する殺人者をプレイすることが私たちにどのような影響を与えるかとは、根本的に異なります。しかし、これもまた、経験的な問題であって、哲学的な問題ではありません。(バーチャルリアリティの洗練さが増すに伴い、ビデオゲームのプレイと映画や演劇で演じることとの隔たりが近づいている可能性があるということは注目に値します。)

それでは、模擬的な殺人を単に見ている場合はどうなるでしょうか?まあ、私たちは上で議論した一般的なアプローチを再び詳述する必要はありません。功利主義者は殺人を見ることが間違っていると考えますか?それは結果に左右されます。カント主義者やアリストテレス主義者はどうですか?それは道徳的な行為主体としての私たちにどのように影響を与えるかに依存します。そして、これらの疑問に対する答えは、やはり経験的な問題です。

私たちは、悲劇のパラドックスとして知られるようになった古代の哲学的問題で終わります。それは直接的に倫理に関するものではありませんが、私たちが議論した他の問題と直接関連する可能性のある真正性や性格を扱う問題を前面に押し出します。

## 悲劇のパラドックス(あるいはより正確には「否定的な感情」のパラドックス)

私たちがホテルの部屋に入ると、壁やシャワールームに血まみれの手の跡が見えた、というところを想像してください。私たちは気分が悪く、不安になり、恐怖を感じます。私たちはすばやく向きを変え、できるだけ早くそこから出ます。そのような感情は歓迎されず、私たちを不快にさせます。しかしながら、動揺させるようなシナリオの映画を観たり制作したりするのに費やされるすべての時間とお金のことを考慮してください。映画を観ることで(もちろん映画に限るわけではなく、演劇やビデオゲームにも同じ推論が適用されます)、私たちの中に嫌悪感や不安、恐怖が生み出されますが、私たちはそのような映画に夢中で群がります。実際、映画がより恐ろしく/嫌悪感を催させ/動揺させるようになるほど、観客にとってより魅力的になるように見えます。たとえばヒッチコックの画期的な「サイコ」を考えてみてください。ここには「パラドックス」があります。一方では否定的な感情は望ましくないのに対し、他の文脈では否定的な感情が望ましいです。

それは真のパラドックスではありませんが、確かに緊張関係があります。説明される必要があるべき奇妙なことです。私たちは、ここでは可能な説明へと入り込むことはしません。私たちにとって興味深いのは、このパラドックスが、模擬的な殺害に言及するときに特に適切であると思われるということです。おそらく、私たちが現実の生活での殺害を目撃すれば、それを特に恐ろしいものと思うでしょう。しかし、それが「模されている」のであれば、たぶんこれらの感情(恐れ、恐怖、等々)は質的に異なります。それらを*恐怖*、*恐れ*、*嫌悪感*と呼びましょう。

これは、模擬的な殺害によって生じる可能性のある私たちの性格の変化をあまり心配する必要がないことを意味するかもしれません。なぜなら、それらは、恐怖ではなく*恐怖*に関係があり、恐れではなく*恐れ*に関係があり、嫌悪感ではなく*嫌悪感*に関係があるからです。やはり、私たちはこれの詳細に入り込む必要はありません。しかし、それは道徳的な意義を持ち、結果として考慮に値するかもしれない模擬的な殺害のもう1つの次元です。

## まとめ

「模擬的な殺害」は、多くの異なる分野をカバーしています。それは、殺人者をプレイしたり、誰かが殺人者を演じるのを見たりすることが含まれます。最初のカテゴリーでは、映画や舞台の俳優でも、ビデオゲームをプレイしている人でもかまいません。

当初は、それは「模されている」ものであるため、このトピックは倫理の範囲外にあると考えるかもしれません。しかし、私たちは、功利主義、カント倫理学と徳倫理学のレンズを使って、これが当てはまらないことを示してきました。功利主義にとっては、それが模されているかどうかは重要ではなく、そこでの質問は、これらの活動のそれぞれが何か他のことをすることと比較してどれほどの幸福を生み出すかということです。それがより大きい幸福を生み出すならば、私たちはそれらを行うべきであり、そうでなければ、私たちは行うべきでありません。カント倫理学者と徳倫理学者にとっての質問とは、模擬的な殺人に関与することが人としての私たちをどのように変えるのかということです。もしそれが私たちを道徳的な行為主体にするのを妨げる場合(たとえば、より合理的でなく、あるいはより有徳でなくさせる場合)、私たちは模擬的な殺人に関与するべきではありません。

しかしながら、この章から得られる主な教訓は次の通りです。つまり、模擬的な殺害を取り巻く問題は、心理学を介して対処されるであろう、ということです。そして、それはこれまでのところ決定的ではありません。そのため、私たちが言える最大限のことは「そう、模擬的な殺人は道徳的な問題である」ということだと思われますが、特定の活動が道徳的に正しいか間違っているかの決定は、実験を通じて進められることでしょう。

## 学生によくある間違い

* 功利主義者が模擬的な殺害には間違っていることは何もないと言うだろうと考える。

* 倫理的問題にとっての心理学的データの重要性を見過ごす。

* 時には私たちが悪いことを好むことを単に指摘することによって、私たちが悲劇のパラドックスに答えることができると考える。

* 悪い趣味が単に道徳的に間違っていると仮定する。

検討すべき問題

1. ダニエル・ラドクリフ主演の2015年の映画のゲーム・チェンジャーズを見てください。この映画では、グランド・セフト・オートの製作者とジャック・トンプソンとの間の裁判例を見ています。この映画が倫理的な問題を扱っていることに対して、あなたはどう思いますか?特定の倫理理論がより好意的に表されていると思いますか?
2. 「模擬的な殺害」とは何ですか?
3. (1)-(4)を読んで、模擬的な殺害が真の道徳的問題を生じさせると思いますか?
4. あなたは、(a)動物の模擬的な殺害をどのように考えますか?それは人間の模擬的な殺害とは異なるように扱われるべきでしょうか?(b)殺害を含むゲーム、たとえば遊び場での兵士ごっこを小さな子供たちが遊ぶことをどのように考えますか。
5. 私たちは、「模擬的な殺人」を窃盗や強姦など他の「模擬的な」行為とは異なるように扱うべきでしょうか?
6. あなたは、(1)の受刑者が得た喜びは、「より低い」喜びだと思いますか?
7. カント倫理学者/徳倫理学者は、(1)についてどのようなことを言うでしょうか?
8. 将来AIロボットのような高度に人間に似せたものを購入できるようになった未来というケースを想像してみてください。これらのロボットは「殺される」ことができます。彼らは「出血」するでしょう。彼らは慈悲を懇願して、すすり泣く等々をするようにプログラムされています。ひとたび彼らが「殺される」と、彼らはリセットされ「再び殺される」ことができます。私たちはこのケースを異なるように扱うべきでしょうか?もしこのロボットが非常に人間に似ていて、人々がもはやそれらと人間の違いに気づかないとしたらどうなるでしょうか?それは物事を変えますか?
9. 政府はコール・オブ・デューティーやヘイトレッドなどのビデオゲームを検閲しています。彼らがそうすることは正しいですか?つまり、たとえ私たちがそれを不道徳と思うとしても、これは「模擬的な殺害」を統制する法律とどのような関係があるのでしょうか?
10. 「悲劇のパラドックス」とは何ですか?模擬的な殺害の道徳性について議論する際には、それは関連性があると思いますか?
11. Google Scholarを使用して、「模擬的な殺害」(あなたが求める任意のバージョン)の心理的影響に関する最新の研究を検索してください。現在の心理学的研究は、この章で提起された倫理的問題について私たちに何を教えてくれますか?

## 重要な用語

模擬的な殺害

悲劇のパラドックス

より高い喜び・より低い喜び

リスク増加行為

## 参照文献

Bentham, Jeremy, An Introduction to the Principles of Morals and Legislation, freely available at http://www.econlib.org/library/Bentham/bnthPML18.html
<br>[関嘉彦責任編集「世界の名著49 ベンサム/J・S・ミル」、中央公論新社、1979年]

Frisch, Max, Homo Faber: A Report (Houghton Mifflin Harcourt, 1959).
<br>[「アテネに死す」中野孝次訳、白水社、1991年]

Horgan, John, ‘The Forgotten Era of Brain Chips’, Scientific American, 293.4 (October 2005): 66–73, https://doi.org/10.1038/scientificamerican1005-66

Lacewing, Michael, ‘Simulated Killing’, freely available at http://documents.routledge-interactive.s3.amazonaws.com/9781138793934/A22014/ethical_theories/Simulated killing.pdf

McCormick, Matt, ‘Is It Wrong to Play Violent Video Games?’, Ethics and Information Technology, 3.4 (2001): 277–87, https://doi.org/10.1023/a:1013802119431

Young, Garry, Ethics in the Virtual World: The Morality and Psychology of Gaming (Abington: Routledge, 2014), https://doi.org/10.5860/choice.51-1780