# 動物を食べること

> 人間は食糧のために動物を殺さずに生きることも、健康でいることもできる。したがって、もし人間が肉を食べるならば、その人は単に食欲のために動物の命を奪うことに加担している。そして、そのように行動することは不道徳である。^[L. Tolstoy, Writings on Civil Disobedience and Non-Violence.]

## 動物を食べることへの入門

英国をはじめとする多くの国々は、動物との奇妙な関係を持っています。たとえば、いま私は、うちの鶏のために余分なわらを加えた後に、この章を入力するために戻ってきたところです。この鶏は、毎日私が世話をしており、彼らの福利に対して私がお金を注ぎ込んでいるものです。しかしながら、私は昨夜にチキンの夕食を楽しく消費しており、この事実は、私はもっと一般的な鶏の福利にさほど努力をつぎ込んでいるわけではないことを示唆しているようです。しかしながら、私自身とうちの鶏の間の関係のこの奇妙さは、私に特有のものではありません。英国には、菜食主義者はほとんどいません(データでは近年は一貫して2～3％の間であると示唆されています)が、それよりも多くの人々が動物愛好家であると主張するでしょう。^[Data available at https://www.vegsoc.org/sslpage.aspx?pid=753]この章では、動物を食べることの道徳的な容認可能性の応用倫理的な問題が考慮されます。動物に対する私たちの多面的な行動や姿勢のいくつかの側面を正当化する、あるいは非難するような結論が導き出されるかどうかを見ていきましょう。

## 肉を食べることを正当化する

肉食がどんな理由で道徳的に正当化されるのかを検討することから始めるのが理にかなっています。この目的のために、以下の2つの可能な正当化が考えられます。

### 比較による正当化

動物の肉の消費のためのこのよく引用される正当化に対して、適切な名前を付けるのは困難です。なぜ肉食が道徳的に受け入れられるのかを疑問視するときにかなり一般的な回答は、肉食者としての人間と肉食者としての他の動物との比較に関連しています。(もし自分で捕まえることができるならば)ライオンがガゼルを食べるように、熊が鮭を食べるように、狐が鶏を食べるように、人間は豚/牛/羊などを食べます。私たちが(最も熱心な菜食主義者にとっても)ライオンや熊や狐を道徳的に批判するのが奇妙であることを考えれば、これらの異なる種の行動の間に道徳的な同等性があり、それは非菜食主義の人間の行動へと拡張されるように思われます。そして、私たちもまた、肉を消費することにおける道徳的な批判から解放されるべきです。

しかしながら、上記の返答の中にあり得る弱点は、識別するのが難しいものではありません。1つは、私たちは、ライオン、熊、狐などの行動に基づいて、特定の行動の容認可能性に関する道徳的判断を決定することは、あまりありません。実際、ライオンが時たま人間を食べることは、他の人間を食べることが道徳的に受け入れ可能であるかもしれないことを示唆しません。さらに、ある種類の肉を食べることは他の種類の肉を食べることよりも受け入れやすい(たとえば、鶏肉はゴリラの肉よりも受け入れやすい)と考える人は、このタイプの正当化の中には限られた手助けしか見つけられないでしょう。もし肉食のためのこの切れ味の悪い議論にいくらかのメリットがあるならば、それはおそらくもっと広い規範倫理の理論の文脈の中で、より正確かつ鋭く引き出される必要があるでしょう。

### 支配権に基づく正当化

肉食のために私たちが検討する2番目の正当化は、あなたの世界に対するより広い見通しに応じて、もう少しだけ進むかもしれません。聖書によると、「主なる神は土のちりで人を造り、命の息をその鼻に吹きいれられた。そこで人は生きた者となった。」^[Genesis 2:7, New International Version, https://www.biblegateway.com/passage/?search=Genesis+2%3A7&version=NIV] この節は、神が人間に魂を与え、人間と動物の被造物の残りの部分とを区別したとしばしば解釈されます。さらに、「大洪水」の後、神は、こう言いました。「[すべて]生きて動くものはあなたがたの食物となるであろう。さきに青草をあなたがたに与えたように、わたしはこれらのものを皆あなたがたに与える。」^[Genesis 9:3, New International Version, https://www.biblegateway.com/passage/?search=Genesis+9:3&version=NIV] したがって、多くのキリスト教徒がさまざまな要因のためにベジタリアンのライフスタイルを選択しているにもかかわらず(何かが許されているという事実は、必ずしもそれを望ましいものにすることはありません)、神が動物を食べることに対して異議を唱えていないことは、かなり明らかです。

しかしながら、この章の残りの部分では、私たちは功利主義、カント倫理学、アリストテレスの徳倫理学という視点から肉食を取り巻く倫理的問題を考察します。これらの理論は、どのように行動するかを決定するために聖書の参考文献を中心には置かない理論です。したがって、聖書の教えに焦点を当てた宗教的倫理は、動物を食べることの正当化について明確な答えを与えるように見えるかもしれませんが、AQA試験のために勉強する学生は、試験に向けて良い準備をしておくために、上記の3つの理論の適用に精通していなければなりません。次の節では、私たちは第1章、第2章および第3章で概説したように、規範理論を適用するこのプロセスを開始します。この応用倫理のトピックへのメタ倫理学の理論の適用は、第6章と、第11章の応用的な文脈におけるメタ倫理学の議論から理解できます。

## 行為功利主義

第1章で説明したように、功利主義は、ジェレミー・ベンサム、ジョン・スチュアート・ミル、ピーター・シンガーがそれぞれ示唆するように、行為功利主義、規則功利主義、選好功利主義といったさまざまな形で出現します。ジェレミー・ベンサムや他の行為功利主義の見解は、動物を食べることの容認可能性に関しては、かなり簡単に確認できるように思えます。ベンサム的な多様な行為功利主義者は、最も多くの数の人々に最も大きな喜びを確保することを単純に目指しています。ベンサムは利害の平等な配慮という考えを抱いていますが(社会的地位や社会的権力にかかわらず、女王の喜びは、農民の喜びと同じものであるべきです)、平等のこの概念は、人間にのみ適用されると考えられるでしょう。このように理解されるならば、行為功利主義者の見解は明白となるでしょう。なぜなら、牛肉のハンバーガーを食べるときの人間の喜びは、道徳的に意味を持つ苦痛を上回るためです。結局のところ、利害の平等な配慮というこのバージョンでは、牛が被るかもしれない苦痛は、どのように喜びの総量を最大化するかを決める上で道徳的な重みを持っていません。

しかしながら、ベンサムは、平等な配慮の原則に対するこの人間中心主義的なアプローチを採用しませんでした。彼の最も有名な文章の1つで、彼は次のように述べています:

> 動物の被造物の残りの部分が、圧制者の手によって抑え込まれてきたものの決して彼らから手放されたことのない権利を得ることができる日が来るかもしれない。フランス人はすでに、皮膚の黒さが、人間が非道な人の気まぐれからの救済なく見捨てられるべき理由とはならないことを発見した。脚の数、肌の体毛、または[骨盤]の終端部が、同じ運命[…]の感覚を持つ生き物を見捨てるのに同等に不十分な理由であることが、いつか認識される日が来るかもしれない。問題は、「彼らは推論できるか?」でもなければ、「彼らは話すことができるか?」でもなく、「彼らは苦しむか?」なのである。^[J. Bentham, An Introduction to the Principles of Morals and Legislation, http://www.econlib.org/library/Bentham/bnthPML18.html]

この文章の中で、ベンサムは、動物が話すことができないことや、人間と比較して不十分な理性の能力を理由としては、特定の行為に関連する苦痛の総量や喜びの総量の計算からは動物を排除できないことを明確にしています。逆に、動物が何らかの苦痛や痛みを経験している限り、この苦痛や痛みは、どの行動が最も多くのものに最も大きな喜びを生み出すかを決定するための計算に含めなければなりません。簡単に言えば、すべての苦しんでいる生き物 — 人間であろうとなかろうと — は、道徳的に関連のある生き物のグループの一部です。

この動物に対する平等な配慮の考え方は、人種差別の倫理的な欠点との比較がされている最初の節において、ベンサムによって正当化されています。ベンサムは、肌の色は道徳的に無関係な個人の特徴とみなされ、彼らの苦痛や喜びを無視する理由ではないと言います。したがって、肌の色や人種に基づいて道徳的関連性を否定するのは恣意的であり、私たち現代世界の人間がジェンダーに基づいて道徳的関連性を否定するのは恣意的であると信じているのと同様に、種族だけに基づいて道徳的関連性を否定することもまた恣意的です。もし重要なことが苦痛と喜びであるならば、その苦痛と喜びの主としての役割を果たす種族は無関係なように見えます。

功利主義的な意思決定において動物の苦痛と喜びを測定することについてのベンサムの寛容さは、彼のことを動物の権利と動物の厚生の運動の中で英雄的な人物としました。あなたがベンサムに同意するかどうかに関わらず、彼の意見は確かに彼の哲学的な同時代の多くの人たちのものからはいくらか外れていました。たとえば、ある逸話によれば、1世紀少し前に、すべての時代の中で最も尊敬されている哲学者の1人であるルネ・デカルトは、犬の機械的な動きを研究するために、妻の飼い犬を壁に釘で打ち付けた後に、このかわいそうな生き物を切り開きました。デカルトにとって、犬のような魂のない動物は苦痛を感じることができず、本物の痛みの表れ方を模倣しているだけなので、この種の行動には道徳的な問題は何もありませんでした。ベンサムは、もし彼がデカルトの行動を知っていたとしたら、道徳的に関連を持つ犬の苦痛を認識していない無能力さにたじろいだことでしょう。

彼の理論化の個々の部分をまとめると、私たちは、ベンサムは動物を食べることの容認可能性を考慮するときに、動物の苦痛と喜びを道徳的に関連するものとして勘定に入れるとともに、彼が苦痛と喜びを勘定に入れる際に、彼の平等の原則へのコミットメントに基づいて、人間の苦痛や喜びと同じくらい価値のあるものとして、動物の苦痛や喜びを見積もっているように思われる、という見解に達します。したがって、もし肉食の行為に関連する苦痛の総量(動物が被る苦痛を含む)が、そのような行為に関連する喜びの総量を上回る場合、ベンサムおよびベンサム的な哲学者は、肉食のこれらの事例は道徳的に間違っていると結論せざるを得ないでしょう。

次に移動する前に、上の段落で使用されている言語が重要であることに注目に値します。ベンサムも他の相対主義的な功利主義者も、動物を食べることは絶対に正しいとか、絶対に間違っているということは決して言っていません。相対主義と絶対主義の考え方は第1章でより詳細に探究されていますが、今のところは、行為功利主義者は個別の状況それぞれにおいてどのようにして良さをもたらすかを考え出すことにのみ関心がある、ということを思い起こしておくことが有益です。したがって、この見解では、癌の治療法に近づいている研究者が、彼の研究を誰かに伝えるのに十分なだけ生き延びるために健康な犬を食べる必要がある場合、肉食は道徳的に受け入れられるかもしれません。一方、安く生産され、その動物に対する大きな苦しみを伴うターキーのハンバーガーを食べることは、消費に関連する喜びが最小限であるため、正当化できないかもしれません。もちろん、これらは、行為功利主義と動物を食べることという文脈の中の現実世界の倫理的意思決定からはある程度離れた「ボール紙を切り抜いて作った」ケースです。しかしながら、この応用された文脈であなたがこの理論の適用の頑健な批判あるいは擁護をするために、行為功利主義が動物を食べることに反対する声を上げる可能性のあるケースの範囲と、行為功利主義が動物を食べることに賛成する声を上げる可能性のあるケースの範囲とを検討しておくことは、あなたにとって非常に大きなメリットがあるでしょう。行為功利主義は、適切な結論を持つような、適切な種類の決定手続きを提供しているように見えますか?

## ベンサムへの挑戦

ベンサムの行為功利主義的な見解に対する1つの挑戦は、動物と人間の間の道徳的な区別を作ることは決して恣意的ではなく、そのような「種差別」(ピーター・シンガーがこの用語を有名にしました)的な区別と、人種差別や性差別などのような差別的な思考プロセスとの間には違いがあるという考え方に基づいています。もしかしたら、人間の喜びや苦痛は、私たちの知性や高次の思考や経験に対する能力のために、もっと価値があるのか​​もしれません。

しかしながら、私たちは、このような方法でベンサムに対応するときには慎重にならなければなりません。認知症に罹患している高齢者、または生まれて2か月の赤ちゃん、または(第7章で議論した)永続的な植物状態の患者を考えてみてください。これら3人の個人はすべて、かなり深刻なレベルで理性の能力が欠けているように見えるでしょう。これに対し、元のベンサムの引用文から削除された部分の文章では、ベンサムはこう言っています。「完全に成長した馬または犬は、生まれてから1日、1週間、あるいは1か月の乳児よりも、比較にならないくらいより合理的でより会話のできる動物である。」^[Ibid.]したがって、合理性という言葉によって砂の上に線(人間と動物とを区別する線、その線よりも下のものを食べることを正当化するが、その線よりも上のものを食べることは正当化しない線)を引こうとする人は、一見して乗り越えることのできないジレンマに直面しています — つまり、合理性は道徳的に関連しており、人間の一部の人には道徳的立場がないか、あるいは、合理性は道徳的には関連しておらず、人間を動物から分離しようとするこの試みは失敗であるか、というジレンマです。

この問題を克服するために、潜在能力の議論が持ち出されるかもしれません。生後2か月の乳児は現在よりも合理的になる潜在能力があり、認知症患者やPVS患者もうまくいく治療法が発見され施されれば同様のことが言えるため、砂の上にひかれた人間と動物の間の道徳的関連性についての線は、すべての人間は人間以外の動物が持つ理性のスキルよりも高い潜在能力を持つという根拠に基づいて再度ひき直されるかもしれません。

しかしながら、シンガーは、この潜在能力についての示唆に対する賢明な答えを持っています。それは、もし私たちがチャールズ皇太子の権力を検討するならば明らかになるものです。彼は潜在的な王ではありますが、チャールズ皇太子は現在のところ王子に過ぎません。これは、現時点では、彼は王ではなく、王子の権利しか持たないことを意味します。彼は実際に王になるまで王の権力を得ることはありません。同様に、生後2か月の赤ちゃんは、潜在的には犬や馬よりも合理的ではありますが、その潜在能力が現実化されるまでは、いかなる余分な道徳的配慮もされるべきではありません。したがって、合理性や知性といった理由づけで動物と人間を道徳的に分離しようとする試みは、やはり、前の段落で述べたジレンマに直面するように見えます。

## 動物を食べることについての功利主義的な理由

前の2つの節では、ベンサムやシンガーのような功利主義者にとって、動物を食べることが道徳的に間違っている時があることを明らかにすることができたと思います。それは、動物を食べることに伴う苦痛が対応する喜びを上回るときです。しかしながら、動物を食べることはまったく道徳的に正当化できるものであり、それはまれにしか起こりえない状況ではないということをシンガーが非常に明確に示していることは注目に値します。シンガーが、工場で飼育された食べ物を食べることの道徳的な容認可能性を蔑視しているのは事実です。それは次の引用に示唆されています:

> これらの[動物を苦しめる苦痛の道徳的な関連性に関する]議論は、工場的な飼育場で育てられた動物に適用される。それは、私たちが食べている肉が工場の飼育方法によって製造されたものではないことを知っていない限り、私たちは鶏肉、豚肉、または子牛肉を食べるべきではないということを意味している。^[P. Singer, ‘Equality for Animals?’, p. 174.]

シンガーはまた、放し飼いにされた鶏から採られていない卵の消費にも反対しています。同じことは、おそらく鶏肉自体を食べることにも当てはまるでしょう。しかしながら、この種の特定の動物を食べることへの異議、特に条件についてのものは、シンガーのような選好功利主義者にとって肉を食べることが道徳的に受け入れられるような状況を私たちに指し示します。たとえば、もし鶏が、痛みを伴わずに殺される前に(現実には必ずしも達成されないものであっても、完全に可能と思われるもの)、自由に動き回ることが許されていたとしても、選好の満足の天秤は、鶏自身の存続からは離れて健康的な食事を求めている飢えた家族のほうに傾くでしょう — 鶏は、それらを扱う人々が知っているように、それらの生命が短く切り詰められた時には叶えられることのないような長期的な将来の選好を持つ精神的能力を有する可能性は低いです。

確かに、ベンサム自身でさえ、前で示唆されたすべてのことにもかかわらず、動物を食べるという考え方を支持していました。飼育され、殺された動物は、管理されていない荒野の厳しい現実の中で死ぬままにされた動物よりもはるかに少ない苦痛を被っているのかもしれないとベンサムは考えています。よく管理され、迅速に処理された屠殺は、飢餓、病気または捕食者の攻撃にさらされた後の暴力的な死よりも苦痛を少なくする可能性があります。

絶え間なく変化する世界では、動物の屠殺に関連した慣行が企業ごとや文化ごとによって異なるため、功利主義者は動物を食べることの一般的な容認可能性について明確な答えを出すことはできません。シンガーは以下のように言ってこれをまとめています:

> […]重要な問題は、動物の肉が苦しみなく生産できるかどうかではなく、私たちが購入しようと検討している肉が苦しみなく生産されたかどうかである。そうであると私たちが自信を持つことができるのでない限り、利害の平等な配慮の原則は、私たちがそれほど重要でない利益を満たすために動物の重要な利益を犠牲にすることは間違っていることを意味する。その結果、私たちはこのプロセスの最終結果を拒絶するべきである。^[Ibid., p. 175.]

第1章で功利主義に向けられたさまざまな批判 — たとえば、厳しい要求に基づく異議、または快楽や選好の計算の問題に基づく異議 — は、この章でも無関係ではありません。しかしながら、反復を避けるために、動物を食べることへの(行為・選好)功利主義的な反応が成功する可能性についてあなたが考えるときには、これらの批判の適用を自分自身で考えるべきです。

これまでのコメントを踏まえると、ミルと規則功利主義の議論が欠如していること、そして、より高い、より低い喜びの議論が欠如していることは、この章における重要な省略であることが示唆されるかもしれません。ある意味では、私たちは同意します。しかしながら、ひとたび動物を食べる行為に対する功利主義の適用に関する問題を上記のように定めてしまえば、規則功利主義的な考え方の適用は、はるかに簡単な作業になるはずです。今のところは、以下の問題が検討のために提案されています。

1. 肉食は高い喜びですか、低い喜びですか?子羊が小さな大衆食堂で消費される場合と、世界的に有名なシェフによって調理される場合とでは、何か違いがありますか?動物を食べることの道徳的な容認可能性は、動物が消費のために調理される方法によって変わるべきでしょうか?
2. 動物はより高い喜びにアクセスできないために人間よりも価値が低いものですか?
3. 工場での飼育を完全に禁止することは、もし普遍化されれば、最も多くのものに最も大きな良さをもたらすようなルールとなるでしょうか?この応用倫理的な設定において、規則功利主義者によって提唱されるかもしれない他の規則は何かあるでしょうか?

この章と第1章の両方の議論に照らしてこれらの質問に答えることは、この分野における功利主義的思考のしっかりとした理解をもたらしてくれるでしょう。

## カント倫理学と動物を食べること

イマヌエル・カントによれば、人間は「[…]非合理的な動物のようなものからは、階級においても尊厳においても全く異なる存在である。それらのものは、人の裁量で取り扱い、処分できるであろう。」^[I. Kant, Lectures on Anthropology.]もちろん、人間が動物に対して何ら責任を持たず、それを思いのままに消費することができるという考え方は、第4節で概説したのと同じ異議に開かれています。しかしながら、それらの懸念をいったん脇に置いておくと、あたかもカントが、この文脈で適用されるような、彼の倫理的思考についての役に立つ明確な表現を私たちに与えてくれるかのように見えます。

カントは、第2章で探求したように、動物を食べることは定言命法の2つの定式化に違反しないため、私たちが動物に対する直接の義務はないことを明らかにしています。動物を食べることは普遍的な法になることができます。なぜなら、この行動を普遍化されたものとして考えることにも、この行動を普遍化しようとすることにも、何の問題もないからです。さらに、動物を食べること自体は、他の人を単に目的のための手段として扱うことにはなりません(そしてカントは、動物は目的のための手段としてのみ存在していることを明確にしています^[I. Kant, ‘We Have no Duties to Animals’, p. 395.])。もちろん、私たちは食糧を確保するために単に人を目的のための手段として扱うことがあるかもしれませんが、動物が消費されるときにはこれが必ず行われるという必然性はありません。したがって、動物を食べることは一般的に許容され、私たちが食糧を確保する上で仲間の人間に対して間違って行動するときにのみ許容されません。動物自体は私たちの義務の評価には関係しません。

カントは上述のようなことを言っていますが、しかし、私たちは動物に注意をする直接の義務がないにもかかわらず、私たちが動物を何の配慮もなく扱うのではなく、世話と気遣いをもって扱うことを奨励しています。カントは、ある人について「[もし]彼が人間としての気持ちを抑えつけたくないのであれば、彼は動物に優しい態度をとらなければならない。なぜなら、動物に対して残酷な者は人間とのやりとりにおいてもつらく当たるからだ」と言っています。^[Ibid.]動物に不必要に残酷な人、気まぐれに殺す人、あるいはその苦しみを軽視して動物を扱う人は、生命に対するこのようなアプローチに慣れていき、その結果、彼らが他の人間とやり取りする際に義務に従って行動する可能性が低くなります。そのため、動物に対する私たちの義務は直接的なものではなく間接的なものであり、それは私たちが仲間の人間たちとやり取りする際に便益が得られる限りにおいて存在する、とカントは言っています。

この考え方を動物を食べることに適用すると、私たちが動物を処理する際に残酷でも不親切でもない限り、カントが反論することはないでしょう。おそらく、工場で飼育された食べ物を食べることは、残酷な行為、あるいは残酷さを受け入れるものとみなされます。いずれにしても、皮肉なことに、シンガーとカントは、動物を食べることの領域で行動する方法に関する助言については、ほとんど同じ立場になると思われます。

最後に、クリスティン・コースガード(1952年-)のような現代のカント主義者が、カント自身による動物に対する直接の義務の無視に反対していることは、知っておく価値があります。コースガードは、苦痛を経験する生き物を単に目的のための手段として扱うことは許容可能あるいは受け入れ可能であることを認めていません。なぜなら、「[…]それは苦痛を伴う苦痛である。そして、それは取るに足りない事実ではない。」^[C. Korsgaard, The Sources of Normativity, p. 154.]したがって、たとえカント自身が認めなかったとしても、カント主義者が動物に対する直接の義務を認めるかどうかは、未解決の問題となるでしょう。

## 徳倫理学と動物を食べること

徳倫理学は行為主体中心の道徳理論であるため、動物を食べることの倫理的な容認可能性に関して絶対的な道徳的回答を徳倫理学に期待することは、徳倫理学を誤解しています。徳倫理学は、動物を食べることの特定の事例の道徳性に関する倫理的判断をすることを試みるのではなく、それは有徳な人に関連する気質や性格の特性について話し合うことを選んでいます。彼らは、有徳な人が動物を全く食べないか、いくらかの動物を食べるのか、または提供されているすべての動物を食べるのかどうかということについて、指針を提供するでしょう。

第3章で与えられた徳倫理学の説明から、私たちは最初から次の重要な教訓を引き出すことができます。菜食主義は性格の特性や気質ではなく生き方であるため、菜食主義がそれ自体で徳である可能性はありません。むしろ、もし私たちが徳倫理的思考に従うならば、私たちはどのような状況でどのような時に肉を食べることを避ける気質が有徳になるのか、そしてどのような時にその気質が過剰または不足の悪徳として表示されるのかを尋ねるべきです。

ロザリンド・ハーストハウスは、この分野におけるシンガーの主張と徳倫理学者のアプローチとの間の興味深い比較を描きだします。^[R. Hursthouse, ‘Applying Virtue Ethics to Our Treatment of the Other Animals’, http://www.hackettpublishing.com/pdfs/Hursthouse_Essay.pdf]ハーストハウスは、シンガーの選好功利主義的視点から生じる動物に対する残虐さに反対する際に、動物を食べることが有徳な特性というよりむしろ悪徳のような性格の特性をしばしば反映するだろうという見解を支持する証拠をシンガーが提供していると示唆します。私たちの多くが、肉を買うときには、対象となっている動物がかなり不愉快な存在になるであろうということに気付いていることを考慮すれば、この情報を無視しようとする意志は、生活での買い物や食事の決定をする領域の中で、思いやりという有徳な手段の実践とぴったり一致することはないでしょう。故意の無知は、不足の悪徳とみなすことができます。

私たちの食べ物のための価値の領域における買い物という上記の例は、動物を食べることの問題を、より高価で魅力的ではない菜食主義的な選択肢ではなく夕食のための安いチキンの選択といった、特定の状況へと移します。しかしながら、他の選択肢が(おそらく経済的要因を通じて)利用できないときに、あなたの子供の健康を増進するために動物を食べるなどといった、肉食が有徳的な性格の結果であると考えられるかもしれない状況を想像することは難しくありません。このような状況では、あなたの子供の必要性を明確に認識しておきながら菜食主義に頑固にしがみつくことは、過剰の悪徳に基づく行動を表すかもしれません。(ロジャー・スクルートンは、肉食の徳を語る徳倫理学者の1人であり、彼の考え方は、この問題に対するわずかに異なる徳倫理的応答のために探求する価値があます。)^[R. Scruton, ‘Eat Animals! It’s for Their Own Good’, http://articles.latimes.com/1991-07-25/local/me-54_1_animal-rights]

もちろん、2つの概説したケースでの有徳な反応についての具体的な研究でなく、より一般的な指針を持つことは有益でしょう。ハーストハウスは、動物を食べるか否かを選ぶことに関して、残酷な意思決定よりもむしろ思いやりを促進することに焦点を当てて、こう言います:

> […]私たちがさらに進むためには、私たちは私たちの見通しに相当な変化を必要とする — 徳倫理学者の言葉で言えば、人間と人間の生活は人間同士で織り合わされているだけでなく、残りの自然とも織り合わされているという事実についての、明確に見定められた実質的な認識である。そして、そのときにのみ、私たちは、私たちがやっていることに対して正しく徳倫理学を適用するだろう。^[R. Hursthouse, ‘Applying Virtue Ethics to Our Treatment of the Other Animals’, p. 154, http://www.hackettpublishing.com/pdfs/Hursthouse_Essay.pdf]

アリストテレスは、徳が人間の行動に関係しているため、徳の適用にもっと関心を持っていましたが、人間の開花は一生のプロセスであると考えられていました。したがって、ハーストハウスのように、動物に対する私たちの気質に焦点を当てる動機がなかったわけではありません。この指針がアリストテレスの考え方の正確な解釈であるかどうか、それがアリストテレスの考え方の独立した都合のよい延長であるかどうかは、第3章で与えられているアリストテレスが実際に概説したような徳の文脈の中で熟考してみる価値のあるものです。答える必要のある重要な質問とは、ハーストハウスの推論がアリストテレスの核となる思想に沿ったものであるかどうか、あるいは彼女が徳倫理学に対抗する見解を作り上げたのかということです。

徳倫理学に適用されるかもしれない批判の中で、不明瞭な指針による異議は、上の考え方にもかかわらず、非常に厄介なように見えるかもしれません。以下の3つの問題を考慮することは、この設定において行動する方法を決定するための徳倫理学の実用的な有用性についてのあなたの考えを明確にするのに役立ちます。

1. 私たちが動物を食べることについて学ぶことができる、有徳なロールモデルは誰ですか?料理するときに「動物を満喫する」と話すテレビのシェフですか?ベジタリアンの運動家?ピーター・シンガー?
2. ベア・グリルスやエド・スタッフォードのようなテレビの登場人物は、しばしば私たちの娯楽のために荒れ果てた場所へと置き去りにされ、食べるためだけに動物を殺すことによってサバイバル生活をしています。彼らの殺害は徳、あるいは悪徳を反映していますか?
3. アンジェラは非常に高価なレストランで友人と食事をしているベジタリアンです。アンジェラの友人がこの夕食代を払い、食べるコースを選びました。1つの料理は、丁寧に調理された鴨肉を食べることを含みます。アンジェラがこの鴨肉を食べることは有徳ですか?あるいは、極端な状況であっても、彼女の信念を守ることは有徳でしょうか?(あなたの答えを展開するために、シンガーの「パリ免除」の考え方を調べてみる価値があります。)

もしあなたがこれらの質問に答えることができれば、あなたは動物を食べることの問題に徳倫理学的な思考を適用する能力について、より自信が持てるはずです。

## コーラ・ダイアモンド

この章を終えるにあたり、これまで議論してきた規範倫理学の理論に基づく視点とは距離を置いている、動物を食べることの倫理的な容認可能性に関する別の視点を提供するコーラ・ダイアモンドの考え方を簡単に説明します(AQAはダイアモンドの論説を読むことを推奨しています)。^[C. Diamond, ‘Eating Meat and Eating People’, http://www.laurentillinghast.com/DiamondEatingMeat.pdf]この章の焦点の大部分は、動物を消費することの倫理的な容認可能性を検討する際に、動物が道徳的に関連があるかどうか、あるいは動物が人間と同程度の権利を有するかどうかという問題にありました。ダイアモンドはこのアプローチに完全に反対し、動物を食べることの道徳性について、道徳的な権利の話をすることを介した批判をしようとはしません。彼女は全く違う批判をしています。

ダイアモンドにとって、動物の「道徳的権利」という概念は、動物を食べることの道徳的な容認可能性を説明することに関しては無関係です。なぜなら、私たちは、特定の存在を食べることの権利に関連する話をすることなしには受け入れることができないような、他の生命の領域に関する意思決定を行うからです。特に、ダイアモンドは、人間の死体を食べることに対する嫌悪感は、死体を食べるべきではないという道徳的権利に基づいているのではなく、私たちが人間の死体や切断された人間の四肢を食べる可能性について言及することに不快感を感じるためである、ということを示唆しています。この不快感は、権利の話ではなく、「人は食べるものではない」という考え方によって説明されます。これは、私たちの生活の中で人間と人体の身体の部分との相互作用の性質のために現れてくる考えです。^[Ibid., p. 468.]

この考え方を動物を食べることの問題にまで広げてきたダイアモンドは、この問題について以下の流れの議論を持ち出しました:

もし
<br>あなたが人間を食べない、
<br>そして
<br>あなたがペットを食べない、
<br>ならば、
<br>そのような動物とあなたが食べないものとの間に意味のある違いはないので、あなたは他の動物(おそらく、少なくとも高度な霊長類)を食べるべきではない。

ダイアモンドにとって、そのような議論は非常に説得力がありません。この議論は、その冷たく論理的な形の中で、ペットが、死んだ人間の体や切断された人間の四肢と同様に、食べられるべきものではないという事実を見落としているからです。ダイアモンドが言っているように、ペットには名前がつけられ、私たちは彼らを家に持ち込み、私たちは野生動物とは行わないような方法でペットとやりとりします。野生動物は、スーパーマーケットに陳列されている鶏が食べるものであるのと同様に食べるものかもしれませんが、庭にいるうちの鶏はそうではありません。

このアプローチは、道徳的思考と道徳的な話における非認知主義的、反実在論的な解釈にとって魅力的かもしれません(これらの理論は第6章で説明されています)。私たちは、特定の動物の道徳的地位に関する「食べるものではない」という運動家の叫び声が、認知主義者または実在論者が望むようなこの世界の中に真に存在する道徳的特性を取り上げるように設計されているのか、それともこれらの叫びが非認知主義者の(おそらく情緒主義的なスタイルの)態度を反映しているのかどうかについて疑問に思うでしょう。

しかしながら、ダイアモンド自身は、前で特定したような冷たく論理的な議論や道徳的権利の話によってではなく、食べるべきでないもののリストに追加するように動物との関係を再構築することによって、彼女が提案することができると考えるような菜食主義的立場を保持しています。この目的のために、ダイアモンドはジェイン・レッジェの詩「忠実な肉食動物であることを学ぶ」を、菜食主義への動きを確保するためのはるかに効果的な戦術の典型例として提供しています:

犬と猫と山羊と牛、
<br>鴨と鶏、羊と豚
<br>こどもの話に編み込まれ、
<br>壁やお椀に描かれてる。
<br>ごはんの時間よ!いただきます
<br>みんな大好き、ジューシーなお肉。
<br>今日はパーシー・ポーカーのハム
<br>(漫画では彼はすごいんだ)
<br>お次はクルック夫人の胸肉
<br>さらにドナルドダックの手羽。
<br>もう1つ牛のクララの肝臓
<br>(大丈夫、今は彼女を傷つけないよ)。
<br>そう、その脚はピーター・ラビットの
<br>きちんと噛んで。習慣にしてね。
<br>売るために殺された生き物を食べて、
<br>でも、猫の尻尾を引っ張ってはだめ。
<br>「汚い豚」からの肉を食べて
<br>でも、犬には優しくしなきゃ。
<br>二重に考えられるように成長して
<br>ハムスターにキスして、ミンクの皮をはぐ
<br>あなたは屠殺のことは考えないで
<br>それが動物たちがここにいる理由だから。
<br>彼らは死ぬためだけに地上に来るから、
<br>あなたは肉を食べて、それがなぜかを尋ねないで。^[Ibid., pp. 472–73.]

この詩は、ダイアモンドによると、行動の形態を宣言するのではなく、どの動物が許容される食物資源であり、どの動物がそうでないかについての当然と考えられている信念に挑戦しています。もし私たちが動物を消費の対象ではなく仲間の生き物と見なすならば、その動物たちを殺したり食べたりすることが死んだ人間を消費することのように一線を越えた行為とみなされるような形で、私たちと動物との関係を変化させるかもしれません。難しい状況が私たちの視点を変えるかもしれないため、人肉食は常に道徳的に間違っていると見なされるわけではありません。しかしながら、ほとんどの場合、私たちは正式な功利主義やカント的な正当化の必要なしに、この可能な行為に対してたじろぎます。

ダイアモンドの論文にはあなたの注意を払う価値があり、彼女は、動物の非倫理的扱いに反対する彼女の一連の議論が、性差別や人種差別に反対すべき方法との不幸な類推を生み出すかもしれないという挑戦に応えています。性差別や人種差別の場合、私たちは、たまたま人々を仲間の生き物として見ているという単なる事実(道徳的な権利を持つべき人ではなく、私たちに依存しているように見える事実)によってではなく、道徳的な権利によって公正で平等な扱いが正当化されることを願うでしょう。私たちは、人種差別に対する反発は、ある人が持っている道徳的権利から生まれたものであり、私たちの反発がそのような差別を道徳的に間違ったものにするのではないことを示唆するでしょう。あなたがダイアモンドのアプローチを説得的であると思うか否かは、あなたが彼女の結論に同意するか否かよりも、おそらくもっと重要です。もし彼女の方法が妥当であれば、それは権利や義務を参照することに基づく規範的理論のアプローチの弱点を示すのでしょうか?

## まとめ

道徳的な理論家の中に、動物を食べることがあらゆる状況下で常に絶対的かつ完璧に受け入れられると主張する者はほとんどいません。カントですら、人間が動物に対して何らかの義務を負っていることを明示的に否定したにもかかわらず、動物に対する残虐さという考え方には尻込みしました。この事実は、動物を食べることの倫理的な容認可能性に関する結論は、動物の選好、苦痛または喜びに関する経験的および現実のデータ、および人間が消費するための動物の飼育および屠殺のプロセスの影響によってしばしば決定されることを示唆しています。現実世界の状況は常に流動的ですが、この章では、さまざまな主要な理論を説明したり、あなた自身の視点に到達したりするために、現実の研究をつなぎあわせることができるような道徳的枠組みを提供しています。

## 学生によくある間違い

* 動物に対するカントの立場を過度に単純化する — 直接の義務がないということは、動物に対する義務が全くないことを意味するものではありません。
* 良さと喜びとを結びつける自然主義的な功利主義者に対する開かれた質問の議論(第6章を参照)などの、道徳的立場を批判することに関連するかもしれないメタ倫理的な問題を完全に回避する。
* ダイアモンドの議論を考慮することなく、動物を食べるという問題は、利害の平等な配慮の問題と動物の権利の問題へと向かわなければならないと主張する。
* この論争を解釈する非認知主義的方法としての情緒主義および/または指令主義を十分に考慮しないこと。
* 肉食が受け入れられる可能性があるときとそうでないときとの間のより深い区別をすることなく、すべての肉食の物語と完全な菜食主義との対立に落ち込む。

## 検討すべき問題

いくつかの質問は第5節と第7節の最後に記載されています。

1. 動物を食べることの容認可能性に関する道徳的表明はしばしば感情的になります。このことは、情緒主義の説明が最良の説明であることを意味しますか?
2. すべての動物は利害の平等な配慮をする価値がありますか?一部の動物だけですか?だとしたらそれはどの動物?
3. 動物を食べることが受け入れられるかどうかについて、私たちは明確な道徳的回答を期待するべきなのでしょうか?
4. この応用倫理的な領域における道徳的な意見の不一致は、反実在論を支持するものでしょうか?
5. この道徳的な問題のどれくらいが、屠殺前の動物の扱いに関する経験的データによって決まるでしょうか?
6. この倫理的な領域で正しい結論を見つけるために、あなたが好む規範的な道徳的理論を適用するべきですか?それとも、それがこの倫理的な領域で正しいのかどうかを調べるために、あなたが好む規範的な道徳理論をチェックするべきですか?

## 重要な用語

種差別

利害の平等な配慮

直接の義務

間接の義務

## 参照文献

Bentham, Jeremy, An Introduction to the Principles of Morals and Legislation, freely available at http://www.econlib.org/library/Bentham/bnthPML18.html
<br>[関嘉彦責任編集「世界の名著49 ベンサム/J・S・ミル」、中央公論新社、1979年]

Bible, New International Version, freely available at https://www.biblegateway.com/

Diamond, Cora, ‘Eating Meat and Eating People’, Philosophy, 53.206 (1978): 465–79, https://doi.org/10.1017/s0031819100026334; freely available at http://www.laurentillinghast.com/DiamondEatingMeat.pdf

Hursthouse, Rosalind, ‘Applying Virtue Ethics to Our Treatment of the Other Animals’, in The Practice of Virtue: Classic and Contemporary Readings in Virtue Ethics, ed. by Jennifer Welchman (Indianapolis: Hackett Publishing, 2006), pp. 136–55, freely available at http://www.hackettpublishing.com/pdfs/Hursthouse_Essay.pdf

Kant, Immanuel, ‘We Have No Duties to Animals’, in Ethical Theory, ed. by Russ Shafer-Landau (Oxford: Blackwell Publishing, 2007), pp. 395–96.

―, Lectures on Anthropology, ed. by Allen Wood and Robert Loudon (Cambridge: Cambridge University Press, 2012).
<br>[カント全集「講義録」八幡英幸・氷見潔訳、岩波書店、2002年]

Korsgaard, Christine, The Sources of Normativity (Cambridge: Cambridge University Press, 1996), https://doi.org/10.1017/cbo9780511554476
<br>[「義務とアイデンティティの倫理学 : 規範性の源泉」寺田俊郎・三谷尚澄・後藤正英・竹山重光訳、岩波書店、2005年]

Scruton, Roger, ‘Eat Animals! It’s for Their Own Good’, Los Angeles Times (25 July 1991), freely available at http://articles.latimes.com/1991-07-25/local/me-54_1_animal-rights

Singer, Peter, ‘Equality for Animals?’, in Ethics, Humans and Other Animals: An Introduction with Readings, ed. by Rosalind Hursthouse (London: Routledge, 2000), pp. 169–79.

Tolstoy, Leo, Writings on Civil Disobedience and Non-Violence (Philadelphia: New Society Publishers, 1988).