# 用語集 {-}

**絶対主義的**:ある規範的な道徳理論は、ある行動がすべての状況において例外なく間違っている(あるいは正しい)ことを示唆している場合、相対主義的ではなく、絶対主義的です。たとえば、殺人はどのような状況にもかかわらず、絶対に間違っていると考えられるかもしれません。

**行為中心の**:道徳的正しさ/間違いと行動とを関連付ける規範的な道徳的理論(たとえば、功利主義)。

**能動的安楽死**:人間が能動的に安楽死させられるとは、彼らの死の原因が、自然の原因ではなく、外部の介入(最も可能性が高いのは、致命的な注射や致死的な組み合わせの薬物を自発的に飲むことなど)によるものであることを意味します。

**行為功利主義**:帰結主義を参照してください。

**アガペー**:「愛」を意味するギリシャ語の単語。神に対する人間の愛と人間に対する神の愛を表しています。愛の「最高」の形態。フレッチャーが論じたように、アガペーは態度であり、感情ではなく、お返しとして何かを期待することなく、誰に対しても特別な配慮をしないものです。

**アガペー計算**:フレッチャーによって導入されました。私たちは常に、最も多くの人に最も大きな愛をもたらすように行動すべきだという主張。

**行為主体中心の**:道徳的正しさ/間違いと人々とを関連付ける規範的な道徳的理論(たとえば、徳倫理学)。

**行為主体-中立性**:個人的な感情に特別な重み付けを与えることなく、道徳的な決定を下すべきであるという見解。

**肛門期**:フロイトの心理性的発達理論の第2段階で、おおよそ1歳半から3歳まで。トイレに行くことをコントロールすることによって快楽が得られます。この段階は、体の制御を得るところであり、それは(トイレトレーニングをすることにより)膀胱や腸を制御することから始まります。

**無律法主義**:フレッチャーが導入した言葉であり、道徳的には行為主体がある状況の中で望むことを何でもできることを言っています。

**反実在論**:単純に実在論の否定。反実在論者は、心から独立した客観的な道徳的な性質の存在を否定します。

**見かけ上の良さ**:自然法理論を議論するときにアクィナスによって導入されました。見かけ上の良さとは、二次的な教訓が自然法からは外れており、そのため道徳的に従うことを要求されない時のことです。

**ア・プリオリ**:世界をテストする/経験する必要なく、理性のみで得られた知識。

**ア・ポステリオリ**:世界の経験の結果として得られた知識。

**態度の快楽主義**:人生を良くするものは、ある人が経験する喜びの量によって完全に決定されるという福利の理論。そこでは喜びは、感覚ではなく、態度の状態(すなわち何かを楽しむ)として理解されます。フレッド・フェルドマンはこの見解の擁護者です。

**信念**:ひとつの心理状態。もしあなたが何かを信じるなら、あなたはそのことを真実とみなしています。

**歯をくいしばって耐える**:明らかに厄介な結論のことを、理論の致命的ではない含意として単純に受け入れるという議論の戦略。

**「ブーイング/フレー」理論**:情緒主義を参照してください。

**定言命法**:カントの道徳性の最高の原則。これを使って、私たちはどのように行動すべきかを見つけ出すことができます。それは、結果にかかわらず従うべきである(定言)命令(命法)です。

**定言命法1**:普遍化**:「…あなたがその格率を普遍的な法にし得るように、と同時に普遍的な法にするように、その格率に従ってのみ行動せよ。」^[I. Kant, Moral Law, p. 15.]

**定言命法2**:手段と目的**:「そのために、あなたは人間性(あなた自身の人格の中にあるものと、他の人の人格の中にあるもの)を、決して単なる手段としてではなく、常に同時に目的として使用するように行動せよ。」^[Ibid., p. 66.]

**定言命法3**:目的の王国**:「…すべての理性的な存在は、彼の格率を通じて、あたかも常に彼が目的の普遍的な王国の立法者であるかのように行動しなければならない。」^[Ibid., p. 21.]

**心理学的認知主義**:実在論と混同しないでください。それは、私たちが「殺人が間違っている」または「他者を助けることは正しい」という形態の道徳的主張をするときには、私たちは感情などの非信念の状態ではなく、私たちの信念に対して声を与えているということを示唆しています。

**意味論的認知主義**:実在論と混同しないでください。それは、私たちが「殺人が間違っている」または「他者を助けることは正しい」という形態の道徳的主張をするときには、私たちの主張は真か偽になり得る(哲学者が真偽の区別が可能である(truth-apt)と呼ぶもの)ということを示唆しています。

**良心(アクィナス)**:アクィナスにとって、良心とは道徳的に中立であり、それは単に「証言」し、何が正しく何が間違っているかの「道しるべ」です。それは道徳的な知識の源ではありません。これは、アクィナスにとって良心は誤る可能性があることを意味します。彼はそれを「知識の活動への適用」と呼んでいます。

**良心(フロイト)**:フロイトにとって、良心とは、自我に対処するために超自我が取る形式です。この「良心」の理解は、「良心の呵責」の同義語として考えることができます。

**帰結主義**:行動の道徳的価値はその行為の結果によって完全に決定されると主張する規範的な道徳理論です(たとえば、行為功利主義)。

**厳しい要求の異議**:功利主義への挑戦。喜びは単に促進される必要があるだけではなく、すべての機会において実際に最大化される必要があるとしたならば、極端に高い基準が設定されてしまいます。

**義務論的**:結果ではなく義務に焦点を当てた規範的な道徳理論。

**直接の義務**:カント倫理学の議論に使用されます。直接の義務は、定言命法の定式化を通じて到達される義務です。

**気質**:徳倫理学に関して、気質とは私たちの心理における傾向のことです。たとえば、誰かが私からものを盗んだ場合、私は怒る気質を持っているかもしれませんし、誰かが私からものを盗んだ場合、私は許す気質を持っているかもしれません。

**神の命令理論**:何が正しいか/間違っているかは、神によって命じられている/禁じられているというメタ倫理的見解です。

**神定法**:自然法理論の一環としてアクィナスによって導入されました。神定法は啓示によって発見されます。神定法とは、神が恩寵をもって私たちに与えるのに適していると考えるものであり、「秘儀」、すなわち私たちが聖書の中で見つける神によって与えられたルールのことです。たとえば、十戒です。

**二重の結果のドクトリン(DDE)**:アクィナスによって神学大全の中で導入されました。ある行為が4つの条件を満たしていればそれは道徳的に容認できます。もしそうでなければ、道徳的には容認できません。第1はその行為が良いものでなければならない、第2はその行為が結果の前に生じなければならない、第3はその意図が良いものでなければならない、第4はそれが深刻な理由のためでなければならないということです。

**自我**:フロイトによれば、心にある3つの部分の1つです。「自我」は、ある人が世界の中で社会的相互作用を可能にするためにイドを取り締まっています。

**エレクトラコンプレックス**:ユングの精神分析では、女の子が父親と性的関係を持ち、結果として母親と競うというような、女の子によって経験される無意識の欲求に与えられた名前。

**情緒主義**:メタ倫理学の理論。心理学的非認知主義の一形態であり、道徳的な判断は何かの記述ではなく、話し手の感情の表現であるとするものです。これは、主観主義または相対主義(「ブーイング/フレー」理論と呼ばれることもある)と混同されるべきではありません。

**経験的**:科学によって研究されるような、感覚経験と世界との相互作用を必要とする、知識を獲得するための方法。

**認識論**:知識についての哲学的研究。質問には「知識とは何か?」、「私たちはア・プリオリに何かを知ることができるか?」、「私たちは何を知ることができるか?」などが含まれるでしょう。

**永久法**:自然法理論について議論するときに、アクィナスによって導入されました。すべてのものに対する神の合理的な目的と計画のこと。永久法は神の心の一部であるため、それは常に存在しており、常に存在することになるでしょう。永久法は、単にある時点で神が書くことを決めた何かではありません。

**エウダイモニア**:「良い人生」についてのアリストテレス的な考え方。「開花」としてもっともうまく翻訳されます。

**安楽死**:それがなければはるかにつらい死に直面するかもしれない人にとって、良い死を提供しようとする行為(自発的/非自発的および受動的/能動的安楽死も参照してください)。

**エウテュプロンのジレンマ**:神の命令理論(DCT)への挑戦。エウテュプロンとの対話でプラトンによって導入されました。それは、DCTについてあなたが問うことができる2つの質問があるが、それぞれに与えられる答えは問題含みであることを示唆しています。質問は**:(i)神が何かを命じるために、それは良いものであるのか。または、(ii)それが良いものであるために、神はそれを命じるのか。

**幸福計算**:快楽計算を参照してください。

**罪悪感**:フロイトは、この言葉を、私たちの良心が私たちに達成できないものを求めてきたときに生じる感情を指すのに使用しています。

**中庸**:徳倫理学の中で、過剰の悪徳と不足の悪徳との間にある、道徳的に有徳な中間の道。

**良い意志**:私たちの具体的な意志のカント主義的な考え方で、それがもたらすもの、あるいは達成することではなく、その意志のみで良いものです。

**危害原理**:ジョン・スチュアート・ミルの原則**:「文明化された共同体のいかなる成員に対しても、彼の意志に反して、正当に権力を行使することができる唯一の目的とは、他者に対する危害の防止である。彼自身の利益は、肉体的なものでも道徳的なものでも、十分な根拠とはならない。」^[ J. S. Mill, On Liberty, http**://www.econlib.org/library/Mill/mlLbty1.html]

**快楽計算**:ジェレミー・ベンサムによる将来の可能な行動に伴う喜び/苦痛を計算する方法。

**快楽主義**:ある人の人生の改善はその人が経験する喜びの量によって完全に決定されるという福利についての理論。その他の要素はまったく関係しません。

**より高い喜び、より低い喜び**:ミルによる喜びの質の区別。より高い喜びとは、詩、読書、劇場へ行くことなどの活動を通じてもたらされた知性の喜びです。より低い喜びとは、動物的であり基本的なものです。ビールを飲んだり、セックスをしたり、日光浴用の椅子でだらけたりすることに伴う喜びです。

**ヒュームの動機づけ理論**:信念が適切に関連した欲求と結びついているとき、つまり欲求が主たる役割をしているときにのみ、動機づけが生じるという見解。さらにそれは、信念と欲求とは、信念が欲求を伴うことができないような別個の精神状態であるという見解です。

**ヒュームの分岐**:ヒュームは知識を2つの種類に分けました — 考え方の関係から得られた知識と、事実から得られた知識です。

**仮言命法**:行為主体の欲求/欲望のためにのみ、誰かに適用される命令。たとえば、もしあなたが健康であることを望む場合には、あなたはランニングに行くべきです。

**イド**:フロイトによれば、心にある3つの部分の1つです。イドとは私たちの原始的な衝動、つまり食物、セックス、飲み物への基本的な欲求のコレクションであり、心の最も古い部分です。イドは適切に公式化されたり理解されたりすることはできず、フロイトはそれをカオスに似せています。

**間接の義務**:カント倫理学に関連して議論されました。私たちがX(たとえば、動物、環境など)に対して負う義務は、実際には、私たちが人間に対して負う義務です。たとえば、私たちは動物に対して間接的な義務があります。なぜなら、もし私たちが動物をひどく扱うならば、私たちは人間に向かう私たちの義務を守らなくなるからです。

**本質的**:もしあるものがそれ自体として根本的にまたは必然的に良いものであれば、それは本質的に良いものです。それが良いものであるために他のものに頼ることはありません。

**直観主義**:少なくとも1つの(そしておそらくは多くの)自明に正当化可能な道徳的信念があると主張する、道徳的認識論における見解。これは、道徳的主張を正当化する他の方法を排除するものではなく、また、直観主義者が判断に誤りがないと信じていることを意味しません。

**克服できない無知**:アクィナスによる。理性を用いることによっても克服することができない無知。よりよく知ることができないときに間違ったことをすること。

**「である/べきである」の隔たり**:ある(記述的な)主張から「べきである」という(規範的な)主張を導くときに想定される問題。

**潜在期**:フロイトの心理性的発達理論の第4段階で、おおよそ6歳から思春期の初めにかけてです。この段階では性的欲求が抑圧され、新しい性的欲求は形成されません。女の子たちは女の子の役割を学ぶために女の子と遊び、男の子は男の子の役割について学ぶために男の子と遊びます。

**律法主義**:ある倫理システムに言及するためにフレッチャーによって使用された用語。そのシステム内にいる人は、状況に敏感になることなく道徳的なルールを「盲目的に」遵守しています。

**格率**:私たちが行動するための一般原則またはルール。

**成熟した性器期**:フロイトの心理性的発達理論の第5段階であり最終の段階。

**道徳的錯誤理論**:意味論的非認知主義、反実在論、真実を真実とさせる理論の組み合わせ。その結論は、私たちが行うすべての道徳的主張は系統的かつ一様に誤りであるということです。

**自然法**:自然法理論について議論するときに、アクィナスによって導入されました。人間が理性の目的/機能に従って行動するとき、彼らは自然法に従って行動しています(主たる教訓と二次的な教訓を参照してください)。

**自然主義、実在論**:道徳的な性質が存在し、科学で議論され検討されている性質と同じくらい自然であるという見解。

**自然主義的な誤謬**:G・E・ムーアによれば、道徳的性質が自然の性質へ還元できるという考え方。ムーアは、良さ = 喜び/幸福/選好の満足と主張する人は自然主義的な誤謬を犯していると信じています。

**虚無主義**:価値観を排除しようとする理論に関連しています。たとえば、道徳的錯誤理論は、この世界の中のいかなる道徳的価値観の存在をも否定するため、虚無主義と分類されます。

**非信念の状態**:何かが真実であるととらえることに関連しない心理的状態。これは、典型的には、非記述的または抽象的な状態であると考えられます。たとえば、喜びや怒りなどの感情的な状態。

**心理学的非認知主義**:私たちが「殺人が間違っている」または「他者を助けることは正しい」という形態の道徳的主張をするときには、私たちは私たちの信念に声を与えることはなく、むしろ私たちは感情などの非信念の状態を表現しています。

**意味論的非認知主義**:私たちが「殺人が間違っている」または「他者を助けることは正しい」という形態の道徳的主張をするときには、私たちの主張は真でも偽でもありません。それらは、真偽の区別が可能(truth-apt)なものではではありません。

**非自然主義**:もし道徳的な性質が存在する場合、それらは存在しているものについての科学的な図には現れることがないという見解。

**非自発的安楽死**:非自発的安楽死は、安楽死させられようとしている個人が自分自身で決断を下すことができないために、早過ぎる死および慈悲殺に関する決断が他人によってなされた場合に起こります。

**規範的**:規範的な道徳理論は、どのように行動するか/生きるかの指針を提供するために考案された理論です。

**神経症**:超自我がイドに適切に対処できないとき、特に、快楽原則が抑圧されているときのことに言及するためにフロイトが使用する用語。

**客観的なリスト理論**:人生を良いものとするのは物事のリスト(たとえば、愛情のある関係、有意義な知識、自律性)によって決定されるという福利の理論。

**エディプスコンプレックス**:精神分析では、子供が抱く異性の親と性的関係を持つという無意識の欲求に与えられた名前。これは少年の母親に引き付けられる性的な魅力として表現されることが最も多いです。

**開かれた質問の議論**:G・E・ムーアによって提唱されました。それはメタ倫理学の自然主義的・実在論的立場を攻撃します。道徳的性質(たとえば、良さ)が自然の性質(たとえば、喜び)であるならば、道徳的な言葉(たとえば、「良さ」)は自然の言葉(たとえば、「喜び」)と同義でなければならないと主張しています。しかしながら、道徳的な言葉が自然な言葉と同じ意味であるかどうかを尋ねることは、常に開かれた質問です。その答えは私たちにとって明らかではありません。これは、道徳的な言葉は自然な言葉と同義ではないことを意味します。これは、道徳的な性質が自然の性質と同一となることはできないことを意味します。

**口唇期**:フロイトの心理性的発達理論の第1段階であり、出生から約1歳半までです。この段階は、赤ちゃんがものを口に入れることや、噛んだり、吸ったり、しゃぶったりすることから快楽を得るところです。

**緩和ケア**:「もしあなたが治療不可能な病気である場合、緩和ケアは痛みや他のつらい症状を管理することによって、あなたをできるだけ快適な状態にします。それはまた、あなたとあなたの家族や介護者のための心理的、社会的、精神的なサポートも含みます。これは全体的なアプローチと呼ばれます。なぜなら、それはあなたを「全体的な」人間として扱うからです。」^[NHS definition, http**://www.nhs.uk/Planners/end-of-life-care/Pages/what-it-involves-and-when-it-starts.aspx]

**悲劇のパラドックス**:否定的な感情のパラドックスとしても知られています。真のパラドックスではありません。現実の生活では否定的な感情は望ましくないが、ホラー映画、ジェットコースター、ドラマなど、他の状況ではそれらは望ましいという奇妙さのこと。

**受動的安楽死**:受動的安楽死は、ある人が生き続けることを可能にするかもしれない治療から意図的に離脱することによって死ぬことを許されたときに起こります。

**永続的植物状態(PVS)**:ある人間が生物学的には生きているが、世界との心理的な相互作用の兆候を示さないような状態。この状況がいかなる治療によっても変化する可能性が低い場合、その状態は永続的と表示されます。

**男根期**:フロイトの心理性的発達理論の第3段階であり、おおよそ3歳から6歳までです。そこでは子どもが自分の生殖器を発見し、また重要なこととして、それは男性と女性で異なるものです。フロイトが考えるには、この段階は私たちがエディプスとエレクトラコンプレックスを発展させるところです。問題のある男根期は、後の人生での親密さの問題を引き起こすでしょう。

**フロネシス**:「実践的な知恵」のことを表すアリストテレス倫理学の用語。おそらく最も重要な有徳な気質や性格の特性です。

**快楽原則**:フロイトが提唱する考え方。これは、イドの衝動を特定し統一するものとは、苦痛を避け快楽を追求することである、という主張です。

**選好功利主義**:功利主義の非快楽主義的なバージョン。最も多くの人の最も大きな良さをむき出しの形の喜びやより高い形の喜びに還元することはできません。代わりに、ある人の人生を改善するものは、彼らの選好の満足によって完全に決定されます(たとえば、ピーター・シンガーによって擁護されています)。

**指令主義**:私たちの道徳的発話が単純な感情的な承認と不承認以上のものを表明していると主張するメタ倫理学理論。代わりに、私たちの道徳的な発話は、他者が私たちの道徳的判断に従って行動するための主観的な指示を表しています(たとえば、ヘア)。

**プリマ・ファシエ**:「最初の印象/外観」または「一見して/一目見ただけで明らかであること」。

**主たる教訓**:アクィナスの自然法理論の一部として導入されました。それらはいくつかの包括的な一般ルールです。それらはすべての合理的な行為主体にとって絶対的かつ拘束力があります。彼の例は次のとおりです**:人間の命を守り保存すること、自分の子孫を再生産し教育すること、神を知り礼拝すること、社会に住むこと。

**慈悲の原則**:相手を合理的だと認め、彼らの議論の最も強力な解釈をとるという議論の戦略。

**効用の原理**:ある行動が道徳的であるのは、それが最も多くの人の最も大きな良さにつながるとき、そのときのみであるという原則。功利主義に関連しています。

**等価の問題**:功利主義への挑戦。功利主義は、あなたが愛する人の人生に対して余分な道徳的重み付けを与えることを許しません(行為主体-中立性を参照してください)。

**奇妙**:道徳的錯誤理論に関連するJ・L・マッキーの考え方。あるものが、他のいかなる既存の性質/本質ともまったく違う場合、それは奇妙です。

**ラティオ**:アクィナスが自然法を発見するのに役立つ理性を表すために使った用語。

**実在論**:道徳的な性質が人間とは独立して存在し、世界の中に見つけ出すことができるという見解。

**相対主義的**:ある規範的な道徳理論は、ある行動が1つの状況では道徳的であるが、別の状況では不道徳であることを認める場合、絶対主義的ではなく、相対主義的です。たとえば、窃盗の道徳性は、窃盗が行われる状況によって相対的であると考えられるかもしれません。

**実際の良さ**:自然法理論を議論するときにアクィナスによって導入されました。実際の良さとは、二次的な教訓が自然法に従っているときであり、その結果、私たちは道徳的にそれに従うことが求められます。

**規則功利主義**:もし皆がそれに従うならば、最も大きな幸福の総量を生み出すであろう一連のルールを作成すべきであるという見解(たとえば、ジョン・スチュアート・ミルによって擁護されています)。強い規則功利主義、弱い規則功利主義も参照してください。

**生命の神聖さ**:生命には絶対的な価値があるという考え方。生命は神によって与えられたという考え方によって正当化されることが非常に多いです。

**二次的な教訓**:自然法理論を議論するときにアクィナスによって導入されました。二次的な教訓とは、私たちの理性によって生み出されるのではなく、政府、団体、クラブ、社会などによって課されます。例**:高速道路で時速70マイル以上で走行しないでください。人を誘拐しないでください。バイクに乗るときは常にヘルメットを着用してください。誰かの銀行口座にハッキングしないでください。

**意味論**:意味論の関心事項は、単語とその意味にについての関心です。それは言語と意味に焦点を当てることに関連しています。

**種差別**:ピーター・シンガーによって導入された用語。人間は1つの種であり、別の種ではないという恣意的な事実に純粋に基づいて人間以外の動物を人間とは異なるように扱うという主張は、道徳的に間違っています。シンガーはそれのことを、ジェンダー(性差別)や人種(人種差別)の違いに基づいて人を異なるように扱うことと道徳的に同等であると考えています。

**藁人形**:藁人形の議論とは、意図的にその最も弱い形で表現された議論であり、そのため簡単に打ち負かすことができます。藁人形の議論は、人が「同じ土俵」で難しい異議と議論するのを避けることを可能にします。

**強い規則功利主義**:(もし皆が従うならば)最大の量の幸福を促進するであろう規則のセットからの指示には、常に従わなければならないということ。

**超自我**:フロイトによれば、心にある3つの部分の1つです。超自我は、禁止、抑止、道徳的な制約を発する権威の声です。

**シンデレシス**:アクィナスによって導入された用語。シンデレシスは良心と同じものではなく、永久法/神定法を理解するための心の生得的な能力(心の習慣)のことです。

**目的論的**:目的論的な規範理論とは、結果に関心を持つ理論です(たとえば、功利主義)。

**目的論者**:すべての対象物が最終的な理念/ゴール/目標/目的を持っていると考える人。

**テロス**:アリストテレスにとって、テロスは何かの目的です。

**心理性的発達理論**:フロイトによって開発されました。生まれてから死ぬまでの性的発達の理論には、口唇期、肛門期、男根期、潜在期および成熟した性器期の段階が含まれます。

**思考実験**:さまざまな話題について私たちが持っている直観を強調し、それに挑戦するために使用される仮想の — しばしば空想的な — 状況。たとえば、ジュディス・トムソンの「移植外科医」(第1章参照)。

**真偽の区別が可能である**:もしある主張が真偽の区別が可能であるならば、それは真または偽になることができます。ここで注意してほしいのは、その主張は決して真ではないかもしれないが、それでも真または偽になることができる可能性があるということです。たとえば、「真偽の区別が可能である」という言葉の意味についてのこの上記の説明は、それ自体で真偽の区別が可能です。

**真実を真実とさせる理論**:世界の何らかの特徴(所有権のような)がある主張を真実にする場合であり、かつ、その場合にのみ、その主張は真実になります。

**多数派の専制**:功利主義への挑戦。功利主義は、喜びの総量を最大化するというより大きな良さのために多数派が少数派を搾取することが道徳的に必要とされるという事例を受け入れているように見えます。

**効用**:特定の行動に関連する喜び/苦痛/選好の満足を指すために功利主義者によって使用される用語。

**功利主義**:帰結主義を参照してください。

**検証原理**:もしある文が分析的でないか潜在的に経験的に検証可能でない場合、それは無意味である、ということを述べる原理。

**v-ルール**:ロザリンド・ハーストハウスによって導入されました。彼女は、徳倫理学が「v-ルール」の形で指針を提供することを示唆しています。それは、「正直なことをする」または「嫉妬を避ける」といった形式の指針となるルールです。

**克服できる無知**:アクィナスによる。理性を用いることによって克服することができる無知。よりよく知っておくべきときに間違ったことをすること。

**徳**:道徳的に正しい性格の気質または特性。道徳的な悪徳を表す性格の気質または特性とは対照的です。

**自発的安楽死**:自発的安楽死は、ある人が将来の苦しみを避けるために、自分の人生を終わらせるような選択を自らしたときに起こります。

**弱い規則功利主義**:(もし皆が従うならば)最大の量の幸福を促進するであろう規則のセットからの指示は、その規則を破ることによってもっと多くの幸福が生まれる状況では、無視することができます。

**福利**:ある人生が、その人生を生きている人にとってどれほどうまくいっているかの基準。