# あとがき {-}

## この本はここで終わる必要はありません… {-}

私たち Open Book Publishers(OBP)は、伝統的な学術書の性質を変革しています。あなたがたった今読み読み終えたばかりの本は、図書館の棚に置き去りにされることはなく、世界中から毎月何百人もの読者がオンラインでアクセスするでしょう。OBPは最高の学術研究のみを出版します。各タイトルは厳密なピアレビューの過程を経ています。私たちは、印刷された版を購入する余裕のない学生、研究者、そして一般の皆さんが同じ考え方にアクセスできるように、私たちの本をオンラインで自由に読めるようにしています。

この本と追加コンテンツは次のサイトから入手できます。

https://www.openbookpublishers.com/product/639

## カスタマイズ {-}

この本の複製物をパーソナライズしたり、OBPとサードパーティーの資料を使用して、新しい書籍をデザインしたりしてみてください。私たちの出版物のリストからいくつかの章や書籍全体を取り出し、特別版、新しいアンソロジーまたはわかりやすい講義資料を作ることができます。カスタマイズされた各版は、ペーパーバックやダウンロード可能なPDFとして作成されます。詳しくは以下をご覧ください:

https://www.openbookpublishers.com/section/59/1

## 寄付 {-}

もしあなたがこの本を楽しみ、このような研究が人々の所得にかかわらず全ての読者に利用可能であるべきだと感じているならば、私たちに寄付をすることを考えてみてください。私たちは営利目的で運営しておらず、すべての寄付は、他のすべての収入と同様に、新しいオープンアクセスの出版物の資金として使用されます。

https://www.openbookpublishers.com/section/13/1/support-us

## リンク {-}
Facebook:https://www.facebook.com/OpenBookPublish

twitter:https://twitter.com/OpenBookPublish

OBPブログ:http://blogs.openbookpublishers.com/

## あなたは以下の本にも興味を持つかもしれません: {-}

### 道徳相対主義の基盤 {-}

第2版拡張版

J・デイヴィッド・ヴェレマン

https://www.openbookpublishers.com/product/416

### 一人称の立場からのメタ倫理学 {-}

道徳哲学への入門

キャサリン・ウィルソン

https://www.openbookpublishers.com/product/417

### 価格を超えて {-}

誕生と死についてのエッセイ

J・デイヴィッド・ヴェレマン

https://www.openbookpublishers.com/product/349

# 裏表紙 {-}

## Aレベルの倫理学 {-}

## マーク・ディモック(Mark Dimmock)、アンドリュー・フィッシャー(Andrew Fisher) {-}

喜びは道徳性と何か関係がありますか?道徳理論の形成の中で直観は(もしあるとして)どのような役割を担うべきですか?もし何かが「模擬的な」ものであるならば、それは不道徳となることができますか?

このわかりやすく幅広い教科書は、これらの質問やさらに多くのものを探求します。規範倫理学、メタ倫理学、応用倫理学の分野における重要な考え方が、力強さとウィットで話題を盛り上げる鮮やかな文章スタイルとともに、緻密かつ体系的に説明されています。個々の理論について本書の前半部分で詳細に説明した後に、それらの立場がビジネス倫理、性的な倫理、動物を食べることの容認可能性などの幅広い現代的状況に適用されます。奥行きと注意深さをもって設定された豊富な現実生活の例は、現代的な関連性を伝えながら、さまざまな倫理的アプローチの複雑さを明らかにしています。

この簡潔で非常に興味をそそる資料は、AQAの哲学コースとOCRの宗教研究コースの倫理学の構成要素に合わせて作られており、章末のまとめ、重要な用語、避けるべきよくある間違いを含む明確で実用的なレイアウトを有しています。この本は、インターナショナル・バカロレアの一環として哲学を教える人にとっても実用的に使用することができます。

Aレベルの倫理学は学生や教師にとって特に価値がありますが、フィッシャーとディモックの精密で学術的なアプローチは、倫理学という手ごわい科目に対する厳密でありながらも生き生きとした入門書を求めている人にとっても魅力的なものとなるでしょう。

この版には以下のものが含まれます:

* 章末のまとめ
* 重要な用語
* 避けるべき間違い
* 検討すべき問題
* 学習用の質問
* 用語集

すべての Open Book Publishers の出版物と同様に、この書籍全体は、出版社のWebサイトで無料で読むことができます。印刷版とデジタル版は、補足のデジタル資料と一緒に http://www.openbookpublishers.com でご覧いただけます。

表紙画像: 空から見たマレーシア、photo by Ishan @seefromthesky on Unsplash

表紙デザイン:アンナ・ガッティ